apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: rtmp-ingest
  namespace: browser-streamer
spec:
  entryPoints:
    - rtmp
  routes:
    - match: HostSNI(`*`)
      services:
        - name: ingest
          port: 1935
