//! Visual reference tests: render scenes in stage-runtime's WebGL2
//! and compare against Chrome-rendered reference PNGs (RMSE threshold).
//!
//! Reference images generated by `tests/webgl2_fixtures/generate.cjs` using Puppeteer.
//! Run `node tests/webgl2_fixtures/generate.cjs` to regenerate.
//!
//! Set `SAVE_ALL=1` to save every rendered output as a PNG for visual inspection:
//!   SAVE_ALL=1 cargo test --package stage-runtime --test webgl2_reference_test
//! Output goes to tests/webgl2_fixtures/<scene_name>.render.png

use std::collections::HashMap;
use std::path::Path;

const FIXTURES_DIR: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/webgl2_fixtures");
const DEFAULT_THRESHOLD: f64 = 0.01;

/// RMSE between two RGBA pixel buffers. Returns 0.0-1.0.
fn rmse(a: &[u8], b: &[u8]) -> f64 {
    assert_eq!(a.len(), b.len(), "pixel buffers must be same size");
    if a.is_empty() {
        return 0.0;
    }
    let sum_sq: f64 = a
        .iter()
        .zip(b.iter())
        .map(|(&av, &bv)| {
            let d = av as f64 - bv as f64;
            d * d
        })
        .sum();
    (sum_sq / a.len() as f64).sqrt() / 255.0
}

/// Load a PNG file -> (width, height, rgba_pixels).
fn load_png(path: &Path) -> (u32, u32, Vec<u8>) {
    let data =
        std::fs::read(path).unwrap_or_else(|_| panic!("failed to read {}", path.display()));
    let decoder = png::Decoder::new(std::io::Cursor::new(data));
    let mut reader = decoder.read_info().expect("PNG decode failed");
    let mut buf = vec![0u8; reader.output_buffer_size()];
    let info = reader.next_frame(&mut buf).expect("PNG frame read failed");
    buf.truncate(info.buffer_size());

    let rgba = match info.color_type {
        png::ColorType::Rgba => buf,
        png::ColorType::Rgb => {
            let mut out = Vec::with_capacity(buf.len() / 3 * 4);
            for c in buf.chunks_exact(3) {
                out.extend_from_slice(c);
                out.push(255);
            }
            out
        }
        other => panic!("unsupported PNG color type: {:?}", other),
    };
    (info.width, info.height, rgba)
}

fn load_scenes() -> serde_json::Value {
    let p = Path::new(FIXTURES_DIR).join("scenes.json");
    serde_json::from_str(&std::fs::read_to_string(&p).unwrap()).unwrap()
}

/// Save RGBA pixel data as a PNG file.
fn save_png(path: &Path, width: u32, height: u32, rgba: &[u8]) {
    let file = std::fs::File::create(path).expect("failed to create PNG output");
    let w = std::io::BufWriter::new(file);
    let mut encoder = png::Encoder::new(w, width, height);
    encoder.set_color(png::ColorType::Rgba);
    encoder.set_depth(png::BitDepth::Eight);
    encoder.set_compression(png::Compression::Best);
    encoder.set_adaptive_filter(png::AdaptiveFilterType::Adaptive);
    let mut writer = encoder.write_header().expect("failed to write PNG header");
    writer
        .write_image_data(rgba)
        .expect("failed to write PNG data");
}

/// Resolve `$ref` references in scene commands using return values from process_commands.
///
/// The scene JSON uses `"__ret_NAME"` as the last arg to capture return values,
/// and `"$NAME"` in subsequent commands to reference them. Since process_commands
/// processes all commands in one batch, we need to pre-resolve $refs by predicting
/// the sequential alloc_id() values, OR process commands in multiple batches.
///
/// We use the batch approach: process one command at a time, collecting returns.
fn run_scene(name: &str) {
    if !stage_runtime::webgl2::gpu_available() {
        eprintln!("  {} SKIPPED (no GPU adapter)", name);
        return;
    }
    let scenes = load_scenes();
    let w = scenes["width"].as_u64().unwrap() as u32;
    let h = scenes["height"].as_u64().unwrap() as u32;
    let scene = &scenes["scenes"][name];
    let cmds = scene["commands"].as_array().expect("commands should be array");
    let threshold = scene
        .get("threshold")
        .and_then(|t| t.as_f64())
        .unwrap_or(DEFAULT_THRESHOLD);

    let ref_path = Path::new(FIXTURES_DIR).join(format!("{}.truth.png", name));
    if !ref_path.exists() {
        panic!(
            "Reference missing: {}. Run `node tests/webgl2_fixtures/generate.cjs`",
            ref_path.display()
        );
    }

    let (rw, rh, ref_px) = load_png(&ref_path);
    assert_eq!((rw, rh), (w, h), "reference size mismatch for {}", name);

    let mut gl = stage_runtime::webgl2::WebGL2::new(w, h);

    // Track return values: name -> JSON value
    let mut refs: HashMap<String, serde_json::Value> = HashMap::new();

    // Process commands one at a time, resolving $refs
    for cmd in cmds {
        let arr = cmd.as_array().expect("each command should be an array");
        if arr.is_empty() {
            continue;
        }

        // Resolve $ref and @shaders/ file references
        let resolved: Vec<serde_json::Value> = arr
            .iter()
            .map(|v| {
                if let Some(s) = v.as_str() {
                    if let Some(ref_name) = s.strip_prefix('$') {
                        if let Some(val) = refs.get(ref_name) {
                            return val.clone();
                        }
                    }
                    if let Some(shader_path) = s.strip_prefix('@') {
                        let full = Path::new(FIXTURES_DIR).join(shader_path);
                        let src = std::fs::read_to_string(&full)
                            .unwrap_or_else(|_| panic!("shader file not found: {}", full.display()));
                        return serde_json::Value::String(src);
                    }
                }
                v.clone()
            })
            .collect();

        let batch = serde_json::json!([resolved]);
        let returns = gl.process_commands(&batch);

        // Collect return values
        if let Some(ret_arr) = returns.as_array() {
            for ret in ret_arr {
                if let Some(pair) = ret.as_array() {
                    if pair.len() == 2 {
                        if let Some(ret_id) = pair[0].as_str() {
                            if let Some(ref_name) = ret_id.strip_prefix("__ret_") {
                                refs.insert(ref_name.to_string(), pair[1].clone());
                            }
                        }
                    }
                }
            }
        }
    }

    let mut rendered = vec![0u8; (w * h * 4) as usize];
    gl.read_pixels(&mut rendered);

    // Save rendered output alongside reference when SAVE_ALL=1
    if std::env::var("SAVE_ALL")
        .map(|v| v == "1")
        .unwrap_or(false)
    {
        let out_path = Path::new(FIXTURES_DIR).join(format!("{}.render.png", name));
        save_png(&out_path, w, h, &rendered);
    }

    let err = rmse(&rendered, &ref_px);
    if err > threshold {
        // Save the failed render for inspection
        let fail_path = Path::new(FIXTURES_DIR).join(format!("{}.render.png", name));
        save_png(&fail_path, w, h, &rendered);
        panic!(
            "Scene '{}' RMSE {:.6} exceeds threshold {:.4}\n  Reference: {}\n  Failed output saved to: {}",
            name,
            err,
            threshold,
            ref_path.display(),
            fail_path.display()
        );
    }
    eprintln!(
        "  {} RMSE: {:.6} (threshold: {:.4}) OK",
        name, err, threshold
    );
}

/// Generate `#[test]` functions for each scene in scenes.json.
/// Adding a new scene only requires adding it to scenes.json and regenerating
/// the reference image — no test code changes needed.
macro_rules! ref_scenes {
    ( $prefix:ident : $( $scene:ident ),* $(,)? ) => {
        $(
            #[test]
            fn $scene() {
                run_scene(stringify!($scene).strip_prefix(concat!(stringify!($prefix), "_")).unwrap());
            }
        )*
    };
}

ref_scenes! { webgl2:
    // Tier 1: State only (no shaders)
    webgl2_clear_red, webgl2_clear_green, webgl2_clear_blue_alpha,
    webgl2_clear_then_scissor, webgl2_viewport_partial,
    // Tier 2: Basic triangle
    webgl2_triangle_solid, webgl2_triangle_colored, webgl2_triangle_uniform_color,
    // Tier 3: Textured/blended
    webgl2_quad_textured, webgl2_blend_alpha,
    // Tier 4: Depth/state
    webgl2_depth_test_ordering, webgl2_indexed_draw,
    // Tier 5: Scissor/viewport
    webgl2_scissor_triangle, webgl2_viewport_quarter,
    // Tier 6: Multi-layer depth/blend
    webgl2_depth_three_layers, webgl2_blend_three_layers,
    webgl2_blend_over_color, webgl2_depth_back_to_front,
    // Tier 7: Clipping & coverage
    webgl2_large_triangle_clip, webgl2_fullscreen_quad,
    // Tier 8: Complex indexed/textured
    webgl2_two_quads_indexed, webgl2_colored_quad_indexed,
    webgl2_textured_triangle, webgl2_multi_draw_uniform,
    // Tier 9: Face culling
    webgl2_cull_face_back,
    // Tier 10: Blend modes
    webgl2_additive_blend, webgl2_blend_multiply,
    // Tier 11: Triangle strip/fan
    webgl2_triangle_strip_quad, webgl2_triangle_fan_pentagon,
    // Tier 12-25: Advanced
    webgl2_mvp_transform, webgl2_depth_mask_transparent,
    webgl2_perspective_triangle, webgl2_depth_lequal, webgl2_depth_less_coplanar,
    webgl2_cull_face_front, webgl2_varying_alpha, webgl2_multi_texture,
    webgl2_perspective_textured_quad, webgl2_indexed_triangle_strip,
    webgl2_three_attrib_pos_uv_color, webgl2_viewport_offset_triangle,
    webgl2_scissor_blend, webgl2_grid_mesh, webgl2_reversed_z,
    // Gap tests
    webgl2_linear_texture_filter, webgl2_discard_alpha_cutout,
    webgl2_draw_lines, webgl2_draw_points, webgl2_unpack_flip_y_texture,
    webgl2_color_mask_red_only, webgl2_blend_func_separate,
    webgl2_unsigned_int_indices, webgl2_texture_wrap_repeat,
    // Complex real-world scenes
    webgl2_phong_lit_sphere, webgl2_procedural_gradient_sky,
    webgl2_sdf_rounded_rect, webgl2_procedural_stripes,
    webgl2_multi_object_scene, webgl2_alpha_blended_particles,
    webgl2_depth_and_blend_combined, webgl2_wireframe_overlay,
    webgl2_scissor_multipass, webgl2_instanced_cube_grid,
    webgl2_two_texture_units,
    // Uniform array variants
    webgl2_uniform4fv_color, webgl2_uniform3fv_color, webgl2_uniform2fv_offset,
    // Stencil tests
    webgl2_stencil_mask_basic, webgl2_stencil_outline,
    // Polygon offset / blend equation / color mask
    webgl2_polygon_offset_zbias, webgl2_blend_equation_separate,
    webgl2_color_mask_channels,
    // High-risk Chrome comparison
    webgl2_stencil_incr_decr, webgl2_stencil_invert,
    webgl2_stencil_notequal, webgl2_stencil_depth_interaction,
    webgl2_blend_colormask_combined,
    webgl2_depth_fighting_close_planes, webgl2_depth_lequal_equal_z,
    webgl2_polygon_offset_decal,
    webgl2_line_strip_colored, webgl2_points_varying_position,
    webgl2_uniform_change_between_draws, webgl2_tex_subimage_update,
    // Stub method e2e tests
    webgl2_stub_flush_after_draw, webgl2_stub_finish_after_draw,
    webgl2_stub_flush_between_draws, webgl2_stub_compressed_tex_no_crash,
    webgl2_stub_transform_feedback_render, webgl2_stub_get_tex_parameter,
}
