apiVersion: v1
kind: Secret
metadata:
    name: aws-backup-credentials
    namespace: browser-streamer
type: Opaque
stringData:
    aws-credentials: ENC[AES256_GCM,data:I8Elj3Zq44jW1xaRTERNFvA3fEJahdb4fXFPZs6oFtT7ycmusqsQXnjK0/ce/VZdg+tIipld3CcStEAOGxc1gOThVEkZ6SOqUD7rlpapubSwqdRzlXbAEQEjF7HEPJcVvOslpRPehMtFVAOYeUvLGqfr52PSEBr7qAaZBpf79r4hCYKMw0JrqYfdapOKonkzdlrMc7s=,iv:G2pE3yQQuPowJj2OORo1YwC63W/JmMDSsW5sIt8uNCc=,tag:/v/elpj36Qibscq8VLkkbw==,type:str]
sops:
    age:
        - recipient: age1ase59dknkacq26gemrs9dvwvu8xr8akhfya99lagv5py7c7h7plsmtucvv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0UHc5NDdLZlFLc2p0THYx
            TnVTcmtnb0htc3lzbE51MmtQNTdOSU4yWUQwCjczVHpCZFo1VExyRXlDVjFIL1d2
            dG4wa3RiNmdrTUNpS3l1Zy9UUjhUbTgKLS0tIC9HZklWSW1DbFl0b0RzYkw5Szkz
            K0MvNDFGd2JnbWtEb3hyZlZQSWJSaE0Ke5niWO/AJ4yEgFYdavt6ecgGWND0WMMC
            H19zYqKAck+Y6LnGS1WT6sF8NuvVFif46nr+gXkf+OLJXOrhRVdyxQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age13zs054me9k5h4m8u3hwqw9nz4jg6lkpfmkzqn8mdujjqp76h6plsmlmtpy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGUGlHUmsyK1RCRGE0c3F0
            bUpnZ0Y2dHRsdzU0OVV4Z1ZsQWlVNWQ0djBZCmhEWVFCQmJVWHV3cXVBSDNOS1R4
            NGs0dFUvLzNyUmtPUTIrWjk5Z3VhU1EKLS0tIGszYy9GM2FONzZoYnd4SVlRajh1
            M0NDRjI0MHUreHJmSzkzNWJvVzlrblUKUUIdTht3h2pGAj4GiQhEv0DjS55OUT3V
            bCq1zjkd9t5dbFQ/Es4yZaPyHJ5bMTTrTtEZYf+R9ER+jqKoyt9pEg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17ttan4es6923ru96408ctjhs2f97mrxq9uw938plgnw6wkstv9cqsaq5cw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtbGpmUm0wVnViNE5BbnJB
            THZzaHZmUW5EL0pvZEJFMXg4ZkowMTZQZlhJCjNaUWFDMnlyK3FLMGk1d1dVa0hl
            b0Q2eDh4eTlMQ09tV3g3dm9lejNUd28KLS0tIHBpQUxyN09uVmZ3T3BmT2NlbUZn
            NWpRMmhGOUY3MVV1TUc4ejNZODVkWFUKdmo7jb7vlEwLee511VD7zvzRfbZcAPE+
            11COiWGbFw+9nB1ZA6PPLTBLMjSoppUCzHOefDNugese1D5dgNFUag==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1un8ajg06rd075pff8pglkq2q0g020peq7v23qzeqhuchl4y4kyfs0drxyf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtVU9VbGpBZzl2MlVJbHhu
            bFE0REVKSzBwTnA2WnhMNE40TlEzNFhkVEVnCmd2NWJxRkNER0d4WHJSQ005Nk9n
            aE9HdjFETTJqdlJKNHdkV1pSUklNZGcKLS0tIGcwMWh3QTlOOEpwWHlVNEk2Z0pu
            OXg2emZaT1BrZDVQYUtBQnU1Wm4rZGcKPNokwKzVfrm1r2kqGVWVJSFm5rx5i96C
            +oseuRUNe0s5mYqwnWHxcot806qIE9CxbnOLRjENe1zNS0M6qsHagQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18r3vk6aecpcd69ey7fhgjylg6z37ksfeff6c497mxgv4nwmnyupq4gsfua
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIekRGSVNKU1FEZ0RrNFFG
            eGJBNXFWY3I1NWJZak5JNVNQQXllTWFRS3lvCkhDOTN0L1FZK1NqVFJuNkl0OVVP
            dWNUbmdRR0doYnhQNFBIUi84NGdqWlEKLS0tIDgrVFJpd1haWE92ajNxWkR6K1Z1
            Q3N2T3RIUlYyRXdBUnQyS1owd3FLNk0KN8N/7p2bEN0IIPjRrxZ23QUzWNgtfEqd
            DaZVvY4d0zpRa78PEhwDSpicdRwp18vIdnGISTUrd1igqK/G+xxwjA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1emw2e5x3d4cu0x4g0q4lrw8nj2fdv0qfzta6g62m5y24j02zu44sflkxln
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2NEdOOStuK0ZvdVBuYXZo
            UWw5RlZubFREdTVvbUtERlJHWTRBL1U5eWhzCldET2E1bG5CTGNGUlpKV3haTnlM
            S1JXakZBa1JFejNWT2NGNnZEck5qbzgKLS0tIDVmYXI5ZEg2TUFWTHhGQnlnbkZS
            ZXpCYmt3QkRQcmltWjlJaVdicExKT3MK7iQVKUGlFycs5xIGF2EDoGl68X+GvFhY
            XAQRvOjd8FCDUJc99XzyfOPDd7U6J0QODSfgOdFfOiSRzCCpSsxvyQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1x9049ry5hz876qratphuc9gdxzuv4nnd06076842zdukl4unvazszfnjf6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBURlF4Zld2bkpMaFFNQ2t6
            dmpTOFRMZWVOT1k5bis2V0drQlYzY2pUVXlnCm92c0lBSitoeDNhL2dwb0R3dGk1
            eHBtWTB4ZWVUaGkyK1ovNnNzUFVIMFkKLS0tIGxpWGREUGJhQTNqaXlxVzFoSVpo
            S1lVUTlRaS94aHZFMTBIRVUrZ0VaamcKDMC2qnffBeng7UTpxEZKl0NnGAtKSr6i
            Xt5mTDVjSMYvl3FFokzU9Jc0ZlxK24t7wTJ5Y/koJqsJ2UJufK19NQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-28T16:05:06Z"
    mac: ENC[AES256_GCM,data:sM+AnFteKdCfCUpqZWcESUwgpBXo3pD9k6VQlZg/foFwX4RkSnrAr2vWGRqsIBp5z6OSMi+VOP5qJaYhhS9G9HQDfzPTcyjjzBJd/S5WtgVbz8jI5zoJgOo5n7Sxn1IAa2OPV6AwR+yHNHkvx7ky5G6xqq2PF9NdPGLVqXxnXEU=,iv:UC4ew0Xl+Ovc7o48PbQrgURd6NIulRlCHHJy7+CwvkQ=,tag:nVDal9zptCOh7Hg08kyKXg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
