apiVersion: v1
kind: Secret
metadata:
    name: aws-backup-credentials
    namespace: browser-streamer
type: Opaque
stringData:
    aws-credentials: ENC[AES256_GCM,data:I8Elj3Zq44jW1xaRTERNFvA3fEJahdb4fXFPZs6oFtT7ycmusqsQXnjK0/ce/VZdg+tIipld3CcStEAOGxc1gOThVEkZ6SOqUD7rlpapubSwqdRzlXbAEQEjF7HEPJcVvOslpRPehMtFVAOYeUvLGqfr52PSEBr7qAaZBpf79r4hCYKMw0JrqYfdapOKonkzdlrMc7s=,iv:G2pE3yQQuPowJj2OORo1YwC63W/JmMDSsW5sIt8uNCc=,tag:/v/elpj36Qibscq8VLkkbw==,type:str]
sops:
    age:
        - recipient: age18r3vk6aecpcd69ey7fhgjylg6z37ksfeff6c497mxgv4nwmnyupq4gsfua
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMYVR2YjFTNWZzTDB5eVI1
            U0hYcUR1RUpTTWFVNnozYU9wc1d0dzZqUTBjCm1QUzRFTlZXek5jR2U2SnRhTWNn
            cUdNcDIramtMZWorR1NUSlRkM240MEkKLS0tIFhyc3NweGZnNS9mL3RkcFV1R2s2
            ZUZqWWtSdGJpdDZwSU8yYUd5MFExU0EKh1322u14CijNwn5ymcATqypXl8D/GYXH
            hdlCLR6lel8beOH9c9Ekri6SovcOxsXEkEVKGYmB/gv8Lzbzq2oh4A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1emw2e5x3d4cu0x4g0q4lrw8nj2fdv0qfzta6g62m5y24j02zu44sflkxln
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOTXBTSG12RlNjbnA3S0VZ
            MXcvZVVTUGNaa1JMZytsWmVROHBCUFhYUFVvCjg4ZldaT29MUmNGay9XVDVYdy9B
            U1E4RXhnQ2xqSGtmSFU0WDA2Qk8yOTAKLS0tIHhEVmJ6VStjcWNpcFJLSG5sSkRJ
            SDVvdkFlb0pSNDcwNjJXWmtzY1cxRG8KbpB5xILhpQblxvl707c/glFG5S0EyEvq
            cLevos+vKC1p43UkZkfKyY5zZj8eSOWNAbh/mmjMw5161DELSF4QAQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1x9049ry5hz876qratphuc9gdxzuv4nnd06076842zdukl4unvazszfnjf6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZdmZPRWUyckE4Q25NaDNn
            STdaNEl0bTE5cjhKUjk2TElLd0sxcFV6bG40CkE3cFV6cnFHSkpHYVk5WU5ya21s
            c0hPNFpucC9RdXR6cWRDWXdqanh2cUEKLS0tIHM3RDBlUFUwcUoyRXdoekpWVjF6
            aVZFUXJPaXdjQWlYTWFhOGJ0Smc3LzQKauoH/lxRmw8nv/5Pewmu/LKewoblNYfM
            IqP66DlOcuelKS8Il90ApnoTtE4Tx7snwjO3lZsuK8nPvtbfhFuk9Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1y5txpqz0vyyq03yyysmzuyvuyh8uzzpcw30cp5q3twxnwenfzpvs48ts0z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0RnlNRDBlSmx2T1hZMXYy
            WXRjdUFCMVN2TS9RY0JvN0gwUS9TU1A0MHdNCmNSTnl5K0J3bGJBSEY1R2tmWXJN
            Si9PdDByQXcxMUZkWlZvRGVIc3Zpb1kKLS0tIHp0Vk5zRTZEeUVUNzlCaGhYUURr
            QjdkSWRPamkvbHl6cjlWeEUzVHROWTAK9Ix/EuH2AsLToZTM40HA0t19Bxq2vyKQ
            GZMuvZz4Ay15ePRVuhDbiSw11UrZCWsEuj4DGA5MJ4Sf3qYbE6y3kQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-28T16:05:06Z"
    mac: ENC[AES256_GCM,data:sM+AnFteKdCfCUpqZWcESUwgpBXo3pD9k6VQlZg/foFwX4RkSnrAr2vWGRqsIBp5z6OSMi+VOP5qJaYhhS9G9HQDfzPTcyjjzBJd/S5WtgVbz8jI5zoJgOo5n7Sxn1IAa2OPV6AwR+yHNHkvx7ky5G6xqq2PF9NdPGLVqXxnXEU=,iv:UC4ew0Xl+Ovc7o48PbQrgURd6NIulRlCHHJy7+CwvkQ=,tag:nVDal9zptCOh7Hg08kyKXg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
