apiVersion: v1
kind: Secret
metadata:
    name: aws-backup-credentials
    namespace: browser-streamer
type: Opaque
stringData:
    aws-credentials: ENC[AES256_GCM,data:I8Elj3Zq44jW1xaRTERNFvA3fEJahdb4fXFPZs6oFtT7ycmusqsQXnjK0/ce/VZdg+tIipld3CcStEAOGxc1gOThVEkZ6SOqUD7rlpapubSwqdRzlXbAEQEjF7HEPJcVvOslpRPehMtFVAOYeUvLGqfr52PSEBr7qAaZBpf79r4hCYKMw0JrqYfdapOKonkzdlrMc7s=,iv:G2pE3yQQuPowJj2OORo1YwC63W/JmMDSsW5sIt8uNCc=,tag:/v/elpj36Qibscq8VLkkbw==,type:str]
sops:
    age:
        - recipient: age1ase59dknkacq26gemrs9dvwvu8xr8akhfya99lagv5py7c7h7plsmtucvv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtZmNxZkxWalBYUzBDR3Ns
            M0h5bDBZdjlJVEUyalFteGxIUVZzWSt4S1FzCnFaY3dXeUhFVTNIOFRhbHZTSVdO
            c0RhekdlV3lWeWNRbnlyVXE1bXZoaVEKLS0tIFVjYXM1OEZBU0UrNWU1Z1plSWtW
            dWFEY0Y5akdybm5tS2hjN05DUE9SbTQKRDVdFOC0bp4qvoZiELtsa5Fq7Q2M5IBO
            fkIOVqfD74LXXv4wYY4D6i6ih4I/3vb1AshdPNprg1UsSETbaNGONw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age13zs054me9k5h4m8u3hwqw9nz4jg6lkpfmkzqn8mdujjqp76h6plsmlmtpy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5dkttK1ZQclpxdzBLalRv
            cldHc1hkaTZlaXl2d1k3UkhXK095T3J4bXo0CmtHTlJISXhtbm9yZG1aOGJVMUNV
            bDJQRHBnWExKZCs3KzBXT0dhR0c4NHMKLS0tIHo4K2ZEWXJ5RGJCOHBLWE44eEpm
            YThUUDBUcDlGYnQ4WUJzQVIvU2lhVkUKUMs64eyAYsZ3OWppswiSULSJhBhG15gc
            IJ0jC+S9z3TC2qKhhKXkz+LYYs4HJHSBdFSPsbotKB343Qboj0ZtNw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17ttan4es6923ru96408ctjhs2f97mrxq9uw938plgnw6wkstv9cqsaq5cw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIcTMxVSs5NHVoditEL0Fp
            YkNmZGxlN1JXVGxCTWhvTmgyVEF4VkJFZUhBCkF4VzN4ZUkwVWtnMFBjaXlldjFq
            S0RMSjVWOGZIbGw3RDhYVFN4VzMxK2MKLS0tIDR4U0hRQkxFbklkSWNqSkgwTTZ5
            OXFxZmJqMi9Oa0JoSGZ2Ky9zdUFIUUkKgmVtqsrQtpiivkE1daRGW88lIeYI+3di
            l6+IFLUuyN2iWKTumDzikfkQOgPVrh5AjsD052B7IbtrDSYGeV2Bzg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1un8ajg06rd075pff8pglkq2q0g020peq7v23qzeqhuchl4y4kyfs0drxyf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTaEhlM1YxTFpkZmtoejhu
            b2JldWlvV0VJZWw1TTZDRFhDckpONFI3N0ZzCmRXZnlzQTh4TnhFUVQ5U0xsUFl0
            YTJqNWRaVzlCYkRkc0JzSkN5dVZZOHMKLS0tIHc2cXhJZjhXVU1ONmFySHlnSVZS
            QzhMTWtMUW9hYTd4S3hTc1hiQU5obEkK5cN1kJYkFY/7CpLrEb2lfrBafYzljGeU
            7c0u/b1kXKJb3QYWmK5rZ+3CGRzQKHe1R9lwrh7+RJv8iwbxTexNBw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18r3vk6aecpcd69ey7fhgjylg6z37ksfeff6c497mxgv4nwmnyupq4gsfua
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFYTNKWlYvTytSWDdmaS80
            Sk5kd0hjOWxYQXNNZC9oS1BhbElCVVFXVnhzCkNaS2ZzVDBoZ2lCYUxCVHc4d2dq
            aUtpV2VVd2FrWk4xcTJVZE5jOExQY1UKLS0tIHNBZ1FabFJRWG9kdkRjSHFCbHVj
            MTRteEcySXRnSEhrMVl1NUVqbklIWWMK4/rZzRqv8KRfRYt2O1CLZOOjQLxNfFIf
            apNh17U36WziDyX8st3n9bC+aZjgjETLaw5yedKnrJdAmM+9Jsh05w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1emw2e5x3d4cu0x4g0q4lrw8nj2fdv0qfzta6g62m5y24j02zu44sflkxln
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUdDYwNE8wV0JBUXpCQksx
            OWhmNXhhUmhGbVh1eXBRZHNpSzdNRmc3TlZRCm9iRno0NjhMMElKNXZOMHpuUUtr
            US9aRzJVbWZMQWJCSGpueU9GOE9FTGsKLS0tIFZ5bXB0OXdlWnRKYnFqamVtazJp
            bHNKeVNYNlJ6cUpXeUw3UG5UbXdqcUUK3EtHJxn7yRMTO2HPW956D8CpKfB+5o94
            reqtXTtroH6vC37esggYGqsrhJiUxxT920JNGKPaKQV4TfVJjb3WBA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1x9049ry5hz876qratphuc9gdxzuv4nnd06076842zdukl4unvazszfnjf6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWdmFaK3cvb016aTlMMjhN
            L0F5MGlJS2RPM1d3RGVSeTRFeDlCQlBPM25NCjQxZnhKUzNrN3VJSXVKYVhISXRK
            N0hIcktkQlphakdHcXFvejM1RWo4S1UKLS0tIEdxZlIxZzFsa0xtcGFQUUhLTkRR
            b29OSmVwcjNTQVRKYWVFU1VhSVp1ODQKre2YVZiv7PK8QlQWegn5VpBLBjiCLder
            qdH7zfg0CjCLp1IA+6dLgaVbk8WmYJ1lhKEUBi3gikujQQOVzU/Qsw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1y5txpqz0vyyq03yyysmzuyvuyh8uzzpcw30cp5q3twxnwenfzpvs48ts0z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvc0JBclBHNHpTY3ZXajFs
            UXErSW9CRlA5RUI5aUdqMVE4Z2pZM0NmZ3dFCnBleGdpUU1ZSHI4QW9iKzZML0pE
            aFlDWWlLcHl1UE13bHdLdXlKNFo4aDQKLS0tIDhTMXhzaFBGRWFDWEVPaTdYY3Rl
            cEVqRSswTnF3UGZkSy9iL2RnQmZUMEkKk9+kRjYi6rDwZk9eDC1ym0K0xsYYauGH
            mFH9zqyO1A76l4ZV6luiMF3Gwb5pkM47tXp+aHE5obZkhn4tPGLvGA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-28T16:05:06Z"
    mac: ENC[AES256_GCM,data:sM+AnFteKdCfCUpqZWcESUwgpBXo3pD9k6VQlZg/foFwX4RkSnrAr2vWGRqsIBp5z6OSMi+VOP5qJaYhhS9G9HQDfzPTcyjjzBJd/S5WtgVbz8jI5zoJgOo5n7Sxn1IAa2OPV6AwR+yHNHkvx7ky5G6xqq2PF9NdPGLVqXxnXEU=,iv:UC4ew0Xl+Ovc7o48PbQrgURd6NIulRlCHHJy7+CwvkQ=,tag:nVDal9zptCOh7Hg08kyKXg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
