apiVersion: v1
kind: Secret
metadata:
    name: browserless-auth
    namespace: browser-streamer
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:pYdCqTj5iugO3fBYRvjPQ0sR1A/h9eesPiena/9pJjHjfq45F2zfLn01fPW6actpT+p22hT5r7jBfx9yKoiY8g==,iv:c4uw1h9vmDapWa/BxCi8ooYml7nuMQA7dj9toUtyPWY=,tag:mRoYQ+SauNHQmx5UdfPwAQ==,type:str]
sops:
    age:
        - recipient: age1ase59dknkacq26gemrs9dvwvu8xr8akhfya99lagv5py7c7h7plsmtucvv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoN3lPbE9BR2tEdTVPU0Fs
            UUREWmZDdXFMT2FqaXFiQnpkeUt0dHd5dmowCnYvTUlUSjVJVWpMNU5YbDMxQjVF
            SllsaUpUWHZCTG56ZlZ3ZVk1aDBlSmcKLS0tIG85eGpiZ3diaG5meVBGYW03WHFv
            dm1oakZyTm9uRUE1NGl1ZlJzd25oNFEKRhMvdAAYGn4A1YuCX0fFdXHcBzSQcsP+
            NBRtHT/5NH/x0KLgwtTv21uCeqds8d27yQsfP8EENed60EGnBoO/XQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age13zs054me9k5h4m8u3hwqw9nz4jg6lkpfmkzqn8mdujjqp76h6plsmlmtpy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxUncyZVZqa1NQN2dhNTZY
            Z2xxNHI1MGVoUGdFdEw2RnF4cFhrdzVCK1FFCk80MUZ3WTE2VWtmMEhxTmFmdW81
            T3hpbnZOcnIxLzBnRWFOZVR4NzRPWUEKLS0tIFduYnRBQ09qSU5xWHd4TWVGMk1I
            VnF0RStEb3Zwd0xIOWNmSTB1VmY3d0kKvq3l92+gEmV5e1I7tP3XQuJt2wqh1Lq0
            J7QFtJPNLOBW4YxwZy0JE8gwzl3mpZtgwVuE95zZ9skfuKK51VFujQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17ttan4es6923ru96408ctjhs2f97mrxq9uw938plgnw6wkstv9cqsaq5cw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzSjg5ZG1iY2hJVEhUZU1W
            QnJSbUJRMVJ5S3ZNL3V2U3JTMnFxcXNTZkZ3CnRBcVQvTENPRWw4dUFpUzdybUdI
            U09qS1RKZm1zQ2xVeCs3enpxejJUdFEKLS0tIGZDNG5qOW1DT0ZGRFVleTJZNWJo
            VnNWempaTlpvWVBZR3JmUjUyT1BFeWsKOG5W8S8at8SIe62lv4idWbbc1Rn6v2sK
            NMcpPQmk9qvUNEFlH/l717e5Rw8NQJnqL7RS9QpQP5jyOe1gJV7uVg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1un8ajg06rd075pff8pglkq2q0g020peq7v23qzeqhuchl4y4kyfs0drxyf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSUnJaWmVZR2hhTlNkQVZs
            YkltV2MxOFU1d1hKMUQyZmp0MzJVRXE3YlFnCi9OeWl1M1dSUWxXeS9WYUk0ME90
            Wml3cjd5TFN4Ykl2bUprUUl6TmU0cUEKLS0tIG0rUnN6RlNuaVdrQ0d5b043VnNZ
            QUxQOUJmWmRiejlkaFo4TGprZm5DdVUK8Xrk0uDnFO5Gw2HmBTZTPh9OlSYQ/RVb
            blQN3SnWqkU9x0gtlZP/rtovYujqwIqSFlO+pRfkbwbL3xm/rlBkdA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-07T21:13:00Z"
    mac: ENC[AES256_GCM,data:mPYM5AjwA6vaIbyvGlbHT8k9mV/I1jix/pGfGLpixVQLbE87GfhyMmIZvcwKNsxD1b4ChgoNXi57mMTlxALQkIMnrnMwvvKGEhHL3AmG8HfO5JY2RAxqpVN6lFv2xf4TuKjGoecmz/Y76hZEUZARI+NBSaM9duiRskGHD6DNKSQ=,iv:APFaZo4iCEeC6SbjJHSYZcU1+FhJxxemngc+1wfwNVY=,tag:m6mtQKAwesAE5InxoApRGA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
