apiVersion: v1
kind: Secret
metadata:
    name: browserless-auth
    namespace: browser-streamer
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:pYdCqTj5iugO3fBYRvjPQ0sR1A/h9eesPiena/9pJjHjfq45F2zfLn01fPW6actpT+p22hT5r7jBfx9yKoiY8g==,iv:c4uw1h9vmDapWa/BxCi8ooYml7nuMQA7dj9toUtyPWY=,tag:mRoYQ+SauNHQmx5UdfPwAQ==,type:str]
sops:
    age:
        - recipient: age18r3vk6aecpcd69ey7fhgjylg6z37ksfeff6c497mxgv4nwmnyupq4gsfua
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYREVqTEZ6ZlZ6UG9FNHRj
            NTdRdyttdEZPWkVGVjNpeVY0K3EvbDNYRWtVCnFBTEU1U2lHSUhTL2p4TGNBZCtp
            UkJvVVBLVVRBS0RyTXVNUHo5UXF1MXMKLS0tIFZIekovYmh1UXp5YUlOVk5HamZl
            ZFZ0ZzdqaVphK3Y1bEtaZm9jb3BJYkEKvZHUUKwt45NWst1O6Ibpzl9RxOGbM1hp
            5v9RhKBhn4IuT/tVGjzAXHEhVlPbEU9rBy1xHDT4WWp3c/gbzH4vRg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1emw2e5x3d4cu0x4g0q4lrw8nj2fdv0qfzta6g62m5y24j02zu44sflkxln
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqQkdOWEdHejRrdThaV0NC
            MVMxbFJ5SzREVXVyZzQ1Z0dVWXpDSnZkWFRNCmhzdnFKQVRYcWhLRXM0azRXckR3
            cWk2dnFzK2U2bEd6RElsbXZIVWVPRkUKLS0tIFRyUUlWZUtZOHdpL3NyT0gzcUdK
            SGs1cithTERmcElWaUlmdWV5U1Q3azAKa3PtXiYe8OCCc/UFq+fbRtB/ksVdrA7A
            y/BgV/QtGKZgnb1V1dvclbuhEcOU2xLjaxT55DRShcP2ha925V+fXg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1x9049ry5hz876qratphuc9gdxzuv4nnd06076842zdukl4unvazszfnjf6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhMUozbm9ISGZ0K3A5OFIy
            SStFeHhKaGdsenEwWll0dmZJNnhhMnlydW04ClBEb1YrQXpEMStXUDdpMjlJNDc0
            WG1jaFllc2QwekwzYTdvY0xNOW5tRmMKLS0tIDh5TmtzQUVaMXhlcUZSd2xrVTRv
            alBiS3BSTWxXVmx2dWE4S3VGdUpWTzgKnM/355bB4xjwhhXsnVnMQdnormGlQeNw
            ClxQVhTOU+EFUxlRkb90QNinNxNHtEmfat4Nsi7dmcJUtMEXchRa3g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1y5txpqz0vyyq03yyysmzuyvuyh8uzzpcw30cp5q3twxnwenfzpvs48ts0z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTb0VlOWozczBMZCtya216
            d0dwYkw5QU9MK296Z0NVaW1kNVdhUTZVaVdFClJmdk1sUWZzUHZvRDRyTkFDeXZT
            NVBTQXdyWVhlUXNSNnhmWE8wSzZTV0UKLS0tIGM4NmJwalVqUjdHM1crUWo5azU2
            ZDB2Qzl3UzQrVHNwZ2FtNGFYUzc0cGcKZvcUMByaxGcB5A6fR85QRq/1FGOc23Xn
            LR3ax2/gwlwEVl5Et+JU6BwQswNeNxco3YzGkFj43MhaZN+wo3LXIg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-07T21:13:00Z"
    mac: ENC[AES256_GCM,data:mPYM5AjwA6vaIbyvGlbHT8k9mV/I1jix/pGfGLpixVQLbE87GfhyMmIZvcwKNsxD1b4ChgoNXi57mMTlxALQkIMnrnMwvvKGEhHL3AmG8HfO5JY2RAxqpVN6lFv2xf4TuKjGoecmz/Y76hZEUZARI+NBSaM9duiRskGHD6DNKSQ=,iv:APFaZo4iCEeC6SbjJHSYZcU1+FhJxxemngc+1wfwNVY=,tag:m6mtQKAwesAE5InxoApRGA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
