apiVersion: v1
kind: Secret
metadata:
    name: clerk-auth
    namespace: browser-streamer
type: Opaque
stringData:
    secret-key: ENC[AES256_GCM,data:n8oMAwNG+lQddxYtpCwKlqSkYCnv9AHFNgBtFBTsw993P9RoddY905H8JJbouqzs8TE=,iv:cysNu77Dieg1ZM2j5eDJNYiI4Na/JbpYFDUMdLGS7S8=,tag:bT3BA5GP2nlh0U+qJ26Rxg==,type:str]
    publishable-key: ENC[AES256_GCM,data:FMsHudFVRrzB+gDMMvcsmyqj8sHxuu/9WLBuRvR7,iv:HZPI5eFRyu8b92Y9U6GM7npuBCQs2p9mQ0zUT1l4pCs=,tag:f/LbTVrYN6ML9fE+kPcsMQ==,type:str]
sops:
    age:
        - recipient: age1ase59dknkacq26gemrs9dvwvu8xr8akhfya99lagv5py7c7h7plsmtucvv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSN0pOem5GcWhnTGRwUW43
            d0twbEI5SnJhNk91aVdmYlVUdVVERWdSbEVVCndGUDZvWGlOUVppRHVFR3hHRVFC
            eHFSMk03UVZPVzNPWGp6K0xMSi9vM1EKLS0tIGJ2bWxLaXhqQzdSc3lVU283M2tN
            WlhGNnpQS2RObFIrZVU1MmQ1UWw3MzQKf0OGEPzflbdFWsXV8BhrNNBBZJaCKTO+
            uysP18j50biC4iDZPrakH6xRcqYZLOOnTyksLp6rlJG8UGABnpOATg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age13zs054me9k5h4m8u3hwqw9nz4jg6lkpfmkzqn8mdujjqp76h6plsmlmtpy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1YUVvdHhrcTdRcFJqdERF
            VmFvU2hzMUM1WUliYVVNQmpsdjhJVW9ieUVnCjU1d0JGQU0vakZoWldzYUwwK1J5
            aEplQmYvOEVXdmdpZzRPRVpZTWgvVGsKLS0tIFpSVEdEemo2ZmgyS1dWL0J4WUdD
            UjFHblo3N2l1UjVnaXFaMVR0Q08ySEEKRvX4QayzJ0gI96XTJ4CubHCP4NT68shw
            ybxbu0JGFGkih0kqwqPLDaSuyYPRKiFORidfqkhyCL54gOs+VW0Q5Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17ttan4es6923ru96408ctjhs2f97mrxq9uw938plgnw6wkstv9cqsaq5cw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2djVJRDk2dW1qSzJKS2pT
            Z1dxbHg1RzV2ZGxPZjNtbndhR1dXUkZZZldrCklpMTB5SFpVVDFqUVU0bGtGYlNw
            YlE4YUNjYXBkTm5Vbldkai9sbEYwcm8KLS0tIFFlbkxtMzhMd1VWcnpCcFhqRXcw
            ckVpV29qUmlaN0x5b1lIOXAzQ3ZQWmcKkdVtVTq6G8XJ4KWjb18RHrCdrcWSmoIt
            7/WcKMJwL27b1chbrN3S01+ZQNe/G3OnHJIY2H4FgSJn/EJ9XQcBjw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1un8ajg06rd075pff8pglkq2q0g020peq7v23qzeqhuchl4y4kyfs0drxyf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6b2tpRHEycVBXSDhJN3JX
            RDlzV0hqREtPRTVGT2MyMDh0akQzc3U3aFI0Ck81UjZ3QVBKQTZGd09JN1JSRXN3
            UFhjUHBUa29NaFZpVnZYZUVLR0hreEEKLS0tIC83d25VYnZBOG5iZ0p2RCtQSHRy
            bHJNS05HczNQNG1CVnVpS2ZvYXZhSEkKQ81nH4qzkQEEIxGB+tqBKlE+eU4p40+7
            uahyvSOoU7emcjEq90p3pbX9FydExZwF+tO3yzxhodt095dnhLoEBg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18r3vk6aecpcd69ey7fhgjylg6z37ksfeff6c497mxgv4nwmnyupq4gsfua
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4N2pEVWlyMlhBcFhtNmE5
            ZDJibEs2aDVEZ1o1Ym9yekpLOGpDTGxZelg0CnFsVVhpK0ZkQjcwNmpBb09TYjFW
            bDNuV2tLOCtpVmVZaCs1RHhhZUZrejgKLS0tIE9PbnN5QllVNWdZamxuM0pvVjNH
            U2hpMEs3dFZ1VDZGN1FBTWorNi9yRjgKiJDQ3KxNCnwI4pjHPpR0aXs23gs/v92S
            GO5G2OlnloWNqb2Z2Jy7vrcRRXmvzkIsJC5w7k8NRLUtZOilZp4uVA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1emw2e5x3d4cu0x4g0q4lrw8nj2fdv0qfzta6g62m5y24j02zu44sflkxln
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzR1JYWDNNTFNONGVJV0tQ
            Z0xsM1A1ci9SUDJlT290NG1OZWg3dm9Qc0dJCjNZb2hPQTlRREFGUy9mU3lXSzBH
            OWtGcVF5SWI3bnNYN2pvWU93djhiTWsKLS0tIExkenNCczRrdE0zb3NtN0lXT3pZ
            aUM1TnZyd1dWSjlqWk5xTVlzVnlwOXMKI/RnD6YN+p8k0/eDqBtC4WWWbtAG09hn
            dWoT9RcOQG/5YI4t4se2zWUISgHaX7JlybcFMlqsLw571bvyJl5Lbg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1x9049ry5hz876qratphuc9gdxzuv4nnd06076842zdukl4unvazszfnjf6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWZWNYOTI4TWg5RGJ1MjdE
            bFZid2thSXVRQ04vQVR0SWpER1YxMjR1TlJBCmZ5YjBJYTlDT09oRWlITkM2WjZH
            bXhJSEYzcmdFaEFjMlhnWXN0bERkTHMKLS0tIGVjSjZZS0RyQjhQeE83b0cyUmVD
            SkJ6NVQ3WnpFdURGK2M0em1BSitQNUEKdyDGNHEMisA62ydLTCcv/RtybJM58xwN
            llvxsTeDvoUSf8LonBXaBJcmqBPwa+hwGCioWLgoCp/mSiKzr/mPXA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1y5txpqz0vyyq03yyysmzuyvuyh8uzzpcw30cp5q3twxnwenfzpvs48ts0z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVS2hmSUpQbHZnOVMxSWtn
            QUxMMEhXUEIyc294NjFlbk03d3RFZlFtN0RjCi8ycEh4enZESEs1WmhTVnJFSyty
            TmF3MkdmcDJQbUU1RzZtbGM4VmNtSlEKLS0tIG1HZzBhZ0JwdkRtVElJcXhBVVZV
            SFhtRWNHeTJzejQyRTF1bzdkNmhCQUkKelPkEaftRg+B6mOTEHYxdTMdGd3O0V6m
            L47TObeIDeMJuIPi8LSTxXw63HERJWJJzngGTIUtf/Gpdb0Oszb8wA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-28T18:34:14Z"
    mac: ENC[AES256_GCM,data:CYA2FN+clgKMtI7h0T19mp6AIkM9YuPiB+aFB4QpnbtSeESU0ctxa3T8r2GNKPsjgWV00QAvoL/PfEvCG7uddbuqAtDbKogX8P8YWqYEEv3S1q6Ax0Lh7iVVblJ6KZim9CEsJMhyWr3+9QRh/zfpE7och8a+84GX4+LXDomc80M=,iv:tPJkFhOY4Lhc9Um7gBmo9plgz1XnFAW9n+xQzEz2290=,tag:zMpcuqBhk4mZ5Llmjy74WA==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.11.0
