apiVersion: v1
kind: Secret
metadata:
    name: clerk-auth
    namespace: browser-streamer
type: Opaque
stringData:
    secret-key: ENC[AES256_GCM,data:n8oMAwNG+lQddxYtpCwKlqSkYCnv9AHFNgBtFBTsw993P9RoddY905H8JJbouqzs8TE=,iv:cysNu77Dieg1ZM2j5eDJNYiI4Na/JbpYFDUMdLGS7S8=,tag:bT3BA5GP2nlh0U+qJ26Rxg==,type:str]
    publishable-key: ENC[AES256_GCM,data:FMsHudFVRrzB+gDMMvcsmyqj8sHxuu/9WLBuRvR7,iv:HZPI5eFRyu8b92Y9U6GM7npuBCQs2p9mQ0zUT1l4pCs=,tag:f/LbTVrYN6ML9fE+kPcsMQ==,type:str]
sops:
    age:
        - recipient: age18r3vk6aecpcd69ey7fhgjylg6z37ksfeff6c497mxgv4nwmnyupq4gsfua
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0NWY1QWM2RHlaYTB6MkVi
            SUNWZm9JTUlxVWJRZHY3cG9EK0grTVBFeFQ4CndOQzJhWkt4bytnbTNJTU9wcHBU
            SGNSZnJ6ZkZFRHBuejBqL3IzVGdCdjAKLS0tIFJzdmZmOFNTOEliS0xXVElrRWw0
            MU0zWHNPQmRPWjlidkQ5bnJ4Z0RMYlUK87mIBjyAxAvyMx110wxEVSlXF1gu+zF5
            JrbVi2VFQB8qb021ni5u+Az5iAtDsojT3Xx+eKWfZTgfOIQrbFknQg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1emw2e5x3d4cu0x4g0q4lrw8nj2fdv0qfzta6g62m5y24j02zu44sflkxln
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqd3NPSVIrOXNZMGNMRmRu
            ZmoxZ0VuQVAxQ1gyUFpCZ3Zhak95M2JFbjNrCmhmZkNRZWl0ZFMvU1BZc1RjU2FH
            WTN5WUdEVDQzY2xiZm9oSW16T3pjSkkKLS0tIGcwTHJTeEJuc0h0QmFlc0hqK3ho
            Q1Q4U2ZNZzAxa2ZhR2tmT3hpOXpkSzQKCjo1xl6+svZ3GItbatU5TfIz0Gq261+N
            Zkh3YnKMU89ghcKc6Okwclc3joLkowQbNPxNcjuOC8nFMveH9FQRog==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1x9049ry5hz876qratphuc9gdxzuv4nnd06076842zdukl4unvazszfnjf6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4eHZCd0R6MzlGRjlFaExL
            c3B1U2R3ek43RE9xV2dwOVRxSUR6bkRmRUhvCm5renpQWUZLMFIxZUdXamJ0VUNp
            T2t2cnNkZGxmUGVwOUpCa0grdnhLZzQKLS0tIE1PRlJlSk5WT2NFTjE1bGEvT00x
            c0ZHYkZGOUNkN2t5N1h5eDZPdjlZWU0KJAtPX82pFCXlgHJe99gwCAY1TzWWuJia
            EeRo8e/RFNDmmvyvnt23P/UaWFXc9hqyrMft7bqnLxEvDB3Uit2WSg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1y5txpqz0vyyq03yyysmzuyvuyh8uzzpcw30cp5q3twxnwenfzpvs48ts0z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPUTY4Nm9oWGl2YXJBT2Z1
            KzFYQ3BCMTcvdTBrd3NEaVdvdGFKNEU1MkZNCld5aklNQVJyTFhwMHNXSmZPV0NO
            Q3VMdytKVEU3YjNHMGZEYlMwY1M0c0EKLS0tIHp5NFJpMDdMR3Q3czhlR2tKMDVL
            VW1wMHR0VE80d1lReTNya3Q4cGo2dkEKEXRivfs+Ht3eqMYyBZiliFgi1H/Zc4WL
            PSXZcnI7j6uBywzxzPdc0D/qbxwf/tDnMcC0ip5aBHlbQVojwlIjXA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-28T18:34:14Z"
    mac: ENC[AES256_GCM,data:CYA2FN+clgKMtI7h0T19mp6AIkM9YuPiB+aFB4QpnbtSeESU0ctxa3T8r2GNKPsjgWV00QAvoL/PfEvCG7uddbuqAtDbKogX8P8YWqYEEv3S1q6Ax0Lh7iVVblJ6KZim9CEsJMhyWr3+9QRh/zfpE7och8a+84GX4+LXDomc80M=,iv:tPJkFhOY4Lhc9Um7gBmo9plgz1XnFAW9n+xQzEz2290=,tag:zMpcuqBhk4mZ5Llmjy74WA==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.11.0
