apiVersion: v1
kind: Secret
metadata:
    name: clerk-auth
    namespace: browser-streamer
type: Opaque
stringData:
    secret-key: ENC[AES256_GCM,data:n8oMAwNG+lQddxYtpCwKlqSkYCnv9AHFNgBtFBTsw993P9RoddY905H8JJbouqzs8TE=,iv:cysNu77Dieg1ZM2j5eDJNYiI4Na/JbpYFDUMdLGS7S8=,tag:bT3BA5GP2nlh0U+qJ26Rxg==,type:str]
    publishable-key: ENC[AES256_GCM,data:FMsHudFVRrzB+gDMMvcsmyqj8sHxuu/9WLBuRvR7,iv:HZPI5eFRyu8b92Y9U6GM7npuBCQs2p9mQ0zUT1l4pCs=,tag:f/LbTVrYN6ML9fE+kPcsMQ==,type:str]
sops:
    age:
        - recipient: age1ase59dknkacq26gemrs9dvwvu8xr8akhfya99lagv5py7c7h7plsmtucvv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBU2JJNG8vNWQxU2dobVZy
            SDhzNEl5dnRrNmZJdVBFVXViM2Y5VVlZMFJzCldrdjJCYkdqZHVHd3Bkbk1pWHd1
            SDl6RWovNDZhWU9ZUWN5TzM1TzJPczgKLS0tIHJEeHBkcHBhVnJnYkpScm9GTDN0
            bndSSk9Md0FFVWtYeExSbzdaRUF2cFkKSr3Kk5YhGqrCZ4iUkXv3MqWoMWyVAiQs
            qeDFs4srAf9Dt6i6nlesvRyXthnfbGw5eNYq/Hryw6Qn4FwIl/nHuA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age13zs054me9k5h4m8u3hwqw9nz4jg6lkpfmkzqn8mdujjqp76h6plsmlmtpy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsVlZ6K1RuODl6VVVOZnNz
            c0tSbFh6cFhvSzd5NnlmZlQ3Y1VUYWs4czJjCmFwbWNmenRuVHNLSVVzNDJrejFZ
            aGlLTTRueFRtU05ycnRPZCtkcHV2djgKLS0tIEFkZlpSRENmbjlVVVV1U3JLNnRF
            b2lVOVJaVVZYYTRhRUMvanVWL3BmZEkKlt/JwsFEZ+cpLryM3Ae42h+2ONqhR7GG
            namssc+awuOQiXbOpPbzPvySQMb3T2wmjdjp4uD1q45MnQNqryY6gQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17ttan4es6923ru96408ctjhs2f97mrxq9uw938plgnw6wkstv9cqsaq5cw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlQzV5NW9tWnhpTXFyazZ2
            b3VKYTEvbXB5b2UvMENEbUovbXhuRDdHTmd3ClNGU0piM3o0ajFjSkZRcUpCRi9m
            bTY3TiswMXBIVUY2T2V5MWhYUW9SaXMKLS0tIFFrNzZEcjV1YXVSemlnZUFhdnZY
            QmpvNDlaV3R3SmZhUWdydFVPUDJCTVkKeYyrKQNzvZaL7GXMBprlyYCiE8ayI1jf
            VwnLEyQAW+DwCj2V8XyTKj55B3Zz6vw2B4MmaeGDNdplj2NRmnPpAw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1un8ajg06rd075pff8pglkq2q0g020peq7v23qzeqhuchl4y4kyfs0drxyf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1NDJraFVxaTNaOVJ3UkJn
            NHB2dlc3eGJOZ0phcWdPMkFpT1YvZlhRNnlzClpPb3hqZ2U5d3FRTmN0eXJwNkpJ
            L043eE53WUJ2OHRybHVJd0hjVHNkMnMKLS0tIGtzUE12TzE2NEpwNHI2T2owWHJQ
            cEllYXA3OGZXZ1IyZTEyVmxnT1IxQTQKj/Ggxq6gDcw2/bS00Vw2vQ/NWpiXWLWE
            ATzbTYJiNYVdlKwZ8xK40nYDLLlxZeghPRCusTSDxG6USw7/zOXSEw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-28T18:34:14Z"
    mac: ENC[AES256_GCM,data:CYA2FN+clgKMtI7h0T19mp6AIkM9YuPiB+aFB4QpnbtSeESU0ctxa3T8r2GNKPsjgWV00QAvoL/PfEvCG7uddbuqAtDbKogX8P8YWqYEEv3S1q6Ax0Lh7iVVblJ6KZim9CEsJMhyWr3+9QRh/zfpE7och8a+84GX4+LXDomc80M=,iv:tPJkFhOY4Lhc9Um7gBmo9plgz1XnFAW9n+xQzEz2290=,tag:zMpcuqBhk4mZ5Llmjy74WA==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.11.0
