apiVersion: v1
data:
    api-key: ENC[AES256_GCM,data:S85XNiJhxoy2NpBsRnPSs5Pio+8pOeUa4yr4FlNzKRNETafaIl7onhn5SDIB6lGncvZN306QvsS7mO6mCCIZQXxi/1Q=,iv:me/9H8MJUnSTRPEKmhM36MJmcvp7jDzs+INEMvKtjR4=,tag:3g01d0QXs4ogHknIinmZDg==,type:str]
kind: Secret
metadata:
    name: dazzle-runpod
    namespace: browser-streamer
sops:
    age:
        - recipient: age1ase59dknkacq26gemrs9dvwvu8xr8akhfya99lagv5py7c7h7plsmtucvv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyT2RtK20rWGsrRThJTXRD
            RGhLQ1hZdGFSWnU1QVlmU0tJVjRUVDFNakhBCmU1aHA4WVhmUk1ndW05Q0NxL290
            NFExUENjMk5nanhsNllxQ3IwQ25ESUEKLS0tIDJJeUVVWEhKbEJYTUlKbmZrTE9Y
            b0c2c3ZBQXAxOWhlQjlCRTllelpiV0EKwxT9w9m6ZNnBDYgYrP13uUzzdcr9RS4U
            4Q/CUktRvggU6qbp3lpvvlrQvIR8gFCw9OSOePM6Y1rkaEsfTHkYKw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age13zs054me9k5h4m8u3hwqw9nz4jg6lkpfmkzqn8mdujjqp76h6plsmlmtpy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPa3NOcE1rM0RXd28vdGZj
            bjBRQ2xCZU9kcEJkU2J6b3F1V0VhWUZEeHhZCkVVMTRjMmVTcnowa2JKWmlIQ2Mz
            VkdQdStaY0oxcFlROUZ2ajJiQkJOT3MKLS0tIFJ0Y2pTN1JqZ08zRHBBVUdQeEdn
            UE9NZHVodjJ0dzQvWW9uc0hoTGNxMzgKp2HoZCMciZByyjEG0SAZ3i2p7NXQckzd
            1xHdPeYlEu5UaoxtgBczZgiguIQnK8hoKo+J0cIzZxhx/HrCGu3MGA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17ttan4es6923ru96408ctjhs2f97mrxq9uw938plgnw6wkstv9cqsaq5cw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvUkdOcjlLUXJReVNZZDdh
            VFpBYnVYTVYralNaTmZmNTAyV09nUGhyNlZ3ClJQWTJjR1FpUVo5b1E5WTJFcXY0
            QXVNemVCUkdHOWI3aXhlaFN3Q1VJMTgKLS0tIFJhU2lZVHQ4cWNpYmwxMlJVaENY
            SG5ON21CVml2NHVlRVJFUUZPZ2FHc1UKLYTCsyyXdaAVjitJU/usOW/JNP6pKSll
            kDeBLtpsnGi+GQlhDJOOc6S4uf2bPPG416rJBsn5uke+cABMGMRpuw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1un8ajg06rd075pff8pglkq2q0g020peq7v23qzeqhuchl4y4kyfs0drxyf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0TDNvMnpXb1c2Zk8rQ1Uy
            VzZ6S1FqQUw1bTJFTWdSbnpINWFDOHU0Y0NjCkdWWDFEOEg1cU0zRlc0NHdmVTU4
            Z3VmMlV0VW1XQzZIN1ZJN3FBdlpqLzgKLS0tIE9Vak5tY0JRU3JrY1RiU1c2UWMy
            TFFWUXFWNjcrbGZhMElBRkJVOXdkcG8K7lVmOdlZ9HZrP4zQgBYklkRKQX7wcFJQ
            fhA/SWTs+bjb6yh/mQWhCwtTrf7ctDjRn4wjqDN47nDy/GuTfDJVQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-12T02:07:45Z"
    mac: ENC[AES256_GCM,data:ntaPonJqMrK4ZJYRiUIf5dPAX02D0oQk7sYUu/HZmZwxYZjP7/veCkeDqdXoHiXpjTpK23bUGyARWFn1F804IvN5RmwZX4kWc4EStowIQn2zsh7GEhNfzb2VkUXn3yJRkP8fs14WvTYYcAMk2WVuxtupbmIMMf8xF5mItStYHOM=,iv:Xp9AlCiElHrYoBvl539iSWe3SlKHpxgDRMmZ2xTe4RA=,tag:zrDPXQgZBQmeHmwdlhQQ4A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
