apiVersion: v1
kind: Secret
metadata:
    name: dazzle-mtls
    namespace: browser-streamer
stringData:
    ca.crt: ENC[AES256_GCM,data:gJFLRzBHXwKTF64OWWBKeOtPguLMm0TaVHHx1/c/J3SY0Ko0gophWC6Oag35YHRzBvejtmOvo07O777/2BiSHr1NYBZ/ttfpjtfcXaoYipidmUl1IWV6nfSUHVKqHNBU+tM6N0YoYHnMldO+tDKpxayB4DJxoUz6m8cLKqCDma0d9v3ths3gsDsL57Gq+vOd1HoSJ4NjFJ5k++7sGe/+KyQoQ+bs04iqKq0Ct2Dgi3lsxbhQeq1mUF50xn824BWLqgfyBRgEwCPrytyt70mnyelybIbTXAh7si11kW/4LMNr8joa+lYTMuEyr63T3DL9SLHopOFfjKZNAdVwSfm7A6irIPpL48oVXtaVqQdPs8IBF+U1yktISWIJs82j1Vjew4k7bl9xU/BZUztn2xkOaNpmoB+wIaRuRzSka6sT07lQ5h+scyTgHogkIBrKw+Ac21qCRvxV/l0s1KYn7bw3YZ+x/p5s/dEL0LdR74iDZKRYG43sBIUb26ChsT8UzwrMwDr7kii7//3z35jFCkySf5OYXHU+KpHP6bqmfCM69nWFo8rnZtjmE6NIWsIj2DfBY3uby1IUuBuWqHDCzQPC6u5EvKPbGrXJJJh7xstthRGTgwmkAFB4bWwOBapvXBzg9HPL79h3f/mB39j8ir0VlM5tx3M2nUmklMEA2B0vJvtYI8VYyV2fPEMVa4Mo0tkNMXIm+FJFI7z9tr3nko9gRN7T5kI3aRGkq8AC77QYPFDLLERFuGPFe8y3grKfFWoRwHvqI388NihpSmz5yBbR,iv:07KpJmIG0A0tdRpZF7RUUFySPzPfRZNguzrojd3y6qg=,tag:4dBMqNhmv6VhjLo6apMw+g==,type:str]
    server.crt: ENC[AES256_GCM,data:pAszfOhabtrMd1CA2jDWcPrwOTuqvDLKsc/cs5cFPdd7Mf7Cuyw/ZKZALQUHev5TOR5UU7LDrP5U1kOLTrHRPsXYG0PRdZOGr77KrzESUuMGboq8Ntd7/VhJrMPydoKia1K60+053DdvHsGqRPdZUGm7fxrE/YGRMjqLdGoEaJS+w8X5LrHzM0bgfXgAf1CgTxKcrbMxt8RqMCL3De1PpgfFR/usjMRG5RY554K2o1wyxMcryqD8kb+svrMKbv3PdVwyZ3UUHT7Mhnl/Ei5yPliKssBR6TkxxYGI8HsuEARhVbJLL8M05q7PaSah4dYEZPrjvml9CRB/8Z8JtCioFsmM1UuY5UyOBDtAU6FEIyg/4EOUsUN1Z2r5z3VKuAOLeqsFKhjuE4l9mzkhcybYe+YxKYbKREN7YQlDRiZeILPZrjzJid9wXuNTfkMg5pSw6CpnIPKCmb1c3GFyWs0gMmOYZ09J4F/o/XZHNlfK1JqfJwyH50KM+vNHZi7V1+yg/GmuVd+jt/kdB0De4N/HI8ql4ej/sWH3xNmIYpbUPlVlK+rVsLgJaciPJmPYB4kibk7jM5kPq52eIMRLgKiWujsRzDntKBnjPHpCKg8oqg0t/rAUTKG8PDrMTqrNiA79njWHmINwG0Iz1FLDm3qRNrc/zKL6OKhOqRDcj67A6pnNSaibiMZEwsQbcAdbrjN53KP76Et93+iOaG3tvXlYMW+jzrvrQmSiA/WEu5Nz9k2dbKjEuvI=,iv:Xs7KISIseFuDSL/NXy/RZZNZicZqf8q5qI9P3rJp9WM=,tag:RHfd2jj2eT/h5KbNC9yyCA==,type:str]
    server.key: ENC[AES256_GCM,data:F6EdcZ+b0mgkSPhXkOxLYLBpnOwpxVmTnEHnkUSFQ8+uwRsrrcIohfjOcEbU1KvuLqowEMBzatw9aE8b9k2JyoHInycIZxSBGc1+lzvqq98RmB/5xdI51IJoNu/GtYrJVMwRv/S80KSgkZAwNYs7t0uD5x26utXsde7lcziCfIeSPWYWdBzH3cq3YHAiSxHt3sch1N4e4vN1vgt91ytN6gixf4eclTYJPSBBssfTw4YAwolaRrbeI3J/G7KFACiosippV887lfFYmqOfuq25N4jmYk9beLAe9bqz7BHuvk2876AgdmsYBwdusDxWR7t6LSUhbyRnIh/A9iVAAs9X0kyEA9rnf2GLrxvqK3h0Ydf5oHb38j5G3DITcZ0QC5kSzb52khzhNV8j+ypf8cg=,iv:BktU1/UAH3KhR1XjNUVf8MydtSbKVd3O0FUeCq/6B0M=,tag:MxTQ6BVmGNJ8uo5mm0XpXA==,type:str]
    client.crt: ENC[AES256_GCM,data:Bj28nkZmMEKsWTCHjv6kY6g83riOJpLxboAGcx9rEd0qcutTlggcnAGj/3sSe8LiCHQLDDsK15Z3nGE3quUYkq9fg0v9iVdjglgvEFIkC3aRt/VpLkMkaLuEYTelr0nL0ACYxTw36+NQicqNBG77j0vIWLndVUgcAYqpC4LMOnJN1sdcPMgDoP3Vb1ykKxX5oOcjU7f+2Fflco4loj0HF9aHDk8PfVZr7bOXOiykDfLgjFCBH+ALuRWOcNWIklEHcBwvuiszjF+qVa/LEC9PszzW+1E2D/006OaOHaTCFQfeJySmQTOXmQcFipI0zsTJm+gPRe0F0vmAfLOaRyFfsCjLq+dpsn/3FPpK1Jsr5AieOOxGdXGqKZRRNvjXgaGpXsu/38i7vNTqQ/cWHxGntB5aJU9AG+nB2T/lJZt6ZqHjjADBZbklIhbklKs4iFBLPf1FPv/t5k3arnO51lzUmED70Fq7E42gKLga3guCvm2QCtXc10QgDiO1qCHlds4lRpeJAnYVBv075aOPTh/CRuGu75ktKr8ILkkRf7BsiGC/YJSVib5mq4YNCg3N+0wglptNqTCEmKH2bVpDPQyv8jdpbrI0EohsoEF/Bm+kILdB6RRe+hyNMdiMz2Ww8/1zjPGzJCUpGcpMyEmHXbcN8YE5r9gE4VUVz8VYar2BcZVJQlB7odjpeT7+urWxiinSI6xjddhYQ18MCFeggzY0N3uARIHrmauRZs1nickjXhvXPHRZcvxWASrbCecRIg==,iv:jXp8fBmCD4c7T8hcFOeaWOgXarbqHEdCPLR/2MMex10=,tag:TtcR3tfJCTePcq7HR/674g==,type:str]
    client.key: ENC[AES256_GCM,data:q29jxt25+nucq2sjMb50pxWHeNEDkha2n1II3iAvIa2TZhr0f7fKBtc5Nl6guaUBgqPh3vukFnrd9xmjlOSicq0xpfcsEuWiUlui7PQE1EcKzrQbIL0YNk5hCb8Vorv4Qh4fAE+OzM5TSVgGmth3nMnUwobH5mv7KePXCQFLH6fEodAT820FEiygVHkSBP8bRweMMalcCrJXuyM3BK5qSbfMIey16uUO024sHNg8t/1sFmSx4sylkKhSst4ppvaxWJ4xiVlgH8w+imxUuJeweSm8MxDSIxI3jSZoyEexw9PJfoPR2riBvEIbuCYF3FITELQ7NPbDqLRMACpgRs3U1KfrRx40XkODMH8PcdtKdlpz4VTsTXZw5PND+VC1f/xd92AiI4LDxZboPVTw3KE=,iv:TjjJtga3+NfFDsy5LFag6/uY7lGSCxyoeGyBBj4GNpM=,tag:0AeR9fPcWGDnTW1dkjhcmg==,type:str]
sops:
    age:
        - recipient: age1ase59dknkacq26gemrs9dvwvu8xr8akhfya99lagv5py7c7h7plsmtucvv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtRXppTzl1ek8yRkRYOHFh
            ME5MaXJtb0FGMDREL2N4eFJHOHRzUnI2NmpnCnh3QzZDZ3Q1Qy9aNDU5M3VhZEIw
            WHpOUHcvSkNQdEt3TlFtMTJpanNaQncKLS0tIDNTS2JlNCtOdlc4ZnJ5ckJZS3RM
            SmU3ay9WNWtIRWZFKzNTM1Nta3lSTVkKFxD9ZU0AKyXdpc5zmvHniingXP3K/grw
            bidLB+NWLbB6oX1/mbjZ5lBHj0IcQJkUHrF0m838jB3qWzGq4XG4/g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age13zs054me9k5h4m8u3hwqw9nz4jg6lkpfmkzqn8mdujjqp76h6plsmlmtpy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxeXI0RmZxTDN6WUNsNktD
            Mk1HcEM4RVBNRUYwN3d5d2lleXJEZVEyYlRBClRTMS9sQVlBZDdoZTFqZXQvQzc5
            Zldzd3BnQVU0bHFBdlJJSzk4eWdncFEKLS0tIDEyNXY3NjVIWGpOU21hcEdBVnJD
            SGxrZXFqeEgzNlRMR0VZS21RRkZPVEkKqsvQjTp3oEBOyusrYZklYTosq96IUz7I
            CQRBU120OjFWpBpMC3hxsgqUJTr1NzYpnox3qtT2ReEpSbQapq6UfA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17ttan4es6923ru96408ctjhs2f97mrxq9uw938plgnw6wkstv9cqsaq5cw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYR2VZQkVzSzNRTU1jMkhY
            UElSZEN4c1lXeWs5TXdLdnJUbUkrQmhPNnhnCjJJQkRzdERKR1U2aERvcmVnSHIx
            Zm1XK0RGNVJ4a1ZzdldOMHJ0SEIvVzQKLS0tIFN5NGNiaVIzckNTcm9jektWQWEz
            Y2FmakRqZlBibnp3TTdhWXVLR21OZUEKWzDC2k+hKYLPizPwGTWYO9hqx4DAGXcv
            eOoF2sYwfcZjJytduXT78bkcAY08pF1UqUGlL+9w5Q5Ba5/jerYfaA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1un8ajg06rd075pff8pglkq2q0g020peq7v23qzeqhuchl4y4kyfs0drxyf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2MDMxL1V3ZDhwSE9IWGxP
            NTRUSUpXQlhtcE1YckpLN05JMjlTNEF5ZVdRCjNna2lDbWJwRDBldm54VnlWYkw1
            d1c0VktMWkc4TFVHZHkzc0ExWXQzb2cKLS0tIGhLSjg5OElsR0NqUmVrb1QxaFhq
            bnNRT2tOdUFnbU5jTUR2dk1HNUVySkEKpu3v3HjLB9tlTnltPJMkE2gV5hj2WOwX
            2qlsKHRdIT4H051gLBZJGWm7Oc+HmVD1ntwZV/FQa/knNeSCoiKj7w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18r3vk6aecpcd69ey7fhgjylg6z37ksfeff6c497mxgv4nwmnyupq4gsfua
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0TUNUOUZBZjBPRzk2NFVu
            blE1MUl0aXVtSEVjN1hiVHRYblZlcE1hNVc0Ck8wNWpsSWFXZFFJbC9tdEdNM05h
            cW5BU1NYTzZ0UWxjVi9rRWpJbEVXencKLS0tIGJvOWhqclQyaUFQSTI3bXpEUnhF
            MmhKbzB6dEJxOTVodXhZR1VhaFJ6b2cKe99HbepR8ruoS0Rnab2ptKlq6ogc6VBp
            cNX5EF3Eld7wVrpQrV1imHYiE0eTMJuJ/mgW9kznhOCwNAfZ/VhUnA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1emw2e5x3d4cu0x4g0q4lrw8nj2fdv0qfzta6g62m5y24j02zu44sflkxln
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuaDZ5aGg0ZW54MTVxMTVZ
            NlFRaFQvTTZ2TVd0S0VrOWYvelVjZ1ozVURnClZsWUU4QXpzUHdqOFdNc2dQeE54
            eEhMSS9DR2pNWUNTUGZhYnFZYmRiUWcKLS0tIDhEN2orQkhiTFFwNEFDNThUWlBX
            blphMmtGNnVBS3dDNGY4eHprcEpENUEKzCIwphOZn6tVr3XIC6KADUMFer2sZzBO
            0GhMbIuvlfV8TuDrASPS6yHKNaNncqGlk/Q5v7Pjw0lqbKPu3SJwVg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1x9049ry5hz876qratphuc9gdxzuv4nnd06076842zdukl4unvazszfnjf6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1dno4aHdQQUhDQVQ2WFhU
            bnhVR2F1VTRpejVSYkczYWYzaGNJQzYzVlRBCnpQL3lucnVUdEEwN2V5c3ZHRTgr
            TVhXdnF0NFJIV3RpaC9SNUNNcGxOZXMKLS0tIEFlT3cyNDF2TW9uZzNTdFJWazBN
            SktvM3d2RXRXMWFza2kwa2t6OUhrR0EKu4j7u27RQanHl78sf+S3YYOrqtMi/iuU
            wkBW5YVQUC7JRr1/l+0DJ5VDYKVXjEPUg3xL0q38Y1H9Nr28mDpR6A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1y5txpqz0vyyq03yyysmzuyvuyh8uzzpcw30cp5q3twxnwenfzpvs48ts0z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFYW4rUnRzZHNTMnZmSWI5
            cFlLZkRhdjFMdFlWR1NJV1VvWDhEcDJIMVgwCkpkTlVsVmRxS0FEbXVvWVBUNEFW
            ckpBa1NhK3FjQ1FOWExoM29XQ2lvYjgKLS0tIEU2dHhpVnp1MzMyQStvUUhMK1JJ
            V01ocldlRHlIK2lzbmZJU2NRSW5pYW8Ko5SxXm4gQNVx8Qw2fAQ/P+lLFdK62blA
            wI+JsPGSoeZgwysEDpnyrOiuWXAKHIBeYa89PXtQFDJFlJgcqNrAQg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-12T02:05:44Z"
    mac: ENC[AES256_GCM,data:FC4h2ANyEL+7vD4xRCToHP81wQKwemeaqY5eqaAy7UUniWGZvvmmQdMYcRynHfis7U3FsevX40LlECKSlyjR6hVojBf8fRjxARD1pGH0mCMVaIKzsYeXi8Xl+0UuHixNc8Q676yQE+Rm6I1x1ofaTXuhR8xFbNbou+wq94kpmoM=,iv:wx+OFi40bY+bX+Uwjje30o1V6purxxyNrXBJrMXuy7Y=,tag:WlL6fImxvs/fb9HDiPizNQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
