apiVersion: v1
data:
    api-key: ENC[AES256_GCM,data:Ikb6ehBg419KBzrIfFtkmqTiQBxYYdW+cE13WTOTluS5s+uYCc0tIYsetYch/26NolLXs4Ei7JmDktaGSNNZ5ZBi+PU=,iv:kdtizKJ9kFlrvGENubng7XAUVEvP/LDgRFTOljFbdc0=,tag:a6PmD7ejFFNkYk99fiTqSQ==,type:str]
    registry-auth-id: ENC[AES256_GCM,data:UmBxrS0NGWEK0+LavkY4t66B2bQQ9js0+cPlZeOw49mO3i9p,iv:WgjaSBc4ooeStHGBTKd55X8Eg09MUe9h5FzIOPlY218=,tag:rmkckE6qYPvd8Aj/78PfxA==,type:str]
kind: Secret
metadata:
    name: dazzle-runpod
    namespace: browser-streamer
sops:
    age:
        - recipient: age18r3vk6aecpcd69ey7fhgjylg6z37ksfeff6c497mxgv4nwmnyupq4gsfua
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBERGxEVHVUOFlPL0Jta0FC
            ek41ajRPRmdTT3grbk1TUG1HK2R3ZjhyZ240CmgzbFhWeTJWTFFISEQxZEZEUHly
            SldLZ1lqcTIwTE1qMDdXc1VNSGR2a0UKLS0tIHVhQTBaUXNoMkJQTEdnRERsTzla
            WUMvTjhnY3BNTDl3NkNiZXV3V2dMV1kKdG+L5jNLByxisAEAlRIAn7JuJHclGsQI
            Tg2xqblmlS5FpByQDQ5RAX0rL0DQ6vUAZoWfQLI4Jf8nlwxTDccedQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1emw2e5x3d4cu0x4g0q4lrw8nj2fdv0qfzta6g62m5y24j02zu44sflkxln
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtMDFVWGo0YzkzMHN6NndC
            clAvWE9maEpvM080TW96b1RUS2h3NzY0RG5BCmt1ZWtSa3RieS9ESTZ0ZTRTSG1M
            U1pCa25zSGg2TGJYUVIrZGJrUmRRbjQKLS0tIDVQNjVIR2FWVTgxYXltWmNMZ2Zj
            MlEwSTVBNVJMa2FjdTZNSmtRWWdOSlUKBiY6Md6k04sVbBcCXAhUNVTWCwASz0xo
            0v7w3SWfi+i10LJtKhOnb9p1KuK7lQb8mniPJa3lrY4ic/HU91Cd6A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1x9049ry5hz876qratphuc9gdxzuv4nnd06076842zdukl4unvazszfnjf6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPU1hCeFQ5STk4aGRxTG5T
            ekNnZENSMWN1U3p1QjAvNS9qVlJLUUdXVjA4CkRXM0NyRzFOa05wb0ZzT2lzUEhM
            bW83TDQ1TzNtUkxodjc3eXV2bDRBaWsKLS0tIEhQdGozMWRkbXBLdzRkMEMyVjV6
            dVQyNVRBN1hDbW1GZlI2amcyN3ZMMHMKuA3M5DRbDBmjGUdWUU7S+IkyfTdowErb
            rMaGkk57xipchqdESwxTQJPlNcHWe/zyBjmxyPbskFj5W0BDc6K7vg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1y5txpqz0vyyq03yyysmzuyvuyh8uzzpcw30cp5q3twxnwenfzpvs48ts0z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMbkxQdlFGS2tnNTEvQlR0
            aVdONjQ4NkJuUVovZlk1dFpGQ0xKOHRDNTBVCk50dzU2U2J2UFIzUlZiNlFCS3NF
            cHNpMEdJOC93QXZSdEREdlQ2WGVndlEKLS0tIHVRYnFTaU00cDBlYkZtajllTXJM
            QUtmMWR5Um13ZmhwSFo5Y3VGVlkrSmMKD2Pr/a19uIJlii7FBfG0FsRND0Idy03z
            Ul0Kvd6u2Yhil92clREoQ0x0uYeSexK/T6fvKczW5F1zDA3gbXwUDQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-29T00:35:20Z"
    mac: ENC[AES256_GCM,data:N9rAzn+vbkBdE6C3mik8yhfoiaCoKbBpmtJvBUPqMeStjK2PM7/Xjr5Z7yrZ094cyCESzbyAfIN+x6Oq9tWe1PzUy6LQR9fHX5LfWnemOcZgZAtcivk/I06PW5VDFFRYoOfsDUBUl5CPyhmrsiyqDiechajXgSPEPAwqwrMeWew=,iv:zjfkK91GBOURNaAbMIOh2pHMG1JiY2GdR3KQk2gvB3s=,tag:Rvtfp5cN6j7PCuFhcdcIsg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
