apiVersion: v1
data:
    api-key: ENC[AES256_GCM,data:Ikb6ehBg419KBzrIfFtkmqTiQBxYYdW+cE13WTOTluS5s+uYCc0tIYsetYch/26NolLXs4Ei7JmDktaGSNNZ5ZBi+PU=,iv:kdtizKJ9kFlrvGENubng7XAUVEvP/LDgRFTOljFbdc0=,tag:a6PmD7ejFFNkYk99fiTqSQ==,type:str]
    registry-auth-id: ENC[AES256_GCM,data:UmBxrS0NGWEK0+LavkY4t66B2bQQ9js0+cPlZeOw49mO3i9p,iv:WgjaSBc4ooeStHGBTKd55X8Eg09MUe9h5FzIOPlY218=,tag:rmkckE6qYPvd8Aj/78PfxA==,type:str]
kind: Secret
metadata:
    name: dazzle-runpod
    namespace: browser-streamer
sops:
    age:
        - recipient: age1ase59dknkacq26gemrs9dvwvu8xr8akhfya99lagv5py7c7h7plsmtucvv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEVjJ0dU1QQTFGamJWWFZF
            am5JVktsR2d5Y1pkMmFjZUFhT0RxQ2tLNGwwCk9HcTlVSnhoM0Z1UmlWVTJXYVA3
            K2pmaTBOTHU2NUROUlgrYzZZaUZYU0kKLS0tIHdLcWZjejV4bk95WUtuMWI0V1Fr
            YWVlckpGU0JLZVhFSWJoSTNtWVNRT2sKGrQWZw92YbEX5CKWfS/RRe86UxefGrC7
            KF/nHKC8p+l96+7B3wkk22rIGgiOJVLwh3DCfTJfN5+9WTzj9poNxg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age13zs054me9k5h4m8u3hwqw9nz4jg6lkpfmkzqn8mdujjqp76h6plsmlmtpy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDblNyeEdXcllBSWNlNTlo
            bHVwZWE3eGFQVi9JV2E1Qy8rZlNSMXZGTndrCkVjVWxlNmZlQlV3RUdWR2ZBU2NK
            N09lREJrOWFYWnJ5bGFybmw3ZDZPL2sKLS0tIC8rQ0VOWkFxREh6bG15UmlhSnY0
            b2FUSlZpNU5kRVBXdUdrR3h5d2l1WEkKHBg3MQkKomFP0CyKbRI2BwTWVcpGGWVp
            cwK2Yzm2ZllQY1KHsnrktZ5XqsmDzqGZ3n+uacwuBDjE0zC3mstYBw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17ttan4es6923ru96408ctjhs2f97mrxq9uw938plgnw6wkstv9cqsaq5cw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpYzdaT2NDb2NzVFYxU1ZT
            MmFueHNuTXkzcy9lejNkSW1oOEVucXlDbUJRCjFzQTh5VVdFQkhCUmFsWTBNeXlL
            ZUhHNGlTd0xORUdiS1BWYm50bm1EUmsKLS0tIHJCOExRU3V2K2FpdzBmNWVaVEsy
            aTgwWGNUaG5MMU9ZMCtwbWxYdVJjZmMKrHvpqbfqwEhikxRef2xU/iifB0zA1k4o
            yRnz8spGvbxW3bbLi9q93oW2iabFRbhVGXMdxI3E2Y01qwILe5TMTQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1un8ajg06rd075pff8pglkq2q0g020peq7v23qzeqhuchl4y4kyfs0drxyf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEZzdDZlVvNFpVYmEwZlk4
            TWZGUXVLVlNLTmZBMFJreHkzM0JtSWRvM0Y4CjdQb09xT0NMU1QvZWVyaXhPRWFD
            WGVzamFyUkpzMkxkUkp4VzhucDQ0SjAKLS0tIFcxb3RaeEYxNHEzM0VkRG9QeEdY
            Zk45WjFvTkdEeHdkQ2tzSzlaS1hHTFEK0ISDvflgQbkR7ZCqIfMT2b/hKqY4wvpI
            MGI5J//hHNqBC1v8qgHRVyl4Se2ZtttWHQNQzDJR3ySPh8RsCaCyDw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18r3vk6aecpcd69ey7fhgjylg6z37ksfeff6c497mxgv4nwmnyupq4gsfua
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0UTNMdzFnZzFtMmM0S3Jj
            ckFyWUNOcjZzV0lMNEU0MVhsTWxrdGlxU1NJCmQ3aVZVdmRRdTlwUFlEQVJYZFZ1
            TFlJbmxYOWgwa0k1MXdWYndCU2t2WWcKLS0tIC84bWNVeUNQVkFOYjNmdXR5VDdL
            dmhQTGQxZ1hPaFVGNUwzQ1ZCRVkxYWsKOTERglyq9Kkf+eR5rP1/edpHrfAS3Pm8
            E4oVtkTDCXpuW6cfyV6DkPoNwbB3nAalhTHWBlqCdIIAybdxxP/atg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1emw2e5x3d4cu0x4g0q4lrw8nj2fdv0qfzta6g62m5y24j02zu44sflkxln
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDbG1lUDdYYklZcnQ3MWNS
            anFRMzUzQjVOSGhJZXZuNjRBSlZGeFgvUldFClUxZXJaQ0lmUklRR2NtL1c3ZGFi
            RGc4eWJGa1J4OHJKS01KU3hyMFZObWcKLS0tIGE2UDR6L0x2QjlORTNSZmo1UWdj
            OWFySWxOL1hLbXlld21WQWkvMmlYZncKRHqg4L25O1iyBIyIr4hEIyyyPYWtn+q+
            yBkuZGWb+iarNPbbAqzpKyD/cH3aVFGMLiLqx+zYHRvx+kFPaY536g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1x9049ry5hz876qratphuc9gdxzuv4nnd06076842zdukl4unvazszfnjf6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArTmcwdG1wTEFnUUwzOVVp
            YzhIVVVGU0dXcG5CNDVVTDNob0FxU1lIdkhNCnMvTFZSUytVbVlKQkMyTHJZSGt5
            c2NjelQvek52SFlQTDZoQmlwZTArTk0KLS0tIDJURlJkN0FOTEdQdnVHZzBWZGJz
            WjBZYzdHUlZCNnlHZFJXRGxyeEJkU2cK6o6vL1ez0oapR+XgFs4Ybv45LLqBeIPm
            od4nkh4xzos+4wFA4enKEzSzwAF24fZ64sDaiqs266vTu7ugZUOqWw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-29T00:35:20Z"
    mac: ENC[AES256_GCM,data:N9rAzn+vbkBdE6C3mik8yhfoiaCoKbBpmtJvBUPqMeStjK2PM7/Xjr5Z7yrZ094cyCESzbyAfIN+x6Oq9tWe1PzUy6LQR9fHX5LfWnemOcZgZAtcivk/I06PW5VDFFRYoOfsDUBUl5CPyhmrsiyqDiechajXgSPEPAwqwrMeWew=,iv:zjfkK91GBOURNaAbMIOh2pHMG1JiY2GdR3KQk2gvB3s=,tag:Rvtfp5cN6j7PCuFhcdcIsg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
