apiVersion: v1
kind: Secret
metadata:
    name: dazzle-mtls
    namespace: browser-streamer
stringData:
    ca.crt: ENC[AES256_GCM,data:gJFLRzBHXwKTF64OWWBKeOtPguLMm0TaVHHx1/c/J3SY0Ko0gophWC6Oag35YHRzBvejtmOvo07O777/2BiSHr1NYBZ/ttfpjtfcXaoYipidmUl1IWV6nfSUHVKqHNBU+tM6N0YoYHnMldO+tDKpxayB4DJxoUz6m8cLKqCDma0d9v3ths3gsDsL57Gq+vOd1HoSJ4NjFJ5k++7sGe/+KyQoQ+bs04iqKq0Ct2Dgi3lsxbhQeq1mUF50xn824BWLqgfyBRgEwCPrytyt70mnyelybIbTXAh7si11kW/4LMNr8joa+lYTMuEyr63T3DL9SLHopOFfjKZNAdVwSfm7A6irIPpL48oVXtaVqQdPs8IBF+U1yktISWIJs82j1Vjew4k7bl9xU/BZUztn2xkOaNpmoB+wIaRuRzSka6sT07lQ5h+scyTgHogkIBrKw+Ac21qCRvxV/l0s1KYn7bw3YZ+x/p5s/dEL0LdR74iDZKRYG43sBIUb26ChsT8UzwrMwDr7kii7//3z35jFCkySf5OYXHU+KpHP6bqmfCM69nWFo8rnZtjmE6NIWsIj2DfBY3uby1IUuBuWqHDCzQPC6u5EvKPbGrXJJJh7xstthRGTgwmkAFB4bWwOBapvXBzg9HPL79h3f/mB39j8ir0VlM5tx3M2nUmklMEA2B0vJvtYI8VYyV2fPEMVa4Mo0tkNMXIm+FJFI7z9tr3nko9gRN7T5kI3aRGkq8AC77QYPFDLLERFuGPFe8y3grKfFWoRwHvqI388NihpSmz5yBbR,iv:07KpJmIG0A0tdRpZF7RUUFySPzPfRZNguzrojd3y6qg=,tag:4dBMqNhmv6VhjLo6apMw+g==,type:str]
    server.crt: ENC[AES256_GCM,data:pAszfOhabtrMd1CA2jDWcPrwOTuqvDLKsc/cs5cFPdd7Mf7Cuyw/ZKZALQUHev5TOR5UU7LDrP5U1kOLTrHRPsXYG0PRdZOGr77KrzESUuMGboq8Ntd7/VhJrMPydoKia1K60+053DdvHsGqRPdZUGm7fxrE/YGRMjqLdGoEaJS+w8X5LrHzM0bgfXgAf1CgTxKcrbMxt8RqMCL3De1PpgfFR/usjMRG5RY554K2o1wyxMcryqD8kb+svrMKbv3PdVwyZ3UUHT7Mhnl/Ei5yPliKssBR6TkxxYGI8HsuEARhVbJLL8M05q7PaSah4dYEZPrjvml9CRB/8Z8JtCioFsmM1UuY5UyOBDtAU6FEIyg/4EOUsUN1Z2r5z3VKuAOLeqsFKhjuE4l9mzkhcybYe+YxKYbKREN7YQlDRiZeILPZrjzJid9wXuNTfkMg5pSw6CpnIPKCmb1c3GFyWs0gMmOYZ09J4F/o/XZHNlfK1JqfJwyH50KM+vNHZi7V1+yg/GmuVd+jt/kdB0De4N/HI8ql4ej/sWH3xNmIYpbUPlVlK+rVsLgJaciPJmPYB4kibk7jM5kPq52eIMRLgKiWujsRzDntKBnjPHpCKg8oqg0t/rAUTKG8PDrMTqrNiA79njWHmINwG0Iz1FLDm3qRNrc/zKL6OKhOqRDcj67A6pnNSaibiMZEwsQbcAdbrjN53KP76Et93+iOaG3tvXlYMW+jzrvrQmSiA/WEu5Nz9k2dbKjEuvI=,iv:Xs7KISIseFuDSL/NXy/RZZNZicZqf8q5qI9P3rJp9WM=,tag:RHfd2jj2eT/h5KbNC9yyCA==,type:str]
    server.key: ENC[AES256_GCM,data:F6EdcZ+b0mgkSPhXkOxLYLBpnOwpxVmTnEHnkUSFQ8+uwRsrrcIohfjOcEbU1KvuLqowEMBzatw9aE8b9k2JyoHInycIZxSBGc1+lzvqq98RmB/5xdI51IJoNu/GtYrJVMwRv/S80KSgkZAwNYs7t0uD5x26utXsde7lcziCfIeSPWYWdBzH3cq3YHAiSxHt3sch1N4e4vN1vgt91ytN6gixf4eclTYJPSBBssfTw4YAwolaRrbeI3J/G7KFACiosippV887lfFYmqOfuq25N4jmYk9beLAe9bqz7BHuvk2876AgdmsYBwdusDxWR7t6LSUhbyRnIh/A9iVAAs9X0kyEA9rnf2GLrxvqK3h0Ydf5oHb38j5G3DITcZ0QC5kSzb52khzhNV8j+ypf8cg=,iv:BktU1/UAH3KhR1XjNUVf8MydtSbKVd3O0FUeCq/6B0M=,tag:MxTQ6BVmGNJ8uo5mm0XpXA==,type:str]
    client.crt: ENC[AES256_GCM,data:Bj28nkZmMEKsWTCHjv6kY6g83riOJpLxboAGcx9rEd0qcutTlggcnAGj/3sSe8LiCHQLDDsK15Z3nGE3quUYkq9fg0v9iVdjglgvEFIkC3aRt/VpLkMkaLuEYTelr0nL0ACYxTw36+NQicqNBG77j0vIWLndVUgcAYqpC4LMOnJN1sdcPMgDoP3Vb1ykKxX5oOcjU7f+2Fflco4loj0HF9aHDk8PfVZr7bOXOiykDfLgjFCBH+ALuRWOcNWIklEHcBwvuiszjF+qVa/LEC9PszzW+1E2D/006OaOHaTCFQfeJySmQTOXmQcFipI0zsTJm+gPRe0F0vmAfLOaRyFfsCjLq+dpsn/3FPpK1Jsr5AieOOxGdXGqKZRRNvjXgaGpXsu/38i7vNTqQ/cWHxGntB5aJU9AG+nB2T/lJZt6ZqHjjADBZbklIhbklKs4iFBLPf1FPv/t5k3arnO51lzUmED70Fq7E42gKLga3guCvm2QCtXc10QgDiO1qCHlds4lRpeJAnYVBv075aOPTh/CRuGu75ktKr8ILkkRf7BsiGC/YJSVib5mq4YNCg3N+0wglptNqTCEmKH2bVpDPQyv8jdpbrI0EohsoEF/Bm+kILdB6RRe+hyNMdiMz2Ww8/1zjPGzJCUpGcpMyEmHXbcN8YE5r9gE4VUVz8VYar2BcZVJQlB7odjpeT7+urWxiinSI6xjddhYQ18MCFeggzY0N3uARIHrmauRZs1nickjXhvXPHRZcvxWASrbCecRIg==,iv:jXp8fBmCD4c7T8hcFOeaWOgXarbqHEdCPLR/2MMex10=,tag:TtcR3tfJCTePcq7HR/674g==,type:str]
    client.key: ENC[AES256_GCM,data:q29jxt25+nucq2sjMb50pxWHeNEDkha2n1II3iAvIa2TZhr0f7fKBtc5Nl6guaUBgqPh3vukFnrd9xmjlOSicq0xpfcsEuWiUlui7PQE1EcKzrQbIL0YNk5hCb8Vorv4Qh4fAE+OzM5TSVgGmth3nMnUwobH5mv7KePXCQFLH6fEodAT820FEiygVHkSBP8bRweMMalcCrJXuyM3BK5qSbfMIey16uUO024sHNg8t/1sFmSx4sylkKhSst4ppvaxWJ4xiVlgH8w+imxUuJeweSm8MxDSIxI3jSZoyEexw9PJfoPR2riBvEIbuCYF3FITELQ7NPbDqLRMACpgRs3U1KfrRx40XkODMH8PcdtKdlpz4VTsTXZw5PND+VC1f/xd92AiI4LDxZboPVTw3KE=,iv:TjjJtga3+NfFDsy5LFag6/uY7lGSCxyoeGyBBj4GNpM=,tag:0AeR9fPcWGDnTW1dkjhcmg==,type:str]
sops:
    age:
        - recipient: age1ase59dknkacq26gemrs9dvwvu8xr8akhfya99lagv5py7c7h7plsmtucvv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3bUZDY0VjOVpheWh0Z1gv
            MjIwemtmS2VXcFFhUHhiVlB3d0lJZXVSRFVjCmxuTWw4NXFFNUdydElDNUpKUFVx
            R08xemM5TmZ5SEVTWXUxSjlqRFROdGMKLS0tIGF2NTE3bm5QanlpaVFhTDVLQ2o1
            WTU3b0xoQjY4N3YzeFg2SnVhakxrdzQKcdZm++S7P4EfynNqKSzjl7H9Wof65lMs
            FPG6v99G8rAzoSnVD2f5uKtyzFf39kL/ttkUBtxiRRLefsD3XLHXQg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age13zs054me9k5h4m8u3hwqw9nz4jg6lkpfmkzqn8mdujjqp76h6plsmlmtpy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrREprWjBHT2J6dGlNWDFz
            WjNFTUFEOVA5NXdzc29uYklxbDlXOU1mWmlnClVUczFLMHlpZWw1OFhlN1hjaFdD
            YkMvRXNlbzcwNGkwM2FJcnRXaXJvc28KLS0tIGptUE1Tbk9YdVpjck9CSW5HQjRO
            Si9qWkJWeklEbHc0KzJwNk1PVENDNHcKbiBM6InqFw0Rkc2YzbWooPYVSnyEK2Bm
            7EqZdm9MnUsez4L2g0OQVaticNdZPHL29b3PZrbKlRpi+IoYGTieTg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17ttan4es6923ru96408ctjhs2f97mrxq9uw938plgnw6wkstv9cqsaq5cw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByWjVIWi9WbW0wZDdjb0Ir
            Tko3eGI3K25rampvMlNaTXpxV1dVU1NRd0g4CmpOcUxsM1ZRS2RSdzEycVliNnUx
            TlpTbHBVZVhra0xleXBiWUtTbmo2TG8KLS0tIGcyWXZyRzJhc0x0QzlOc2dFR1ZD
            L3hRWXhIS2JMMGtEZkZYUEV1OFE4TzAKAP3FH5et9RwuGTHqC56oONqvRJb2Wn9i
            Ijohz10L7UxZkL0HkedfJ84CdMGch2NQs8BUG3YSU2+DiEC5fe/4wA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1un8ajg06rd075pff8pglkq2q0g020peq7v23qzeqhuchl4y4kyfs0drxyf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLdEFWRmVDQlhyT0k5ZUx4
            WWxsUDc1anJDQ1RjdHBJcTFrT01WTmpnVGdJCkg1QU13T3E2d3hrbzFuaFhtbmw5
            cGRnYXUrSkdyUkp3TFRRVDFhQTN2Q2sKLS0tIDlkYXllaC9yTFFMelBOb3BYV0pX
            SmNQcm4xbVdwOWt4RU9pODlOZkFvcFUKJoldsxqc3Bv22mS+Q+b4mg6oHmMC8tEK
            DBsaVfKxxRJcI5zVZE87bg9eQYhhwJLJXxmlKh4oi5xXJE6lNSPCGg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18r3vk6aecpcd69ey7fhgjylg6z37ksfeff6c497mxgv4nwmnyupq4gsfua
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwWHhET1NJbnRYdkJ0OVdR
            S0twcU83SlFWT25tWnQ0bWpPS0EvRDVVNzBZCnBWeGZQRWJFVXhjUHo4OUNFb3pz
            RjdZRFUvZk5YbGQrWW1xQk5Pem1lK3MKLS0tIGpYNGs0NnFRMEhGcVRvVU55OTFZ
            b0xRWXpsQ3RTcDJFNE5sdUxzUWxuR2MKBnGolJPseGmNTD8YsE/7s65U4kgwOFbW
            gip/IzhoSOGInAIod0LxljQcT8Df1lHiCt3ekpWA+F7FvM6YsnzQYQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1emw2e5x3d4cu0x4g0q4lrw8nj2fdv0qfzta6g62m5y24j02zu44sflkxln
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2SXJYWmc2MzVsNlk3WGtX
            YTk0NzBjc0hMeC9Bc0pqL3dNNzFvQkhSK3dBCnZPTGRVZFdaMzk3Yk52TWp0VDF4
            d3FVaitVMUFpaXY3Y25BVjB5RWY0MHcKLS0tIHNhRUhpWnl3NlUySFhPQkZ4YW5r
            dmwvdFFZZXZ6aTRiUjZERFhQWFhiUncKOAqEnHDKR9lZXIp8I5Rc0rTrMCusXWT9
            CI+cr4Y8rVsRxz/p6J36pwDstfhYVrwhirj6DYp987UKXb0/4oecxg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1x9049ry5hz876qratphuc9gdxzuv4nnd06076842zdukl4unvazszfnjf6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxQ3FOUVc5cUxGYmtvbzNk
            cUgrSkQ1QXV4RmYyMGRHT1o1d3J2M1BYQ1FJCnVVWkU5RVJIMDh2YVRrWmswWlAy
            RG5qMFBFdE03N0pEZkd1Rys5cFNVTDgKLS0tIGZVWS9BNnVlUUJ1dnYwbnFFYk9E
            eXlPRjRCRWxJZmNCTjhQc1BoRGRsa1EKC+pOOPkNARO2Kxm5T86ZsmUU8wIN+eWA
            +xUSipHAub14E8ksDcs/PM88RvH3OFw2p8SWH8sKYkwiSBak5RHPxw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-12T02:05:44Z"
    mac: ENC[AES256_GCM,data:FC4h2ANyEL+7vD4xRCToHP81wQKwemeaqY5eqaAy7UUniWGZvvmmQdMYcRynHfis7U3FsevX40LlECKSlyjR6hVojBf8fRjxARD1pGH0mCMVaIKzsYeXi8Xl+0UuHixNc8Q676yQE+Rm6I1x1ofaTXuhR8xFbNbou+wq94kpmoM=,iv:wx+OFi40bY+bX+Uwjje30o1V6purxxyNrXBJrMXuy7Y=,tag:WlL6fImxvs/fb9HDiPizNQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
