apiVersion: v1
kind: Secret
metadata:
    name: db-replica-dsn
    namespace: browser-streamer
type: Opaque
stringData:
    dsn: ENC[AES256_GCM,data:e8CVucHe4jAr5uoB2ey5p3tce87JTyJD4YfB/OBDCJsQyEb0gLg8gOYAYl4tIRbjrC8Dbr4/Mh8rBOs8NKKwplZExvYEuCt/L3gDJC24i8jBlqHSE913dyEDn/uYytMhoEBeOofJ2z2JWTIoDNdRhUHLTw==,iv:ufWKlnbQaWhILQmgDVUr24gFnVimFi8IgkXi1Pt8+eU=,tag:AwQ20hlKjudVf3JyEIunzQ==,type:str]
sops:
    age:
        - recipient: age1ase59dknkacq26gemrs9dvwvu8xr8akhfya99lagv5py7c7h7plsmtucvv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHWUhIMFVyUWg3ZEVNUWF2
            OWNiSDAzblYzOXA4T3VJbzFiVjkyTC8yc0FvCjBJdjRPNFNkdHUzUXI3cDJOQmsx
            SkMrVGpaY2ZCV1h4bkxhT3I2QWx2OEEKLS0tIFZsZ2x5TjlDMVR3L3pJcVlOY2tm
            MHlnSTkydmtmRHJhZUJQWjRUQXdKdUUKqRxVnr6wf/mQu9w40VlmAkoBLaBK+0dE
            p9+jv22PRxXlTdDn9nDyoLoqrjJb8JF1i+iK1wHAe4d3xlOG4jF8mw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age13zs054me9k5h4m8u3hwqw9nz4jg6lkpfmkzqn8mdujjqp76h6plsmlmtpy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1Rnc4RjY2c09RL29NZzZh
            L0pKRzlsVStSN1UvNEZrRjdMVVhITzdVZUdrCkY2eVd6UFlkZ253QlBnblFzVk5h
            RytIK0NWQlBobFNpd3FCZ1Nyc3VaZ2sKLS0tIFh1c00va1NkUEJHMEU2ZnUwNnpB
            YU13SFY3aTJnNlZkRm1oOHJod3lrdjQKB2smSUjFxFu+8ZZEFG+jDS7kLWwD1JB1
            6SGVbGmCCddnp+ESaRsnvg8sCUmZqe+aKa56W7nseN01SKc3vF5q/A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17ttan4es6923ru96408ctjhs2f97mrxq9uw938plgnw6wkstv9cqsaq5cw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMVmJJV01XemhDMnRmSVZW
            TW5hSTV6cGhTM3ZtZE1FNit2eExacGxId1RBCmxrTFNpUkR3bDhMeFViWGwvMGVI
            dWdqUUQrVVJxQ1FSMU93TExkQjA0TFEKLS0tIFhrajJZc1JiWWMxaVV6VXAxaDFV
            bFd0cDFhZGlENStlUVZqb0w0ZzI3dUkKjahwbR/adElKULKRix2uJVum9ELtbIl8
            mGfcKWDjrTz6rmynxN/iVTw+GwTja+aFamgMSifM7H46Asf4FQ39Xg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1un8ajg06rd075pff8pglkq2q0g020peq7v23qzeqhuchl4y4kyfs0drxyf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5S1RQeXlTNVhIR3c0RVZ2
            T21UMEVvNE5EN0lsN2tscHBvZmpJMFJoMEVVCkJaU0lVWElyaHBuQVBDN1JHRFB3
            dTcyYWFZaFJzRDhrUkZGR3FWTlJmK00KLS0tIG9kOGs2RS9NZmVRL2h0UDdMYU5K
            UkRoS2l1UEJReGxGSWZBb3dnZWlPSkUKpffXF185Ldp8IrGfQb/kMjfZSR7vZHJq
            duSvGvqrxwQGEYrtYYAMEnpY5Li0j5607HVNhbwtfuUgPT4HLxG3tQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18r3vk6aecpcd69ey7fhgjylg6z37ksfeff6c497mxgv4nwmnyupq4gsfua
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxRHVrcFhuQWs1V1plNElL
            bUNLQjFhV2pvSHQxMjBtV01ZTEFvdzZSS0ZZCkJPSDdsNnZVSmRPN1F0bmgvQ0Nm
            dzVKdjRqR2kxMFlPdW8xd1VsRzZiMmMKLS0tIFBBcEtrQ21HZjRJOGxsam96c05G
            VG95R2dtakszUjBhTWdQN2ZQRWlXREUKUeWXUIPchZY+nhLy5XamW5NwJljYyvsf
            I2ejLlmse6W9h+BE+8fW5yjLZ3GeltsT9k2nY2T6xvRQeGMX+RlwWw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1emw2e5x3d4cu0x4g0q4lrw8nj2fdv0qfzta6g62m5y24j02zu44sflkxln
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuTExteDVPdjFJUFArQTc1
            QUtvYURMbG0xdk9VN2g2SEFhT01leFpHZGs0Ck9XSTdmRDR0Sll5amhjV2tVei9Q
            MDdrVElKRTVnTzFJT1IvZm14dFgrWVkKLS0tIE9paW82MkNKY1FlL2RMWmUzVGlh
            a0xTVnR3MXBmVENWbk9teC9teW03amsKWrS/P3wsynnlrvWNaWgsx/XaBIhlQQPB
            tyCHDJ3f0rVgd5lMMyVoXpJhOc0qsJHNDRSB7W2KZz/JpZ1jSpGtcQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1x9049ry5hz876qratphuc9gdxzuv4nnd06076842zdukl4unvazszfnjf6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCQS9KSVorSUVTM3hOVmRv
            ZW1mYklxVWJjc1M2TTNlVytFRjhHT1hKTkVRCjVnYmJwT0ZrZWhoN25UMER1cjc5
            T2JKS0hFaGsxRXdSaVlLaUY2OXBDaHcKLS0tIHhOY1JDbTJWNDdYcXVhL2tndzgy
            M0JVQWZSU0U0TDdOVGdRSTc5UzdUYjAKZdYWjQYpRuUVfzroW2Y8tb5dyMJSPPqi
            gjTZ7GWvZU1Md8PREGYIg0VysovjpA4Yj24aG2jRI/5KKLpnhKjMGw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1y5txpqz0vyyq03yyysmzuyvuyh8uzzpcw30cp5q3twxnwenfzpvs48ts0z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYYnpxV1plaXUzT2piWm8r
            T3lnakNoTG8xS3pjbmg0SjRUV2hVazQ0enpRCjJrUTdQbnVHUFRPQTE3Q1dvWWRy
            U0llaWhiVkN3VHh6SGE1aE5kWGMra2MKLS0tIERodXdCbmsvY2tmOUFkVjdLeE5V
            bTZrditwMDNuY2UxeFd0VkpEQnV3SVEKv8mLeDBRE7N5OnhAUpJw5p5A3s5ftMHO
            WTjjNdvPdOY3NbFyFIvkL0DWJuOqUOXFIHbtw7fCv94OPQV/6w9avg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-28T22:18:59Z"
    mac: ENC[AES256_GCM,data:czXQjH4dKAuTKXg++jd4ri4JymuAvMr3mbOLq3h3U93tlUT1E9x+iMVhbRMEH+9dMS09H7svNvXFXyjuQitfQyuG6qw8ferE9QLCOqM6IVPE2D5/B0ShNgRX4UjhlreuLwaZXCB/w5iQa3YoT563Rdaj1ARK/6zW5RVx/yeP7fc=,iv:H9y5727gPfm3+VHHdWOaa5ygSFlGE7mGnhPRe9WdJ/0=,tag:sfC7o0n60DFBgVr1J4TVpA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
