apiVersion: v1
kind: Secret
metadata:
    name: db-replica-dsn
    namespace: browser-streamer
type: Opaque
stringData:
    dsn: ENC[AES256_GCM,data:e8CVucHe4jAr5uoB2ey5p3tce87JTyJD4YfB/OBDCJsQyEb0gLg8gOYAYl4tIRbjrC8Dbr4/Mh8rBOs8NKKwplZExvYEuCt/L3gDJC24i8jBlqHSE913dyEDn/uYytMhoEBeOofJ2z2JWTIoDNdRhUHLTw==,iv:ufWKlnbQaWhILQmgDVUr24gFnVimFi8IgkXi1Pt8+eU=,tag:AwQ20hlKjudVf3JyEIunzQ==,type:str]
sops:
    age:
        - recipient: age1ase59dknkacq26gemrs9dvwvu8xr8akhfya99lagv5py7c7h7plsmtucvv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtL001TUVLRGljc1YvMFBr
            UEVPcFBxelNWYm85b1ozbWxnbG5kd2c0MW5FClgzMmMzbml2NloxUXR4ei9JN2lk
            QlVjd2pzWE5EalNIVWUwSkh4cmZYelUKLS0tIDFjcHhIWlg3cVBHRjNBbWxIcHJZ
            ZlphdHZWRDlCMXNvK1NGSk85eVlicE0K5cL7Y9Dxxng17/hCWctSfLbX/2zuzPW+
            ySTcFuZ+3riw0bu4FpsH1creuDAvdmdzUUH8vW1UjsDwV3NabYCZAQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age13zs054me9k5h4m8u3hwqw9nz4jg6lkpfmkzqn8mdujjqp76h6plsmlmtpy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxeVFZQnkvbkRVc2ZZTzhz
            OTdDd0Q4cS8yYWdEVWdZeXU3cVBqSmJ5MTBRCnJLWmx5OGlCcDJkQXV4b2dIZVJH
            QzVnQzJzUnpqbE11alQzbWhrREhmYmsKLS0tIGZ3ZTdrNXhxeXlZT0lQZklRSFMv
            STlMcFMwYXAyNzhyTVV3NHVLRHQ1YkEKM2dr3tyTCE375EF7bYNVb1FTNcziFOyY
            95n5jNIL8OfLv44ADIUt7FwjjXoNN3UZMCMHd+KpdYLuc2DWRHq0WQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17ttan4es6923ru96408ctjhs2f97mrxq9uw938plgnw6wkstv9cqsaq5cw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxZ3VDUHEyMU9WcTJibjlR
            Yk9WY1BtSEdEdldpbFpMZ0VMVzlEdENZakIwCk1pcmFjcUx2YVJGeHQ1N3FnYjcw
            RmhKT1pGMjhkZEVuQVhpQVRTSlFsU1UKLS0tIE1xUmZYTnVWbnJneHQwcERySDVp
            SWxBTTd5dEZuZHhJSTRQajhEQ3UxbWcKhE5xZQMs/6IK0X4mO+ZqTsB+RrkWY3yb
            tkgOn0noNrP5s5AF6MKCpl7OmpTBbSpFE5UmIRUM85qlPAESHcgCqA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1un8ajg06rd075pff8pglkq2q0g020peq7v23qzeqhuchl4y4kyfs0drxyf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJZUs4WEs3bjBPVUJQOUF2
            N2J6MDRrRnhldG14dnJobCtBajhGeFl3MEdrCmh6YVkrUTZWM3o2eU1HMmVPR0lJ
            eEFBRXdMK0xocGp4eGhzWm1wWGZUZmsKLS0tIHEzdjlkUEZrc3F1dVUwbmtDNWdD
            L2k0SUVhZFJmNHpTYVBUR0NxTm9QZWMKuExxX3giCKxlZbJtNlx28byAOByoYUDU
            aoEMwl7I/Y0RkLjG4NLnQwwwBfnY3cIKggONBpbhpMlD/sfWU0XP4Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-28T22:18:59Z"
    mac: ENC[AES256_GCM,data:czXQjH4dKAuTKXg++jd4ri4JymuAvMr3mbOLq3h3U93tlUT1E9x+iMVhbRMEH+9dMS09H7svNvXFXyjuQitfQyuG6qw8ferE9QLCOqM6IVPE2D5/B0ShNgRX4UjhlreuLwaZXCB/w5iQa3YoT563Rdaj1ARK/6zW5RVx/yeP7fc=,iv:H9y5727gPfm3+VHHdWOaa5ygSFlGE7mGnhPRe9WdJ/0=,tag:sfC7o0n60DFBgVr1J4TVpA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
