apiVersion: v1
kind: Secret
metadata:
    name: db-replica-dsn
    namespace: browser-streamer
type: Opaque
stringData:
    dsn: ENC[AES256_GCM,data:e8CVucHe4jAr5uoB2ey5p3tce87JTyJD4YfB/OBDCJsQyEb0gLg8gOYAYl4tIRbjrC8Dbr4/Mh8rBOs8NKKwplZExvYEuCt/L3gDJC24i8jBlqHSE913dyEDn/uYytMhoEBeOofJ2z2JWTIoDNdRhUHLTw==,iv:ufWKlnbQaWhILQmgDVUr24gFnVimFi8IgkXi1Pt8+eU=,tag:AwQ20hlKjudVf3JyEIunzQ==,type:str]
sops:
    age:
        - recipient: age1ase59dknkacq26gemrs9dvwvu8xr8akhfya99lagv5py7c7h7plsmtucvv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwV3M2OTJWQU4zNnJIaG1o
            Z0o0TFFwdnB4aTNQclBhc201WkJYdVh3SFUwCndWNE8xZWRBMzRoRjRpWThvaW9L
            dm9GVmtoUCtESi9kd016N050NHF3c3MKLS0tIHpwYXAwVlNYeFM0WVlLL080VnFJ
            UUtBa0h1T1J3RXVzdHJrb21DMk5sbW8KRoofgNVVfgzkD+9d8/TNjHi9OJwtGp5A
            7DB0a2n6mtk2qL6AJxl6ubHwpAbu9jOXg5vZXAgu9PglQ7cL1pZiCA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age13zs054me9k5h4m8u3hwqw9nz4jg6lkpfmkzqn8mdujjqp76h6plsmlmtpy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlN0dFS2NIam1YaDREREVE
            a0Zrd0xWQWh6aFFVME44OVhWSzF5UmNCZWk0CnczUkNPZlRpNHJaNkhJTXp6Y1Jm
            WU9Yd2VlSy85WFlZZ205SHV6ZjdKaWsKLS0tIHV1NC9jcmZNL1BGczd5dXFoZ0RS
            bDJIUThyallrVUczT3RwQW1OcXRPSWsKgG3eKrsJSvYY0Eh6DelVancjogv8Azd6
            dIPFzL8fqiNJimLnb5OR2ivwVV8IKPJ09o9pcDvTSEBDFgy0KuA5cA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17ttan4es6923ru96408ctjhs2f97mrxq9uw938plgnw6wkstv9cqsaq5cw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5ejhKUDR6MlZDTFZiSmNw
            NCtuaFJGQ1B4VEhMdnIvYWN3S2FyVE1JTmlrCjhodFlTcEVQZjAraHlUdlhOT2d4
            UkpDRXBLUENoa1h1czF4THJ0QzNXb3MKLS0tIENGWFUwM1phMXlLWHlDK2VZVG9m
            TkJRYWhnT21aUXNKRVY3WXgzWnhlRGcK0sSQB/xIKScxw1uq9qiZEdTSUPPqbSzK
            2llf9Mfupe4S/EQ9KcOHqfxTgaxgiSKpPLppdNPbjsT95EbneAYlJg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1un8ajg06rd075pff8pglkq2q0g020peq7v23qzeqhuchl4y4kyfs0drxyf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhSnBES01iQzlWMXhLR2Zz
            WjNscnRXN2h0UHJXM0dNdnNlbFd0YndQVmdvCnJFRk0yVjBDSjM4VmErQVVYTkVu
            RHVmNmpIM2orU2x6REMvYndnUUJPam8KLS0tIGE0SXBXeWpFZFJxb1JOd0F4SGgw
            ZGVYOUpHU0N5akM4akpLS29rWXR3OUkKfHyQgDaWBRTixR1fIyUwB9Y6QcW/A22K
            DOPprImcuxUYrcHVdBhtcVLzD+0Vs1KFQ+Tab8zW3JPlZotISaCLJQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18r3vk6aecpcd69ey7fhgjylg6z37ksfeff6c497mxgv4nwmnyupq4gsfua
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSL29jSytwaE5NK1I3ZGFQ
            cEFJblNnZ3J0ZzcvVmthK0hXT09BSWxydEE0Cjl5YUJLNzY1aFozQVZPZUg1bHI2
            ME93S1VEU0IwcEpHNXlZRzI3aVdRbE0KLS0tIERzUGNtMDAzenBFRW1zZDc5SWsv
            RmZzMGd2Sk5FaVlKSWRnaEIvWlMwQVUKGYRykbGs5DXXLoNd5kSI6dtolxo3DfS8
            fGW3GzNok/0SRZ0Hn5yIFYCKI8nprJTYvF3eUM07jBgEOEjNzhSwhg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1emw2e5x3d4cu0x4g0q4lrw8nj2fdv0qfzta6g62m5y24j02zu44sflkxln
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZTVJoeVFWc09MUFlwdzZT
            dURRT2x4MDFkbWNrOTU5c0F6SUxqb3ZtWkVJCnVETjJnWlYrd3VOb0s5UElBdll6
            TzhBaURDUjVwbkxTcS9OR25KZURUOXMKLS0tIDMvZTRCVXE5UmdxWEhrMUdJQnpq
            VCs5MDFoK2FuSGx0Z1ZrcEZhUHZrNGsKaviib7lGT5D5j+Wc/JrCpk/TJGIv2Avs
            OngLHc6vHjznTCBr/ULbdY8HZMkK9AwWhD1rxDrKYvIpZNj72W/PTQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1x9049ry5hz876qratphuc9gdxzuv4nnd06076842zdukl4unvazszfnjf6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBESDNra1Q5cnNWYUJ4d1Yx
            ZGRoQ2ZKNmd1dk83NXdkRVpieWRjbkp4Z25nCjhmdHo2YTVMVmlWYUQ3bWl1bWtK
            YzRmSGJPN0dGSXJ3dGY4Rlgvc3ZtWjgKLS0tIE4zcWpjRjc1ZjJaSENXcDVoMjB5
            Uld3M3pUYXcwaWsyV2NIeWxlWkorMzAKuUtdlQAM8UT8CKgD2Vw9kcXKiI2UeIlS
            jktyvb9PNYmcErKetK5+5Iny4oDM1izXdqS1PDC1kAFoIpU5z8t4RA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-28T22:18:59Z"
    mac: ENC[AES256_GCM,data:czXQjH4dKAuTKXg++jd4ri4JymuAvMr3mbOLq3h3U93tlUT1E9x+iMVhbRMEH+9dMS09H7svNvXFXyjuQitfQyuG6qw8ferE9QLCOqM6IVPE2D5/B0ShNgRX4UjhlreuLwaZXCB/w5iQa3YoT563Rdaj1ARK/6zW5RVx/yeP7fc=,iv:H9y5727gPfm3+VHHdWOaa5ygSFlGE7mGnhPRe9WdJ/0=,tag:sfC7o0n60DFBgVr1J4TVpA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
