apiVersion: v1
kind: Secret
metadata:
    name: dazzlefm-dockerhub-secret
    namespace: browser-streamer
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:Rb3IWzDR7adEAH+cizsGiK2/ZCjM0c6F0Pcre2SptT3GIdY612CnD5uRHlCortHExq9mtBPMKx1ZCGSB/Y/Jq5rGg2+/Roek0Kqsf6UbLMdhnS5PzayqMGmHIIf2sf0TuxpEzCU0R/8B2b7RqMNejn7cW+YSu+GXEkMa1dhn3ETy0HOOFUgDgiJG3Cs5NXdvdJmsohD9Dpmv4+xBGdbdN5oylfdasgyhpFHIa2ESmRyyESj8XzZ/DsKb8O5749jPY/5JUKswGV4t7fRL5xqINdCD+V/iijAHIGknEStZRBhCa1J2JkX12Cl0pe2Tix+nruhWjZPgoEyRaCx/KWKgPS6xLQJ5n5QyDcKEow==,iv:6vWDHeOO1a8z6eFcR1WkgFyrmREn0tCk9ir93bCIhJ4=,tag:Rt1J5R8QHPRpXF6B6OlYZg==,type:str]
sops:
    age:
        - recipient: age1ase59dknkacq26gemrs9dvwvu8xr8akhfya99lagv5py7c7h7plsmtucvv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrWjRNYktoOUltalhuM3Zk
            cVN4UzY2YW9DM01wRE9jOFZhZEFMQlR1SW1nCktwQzdwOEVmNlVoL2w1SDZ0TFFr
            aWRmNmE0djhicGszQnMvRnhhRC8wVTAKLS0tIDFuOXV0ZVdCTjc2K0dmSnFGZ2VJ
            dVZOSFRsYkpmYUk1eHRGVk92aEpPSFUK4fH3vopXUlfF8eSDndPqdoiIz5RRXVXS
            xIomtTLH0iOaQPVSnGKIqH1gNPyHbcC0GyzrQzwg+c66XddKgpbyJg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age13zs054me9k5h4m8u3hwqw9nz4jg6lkpfmkzqn8mdujjqp76h6plsmlmtpy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsYklEenpsSUwwYnVhcnJr
            V3FLVmI2ZUxGRk1uSjRwR2JTeHk5L2VqRFg0CkoyeTF4SmJ3ZU01OUMrMU50Q0Z4
            WmhLREdSdm5DSWQ0VkJwTm14azdYazAKLS0tIFRMV1ViWmRCZU5oY3NPNjJFQWNT
            NC9HM0JhaUtkVFRweDJZNmxySDF0TUUKygaP1SLuNyzoEFPGlHDRAVoY2L5RhlCY
            +tZ2CITeHTKcT1EUeG/ZlrZCReDNgEV/VIKnRRu502L1JI2WZIPIfA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17ttan4es6923ru96408ctjhs2f97mrxq9uw938plgnw6wkstv9cqsaq5cw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByTFB5TVBlSXBacEp4TlQ4
            YzJiOUVCZ3BtQ2ZhRzRJV2hLVVQvcWN4bkJRCktMY2E1YzhrNWltMUJUcno5c25v
            d05JWHdWTXl3RDcrbTMrQ0o5QS9qMnMKLS0tIGhjTWxGOVN3Tjh5Nnp6KzZOYk1r
            VGJ6TXhyT0hSancwV3pBNngxU3RGNWcKtgK+Fqr9oXyobM9roh6GXcbodsIvLkyE
            THGrojyigm82u3Sa9m0JWClGOLSSCjZGy4m27a34M97UI5sI9/cRqA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1un8ajg06rd075pff8pglkq2q0g020peq7v23qzeqhuchl4y4kyfs0drxyf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOa0lGcnI0MnU0cXZWd0RN
            R0FaTVB4WUhPUWpuald5amhQK2d3VmFyeWl3CkpSVGszbTgreHk3VEZzazhRbjhn
            dUZwdXAzbWk2VkMra3VFeks4RWZNNkEKLS0tIFlzQVVYZC96SGhqMGkxYUZybi9H
            Rk1lRGFqVHA5SFo5MDFXYWtEcEhodGMK0XgbStOsLtDC+dmSW7x/aK4tAWRPc1a+
            hVNTT1BuH/Cb2rChoWZcXiIXFeBRqe0agzMP5yMO3GU4a+W9LA+jyw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-05T18:19:02Z"
    mac: ENC[AES256_GCM,data:tgmZrLBXXHySvgux4N3/p6w+HL6BvDpzEWiIDVbQUtQbbORHgNP5BhLbApxtKdgO3fAOm5GBCBoHu8aj5K9PzONJNM3pAB3tfkwaqCbUYlgcCxd1ZZIy+qYf/dualtuSS5RT3gvP926rQK8d1jvbuDxFhJ5AQCpaGVm1i017DBE=,iv:R62RfRFKYkBJVJOqgwpVEvw1Eil6sfyxB357veR41po=,tag:Aiipz9o/K+mbI/vb5XWCsw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
