apiVersion: v1
kind: Secret
metadata:
    name: dazzlefm-dockerhub-secret
    namespace: browser-streamer
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:Rb3IWzDR7adEAH+cizsGiK2/ZCjM0c6F0Pcre2SptT3GIdY612CnD5uRHlCortHExq9mtBPMKx1ZCGSB/Y/Jq5rGg2+/Roek0Kqsf6UbLMdhnS5PzayqMGmHIIf2sf0TuxpEzCU0R/8B2b7RqMNejn7cW+YSu+GXEkMa1dhn3ETy0HOOFUgDgiJG3Cs5NXdvdJmsohD9Dpmv4+xBGdbdN5oylfdasgyhpFHIa2ESmRyyESj8XzZ/DsKb8O5749jPY/5JUKswGV4t7fRL5xqINdCD+V/iijAHIGknEStZRBhCa1J2JkX12Cl0pe2Tix+nruhWjZPgoEyRaCx/KWKgPS6xLQJ5n5QyDcKEow==,iv:6vWDHeOO1a8z6eFcR1WkgFyrmREn0tCk9ir93bCIhJ4=,tag:Rt1J5R8QHPRpXF6B6OlYZg==,type:str]
sops:
    age:
        - recipient: age18r3vk6aecpcd69ey7fhgjylg6z37ksfeff6c497mxgv4nwmnyupq4gsfua
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5OGFVZGNCZW0wQTdxVG5w
            RmxDS3BKdWJaczlQSS9oMXJ3V2FhaVk4Rlg4Cmx0MDdYTXNzdlhDcGZpOGF4Ky9s
            c0FBQi8vaVZmaWE3UlBoUDA3bkl2LzAKLS0tIDAxUkoxaHFZUTNsdXlBUXovUnoy
            VmVhbllwMldhRVpMSmNJQlI2MHVBTFUKJIIJAHz5NpothHa8OagNF6JGlRJOD7iT
            LfsmOyiQLVCvlvSJan/6BTlaX4STBdu6FYAdyZoq98azm+TbxnGstQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1emw2e5x3d4cu0x4g0q4lrw8nj2fdv0qfzta6g62m5y24j02zu44sflkxln
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnRTJQR2F0MHppQnJicmRO
            MUhlZlo5WVZac09uTitFRVVxVGFtZGFkNWpRCmp1V2FQY1h3cXVZa25Kb0tKekcx
            SFJBQlBlMDBPSlpPdnErRWZBVityS1EKLS0tIDVMcGg2eTR0aHI0SVpHL1YvSFBX
            RHQ2dDdITzhacHFTQTRCYmM5WHpJSjgKBZQPwNNN9BtzUZ8iOY9Q95Kz/RB7+3xx
            KHH6Gzd1pEzAsmVgE2MfB0I7kVYpUhHSAxIm3ap+ygIygdKMGs55zg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1x9049ry5hz876qratphuc9gdxzuv4nnd06076842zdukl4unvazszfnjf6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXcWszRHBHTGkxV241VHJu
            TVlYVCsxMk8yMTMxS094VGJsZ005T25zc1U4CklwOXNHT2RpVXkxcXRqdVFUcVB5
            emlDaEJBM0dKNXF0WUtMeWsyRGZnVEkKLS0tIGhCNDk0aXNQeDd4a3A1Z1VHZ29m
            ZFZKR29FNVUwV3JadG1DaHNXd2tPZEUKM5e2q5bjpdHPa4CwVVnNeRysINWnIitb
            36jlAmEPuiz670JdGi0ez4iOEI9MyYTFOE5RVGIMNiR7B/fgKQHAMg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1y5txpqz0vyyq03yyysmzuyvuyh8uzzpcw30cp5q3twxnwenfzpvs48ts0z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBenNJVndLT3piNHRjYk9o
            RVV2N1RhYzdZNjNZMFRKUkxzeVgwc244OTNFCjlzT1p4VVhPN3h0R1NkTDNXZ0c1
            VVRZdjBGbVZyYlh1NjFGNCtnOWxlQU0KLS0tIFpwMEcveWpyTDA3L3Z4VjdHbzJk
            ejVqK2RTQlZRVnVtZkxJK1lCNHhMWkkKYhJUjTO4kZd+jHBDBSAmIVaFl4oPWK2o
            t2zbU3L/xOvQZFY5RhPpZnUicCwV1qOc9bXyNN6lVjDMg8+y1bYQBg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-05T18:19:02Z"
    mac: ENC[AES256_GCM,data:tgmZrLBXXHySvgux4N3/p6w+HL6BvDpzEWiIDVbQUtQbbORHgNP5BhLbApxtKdgO3fAOm5GBCBoHu8aj5K9PzONJNM3pAB3tfkwaqCbUYlgcCxd1ZZIy+qYf/dualtuSS5RT3gvP926rQK8d1jvbuDxFhJ5AQCpaGVm1i017DBE=,iv:R62RfRFKYkBJVJOqgwpVEvw1Eil6sfyxB357veR41po=,tag:Aiipz9o/K+mbI/vb5XWCsw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
