apiVersion: v1
kind: Secret
metadata:
    name: encryption-key
    namespace: browser-streamer
type: Opaque
stringData:
    key: ENC[AES256_GCM,data:VfkOv7yKK7D3S3ckX/0BjOePMG2GgJj1WKAX3jE38ck5bJ5zNLsRJmK8oxB5/AzRklbDc4v7GebLSuNkCAiTrg==,iv:JCdz3yaNnVfVE+aLdL/S/QtV2Mdnz2IKdurC+oEwXIY=,tag:GWfYPoxa0UJEFQEHgQv0wg==,type:str]
sops:
    age:
        - recipient: age1ase59dknkacq26gemrs9dvwvu8xr8akhfya99lagv5py7c7h7plsmtucvv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZWXlnYlRXZVhhbXJMcWRF
            MlUwb0lVUkRENUJjT2wxaTlDeWE3UFdlb2lvCi9XZERjajJJMklTUVRMWTZhMzY4
            bWtEUUdxS01RUHJlOTBRcDVxYTJnQlkKLS0tIEo4SU1aQU1XV3Z0alZTanRsUXMr
            Z3Q2UG9zekRjVDlTWVNhKzVDbk1RSUkK5oG94xpxh4hRRkaZrdTmO1N/YX1k8/eg
            VMRCNrF+sGjDYtR1Wu3Onqvmv+lY4T+wKXneVwR6aVDdAZOs+iuDQA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age13zs054me9k5h4m8u3hwqw9nz4jg6lkpfmkzqn8mdujjqp76h6plsmlmtpy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRbmV4ZWN0U1JBbkx2aWVz
            YUhtWEZkVjZFMHNxOHUxbTBYUjFYVXBMZnk0Cm5lVmplMzVkTkViR1ZUZ0l0VXBv
            T2c0M3I3SnYxREwyVm9td3ZqeWtyQjgKLS0tIHF1M1NpYjF2UjJsc3dPcXFxaUFS
            b0NjdVQvS2M2WWNQRkk1aHJybms5Uk0K3GcBz7Jpu5rxTmUHX8U5n23XwrZK0/aI
            n0VohHaZA6KZaiTS5nuyRA+bOE/zQommKJ9EXr2BoKNCIwH7K12IUQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17ttan4es6923ru96408ctjhs2f97mrxq9uw938plgnw6wkstv9cqsaq5cw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0WlF0S2ZlWExFeFZnbS9K
            OHJxK0lrRkQwR1FoVnVUYWhuaEc2VU9sMTNRCkthQ0d3NGRET3hWS0orQW5HbE5k
            TUNMY1V4ZzNwZC93ZGVhMkZYeEV0L2sKLS0tIFhycjJhNk5oRnZlUXIyNWtXSlgz
            UnNERzhZUGI2SFo2YlpRcERqSjB3bjAKp4m1qhvZZbd5GHL72CUl5LmvsTZFhAgL
            p6sRvxq930MiMhOz29tqjwyF6gvnU3YjXm1x1sXXbMwXWWSODJE8NA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1un8ajg06rd075pff8pglkq2q0g020peq7v23qzeqhuchl4y4kyfs0drxyf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5RTNTRXc0cGUvMXRMNHZ5
            eTduUmlaSXFUMG9yczdiVzZ3OVdPNGVXQUZBCldhTFoxUDBwc2pHRVBCTmNwRXRL
            c2M1QTZ2MFBVcnlVVkREMDI0cytwOGsKLS0tIFM3WUN6b0RveWxFMWtFbElITGhE
            VzJ5NjFaREVVbk8zaHUvc09aVWJNZm8Kpp1KnihI1479ccQ9IblvgJbkLQ9zCRFq
            uuXO3PlurYeVMVeayyZin0TLxjMOzznust5V3AE9XWX7ckdLibiwjA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18r3vk6aecpcd69ey7fhgjylg6z37ksfeff6c497mxgv4nwmnyupq4gsfua
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1UXN4R0xUbkRDYVJYT0FJ
            VU5yY3ZUZWFwbGg1ckVmWXErcmlVY1BQOVFZCkh1ZkpBdjhSSjBCcm8wVEJyWjlN
            eXN6RThuRXdGWUpFanY4Q3FnNTRtd1kKLS0tIEhNQWJqU0g1cmlTVDlld0FHMlZO
            TkJFM2F6Sm44bHpLN3c0eENQZmVFVWMKZkJy2KILdFkMEsfZ3yLdEndev9WJlPYk
            T4GsoSMt8R4APtGXoEe6dsJQPnQ5AVlx93HWbjQzx9cKa9WIFZ+ZYw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1emw2e5x3d4cu0x4g0q4lrw8nj2fdv0qfzta6g62m5y24j02zu44sflkxln
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWdUVLdVVIaktNSitNK2w2
            V0pWMGdmdk1yZUN4VzdGZTN5WDAxeUt4aFZrCmNLbU8ydHcrZ2Y4ejUxUlh1Yzha
            TW5LL0VUbVFRajhhb2lzanRoeFlwZDAKLS0tIDFjRDRzRmlZSGZ0UFo4d0FaRCtl
            eDRIallpS0Yzb1M4Rm5NbUwxMXN1NUUKM6P4cvtLYVajm3+HB1q2F9JV3JXDr1/h
            6JG4JCfuRjvB4VyGTrVqyt8dzAOhjsd9gtRvtgb0kGA7rmNe0yz8Uw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1x9049ry5hz876qratphuc9gdxzuv4nnd06076842zdukl4unvazszfnjf6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0alRXWmN6VGI2bDNxMDFk
            SVpNN3NpTVQ0M0xhRDYxZGtVMHFNMm8zRnhNCkZ5MktvZ3R0dTM5a2ZqMjlhQ2R5
            dkxMYnlYMThRLzVVM0xsdStqdVAzSFkKLS0tIGdJaFlZU3hTNHg4Rkl2RjVrWm45
            bm5yYUVnUGZWYU05cmp5eFpXd2tDaTAKT5JCvWBTxGDNxwBDh2L2geeG4gBFcC0t
            +/H3ipbPfZYidXUMs7T4yj4ek7uqc6LorcGYt9ttd2tdnqn6EYct/Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1y5txpqz0vyyq03yyysmzuyvuyh8uzzpcw30cp5q3twxnwenfzpvs48ts0z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3R2ZIdGN5S2doYWRKcGNF
            cXRZZXJTTFBXeGI2NVgzbW5LK1dCMjdyWWdZCkY2ZU03T3RnUDhCUlllRkJyL2Uv
            Z0o5TVdGQ3hRWHJBZUFXWHJySkt5RU0KLS0tIFEvUnJSQzJRTVloaXcrR0dIV2F4
            Qnh6MGFLUWxqY0hjNElENlYzTVRQNDgK6OmlPbFGEHMGkjWzwX9O8eil5JDXLTgf
            hi9KOYW1XIH4zzQgIfhBeleLww3ZGZoFCrWoXAj6077lVBh8okZfqQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-02T03:20:22Z"
    mac: ENC[AES256_GCM,data:HAM8NIQsMZb9z5vWL8NNX5j4QH0C6hJ4p/9Abd1noqWJbQMKG5GT1uj3nVCEC34B+p6yoqs6TLgZqojlDBXiv2VmRdJd4Ywrsq/gSCZuxyyWVMpB9iGXEJ5M3OWK8Sj0mD1A22GzHXaixRrPGQDMgi2iQrrtmPsXcilmRjtqphE=,iv:DfUwtkyU8ZKZS9iyUrycqngoWPDHCBtf/ffpY9S5g5E=,tag:P/5cJkDlF210RxASbs+mrg==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.11.0
