apiVersion: v1
kind: Secret
metadata:
    name: encryption-key
    namespace: browser-streamer
type: Opaque
stringData:
    key: ENC[AES256_GCM,data:VfkOv7yKK7D3S3ckX/0BjOePMG2GgJj1WKAX3jE38ck5bJ5zNLsRJmK8oxB5/AzRklbDc4v7GebLSuNkCAiTrg==,iv:JCdz3yaNnVfVE+aLdL/S/QtV2Mdnz2IKdurC+oEwXIY=,tag:GWfYPoxa0UJEFQEHgQv0wg==,type:str]
sops:
    age:
        - recipient: age18r3vk6aecpcd69ey7fhgjylg6z37ksfeff6c497mxgv4nwmnyupq4gsfua
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBObTZLaVQ5dVovVVNsZnI2
            WDZrTWIzM1F5cmc0MlFDZXIrelkwNk5UMlE4ClRQZU85eG92Zk0vTmJBMm1SclZD
            N1puaFMzU0diRERNdkhISVNiTWttVVEKLS0tIG9FMDNZRlgzR3N4UHprazJFZFJB
            KzQyaHBqeDY1VTk4SVZQbmpwSlpJUUUKOXKQaN7Oe+JGYRgLkcfxFzU19wYJ4F0z
            3MudPwggnHUFnpVaEduW6Ism1p/Om1BBVrzBsxD0hemIXhveES2XfA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1emw2e5x3d4cu0x4g0q4lrw8nj2fdv0qfzta6g62m5y24j02zu44sflkxln
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtUFoyVzRyaGtqZUVLSnZp
            Y0oyTmtHcmkrc0sxMGY5U0F4WFVnRC9YSkZrCnRMMEQxd1NJQXNnTjQxWVhzY0tY
            OXZDd0xZbEFlLzZ0b1dIWEl4MzdSWFkKLS0tIFBHYTk0c3krNzRwRWpibzh2eEUv
            aDhmalAvZkJaUTRqL1VuZUkzOHlSR0UKYGOttMXwRIpCJEL5lbYsg+oqGStB4FhW
            5wb1KjpmAjBHs2vESUqWWo3bTQW+JKZHhJ4PiWZSXudJftq3F7YU+g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1x9049ry5hz876qratphuc9gdxzuv4nnd06076842zdukl4unvazszfnjf6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBR3hYVktOd3dxd1UwS2dO
            WTBpMjU3YmpYNnE0NE95MWpPdXJZM2E0VFZVCkE0dXRpMGZZdEp0dVpRa3lIVjNr
            T3FhRG92eW92WmdTVmVpYWY5cWQrdlEKLS0tIGE4TlY1SEEyVHE4UVFJMWYvWmRa
            LzZIVlZ1djhKQmt2dW5UV2kwQ3hKZlkKP/vGXMKzpi5TtjoGe1KYR48FD8eq269p
            1iC36EYk4Ob794Ga1Og9cnmM0YajzQhg+rqKvpY86sjoJsj3Zr6lZA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1y5txpqz0vyyq03yyysmzuyvuyh8uzzpcw30cp5q3twxnwenfzpvs48ts0z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhai9LZWlyOS9lbWRGbHNB
            NTVHUWtjdkJKUUYreCs4ejNlOFQzN1R5VVZvCjlLK0NDak9nOTcvOHRZeUd5SnlM
            c3ptZktBbU4vbTVPSGhKd2lIYzBzeDQKLS0tIDIwSS9EMXMwTUc1TjRkVTV6TEdU
            RkJxYVg0bUJMcThSU0tRMjZrWUtSUGMKI+xcqiys1BZbkYrmh/F0N5How2na4tXV
            lqBTv05jg1q8q2ZJ8AOVnQJkxyfti6/lY54LvVStumRhGawyP1/q8A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-02T03:20:22Z"
    mac: ENC[AES256_GCM,data:HAM8NIQsMZb9z5vWL8NNX5j4QH0C6hJ4p/9Abd1noqWJbQMKG5GT1uj3nVCEC34B+p6yoqs6TLgZqojlDBXiv2VmRdJd4Ywrsq/gSCZuxyyWVMpB9iGXEJ5M3OWK8Sj0mD1A22GzHXaixRrPGQDMgi2iQrrtmPsXcilmRjtqphE=,iv:DfUwtkyU8ZKZS9iyUrycqngoWPDHCBtf/ffpY9S5g5E=,tag:P/5cJkDlF210RxASbs+mrg==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.11.0
