apiVersion: v1
kind: Secret
metadata:
    name: encryption-key
    namespace: browser-streamer
type: Opaque
stringData:
    key: ENC[AES256_GCM,data:VfkOv7yKK7D3S3ckX/0BjOePMG2GgJj1WKAX3jE38ck5bJ5zNLsRJmK8oxB5/AzRklbDc4v7GebLSuNkCAiTrg==,iv:JCdz3yaNnVfVE+aLdL/S/QtV2Mdnz2IKdurC+oEwXIY=,tag:GWfYPoxa0UJEFQEHgQv0wg==,type:str]
sops:
    age:
        - recipient: age1ase59dknkacq26gemrs9dvwvu8xr8akhfya99lagv5py7c7h7plsmtucvv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByZHNscGcrOVBlYWZsQ1JY
            cnJjaTVrcmV5cmtIZW1VY1hmOU1jbUZERkI0CmI5NE1abzNtSEVRYTJsUG1DY0hZ
            dDJYUi9sTlNORHRvNE84aGZJUC9yZHMKLS0tIEYwd0NkcVJvN3Y4SWFXaXJiSGpM
            NWZ3dm16REpxcEdBdUpnNTZ3Z1ZmYnMK72Zo6k9/RJd/TgX2N9tLrCQpBYt4Muqc
            7u/+WR3OY2apfp6h1nprcf1KM2jqRM1cCJAHVTR8Sp1aXslygPJxxg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age13zs054me9k5h4m8u3hwqw9nz4jg6lkpfmkzqn8mdujjqp76h6plsmlmtpy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2bFZwdzdyeU51L3ZaaTRn
            VXEwby9qK0FidVBUc2prU0grZUhRaStaZG1vCk8xVUF3WWtSUURjOCtkR2RuNDRC
            dDNZM2NKSWt1UHBJOXdnSkp1UmVlRGMKLS0tIFczNkR4K3M3YzFCTW80QjB1Z2pD
            UHVYSDZLTi9vYUlXRFNIREttRzdFMzgKKWKjZ1aziky+DkTrxKVNrxX0m6oD5ci/
            H5BkBHDsBnFCF9CGuEtaTWLl3IO8isI1GlnJkkw9mSefF/V9Wc1g3g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17ttan4es6923ru96408ctjhs2f97mrxq9uw938plgnw6wkstv9cqsaq5cw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWZlZwamwreDlqSXVOWXVT
            SEZoNmVKZERLYmJoNlhaWk9JVEdVeTgxZmtBCnBhcllzNjJOemdqNkpuZ0dESHQw
            N1YvN0Fxb0V4RE5hdE9OK0hpRmtzSE0KLS0tIGVZYkxWNEtxVzE0bisrTWVidlNF
            bXoyR013aWtBbUxFWXpRWVY3UzNINk0KYVTNfBlh7yTKQ+UM9zbW0n+daHyacGlF
            RMJ8l8HiknIwBDtVdotBTdctY7TQ01OC36We/rNrMio18rBoThQ/Og==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1un8ajg06rd075pff8pglkq2q0g020peq7v23qzeqhuchl4y4kyfs0drxyf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjaloxSVRaSGZpMGJEVXVX
            RkYyeXE0d1N6Qlk4c2NjRmtDSDJmbTAydmpRCllKZDNjNGlnZmxWMWRCWWJZTXRD
            OEo5NmlNUUc3bmxZK0dob0xIeFNSeWcKLS0tIHVLR3RpTERHWGIzMHg4TzlkNmc2
            bmUvMUhFUlZJYVJpNGt6TmVwa1VGWnMKbaTQX7w6PitxkQHex+LA7K7R9Ys0McEO
            vjbiJpDj6M02NvipApgSAKmC8lbwNsbNMcVLqllJdwI7HUpwfJII+Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18r3vk6aecpcd69ey7fhgjylg6z37ksfeff6c497mxgv4nwmnyupq4gsfua
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBScHhSYld0U2JrdURTOHpH
            Vi9PcURiT0gvRVczL0U5NnlCVy80MU44TkZNCkttKzk2UmpkcEJXdGNZTFM0Q2Vy
            Y2tsV0FzblJTZEg1TnF1dXY0VHFTeVUKLS0tIFVIUEFDR3kwT01Jai9ESlh5Q2N3
            M1hUZ0syWGtjRFRiUGZMS0pjZE1FajQKOohXBXjuSkyTMftBhkZfhUVXJH2c3HFp
            4UrTEAHLYsI9LgIn9sdU+ftXiElN1E/JjIs+ChTzaA1oNUXNaQfo5g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1emw2e5x3d4cu0x4g0q4lrw8nj2fdv0qfzta6g62m5y24j02zu44sflkxln
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlRDJZODFPNWhUWmhBU2N4
            L3V0a1k0MzFyOTIvRmVGUldTenoyV09vakNNCk1LS3k2U0dxaG9HUDZ1eU5jOTJh
            a2FNemc1VVhVL2JwS3VHaElWUU1ML2cKLS0tIFdNWE1hUzYzaC9ydU5WWWh3VHRw
            YmxnV0RYVmwyY0lSbG9lL2Y1eFkwWmMKpXZi2LwygCZ1NnVM6CjeOuhNtKIj8x62
            5aWzfggaWH9m3+K/3pzIRZgbaDZwKufRzrLKWyldaXlbqCrHpVSGxA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1x9049ry5hz876qratphuc9gdxzuv4nnd06076842zdukl4unvazszfnjf6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwMjJoNEpibHUxY3dwemtN
            emZKNTBNSzIzTzRoM1BKakVZanNKenc2UVZnCjZwS01uRjQ2SlkwZTJOOTZJZkJT
            MGE5dkFYbU85NytlNUxpeUZZcWxSUkkKLS0tIEFzVWg0K0p3TTUyalRQYjB0bUIz
            T0hoaDZXZjZhTDJ0ekR6Q0ZEMHdaUlEKmoS40Hp2ico6d72yoVd4OveBp9SVA47X
            EefhLOKpIWhFyuZW6WgyDlQ5gnRZWM/52b3m8ns4wsvQQ0OHt2l+2w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-02T03:20:22Z"
    mac: ENC[AES256_GCM,data:HAM8NIQsMZb9z5vWL8NNX5j4QH0C6hJ4p/9Abd1noqWJbQMKG5GT1uj3nVCEC34B+p6yoqs6TLgZqojlDBXiv2VmRdJd4Ywrsq/gSCZuxyyWVMpB9iGXEJ5M3OWK8Sj0mD1A22GzHXaixRrPGQDMgi2iQrrtmPsXcilmRjtqphE=,iv:DfUwtkyU8ZKZS9iyUrycqngoWPDHCBtf/ffpY9S5g5E=,tag:P/5cJkDlF210RxASbs+mrg==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.11.0
