apiVersion: v1
kind: Secret
metadata:
    name: grafana-cloud
    namespace: monitoring
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:+gt/QLxk2w==,iv:XBsVQYMnD/Zs5kKcwDailH4QGHljp1Gvq2JaXiHhISQ=,tag:/JtZA3GLRg+CxjkdYCPVMg==,type:str]
    api-key: ENC[AES256_GCM,data:DUsrh6XWn6AOx32Po4gQr5q27HwafS667Gn91n2HS7SN1f2kwH/MgRw/ua80WjdxXjOm4FysqCC754CUUZj41v83POECTcysfgZTPjuoyGEWLPS0RtgmeoJE61Y1OI/jORrI3zvtPuHTLPD5oXTuUXcp9hU4u45avNoAxiTGQrSP/4AWnfFM6OO9XYKEFkliUoei6lRomHotSgcdNCLIrxlgSiugawbXdn0X1QK89SKUhxOK5rGNX39PCSg=,iv:jCuVhEviiXGLpof9b13oopwDOQ4XxfuFTPVuigP5XVI=,tag:AZ8ee/Iyn3oqd+QPKKs3cQ==,type:str]
sops:
    age:
        - recipient: age1ase59dknkacq26gemrs9dvwvu8xr8akhfya99lagv5py7c7h7plsmtucvv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXN2lVb1JjZnlOdW1EN3VM
            MDdjZ3d2Z3BkaS9DbEh6QVVhRDJpV2d4YjJvCmFxRDg0eTJ1Z1d5Vm9ibE1Ta2hS
            b05WQkdTSTBrUFMxZEVITjFBMzNydFEKLS0tIHhRQlRuMXkzdVA0Nmo1U0dodjVt
            d1lpU0p5cGJsdFJqeUxobzA0cGVFb2sKxrzuQqzAmQctszuKKV9txXvhiAES487A
            B/5jmR65sU9oLG3vs/G+KIMyss132faztTJep1tuJR32ozyWeaJ/gA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age13zs054me9k5h4m8u3hwqw9nz4jg6lkpfmkzqn8mdujjqp76h6plsmlmtpy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAraVpHSGM2OVFOSS9kajZk
            bkRpV05HSjNPNktJRWdQQ3NRcGpnREZqVEJnClpGRWpUcDNmbDczZm9OVkNOZzZy
            WmFmc3F0R2NtN0x2dEJ1eTdXaFBpMjQKLS0tIEhETlZLSWg3Y0FpeVVac1dzNVFO
            aWFFZGFaajdvS3E0THY5SWR0UTdtOWsKN8rMxq/u2U64Z1m1E1A++tu7XljlpW2d
            OWuIQE75V+dR7Z7/pi/FiiHSRbxWHc6rLa0156wLLpksM7fBFK5jew==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17ttan4es6923ru96408ctjhs2f97mrxq9uw938plgnw6wkstv9cqsaq5cw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2bEExcGljM0hYRm9ObVdS
            b2txT1FOUTROTnVscllzRjNvSzFUL0dmRFdZCmllU085dlBxNmhIaXZmVGhKYzRx
            T1ZLeXdjVU41YXlMbWR1NDhBeFNWTkUKLS0tIDF1OGt4UXBBNkVNR09YS2VBS1Ex
            SGlOYWxzUmZDMFpxZXdFelJHWXlRREkKAp5INuVteY51f+wZjh1jXGwFb7urKb8w
            cpdEi/7VEAcpcea8Y3jAplO7SP6sNS1hW8M8RA8UOLcPQnrkjdlk/Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1un8ajg06rd075pff8pglkq2q0g020peq7v23qzeqhuchl4y4kyfs0drxyf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYY3BMOVEzV2UwOGVZUlpT
            U0lHVXlXVmVrVGU1SmtTb01ueUdPem1nQkNFCm9uMXhWdEJwMWs4NjBmTmxRU2Q5
            M0Q4WWhBNUNac1V6cnFJYk5WVE1Tc1EKLS0tIERKdUR5WEdGQXBrQjQ4Sk5XMGUv
            QUpFeS82OFpPSXpXYWE5aU8zbEhOVVUKb75fo564D0SEEG36aQ0E+W7E/+1X9dLe
            eIM5FufS2oF4sQndgzJU1ht4M6MGb/ZphfOuiLe7L2qgHBC5YbyFlw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18r3vk6aecpcd69ey7fhgjylg6z37ksfeff6c497mxgv4nwmnyupq4gsfua
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoZUtLbzB1WEtCNXlhQVFn
            cW5ISXEvcWpOK3RJTWR6bHZZVXJIL3FUdWlzCmZidVBpdGNqV0J5S1VqdXlEb09P
            YjBoVmZBWG03TVY4RXVRcHRYM3RseXcKLS0tIDAyM0xRZU5QNEdpb2NoUG1meDFY
            QmgyTU1CamdUVzhKeU9ZWDlTZzNDd1EKT4X49bw4MRWOyWZVSHElLe/qYfs3BLNx
            kQHm1ZPAYXKHEty3gQWkIkovx05zeC1C6uhqztZnZielMXvBuZHckA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1emw2e5x3d4cu0x4g0q4lrw8nj2fdv0qfzta6g62m5y24j02zu44sflkxln
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1YytvSHhrU3lpV3JyRWo5
            bzBLSVdtWXExeXU0dVAvNFV4cWdEc0F3T1drCnNlQmtpbGhoVllCSzYySGxWMmYw
            eFE1RHAzb2orSjB0WjZKWDUwdGhWVHcKLS0tIDVmVW5ra3pxSWFObG12bkZUOUlJ
            YkFPQkRMdHhTL2hjaXN3UlJUTzA1Y0kKYpZJ5hwCmusHzyiQgW9kaBwfBb7Vr1eO
            uHXtmwNFTCZBnYWZNsU+9HNCljDzD0OoLoufDgv51Z52OwygFy4gAg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1x9049ry5hz876qratphuc9gdxzuv4nnd06076842zdukl4unvazszfnjf6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwVW5NRjdtODlYSkNDYzNJ
            NnlsdXNaTE1LdmZNZC8vV0kzZHZ5WVpwNmpZCm5GMk01UXc4SVQvRHE3Q2ZtZDBI
            NnVZbnlmb09SR25qZ2V6cGdiZWs2Zm8KLS0tIHoyQ2ptZUg5MWNJZHZEUnoyM004
            dXdLK0pyTjNiNEUzL1BpS0FwcVZFZEUKomrjlyYXhfXgoLxnp5YvZhwYWVnBK/Tl
            D8nfycQmb2XFJdHnoplMPpvPxxBuJWZA/4RybWc91LXDf9xJOkebgA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-07T19:58:30Z"
    mac: ENC[AES256_GCM,data:eNldOIklTmq7+BkZRmMbMo6Q4ScLSSEs8i/h4fLA8TB7yyPKTB9iDLeQdmxrA/9kEn8NsCSD0OEc49HUV9kwaOGDWIDgNj9VKF0E1iL3PYhH5YXphDhGXg7Vnsa86A4nmOBvoQkKxmdUksHsqAjUVsmwTq8Q0SFE4i9Xj73B6nY=,iv:1DEcUItdDl3YiMIQ211UgJ3gil3LgfUehJE9ouiqZIA=,tag:83EKcEjhTWS//ChBEWw8wg==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.11.0
