apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin
    namespace: browser-streamer
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:TVrWwHA=,iv:YGRv+YxUrMPxpTGoJYbsQ9GX/W5oK3BTJ269jfZdGFU=,tag:8lqC/wV7kEAsPpJVozsfeg==,type:str]
    admin-password: ENC[AES256_GCM,data:SXhSOplPvbINMoJtxeEHnQ==,iv:7lJHCkpmkmT7LXIY5mPvVLBGrnzmBZdRlShkguddfBs=,tag:kRcENMlAs1dCmefFzOv1ww==,type:str]
    endpoint: ENC[AES256_GCM,data:Y2Htx2pHWjvg10SimN9kdQwD/q9iYtzLZcQS/7qLKfLfRnXUPszR6Vdv875ce3BCe3WeECnU8Q==,iv:QV23EOrAvBmwSLYdIG9uK6lJc1raGKRuuGk9KZYM+uA=,tag:hrtWuA/IMwyUJvX4Q5sQWg==,type:str]
sops:
    age:
        - recipient: age1ase59dknkacq26gemrs9dvwvu8xr8akhfya99lagv5py7c7h7plsmtucvv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzaTF1WFBqSDQ0MzU3Rjg3
            Q1JlclVWeUtxRWhSRjFFbUR5ZkpGU2w4a1dZCitqbHNMNlkyTmlaQzhRR1krdDJ2
            VStYNDA2N1piL3dWVkVNMjdUWkdvVG8KLS0tIHArejFXV2ZIa0NqeHlUSUFLRFlS
            WkU3dWZNem9IY1o4bGFTdmlSTWZrblkK26gLTzfLzlZSfNob1AnYccJU4dYlw/aU
            yFhQ0OVOUW7Rnx+Mx+JCnNnSoSAHEkbvDK/Eaa5dIL8KFXDAgI1W1g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age13zs054me9k5h4m8u3hwqw9nz4jg6lkpfmkzqn8mdujjqp76h6plsmlmtpy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvdUVoRS95U3dvSkhCVDUr
            ZFRrYlhjNTR5ajcyeWVZRjdqUTFKbW1YZm1JCkh6TGVveTZPbXlYczFVdDJlMm1t
            Q2JiakNOMlNCc0xxc3hoQTMzaUtZeFkKLS0tIElTYWpCVkVDNlorc1ZZeEZzVG9x
            bG5FSTdFNnZBNkx0c3d1SUVBV0lka28K2LvKagyxi+hPcCAHUZ8V7fs0yYd/zHBt
            riLoHekrMjjg+i5/koofFAg6lbLlciVVInf/hckF7uy/Ohks7uPnwg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17ttan4es6923ru96408ctjhs2f97mrxq9uw938plgnw6wkstv9cqsaq5cw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6emlOZThBWkNTb2c0azd1
            K0crQThZSjllTVRGSUszT21XMUFUQUtKT1RZCmNEeCs4TnQyeTIyZVNzTXBiVkZ6
            QUQ3SFlaRU0vL2pxMC9QVURxTEZKbm8KLS0tIFlFQlRDczRINVpiaWU4b1hETEt1
            cmVFRkVoS3ZINk9hM3ljY1QxNkxKV2sKYiK1fI+LV9mzzi3R8x0HX99EgCrHd1v8
            Z8KqG/4I1AZtYJqQCg90tOKkzusIlk9M/hRSBIYFFLhtU+pIBgcfEQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1un8ajg06rd075pff8pglkq2q0g020peq7v23qzeqhuchl4y4kyfs0drxyf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2eE51aWw5cm1BRVZacitW
            T0VIVEEyZ0RIM1RZZXhDRndkdU1vbmtwUkJVCld6UlF5UTl6OGlabG1KSnZXT21p
            TW4xcHhuN3IycjJnY0QyMmUyUjc3S0UKLS0tIGVER0x6MVJXeWdYa2tnaHUyUDVD
            R2V1d0ZBcmw1aWVyc00yZFpHVG5hM2sKEWI03S3MIIZG5TtI+BIupoPQ3wQDZpU3
            b7w6HvNcfjmSPIbDOiUVFlQgj18YC3AsVMFEMbGUK1m5mGiR2K62yw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-28T22:18:59Z"
    mac: ENC[AES256_GCM,data:IUyz+tZxxvM26cJ+8ex4k40aJAh8r0Gr4pQdnUQDeOSJ1O4/j2/v+t2iwYqBPOCZG8XxnqKiMxo9dVHEQ8133tQWJxU933rB8QDHeI2MdYQkv1gWNP2xnQMGSO1dwWdUDWVJ2vKrREJgfb/RCrrlaw0k+8xXvgYWVM5/idc9GpY=,iv:EnZdy4nnqikGQ5I41NW+av3uY+2lt1oGJuyGibuM7L0=,tag:uKXlOTcR1vA5oMg7+9LWNw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
