apiVersion: v1
kind: Secret
metadata:
    name: grafana-cloud
    namespace: monitoring
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:+gt/QLxk2w==,iv:XBsVQYMnD/Zs5kKcwDailH4QGHljp1Gvq2JaXiHhISQ=,tag:/JtZA3GLRg+CxjkdYCPVMg==,type:str]
    api-key: ENC[AES256_GCM,data:DUsrh6XWn6AOx32Po4gQr5q27HwafS667Gn91n2HS7SN1f2kwH/MgRw/ua80WjdxXjOm4FysqCC754CUUZj41v83POECTcysfgZTPjuoyGEWLPS0RtgmeoJE61Y1OI/jORrI3zvtPuHTLPD5oXTuUXcp9hU4u45avNoAxiTGQrSP/4AWnfFM6OO9XYKEFkliUoei6lRomHotSgcdNCLIrxlgSiugawbXdn0X1QK89SKUhxOK5rGNX39PCSg=,iv:jCuVhEviiXGLpof9b13oopwDOQ4XxfuFTPVuigP5XVI=,tag:AZ8ee/Iyn3oqd+QPKKs3cQ==,type:str]
sops:
    age:
        - recipient: age18r3vk6aecpcd69ey7fhgjylg6z37ksfeff6c497mxgv4nwmnyupq4gsfua
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpRzVYWGJYMEcweWFqTEEv
            SFlISzNiVXROK2xGQ29MSGJzU0hwcXdsaUg0CllkRjhHeFVWSjMzZmtoZ3VWWUFP
            elBhWWlMd0RDVEZjaFVOcmZKQzQwMFUKLS0tIDZnRHpkV255YVhDN2tsTGt6end0
            a3ArTHRSbjJLZmhoSWFqRmx3NEVobEkKYwW0hFr8X4ryh4D7i6/vfVilKmwLNubi
            X62ucPIHS2rSnbziYZcp74bjHXo6P9WCFa/dwQl/ZxGizoXcxSSt2Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1emw2e5x3d4cu0x4g0q4lrw8nj2fdv0qfzta6g62m5y24j02zu44sflkxln
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmTVhYMjhjMlEzYUMxOXh0
            Z1pYSHJlZHE0VDVJdW9wQ3Jnc0cxZ3pJeUF3CkFVcm02cXNFRjJVM2U2WlBPQnRt
            bHpkNldlNW1BNTFleG9IZy9KOVhFWFEKLS0tIGNkNmM0ZUNZd2I2dFNJVTkyUFZF
            QkJrVTFiT1gxMWtFN0FRNEZJeWVTazQKd/r1Fg5gZMfQi271TgH14//UpiHzS7PX
            EcXdiXPzabfnroevN6vfvs/4bzXrUBM5j87bvTs/bs7OM4RCdfeaLQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1x9049ry5hz876qratphuc9gdxzuv4nnd06076842zdukl4unvazszfnjf6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNQzkrVVkzSUIvZDlPUkxZ
            ZWVPbHMrNUp4dnhLS2lJUTdlRVhTNWxBT1YwCnhBclRGU2VXcENJMVRFZ0IrMFVD
            RFh4dmFEaGRXUWo2MUlNTGJQYU5acmcKLS0tIGJ4ZFZoVVBqTWl4QnRPSzQ5TjN0
            bEpLckN3S0JCUDQ0SUF6NHVKaGJtY2MKsqW2jYimt2WBbknzkBXO+YHks2Wfu8Vt
            6ASa3xIoUivSuxlyPg4yE0Ferb57A21x8oyajYvhG+PpjeE1s3tPWw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1y5txpqz0vyyq03yyysmzuyvuyh8uzzpcw30cp5q3twxnwenfzpvs48ts0z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByczZDeHBtUGcyWDdDN3NB
            OTJteEwycnQwZmduUjh0WkdNUG5RZlhxSFh3CklSOXYrZDJ2dTNWbEl1NlpxL2U3
            bXdZMVVwSjIyN0VyRHhMZ21TdmhsWjAKLS0tIDgrM3FlL0xxN090ZTZwazZvNk5l
            RjByUUJrWi81R2huR1VMR2NMcXRzSDQKhUWMAlQv0EMHi0St0E6ZISEnL/FaJdeg
            Hln+vw7sw7AlJyVDBVhNgtX0K3j7zgkiuC9OC0oj7oqkl8ukAEV02w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-07T19:58:30Z"
    mac: ENC[AES256_GCM,data:eNldOIklTmq7+BkZRmMbMo6Q4ScLSSEs8i/h4fLA8TB7yyPKTB9iDLeQdmxrA/9kEn8NsCSD0OEc49HUV9kwaOGDWIDgNj9VKF0E1iL3PYhH5YXphDhGXg7Vnsa86A4nmOBvoQkKxmdUksHsqAjUVsmwTq8Q0SFE4i9Xj73B6nY=,iv:1DEcUItdDl3YiMIQ211UgJ3gil3LgfUehJE9ouiqZIA=,tag:83EKcEjhTWS//ChBEWw8wg==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.11.0
