apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin
    namespace: browser-streamer
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:TVrWwHA=,iv:YGRv+YxUrMPxpTGoJYbsQ9GX/W5oK3BTJ269jfZdGFU=,tag:8lqC/wV7kEAsPpJVozsfeg==,type:str]
    admin-password: ENC[AES256_GCM,data:SXhSOplPvbINMoJtxeEHnQ==,iv:7lJHCkpmkmT7LXIY5mPvVLBGrnzmBZdRlShkguddfBs=,tag:kRcENMlAs1dCmefFzOv1ww==,type:str]
    endpoint: ENC[AES256_GCM,data:Y2Htx2pHWjvg10SimN9kdQwD/q9iYtzLZcQS/7qLKfLfRnXUPszR6Vdv875ce3BCe3WeECnU8Q==,iv:QV23EOrAvBmwSLYdIG9uK6lJc1raGKRuuGk9KZYM+uA=,tag:hrtWuA/IMwyUJvX4Q5sQWg==,type:str]
sops:
    age:
        - recipient: age1ase59dknkacq26gemrs9dvwvu8xr8akhfya99lagv5py7c7h7plsmtucvv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArUDNIUC9NZnE1ajNsUjRw
            RFBuVlBRU1JWWU5aeEFJQTlHb3JpSGFFazJJCjI1aCs5N1NFcUlUZGtCV2Mwb20z
            aUpFYW9NY3ZybE9UN05VVUhremtMVm8KLS0tIDlyRTNJNHB5dWJuL0tDWUUwRGVz
            K29jMzRxWXdzNWltYWlVc2E1STZRYUUKqLQvhckcUI2olKVu8mR8cSAzzNec63E9
            Upj7eFrVcUp9Yqiq/wPrhNFgpF+pQ1RnwInA+wiesJ25MI5bNuh8kg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age13zs054me9k5h4m8u3hwqw9nz4jg6lkpfmkzqn8mdujjqp76h6plsmlmtpy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwajZaaFBDaFEzSWJzZkNj
            TEg3M1hNUmdodmEyaHJ5SXBBUFZzN3RFV2dVCmZaN3llL2JmVi9Kd0hRaCtWMjVY
            Z2tXVUp4dDJUdmQvQ2JiTmVDamp6MkUKLS0tIElVZjVuOWV0YlpSeGc2VFpsemFn
            Z2NuZE5PTjVLNGpHdTlJQS8xdjk0KzgKQ7JCLkJjObK9AGPUT9cw81cAoHJBb62c
            UFvsoYOIzL9Dbnq51ZmZgZyVG2ZY/mUrJPdBYGGDcMEEn9El+XRAJw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17ttan4es6923ru96408ctjhs2f97mrxq9uw938plgnw6wkstv9cqsaq5cw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSWEExWnk3NWZjOThObGRh
            c3RGVVFLS3RkK0MxNmFFT3ZUcEg4NzA0NnhVClNrMmJSNTZMYWk5K0R6cVRVWDE4
            bTZZdE1ONDlnNEhibmRzK3haZEcrQnMKLS0tIE1zRFlHVi93K2luYlJJcXpSZ3Rk
            QTlqZjJQVTh4Y1VaWWxUR0EzOHl0cW8KSBBbaTNjaH0yPWKYMC0SC/mzbh4qhDXC
            SdmurlyufPAQOrcR59o15PuKd1NOlnWnZRpoLGLH94fiukbgdv5I8A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1un8ajg06rd075pff8pglkq2q0g020peq7v23qzeqhuchl4y4kyfs0drxyf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjZXh2VTVLRnZlZmhpd1R5
            K1M1NWdUOTAvOFh6dVdlK3NlQ2gwODhqOFVFCjh6ZFJaQTlId0g5cEEzVEpBZlNR
            bzJsK3p2eW1iQTRaZ2R4VVl6dXNPYmsKLS0tIGJoM1gzQjVGUGQ1U0FLcGwrVnll
            WitDWXJGYnNJYUF5bWh3S1EzUGdiNDgKPzF7xV3P/p15WxK5pP0xTC14OKL2tumq
            FWZkzmg3BUu8xolJD4mxYECZb51lm68Zmhe4wu498MenM+S2jVeVwQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18r3vk6aecpcd69ey7fhgjylg6z37ksfeff6c497mxgv4nwmnyupq4gsfua
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoTE9HUlRybS96ZkhpOWJO
            c3YzOUZhMGloL05QcmlxVjlSd0hFYUdlbW5BCitzVUFMd2hzUWlIdGpyS2hsQVQ0
            YlBYSS9MeFF6UC9zSkhnaFczTCtxR2cKLS0tIEpzeXMvdE81Tk1RblNHK2dZUVRz
            dWZjMDFKcXhTMURlSnJVb2xxTEkvOE0KACrmjedq1CqyUvCVV/kQthyWsqDuNRxy
            FqYEsEpVK7dJguQDWLywfdyLGMmgIpGPIPb1m1HfccWhHeBiGhYqqg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1emw2e5x3d4cu0x4g0q4lrw8nj2fdv0qfzta6g62m5y24j02zu44sflkxln
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjTWQ1ejFUTzFHNUlVbzBE
            RkZsaXN5VUlaZG9CTkdXbFNIRzE1M0NRUjFFCi85MG9sWDM1VzAwb0lsOW9BaHR5
            T3FaT214ZXRZbmd6Q2hqOW5qdVE1L00KLS0tIENub0FFVUErVWZsT0NDa0ZQTmRw
            Ynh2Ni9BYWlrN2tYbkhscHlDVGdzTVUKZvenyEMSsquSS1J/fIgb+V4QpCt6jfhO
            lXoJTu50lg/p2la6OqjNCD4vTVHtTfKAb60ATZQddjQ+ZkEO5VssgA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1x9049ry5hz876qratphuc9gdxzuv4nnd06076842zdukl4unvazszfnjf6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtK0pMeXE4ejlwcnlaL3VJ
            RE50ZkZrVUxvamdhc1pHVmFqckxyM1EzMVRJCkxYL2ZiQzU4bFppYkVwc3BHUllL
            Zk85aENvNVMydE9JSGFCV05xL2Y2dkUKLS0tIC9DeTdNcnNvTlBvZWpuek5icGFt
            Y01NblEvdEZZZkRGY2hyR1p5R0tEaFkKbPZ3idtZBENYtj1IvcEWeuH8Izav//31
            OpknFQLoq2wPO1Cvz5w7c7JDJk2WExVXnjgGBc4dewZOH1dVJPJbUA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-28T22:18:59Z"
    mac: ENC[AES256_GCM,data:IUyz+tZxxvM26cJ+8ex4k40aJAh8r0Gr4pQdnUQDeOSJ1O4/j2/v+t2iwYqBPOCZG8XxnqKiMxo9dVHEQ8133tQWJxU933rB8QDHeI2MdYQkv1gWNP2xnQMGSO1dwWdUDWVJ2vKrREJgfb/RCrrlaw0k+8xXvgYWVM5/idc9GpY=,iv:EnZdy4nnqikGQ5I41NW+av3uY+2lt1oGJuyGibuM7L0=,tag:uKXlOTcR1vA5oMg7+9LWNw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
