apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin
    namespace: browser-streamer
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:TVrWwHA=,iv:YGRv+YxUrMPxpTGoJYbsQ9GX/W5oK3BTJ269jfZdGFU=,tag:8lqC/wV7kEAsPpJVozsfeg==,type:str]
    admin-password: ENC[AES256_GCM,data:SXhSOplPvbINMoJtxeEHnQ==,iv:7lJHCkpmkmT7LXIY5mPvVLBGrnzmBZdRlShkguddfBs=,tag:kRcENMlAs1dCmefFzOv1ww==,type:str]
    endpoint: ENC[AES256_GCM,data:Y2Htx2pHWjvg10SimN9kdQwD/q9iYtzLZcQS/7qLKfLfRnXUPszR6Vdv875ce3BCe3WeECnU8Q==,iv:QV23EOrAvBmwSLYdIG9uK6lJc1raGKRuuGk9KZYM+uA=,tag:hrtWuA/IMwyUJvX4Q5sQWg==,type:str]
sops:
    age:
        - recipient: age18r3vk6aecpcd69ey7fhgjylg6z37ksfeff6c497mxgv4nwmnyupq4gsfua
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCTlY5KzFPTCtOMmFnTHp1
            VCsvVkpJdmh5b1hMQVBNcmNzOENYemNCKzJFCjdDUE5Za1QzY21QdDNaS3N1SXNE
            V0J4TWhMYWQ1bkY4d05JTDVRQVFieDQKLS0tIHRSV1l4OEhtRlF3Sjl5ZTBBREQ3
            YnRySUVrTEZ3VWpKc0dRbWhnNGRhcmMKFpAnm3aXiuiD7p69nKna0cbv0IvR0qhU
            YGudwlCPWL1xH4xyamfzQJeD00L/rdWyscA2FZvxQO0nn8Kpdq8aLg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1emw2e5x3d4cu0x4g0q4lrw8nj2fdv0qfzta6g62m5y24j02zu44sflkxln
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDdlI5VkoyaUc0MW1nQXlN
            L0xUOERmd1htcno0MnVScUdiVzNOVExyZVUwCjQweXVMWGhIbERjaThMYUI5ejFU
            aSs3Q1dDZ2hoZGozUUl6Mm8vMWhvYXMKLS0tIDFjNXNtTGRmeXdwalZ6dStsMS9N
            SjN1b2RYS3lMVVRxVkcxYWdMZmF2UjgKMutI7M4qRrO6qWpgk4efHTm1CD4vzNdM
            d/4PuxttN7rA8MJ+Aip3dlpp+iCFiJt0LGW4LQ9r7U3M7XtO533ttA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1x9049ry5hz876qratphuc9gdxzuv4nnd06076842zdukl4unvazszfnjf6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBWkFDQTI1VlJiRVJHVGZX
            ZWlKTENUOFZOSXNhTFhSL2kyTWJIRWRMSnlvCnNlMFdtUHZYVTRGRVRXd25SZWM3
            SGRGL1lSZDJHNlJsY0llOFZuZHl5RnMKLS0tIGJaQlFLbk9PZnFVN1hYTTRzejFs
            bUFWRDY4MXFVRkVnNGlNNFlmbjE2L1EK5nqS9RoVfnQBLm7G5ZyJgap17MAK9HO6
            205nEweFO7dB0dOMu3hO65FefpEfBwe7xTGy+jvjsUMed8+TA1Zk7A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1y5txpqz0vyyq03yyysmzuyvuyh8uzzpcw30cp5q3twxnwenfzpvs48ts0z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpMXJJVnN2TE93OTV5NVV0
            VENWMldTOG14elFiMENqRmlEdEo0c1ZFSndFCktsYzRZYU5HMXY3RjhrMzV0UVRR
            RnpPeFcweDVTb2twSk5TZ2xQdlMyTm8KLS0tIGFjeldaOWR1RGNJcUJNY1VoTlBG
            VEhpMXREeVFha3krL0ZXQnFUV0VZMGMKgvm0moZhGdxEKUONXx37NoN+Bn/zlM19
            wZZybtxbeCMqHYF8uFzBP9PbZc7CgXwpZEgeAk2nfnrx1a7qf6MpNg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-28T22:18:59Z"
    mac: ENC[AES256_GCM,data:IUyz+tZxxvM26cJ+8ex4k40aJAh8r0Gr4pQdnUQDeOSJ1O4/j2/v+t2iwYqBPOCZG8XxnqKiMxo9dVHEQ8133tQWJxU933rB8QDHeI2MdYQkv1gWNP2xnQMGSO1dwWdUDWVJ2vKrREJgfb/RCrrlaw0k+8xXvgYWVM5/idc9GpY=,iv:EnZdy4nnqikGQ5I41NW+av3uY+2lt1oGJuyGibuM7L0=,tag:uKXlOTcR1vA5oMg7+9LWNw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
