apiVersion: v1
kind: Secret
metadata:
    name: grafana-cloud
    namespace: monitoring
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:+gt/QLxk2w==,iv:XBsVQYMnD/Zs5kKcwDailH4QGHljp1Gvq2JaXiHhISQ=,tag:/JtZA3GLRg+CxjkdYCPVMg==,type:str]
    api-key: ENC[AES256_GCM,data:DUsrh6XWn6AOx32Po4gQr5q27HwafS667Gn91n2HS7SN1f2kwH/MgRw/ua80WjdxXjOm4FysqCC754CUUZj41v83POECTcysfgZTPjuoyGEWLPS0RtgmeoJE61Y1OI/jORrI3zvtPuHTLPD5oXTuUXcp9hU4u45avNoAxiTGQrSP/4AWnfFM6OO9XYKEFkliUoei6lRomHotSgcdNCLIrxlgSiugawbXdn0X1QK89SKUhxOK5rGNX39PCSg=,iv:jCuVhEviiXGLpof9b13oopwDOQ4XxfuFTPVuigP5XVI=,tag:AZ8ee/Iyn3oqd+QPKKs3cQ==,type:str]
sops:
    age:
        - recipient: age1ase59dknkacq26gemrs9dvwvu8xr8akhfya99lagv5py7c7h7plsmtucvv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMWkZZUkFmQXlIVmhxYk1S
            eWc4TVNLeHVod1BSS21DbTNhQzdsMTJqL3dFCkhYczIzSGVWUlNFZlNtY05NNWho
            M0xmR1V1RnBXaCsxQmhDK1RkZkhwNGsKLS0tICswNEhxS1dzUHNJZS9XQzhxRDF6
            RE5UN3ZIOXdVM0lsUmoybWRyS1c0RXcKL4P4ZWs5cpctF81o1WlrL8tcNSnwabyH
            erYC95imUJrV8YrfMn8wFFwVoVXSrLemdnNT/oQwIcy6BZN2AgFPdg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age13zs054me9k5h4m8u3hwqw9nz4jg6lkpfmkzqn8mdujjqp76h6plsmlmtpy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4YURsNlpiaFVNc0hOMVhO
            bVpTMGltejlQMlZocC9TUFk1U05GazVRaUI4Cm14bUR0MmQwbjJVeTNZNzNKVnlt
            eGtVZ0IwT0NXeUlHNTZnYm9NSTR6VXcKLS0tIFJvSEZqYmV6RXIzRTRsc2JsTWxK
            RDNEOXFWMTJsLzVHK1hxS1JjejNITjAKhEAX4xTBJ9RI91C6Up7qKuVxuzpH04X0
            uylL7vEokmUp3AdgPz3xZnui0FmLyky2xWOpd+qgs5/VGcwXzeXPIQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17ttan4es6923ru96408ctjhs2f97mrxq9uw938plgnw6wkstv9cqsaq5cw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4aVNRcWRwWW8ycVhGcXBQ
            Y3VIQUJ4V1BSUG1EVllGV05CUTQ4d1k0eG5NCjcrRTVwYkxYdzBqRS9Tai9zUkFF
            NElKZmZON25VUnJWbEsxRFdEOFFqZ1EKLS0tIE43TlRZVjg5cGZBQUJOK2w2dnEz
            YmdlM2hUcndDMlNjSzlNcUtvRTg2S0UKXi63UgOppUKaOnCVvYobIDexglXGPJTq
            f5D6kWz+ldRkM9mqabVwMwqmwQBxWwHA2bfN9pO/9K0/WtXkMy4jaw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1un8ajg06rd075pff8pglkq2q0g020peq7v23qzeqhuchl4y4kyfs0drxyf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1N1VTbGlxaVY5Qi9zajhH
            UGNOVEdyYVZPanRleExBOVZ6a0JVUVNSeFdrCmxETC8rYzdrd253bmlpck9idUc4
            WGpnNUlodnZ1Uk9WSXhvYkR3NjZZQTAKLS0tIHZ3YTlBYWVEWjM2UnFKTlc5RnFu
            MHhvMGxhaTlwL05ld21yczdNTWlPczQK+irPmQN7pXwkGFBcYlO/etMb6zGVkr4O
            PoOHCU1hN1y1JYUE1Jd+DIkUgiBuuEc/sfX2qfgGA35i53pwBmIyow==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18r3vk6aecpcd69ey7fhgjylg6z37ksfeff6c497mxgv4nwmnyupq4gsfua
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1S3lLK0M0aUdTVVhmY3R3
            MlB0em91d2lVeWVLWDhuV2JLOG9OY0Z2d0d3CjM0Z1ZIanl5SUlIL1dSM2l4Tmlq
            dVZPLzk1WWMvVVlPVW5UcEFFTFJMUGMKLS0tIEd5YnJ2enJWT29idXlPanpweWwx
            NE0vMlBqbStRbXdNZHoyNURPaVY3SHcKoDUEJDdnm4jU/pRdvMQ9bYWkjNV58bFw
            zJK66m7/EZCQvZaoLvc19RkQREC/taGUYVKN+T1WZ8HvqP0tn87XsQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1emw2e5x3d4cu0x4g0q4lrw8nj2fdv0qfzta6g62m5y24j02zu44sflkxln
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1OGhZeG5FWVdSeWdxY01M
            LzJkMks3b2xpWmRFR1dWVmpIV3JDMnRqVUIwCmpndmdrdTNMakVMUkM4TzVYNnNo
            MGdad2Q4OEhMMHdhYzFmaXZDZDBaYXcKLS0tIEpyR0dZd05pU0pDaWVkakQ0S29K
            QUV6YjFwd3Q5MGdkN1BrOThTSzhFazAKAhM+nKcI17JNF6+6whku5trlFzOJna29
            VmCOCk5kvnTupAU0K+7vtU1llx76GZX+we3tZ0T99GBqJilRq+KYow==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1x9049ry5hz876qratphuc9gdxzuv4nnd06076842zdukl4unvazszfnjf6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1c0ZmdWpmb3dCN1VDL29H
            dEprUjIvckhDZDAweUZXL1E2Vk90eVl2RUFFCmZVZWxmcHVRY2c2NFF3Z21tbjMz
            dVBIM1cyTktCdTgzdWtLdmZWS1p4L2sKLS0tIC9GS3VxTXZMNlFpQkxtQWZVWVp1
            dmJKY01EREZISFJ4VGdwazZiZmQ0cjgKxhBMWWA5cCpr9SpvtR4sUyFD/dRI3re9
            Bnr/Q9sPDJsdxV94c6tqbPPiYZOEgIDMB+fuoa9XWla2027SY7ZBnA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1y5txpqz0vyyq03yyysmzuyvuyh8uzzpcw30cp5q3twxnwenfzpvs48ts0z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEbHpMM3V2bk5RUGVkSmI5
            N2ozMWdNck9ZZVVhM1FjSjFQVHBLdWdldEhNCnhXUVlrWWdiM0tqMXNvU0wvSVRE
            MmxOTkZudktHaHV0NW5oZlFJZmZ5TjgKLS0tIC9GOTZVNzI4RkJIVWhGRE1xUzYw
            NGRQM2IwWUw3dXM3VDVsV0dwd1pZbEEKdFn7IQDZtXMebgtKA8d47AS1BegVO902
            rGLefAwTpvIbe/piiL81N+2Z9iyQY+uY4zsGLXrOCzqZ4IkaRIdCHg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-07T19:58:30Z"
    mac: ENC[AES256_GCM,data:eNldOIklTmq7+BkZRmMbMo6Q4ScLSSEs8i/h4fLA8TB7yyPKTB9iDLeQdmxrA/9kEn8NsCSD0OEc49HUV9kwaOGDWIDgNj9VKF0E1iL3PYhH5YXphDhGXg7Vnsa86A4nmOBvoQkKxmdUksHsqAjUVsmwTq8Q0SFE4i9Xj73B6nY=,iv:1DEcUItdDl3YiMIQ211UgJ3gil3LgfUehJE9ouiqZIA=,tag:83EKcEjhTWS//ChBEWw8wg==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.11.0
