apiVersion: v1
kind: Secret
metadata:
    name: oauth-platform
    namespace: browser-streamer
type: Opaque
stringData:
    twitch-client-id: ENC[AES256_GCM,data:EQe1pRI2XmLDcS8CkMUFQYncCPiQVN8llG7/RiiZ,iv:7VI+3LncXOsb6nP86lnP4vooZgbhgxO9dfsoxRSDD1U=,tag:OMVNh1GRkF3C+16Lbd3wmw==,type:str]
    twitch-client-secret: ENC[AES256_GCM,data:DZSqlvkXY1VmO10wrr6x2CNhbgk3V9DDhSXjoZvN,iv:jruRnk5+luszGp0AaPCGN+2dBjkT2y7tUQzDLtuulyc=,tag:qaRFBcUFmYh8Ml01Xb02jA==,type:str]
    google-client-id: ENC[AES256_GCM,data:69Xpw6MZWCxZEkrR3X3oYeQdt815zgrXM355iNMhOGy8vAe8XggvZ8K456Rwu+GQ5h36q9a2mkOHoyouYT6//a4C1pvNR2mC,iv:a8V7anXV45Rh3aGakYOF4IB4chr5nFgOslcat+BT8MI=,tag:9QfPkt/KfwaKSsXJae3GdQ==,type:str]
    google-client-secret: ENC[AES256_GCM,data:ELBA5tvSXsfhMS5VEapbBBGsna2EicOyibmO6F8jJRiW0OU=,iv:WIjcPW/PH1COGds/gmNDfsfw0uTw4vFHYvtyUk02WXw=,tag:iXM4Vrz/cF30SGCQk9dzmw==,type:str]
    kick-client-id: ENC[AES256_GCM,data:8ggrLR0Lpywjjv6nP3aQDGG5DOXZM0J+4kM=,iv:24dEcD1BFw1TcIuSq0WCPXuI8B05DinWAk+eDPHI30E=,tag:XaVKXMv19K1fBguOWzY/Kw==,type:str]
    kick-client-secret: ENC[AES256_GCM,data:ArlVgBo0nskCCFa8XmWCTkF7vwFJma9YyXtOdBBKfOH1Y7LPlxVFde4Pgrki+QdTDSOoJeHw2zFi0h6F7dqRDw==,iv:HHlKfwM07ARvzXOAnmLj7BSu64Cxj4iSsqDGbD2PiMg=,tag:JzaS5ad8lVYHvmBm4vY1tg==,type:str]
    restream-client-id: ENC[AES256_GCM,data:F9QcXHbv9kYthU7yir369veuqfvFDNvsMDKj3rnRjsWaelNJ,iv:eo3uyqYL+S2sjB8RJg4SM1PAnCr7eW5KQjpk61vtkZs=,tag:Ak2NXu/wq8cG/h9401I6/A==,type:str]
    restream-client-secret: ENC[AES256_GCM,data:acrZJJu7ML9hTdyHfy262CkvJm9Zu9LiFh0IV1Zs7puQXBjW,iv:n6Xocuz3l3OyAvrCwcwAfj0FeBMbAkdH4OBa9PK2Kyk=,tag:5vQ4xJGAZ9+aiGxRBWsQsg==,type:str]
sops:
    age:
        - recipient: age1ase59dknkacq26gemrs9dvwvu8xr8akhfya99lagv5py7c7h7plsmtucvv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzTDNDYVJ4c2l0TW1Bam1W
            VGJCNEZRT01zbmtwbFlnQklsOHcxU1RTNHlRCjNsWDVob3BTcHU0R1hNbW1tcW1s
            RlNSRC9ienhsWU9vQkFvUjVKK21kN0kKLS0tIDF5VGY4MmJOUVh3UjAxVEhDREhR
            QXg4OXpHL0djQ3h3bC9WeHM1Q1ZXYlUKwMHLZ1YWH5E3LZzXhzoqueQJRfpwNwuP
            Gc0/+9ZM7JYQWVeTdBUUk0ueXAdIRi4PSGkigMkdkdpTf2s3lJHMUQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age13zs054me9k5h4m8u3hwqw9nz4jg6lkpfmkzqn8mdujjqp76h6plsmlmtpy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjV2RaYm0xRHZ5Wkw3RVRa
            c21GMnhxT1NpUVNFN3BGTWtIQTkrZ3Yyc1JVClRnNjdoWDMrVlNPSk1pTUVnRWdN
            K2k5NVdpQmxoWHQ3c0l2eEFlcGhwcWcKLS0tIGVhaGRseGVpRlFoOVBnYVpzQ3Ja
            aVpackpRcDNPL3ZzVWRNdkp4emUxdmMKsb1Ux0GpJdBviiNmD7b1Pt2kNyhPGuqQ
            XcJ3Bva01yIEL3EdPTjUW4sNV1lVzijQ1PhFq+GbZNzUHZkpwkZagw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17ttan4es6923ru96408ctjhs2f97mrxq9uw938plgnw6wkstv9cqsaq5cw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTQk9lWjZEZkE3RnJrYWlV
            VWxIUEszRmVXNUNTUW0vUDBWSit0RUQ2VEZRCnAxbWJobE8xa1FROXoyaC92azh0
            NXo3MnJLQm9oZHdFWVkrZFZSRHNsdzgKLS0tIG0zUVZXRGR4U3o0dDFxNm1ZUk5t
            cDEwVm1nazY0Q0xBL1c1RWdDZ3pHaVUKE099d7OM/w7GGrvPds9yOg+ccP+I3Ulf
            7vl8yZWKRwXWLxvYpdUy73LK80iQrTCGf/GOVAD4Sew+K31HBcsymw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1un8ajg06rd075pff8pglkq2q0g020peq7v23qzeqhuchl4y4kyfs0drxyf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVMTZHVEhmV2Rsa3kxQSt0
            cU00Nkpha0NZRDZpVXEzdHNlc0JCU2Jmb0NZCnY1eGM0VWxXOFptaVIxZ2FjVllG
            aE5kNmRKeS9jQVNUS2Z3ZHk3NzNDSVEKLS0tIDdqNFYzbEFFdWJ6VVRoM0phVi8y
            cENwZWcwY3JlQm0zellIZVFua0RUS0EKJw7eoSh6p7X+4A4JfVNB1r41Ool4ne6t
            aoPXFA2/JahIrMfa3X4xsIOfOpFIbbya2c8qRsFdv8Zawy1tqE6n3w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-23T18:29:44Z"
    mac: ENC[AES256_GCM,data:LD21YPBvE5gYOHNSXJoyCTGHz8Joo3wp4f1904y2zd+B9WJXN6znHqxCjiRDh/azzrQ5p/wqjhhyx2RJVywuz+7gzWU1hzpgOKOrHDOHKhxlU9FGbhMjBrBB9I5tMXH+/LRhvyyhAwxaagdfxb6fO1glVHqrtjPooGi//vUAQUo=,iv:0bAnZYdtw52/gHkM8ARUmbe4BeXdwKU6HA54T+6ske8=,tag:EFHZnPzet/uKKuMb7KWErw==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.11.0
