apiVersion: v1
kind: Secret
metadata:
    name: oauth-platform
    namespace: browser-streamer
type: Opaque
stringData:
    twitch-client-id: ENC[AES256_GCM,data:EQe1pRI2XmLDcS8CkMUFQYncCPiQVN8llG7/RiiZ,iv:7VI+3LncXOsb6nP86lnP4vooZgbhgxO9dfsoxRSDD1U=,tag:OMVNh1GRkF3C+16Lbd3wmw==,type:str]
    twitch-client-secret: ENC[AES256_GCM,data:DZSqlvkXY1VmO10wrr6x2CNhbgk3V9DDhSXjoZvN,iv:jruRnk5+luszGp0AaPCGN+2dBjkT2y7tUQzDLtuulyc=,tag:qaRFBcUFmYh8Ml01Xb02jA==,type:str]
    google-client-id: ENC[AES256_GCM,data:69Xpw6MZWCxZEkrR3X3oYeQdt815zgrXM355iNMhOGy8vAe8XggvZ8K456Rwu+GQ5h36q9a2mkOHoyouYT6//a4C1pvNR2mC,iv:a8V7anXV45Rh3aGakYOF4IB4chr5nFgOslcat+BT8MI=,tag:9QfPkt/KfwaKSsXJae3GdQ==,type:str]
    google-client-secret: ENC[AES256_GCM,data:ELBA5tvSXsfhMS5VEapbBBGsna2EicOyibmO6F8jJRiW0OU=,iv:WIjcPW/PH1COGds/gmNDfsfw0uTw4vFHYvtyUk02WXw=,tag:iXM4Vrz/cF30SGCQk9dzmw==,type:str]
    kick-client-id: ENC[AES256_GCM,data:8ggrLR0Lpywjjv6nP3aQDGG5DOXZM0J+4kM=,iv:24dEcD1BFw1TcIuSq0WCPXuI8B05DinWAk+eDPHI30E=,tag:XaVKXMv19K1fBguOWzY/Kw==,type:str]
    kick-client-secret: ENC[AES256_GCM,data:ArlVgBo0nskCCFa8XmWCTkF7vwFJma9YyXtOdBBKfOH1Y7LPlxVFde4Pgrki+QdTDSOoJeHw2zFi0h6F7dqRDw==,iv:HHlKfwM07ARvzXOAnmLj7BSu64Cxj4iSsqDGbD2PiMg=,tag:JzaS5ad8lVYHvmBm4vY1tg==,type:str]
    restream-client-id: ENC[AES256_GCM,data:F9QcXHbv9kYthU7yir369veuqfvFDNvsMDKj3rnRjsWaelNJ,iv:eo3uyqYL+S2sjB8RJg4SM1PAnCr7eW5KQjpk61vtkZs=,tag:Ak2NXu/wq8cG/h9401I6/A==,type:str]
    restream-client-secret: ENC[AES256_GCM,data:acrZJJu7ML9hTdyHfy262CkvJm9Zu9LiFh0IV1Zs7puQXBjW,iv:n6Xocuz3l3OyAvrCwcwAfj0FeBMbAkdH4OBa9PK2Kyk=,tag:5vQ4xJGAZ9+aiGxRBWsQsg==,type:str]
sops:
    age:
        - recipient: age18r3vk6aecpcd69ey7fhgjylg6z37ksfeff6c497mxgv4nwmnyupq4gsfua
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJL0NtZm5lYzNNY0lLeVl6
            YmpEYnVrZG9ib2ZVSFZDK2RQQ0hoYnRYMVM0CkpOekdVUXV6UmtMbTFSSks1ZEJi
            RXlocndoUGxLVWJFcGxha2p5VCthMGcKLS0tIHczU2RYRHJOWEtUNUNUbnVsd1NF
            WU96QnpvV1VWbWJFTytRdnliakdYbkUK7VHkAA5dH1ACxmocrnBQzDaHnfvlOzLV
            on7npGkDSpGvIvSB9eF/PkVz1mdQPH4tpNLbHTmPQD28jt3n868BPw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1emw2e5x3d4cu0x4g0q4lrw8nj2fdv0qfzta6g62m5y24j02zu44sflkxln
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsMWZWTERkK09RU0RKOTg2
            NndJbitWa3pmS1ZacC9ZQ3ZPYk9hS09QOGhJCldDenZBU0NJamp1M2JQQjhka1ZT
            aVp6ejFJaGViQUhiT3lvNEVCRDdYOXcKLS0tIEczbit1YjdIdUpxNlJOWG5oYlYy
            OG4vMW5BU2QxK3RKT3dVWmlzOWNadHcK8Masz/LXxJ2Sqg1XO6MiSdFD92kSmmDP
            X+wIhJYEqq6uzXPUyb8sOZ7RBA8BEzdYAM04NGoDG8wR0RfUA1IFGw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1x9049ry5hz876qratphuc9gdxzuv4nnd06076842zdukl4unvazszfnjf6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCWUxIbC9IU09xYk1CNGhI
            bVEyU21NYnNjWjBvaCt4cDd4UlpaTUtaRWkwCmVIeVVFU0Z2OTJPTXBHRVRGVzM5
            QnZLRktnL0FvTlJGdzJGNk9SSkVYejAKLS0tIFBFVU01WGJYVDFqMXFzTUh0OHZ6
            cjE1eEc1NElIZFdSWVhUODhSMVRlOGcKcQioQEtNCfWHlbSW+a+CTUe3rbmw8QJ1
            BRrSK1OUDRhW159+zIIICwcz12zZpittL9+wCUTmtynBGp8NKEUPsw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1y5txpqz0vyyq03yyysmzuyvuyh8uzzpcw30cp5q3twxnwenfzpvs48ts0z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGR3RMb3d5L3FidzJJTlVE
            OHFzbHpYRVI2WmViUjFSeS9lNGlNTFZSK1I0Cno4OGJXeEtpaTZPOFBQRzhVclpS
            Q2ZkMVJLaXlzb1pDWTNEYlFRQmtnVVkKLS0tIE1yeFo1WlBLZlluZ2lLdys0RTFN
            N0xSMVkzRDJveWovQ2ZUZDlCdEwrMUUKgEGvkfbZxNpOSPyHWsluhv/SuiiLKLcL
            QZBsuA1PBoZcxNPZjI7mWRBOJKGCsUBrEIvEVpdgJnmGaHkxMzvBdQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-23T18:29:44Z"
    mac: ENC[AES256_GCM,data:LD21YPBvE5gYOHNSXJoyCTGHz8Joo3wp4f1904y2zd+B9WJXN6znHqxCjiRDh/azzrQ5p/wqjhhyx2RJVywuz+7gzWU1hzpgOKOrHDOHKhxlU9FGbhMjBrBB9I5tMXH+/LRhvyyhAwxaagdfxb6fO1glVHqrtjPooGi//vUAQUo=,iv:0bAnZYdtw52/gHkM8ARUmbe4BeXdwKU6HA54T+6ske8=,tag:EFHZnPzet/uKKuMb7KWErw==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.11.0
