apiVersion: v1
kind: Secret
metadata:
    name: oauth-platform
    namespace: browser-streamer
type: Opaque
stringData:
    twitch-client-id: ENC[AES256_GCM,data:EQe1pRI2XmLDcS8CkMUFQYncCPiQVN8llG7/RiiZ,iv:7VI+3LncXOsb6nP86lnP4vooZgbhgxO9dfsoxRSDD1U=,tag:OMVNh1GRkF3C+16Lbd3wmw==,type:str]
    twitch-client-secret: ENC[AES256_GCM,data:DZSqlvkXY1VmO10wrr6x2CNhbgk3V9DDhSXjoZvN,iv:jruRnk5+luszGp0AaPCGN+2dBjkT2y7tUQzDLtuulyc=,tag:qaRFBcUFmYh8Ml01Xb02jA==,type:str]
    google-client-id: ENC[AES256_GCM,data:69Xpw6MZWCxZEkrR3X3oYeQdt815zgrXM355iNMhOGy8vAe8XggvZ8K456Rwu+GQ5h36q9a2mkOHoyouYT6//a4C1pvNR2mC,iv:a8V7anXV45Rh3aGakYOF4IB4chr5nFgOslcat+BT8MI=,tag:9QfPkt/KfwaKSsXJae3GdQ==,type:str]
    google-client-secret: ENC[AES256_GCM,data:ELBA5tvSXsfhMS5VEapbBBGsna2EicOyibmO6F8jJRiW0OU=,iv:WIjcPW/PH1COGds/gmNDfsfw0uTw4vFHYvtyUk02WXw=,tag:iXM4Vrz/cF30SGCQk9dzmw==,type:str]
    kick-client-id: ENC[AES256_GCM,data:8ggrLR0Lpywjjv6nP3aQDGG5DOXZM0J+4kM=,iv:24dEcD1BFw1TcIuSq0WCPXuI8B05DinWAk+eDPHI30E=,tag:XaVKXMv19K1fBguOWzY/Kw==,type:str]
    kick-client-secret: ENC[AES256_GCM,data:ArlVgBo0nskCCFa8XmWCTkF7vwFJma9YyXtOdBBKfOH1Y7LPlxVFde4Pgrki+QdTDSOoJeHw2zFi0h6F7dqRDw==,iv:HHlKfwM07ARvzXOAnmLj7BSu64Cxj4iSsqDGbD2PiMg=,tag:JzaS5ad8lVYHvmBm4vY1tg==,type:str]
    restream-client-id: ENC[AES256_GCM,data:F9QcXHbv9kYthU7yir369veuqfvFDNvsMDKj3rnRjsWaelNJ,iv:eo3uyqYL+S2sjB8RJg4SM1PAnCr7eW5KQjpk61vtkZs=,tag:Ak2NXu/wq8cG/h9401I6/A==,type:str]
    restream-client-secret: ENC[AES256_GCM,data:acrZJJu7ML9hTdyHfy262CkvJm9Zu9LiFh0IV1Zs7puQXBjW,iv:n6Xocuz3l3OyAvrCwcwAfj0FeBMbAkdH4OBa9PK2Kyk=,tag:5vQ4xJGAZ9+aiGxRBWsQsg==,type:str]
sops:
    age:
        - recipient: age1ase59dknkacq26gemrs9dvwvu8xr8akhfya99lagv5py7c7h7plsmtucvv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIUlg1YzBMTExlSXpNZGds
            R0Z5TEZqTFJuRWNaUDB1bDZWaThrNEw3REZjCnJPTFltN09XTTJtalhPNkZGWktr
            dG0rWlEyOGFsVm1YckxDcHlGakE3UDQKLS0tIGhzenpIMEMzNFUwcWpUUllLUHlK
            cWxiMWZwR21CT2JVaThvQ0M5aWpyUWMKE8CEHdZha75DSTZdgshYw5sjTPBQGw0W
            QxSiu9rIfalve19KW03zZ/ORBZcIy27+Y3kglPvJLphZM8elrYniyQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age13zs054me9k5h4m8u3hwqw9nz4jg6lkpfmkzqn8mdujjqp76h6plsmlmtpy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIcFJ5a2dQVklLV3NIci9x
            d3g0YWp1OVFrTU5mMlhmcVJFWG53eUxnS3hrCjVZYVhJT2piajRBR0t5L01HaG5Y
            T3M1cXZxd1VoV2dBMTRtblNvOFVhMmcKLS0tIDNkbHRFY2dFYVhWRzJuaGZjQ0tv
            djY3WjVGWUN0d1VKL01uMWtiai9Qc1kKEphvutZmPYz7goIarX8jBo0Ac4yctYDF
            v08nayta1eRiBQF/OdYzQWSpvHT4st63McOht5c3eglIp0A5orF5/w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17ttan4es6923ru96408ctjhs2f97mrxq9uw938plgnw6wkstv9cqsaq5cw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFbWdmVlVJbkg1ZmxlK1Nj
            WDZKcnU5UzZGVUlRUW5JWTRNdnZZWEY0K1FJCnJnSWVyVW9JbGhDYTByOS9GSXhn
            bWdCZDdMUFlnT0hhWDlPb3Ura1VZSkkKLS0tIGJDb1kwd1drT3p4MlJJVFI1R2lF
            N2Njc3BQL0lTSUVBRWxRSFB0akFxNVEKV6I9AT/ibd+hJ15Gb0ezgHZvfN7uw0/s
            3lPMDjTy9YmV2gFicuvxyvfsi3uDaV+nZxBWEobhfXWzZWqXm5/a8w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1un8ajg06rd075pff8pglkq2q0g020peq7v23qzeqhuchl4y4kyfs0drxyf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2VGpBelFDeWZkVkRRVnZO
            ZzFDZ21aQ3JMUHlVdWxkckgwV2FxajVnUGdFCjIxTEdGd0lua0FaWFRYMHdTQTVp
            dWx5MHB2bWlVWDdybHRBOFBYYUEvUzgKLS0tIHdmeVhOTUZRYzY5ZmFoOFdCSEFK
            anE2ZnFlNjdwTXRNWXBHWDFhTk1FRjQKbSZo8UFTJuDWIbeXNGPmIzNA9dep+9Ur
            xoQ03vKlnw3dUlaeHCWb0nzO9dyME1+w6Z5bsOl/7XGH0EKUl0+TXA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18r3vk6aecpcd69ey7fhgjylg6z37ksfeff6c497mxgv4nwmnyupq4gsfua
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOcFhFKzhXUXMvbXBIVjQ1
            Qmc5RDE5ZHZFNUVOakZIdFc2ODdYemE5QWowCkVqMGJXZG5YcTZKeS83MG5FVFJY
            NGZwYTFGN1RQeGxESDJyL2VNWWpWZVkKLS0tIDhScHovTm5IOU5FUjljN0NGWGhU
            Qjg5MUROL3owNFlzeXNTNHo4VzR1Q1EKrmegmKNvWndqG0gpvm/XodO2JJoaP1vp
            Grq+7gOZV2ke4Xd+yo87ahmmSwp848H5T8dBjbf/xCgvY/MxXLRm7w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1emw2e5x3d4cu0x4g0q4lrw8nj2fdv0qfzta6g62m5y24j02zu44sflkxln
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBZVpvY3pzeU1lV2IzWTRX
            N1VYcnB4ejRRNUhWQUpCRW9YSHZaTHpKVDFFCjZ0SDlYNEtia29aUW96Y2pOcGVo
            WmErYkFLMkc3ZTdwZldHd3kzVkRYc0UKLS0tIDZRcnR5ZHRvNjc0aUhNQnRqQ3Ji
            MlJNVDFyU2FHeFNtOUVXWnY1REdBNmsKGU1kXHxD4CV1l2SFcXOKm/eCLrUnV/1X
            37jMGhBqOfb1Z9ehL4XJxx4hVB72N3ESzl3i86SMylO3mXPjD+0FEg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1x9049ry5hz876qratphuc9gdxzuv4nnd06076842zdukl4unvazszfnjf6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxcEQrUWRFNnU1OTYwakFj
            bEp5dGRGbmd0RFNhbWhyWmx0ODBnRU5HRDFFCnE5TXAvTWRBMk9SaEhjSlhYTksz
            ZExQYkJ5VUpzUlpKWEJURzZNRmlhbzAKLS0tIDQza055T2dBb3pTSmFSS2NsUFV4
            bUEybzBkSjZsbmQycmUveHpXRzd4VUUKyy107wa4y9boSqaWWNhhV2CIoI9NXQ22
            cGkub1t8/xwqAgOosa6bEd4qb+clu7ANEuBNqWTYywE5Vg+zTmzvnA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1y5txpqz0vyyq03yyysmzuyvuyh8uzzpcw30cp5q3twxnwenfzpvs48ts0z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0YXBmTHhpSFZ4MkZseVVK
            OWlEY3lXVnJybDUxaUN1R0psbndVcmdIa1QwCmRxWG5XT3h0YTlDcXNwN2dtNFhh
            ZTFsQTlEK2ZERlVtVFFzaENTd1UzUkEKLS0tIDdsL3hudW9sQnM0NHRjeW1sWDBK
            NElwcnY0VUFxOW9aU3hCcFlhUDl4TlEKyrr8BMabAYhgyCrEC/z2RdseKnAZwgws
            Be8fJQgwV2eaIB6SUD1mBcI/OBfCRvY8GsFXJd7w0UrPNDmPVztZnw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-23T18:29:44Z"
    mac: ENC[AES256_GCM,data:LD21YPBvE5gYOHNSXJoyCTGHz8Joo3wp4f1904y2zd+B9WJXN6znHqxCjiRDh/azzrQ5p/wqjhhyx2RJVywuz+7gzWU1hzpgOKOrHDOHKhxlU9FGbhMjBrBB9I5tMXH+/LRhvyyhAwxaagdfxb6fO1glVHqrtjPooGi//vUAQUo=,iv:0bAnZYdtw52/gHkM8ARUmbe4BeXdwKU6HA54T+6ske8=,tag:EFHZnPzet/uKKuMb7KWErw==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.11.0
