apiVersion: v1
kind: Secret
metadata:
    name: postgres-auth
    namespace: browser-streamer
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:ypR30YPgDkYboRzwujRjV8ZXMenz+ovwmW1K41oNTTpTMAfTLAf8CLUZS1AJIXHL,iv:aFl4qMR9tW/5lurLcfr56YVG9zUm4BoqBRo5tXsskVw=,tag:zx4MFKqRzJYCajwgCV0ikg==,type:str]
sops:
    age:
        - recipient: age1ase59dknkacq26gemrs9dvwvu8xr8akhfya99lagv5py7c7h7plsmtucvv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXU0swWEFOaGxlbkplSGt5
            TXRSRjUxa0lwK0VTSXRDMUl3YVFkc0phSTMwCkM5N3JEeEhuTEhVcWsvN1ZKNG1i
            K25QdjBVRFFoK0xSaGFjWW1CSnZCVVUKLS0tIEpSUEd4cXJSZnVXK2JDM3A4ZmJJ
            a0dlNXpQK1BIVXd4eEVVNHAwUHYwRE0KzFUHUv9D9ZXWcNJ558dH4FlM45G7Jp1V
            CbLmjtglk1phBw8GQ48n6f+YCpqkBw9KOhsVHWqjj5jRZtbGFkA9mA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age13zs054me9k5h4m8u3hwqw9nz4jg6lkpfmkzqn8mdujjqp76h6plsmlmtpy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuR2tNN0xxenBNM0R0QjVy
            MXR5blJoUjFpUWQ5T3lvU1A0NytibWlmc2swCjBYeFg3Y1NiM1h0VTdPL25ZNEFW
            WisxblpuWUg2T1V2dXBwVklUcEhEZnMKLS0tIDF3YTFGT2c5ZGRzSVJvYUV1SjBP
            c1ZTRlJncUhVUUNPaHltbVQxT3hJbDQKEf2FM/fduVft/b3oWYXqEpyX35+EVYXB
            nHib80chu8D44EGZ3AtfXD0Ajnf3BgS+6Pb1J9isC5cPN3Bc8JC65w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17ttan4es6923ru96408ctjhs2f97mrxq9uw938plgnw6wkstv9cqsaq5cw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArMDJQRnJJTk83RkV0d01L
            OUxvdTUrOG5EUmJwaEI5YU1KcFBQUjI1NURzCjdBSTU0U1VwREtwalZoQWQvY0NY
            clZvdFNtR3hVK09heU40dEhXVUJRbUUKLS0tIGV4SFZLUk5zYWlGdjlVak9CRUNC
            OC9Xa1RPR0VxWmF0RmFvZ29KazhyVXMKEWRxRyawsuSBGUGAwMPTsG1sij5rfVY8
            QEF36PFRa5WzbnDVVsb8rjnEY/CVJ4vbLqQVDj4N89CJoBe7weBH+w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1un8ajg06rd075pff8pglkq2q0g020peq7v23qzeqhuchl4y4kyfs0drxyf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxbWFaUU5IQ1ZueWRQQyt5
            MXhMT3ZkRnNzMksxcHJWazdKNWlocHF2M0hrCi9CUnhFTTNKVG5HdE1XU2UxZmE1
            ZDJaTWprQzRlWkZ1bjk5MUxrVFlUY3cKLS0tIDdQam5sYklNWm5qVG0wVDlTSXZJ
            eVhRTGxzSGVMdmRVRjN3NmQ2U0QrcnMKzLeAMnzDkOFg+s6YDIEgCw6gia811eOM
            SVimSOMWJR0TdxYwF9G6qWHzQhiGFpdWQena4zqDIrc/tTLY2hPGEQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18r3vk6aecpcd69ey7fhgjylg6z37ksfeff6c497mxgv4nwmnyupq4gsfua
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWN2xKWkRKQ2krOGt2TWlI
            SmVpeG8vZ3U0c2wzclFqamk5SkRUNnVSV0J3CkZ4T0ZES0JQODVXQkUrWkNaQXRM
            WFdVajNCZ25YYlV2UzkrNERUSnBLN0EKLS0tIFZUeFJzNExPQ0pPbDRmd3V1R0J4
            K05VVlJWZ2lqVXlJMHZZTTc1R3FUVkEKf52VmaCnkXja0WLSSNq62nK1RUpU7UoW
            erec/kQh3GFOhfokEw2gFJtsOjRrhb8bS4vT5+z5V27FXYkz9UIopw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1emw2e5x3d4cu0x4g0q4lrw8nj2fdv0qfzta6g62m5y24j02zu44sflkxln
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwdnV3MmdhUzIrdEFvRlI4
            ajlpMHZNVmxTUWlDSlMrU2RlRm4vVVB0K2p3Ci9IcmlLVWRaeGhNazU5Z3I3T0FZ
            SWZyenArZlp2MWxjMDJJODQzTEc3aGcKLS0tIFB5U1pGanFwTnN6UVR2Tmc2YUlO
            RmprVTJVVDR4dmQ0bStVTktibmtvMzQKaNjz1ClrNWqfqpGmsTdhU8WxHNnzGkVU
            5SZ21FkQIXpwOxVDQgu1SNJM7351Cu4CpO0sHw2IZtAaJ7zCpb5IZg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1x9049ry5hz876qratphuc9gdxzuv4nnd06076842zdukl4unvazszfnjf6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtUUxqYzlYajZ5Nnl6ckZW
            S2hGUXIyNG9LY2wvSWdXREJnNXZJZVh4akNFCnY3WGZPekR1MTRYREdJZFUwVjFp
            dEY4c3FuK3RGaStJQWRvb1J6M3BpWU0KLS0tIG10REVKbDk4MTZKVk10cVBoNU5s
            d0RvdWZMUEIzMUViK3l0enVvS1lBRFUK7jutsbOHccMhchqvQKCn9XvPcUZoXNF7
            OYNn3mvQf4d0/Org98TH+JEtXBjLzRfvbdiaiV5qlhjUmWAWPH39Ig==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1y5txpqz0vyyq03yyysmzuyvuyh8uzzpcw30cp5q3twxnwenfzpvs48ts0z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3dkFjcTAxN3djNlZKL0o0
            d0NkMlRNYVBmL3pycW1rNVhTck5XRU9mNzFZCnFsSVE3MktWeENrRThoZzNjQ3lQ
            UnJuNi9tUFNoM3VsZDVkQnVKNFBXNk0KLS0tIHgvVGRmZHlrUWhXUDg0alZRVkhn
            MXVVMXJKRXBzekE2V3BKM2lOY2ZUWUEKhXO2JqIZdflrwLiCOXUrU18rNd6rl1cJ
            kknQ0gKwoQgDTKS8Pz9tQsXPDA/AtxsCPmxdHvoEuuF62QlTHYIHtA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-02T03:20:22Z"
    mac: ENC[AES256_GCM,data:At5etS5TTMBQZ0Al/yny2QvQiVTXhheTYsTseHe/8Almro4698+KZ59nPmUY6qpAay6ofF3doUW82bqsAfXVAamfegks1KaH8UwVPvno2EFf1Qf3T+EZUcb4ap+ospmoTgs67Xdstoc7QFSWgC+LzLnbgQD0lGCxbDqhwHlMBQA=,iv:k8orFx7GpD1PR9beV2XNYZV4loxoOez7m69+LB/j3/c=,tag:kwtwB7mvBUZk3TL87WTJhA==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.11.0
