apiVersion: v1
kind: Secret
metadata:
    name: postgres-auth
    namespace: browser-streamer
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:ypR30YPgDkYboRzwujRjV8ZXMenz+ovwmW1K41oNTTpTMAfTLAf8CLUZS1AJIXHL,iv:aFl4qMR9tW/5lurLcfr56YVG9zUm4BoqBRo5tXsskVw=,tag:zx4MFKqRzJYCajwgCV0ikg==,type:str]
sops:
    age:
        - recipient: age18r3vk6aecpcd69ey7fhgjylg6z37ksfeff6c497mxgv4nwmnyupq4gsfua
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5cnBROWM5OCtZVjhNYzhh
            aGkrT2lBWUNHdmNNNEMzZnBmR0xTR2xybWpnCllwV0wyN0c2T0RyNGlQTmpTVk9E
            c1g3Vk4vSFlTdHBsYlB3QnArMktEWTgKLS0tIFByUGd0VktqZWFlVGlFOE1pUXBY
            aWxnTXhENUdTQStKMEN4Qjlsc1FZQlEKdEvYTkItz/KnlGs1s6t3F2dZoLPPUJaf
            cI4RWB+uSdkzn7b3DzfW7XJ2wKxXCuPu3sA6XQZbAad4hsqRl1hiow==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1emw2e5x3d4cu0x4g0q4lrw8nj2fdv0qfzta6g62m5y24j02zu44sflkxln
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQMXBFaGhYUXd4UHR2bU9r
            NUxqclVqNkNDYTRDMWpVMWoxS3FlSW1IWndjCklrOVJQNjI5VndtTi9rV0lwWTFH
            SkR4ejFnQmtVZXlzN1p4VzhTdkFQdDgKLS0tIEZtN3Q2TDNTUWtKWElYbDJ4U3BL
            czdSeHZRaUhjOWdnTjJCbEgwL201eVEKQ/CWlUpPVx3ZFz0ZIJQkf5bErxsRDrQ2
            v1hSebGC5uC+vZh9NapDPdFk5+6/nRFxkW3L7v0X9PZbFNoQQp2J8A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1x9049ry5hz876qratphuc9gdxzuv4nnd06076842zdukl4unvazszfnjf6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxZ0x4dzRHY3R6SlRxZU5G
            eHJnUlE2QVNIMlFaR3pHYzF1S1hWRmZTYUhjCmdLWkFvMEd1Q1k3T1FhSHRacFd1
            U1U4cUtEY1pwUXNRTkxmSFV5eTcreEkKLS0tIDdzRGZOVnlnL3FIaGZuOWtkUTNM
            djF6OC9KMDFXWm1MZ0prWlhBa3U2RFkKLhiXupu7K45qCp/wmoiSgPWClZLM0wtG
            RzBgxuKw9pxK04oe2NoXtl4XX80sL5dWU46QKkZLH2jWB3lqYQZPXw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1y5txpqz0vyyq03yyysmzuyvuyh8uzzpcw30cp5q3twxnwenfzpvs48ts0z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSb0tlYnd0aGJMSWhQMFBl
            M1dDVUVjci82OUZTMDhjcTBrNysrTWo2MHkwCllYRnNQSUxMSVlJb0h2ZDZLdDE0
            UVUrRmswTnZ1bkliSzJ3TXBmNEZFVW8KLS0tIGU1bXBCeVVkR3kvOVI1V203YzBq
            a2ppZTR6czBNcXEwQkFLVVJUSjBCazQKmwY9Iqa3Zxdl5ZfTiyWLTu5f6sLvkqVR
            5CK7PpqMDqkVXgefGgLL9XF1woio42+nHWu1N1VjagxFlqRxOqc7zA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-02T03:20:22Z"
    mac: ENC[AES256_GCM,data:At5etS5TTMBQZ0Al/yny2QvQiVTXhheTYsTseHe/8Almro4698+KZ59nPmUY6qpAay6ofF3doUW82bqsAfXVAamfegks1KaH8UwVPvno2EFf1Qf3T+EZUcb4ap+ospmoTgs67Xdstoc7QFSWgC+LzLnbgQD0lGCxbDqhwHlMBQA=,iv:k8orFx7GpD1PR9beV2XNYZV4loxoOez7m69+LB/j3/c=,tag:kwtwB7mvBUZk3TL87WTJhA==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.11.0
