apiVersion: v1
kind: Secret
metadata:
    name: postgres-auth
    namespace: browser-streamer
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:ypR30YPgDkYboRzwujRjV8ZXMenz+ovwmW1K41oNTTpTMAfTLAf8CLUZS1AJIXHL,iv:aFl4qMR9tW/5lurLcfr56YVG9zUm4BoqBRo5tXsskVw=,tag:zx4MFKqRzJYCajwgCV0ikg==,type:str]
sops:
    age:
        - recipient: age1ase59dknkacq26gemrs9dvwvu8xr8akhfya99lagv5py7c7h7plsmtucvv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpUzUrR3FYTjJxSzBHenMx
            cHVOMldDMDI2NVdNQjJLMkJYb3pLN2NwbldvCitZSXhMV0dVRFg3cGdET1V3Wmcv
            TEcxWDNtbUFlaUlIb2I0VFRjUyt5WWcKLS0tIHppekFrVGUrV3RJeGxad052WjJ6
            TmdjU0hUSEM2aUVEMUpVallKY292VWsK1+95MwjOPU6k0gwXyH6YLw3KY1r4IVbN
            H8CbowZ8cTGvLgZDjBnxQdhsFGvjqRmzuTC5HfCsFzsq0OpcgWZKPA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age13zs054me9k5h4m8u3hwqw9nz4jg6lkpfmkzqn8mdujjqp76h6plsmlmtpy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0blUrWlRzTFZlRXpUam8v
            eFZ1Uk9hTGFwV3MvaTRrcXNGME5RRVU2ZG1VCm54ZnJCQ0x1YW0wemNLcVRSQVR2
            ZVF2c05TZVcyYTd6dEhKS0ROekgyWGcKLS0tIDRKZDR1SVhtM1FZcDdWVS93eW01
            eW1xYjB6M0FuVWo3Q1BEaE5BOUg4b00K6U74cK5B5wAWJgzvyaZTgmoJII10SeBP
            FJCE+sB1sPb9HWV4EhTrF33L5Z/n5dX2sdewBP+3gFjWI8sgiU0yEw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17ttan4es6923ru96408ctjhs2f97mrxq9uw938plgnw6wkstv9cqsaq5cw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwd2FJaHk5TkN1Wm1MUjZa
            by85bnZ1Vys0dVhUSkMxRUlLeUprWnVxY0E4CnVvQ0xnNExzcU5obDZ2VFMvaDJv
            NUVnYzFSMnp1bjdTUU9FZ2dRbEJqYWcKLS0tIHovQzU3Vk5pN3ExQ0pQUFY2WUpr
            UWFnWCtIVGc2UG9xZHNaNXI4SGJieG8K4OD89/KXsWx3U6YWdT+FRKPEb8ou44Xn
            FX3tPyG7DshG7WQ371+6opOOaBZC6xxRffrlqpQYZVdgNIxxCKlokw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1un8ajg06rd075pff8pglkq2q0g020peq7v23qzeqhuchl4y4kyfs0drxyf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyMysrU0NLaERHSERHOUlU
            eFhUeUpzeFdnUzdjeGhPdmplTE5qZGhHd1NzCjhpcUw5T0tuVmZYUGlOZ2M2UHRR
            cjR5U1BOdmI1c1JyQ0JrYm81b0s4ancKLS0tIEFzOEFXWDlmbkN3NHVkSWs3K1RR
            VTN2VklNSFJJcHFHNlFQZVU5L3BZdUUKbqXcZsYaKtg6eqdRNVCU5+PhSAXpD3Mp
            DqE9GHThyNC3YfodfxWkcC9DVZCYPIjR3p/goLrsC3cIg51dnXkG4g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-02T03:20:22Z"
    mac: ENC[AES256_GCM,data:At5etS5TTMBQZ0Al/yny2QvQiVTXhheTYsTseHe/8Almro4698+KZ59nPmUY6qpAay6ofF3doUW82bqsAfXVAamfegks1KaH8UwVPvno2EFf1Qf3T+EZUcb4ap+ospmoTgs67Xdstoc7QFSWgC+LzLnbgQD0lGCxbDqhwHlMBQA=,iv:k8orFx7GpD1PR9beV2XNYZV4loxoOez7m69+LB/j3/c=,tag:kwtwB7mvBUZk3TL87WTJhA==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.11.0
