apiVersion: v1
kind: Secret
metadata:
    name: r2-credentials
    namespace: browser-streamer
type: Opaque
stringData:
    endpoint: ENC[AES256_GCM,data:a34fUjlRjwzzTeFNDy9JeZhh4pEmIJK5+2KjijNa+OGRro+a/+a3LVkwE41A+QbL07Fsj9KtxI+urZGyIpPBkO8=,iv:ZX4Xy/0rtTM+XWMXsSz+BEkl4FFMusgE92goxR0BUdY=,tag:G11EUH3gDQmrpsBmK1cleg==,type:str]
    access_key_id: ENC[AES256_GCM,data:JjQMV/BxVNYEfcq2HLDAnNkkRxtf51UmFtgg0P8kdEI=,iv:9ZXIhZjq/uNKlzXQQ26t3u3pXQY82FZSwHC2NVNPyy8=,tag:q1tLiZiDFkPhCkIe/80k5g==,type:str]
    secret_access_key: ENC[AES256_GCM,data:/ulBRhSkQnARtdPC/kAwodlk3FRTzj9fy/V+NNfNkVvoKAdv2VjAoWSYZNvZOXFWESKelPpj6IhwF9gi8Qos/w==,iv:I6olpH42ImK9fkRozzc8G3Q0OfcsmnY2jZgI9vAhRv4=,tag:9NezO0xoPfZ+LE6cw3GH2g==,type:str]
    bucket: ENC[AES256_GCM,data:jUdoFNZVQoWGFEzX38V7Vb3t5CwqsiLjF9hj,iv:G9RqDw/BdG8Vw8Mj+MG8d4RMfPkfSt1TGi1Zip5YFY8=,tag:I92qTSejXEi+1asmJsjw3A==,type:str]
sops:
    age:
        - recipient: age18r3vk6aecpcd69ey7fhgjylg6z37ksfeff6c497mxgv4nwmnyupq4gsfua
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxRmtjQVhGNUJKZVdSbmxP
            Vyt5SlF5MGhTeVlHL3FqTlRzVnhKTVZaRkVNCnFSZlJsRnZyY3NBS3BPdUdpakxa
            TWVZSkx4aXZkTDY2cy9ZbDVFQkdVRkkKLS0tIGQwc0FKcDV2UlpHSWVaSzJMM1ph
            MmxPcnhja3EreDQ3aGpMM1lNOWtjVUEKYUQeUnp4bCboZkv0t1gSpM9Xq80Gwixe
            28CcEo1Tww5806Csj7ck8bXE9pS1i+Bc2kpS8Ajk3hGLQ+lkYM5wuw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1emw2e5x3d4cu0x4g0q4lrw8nj2fdv0qfzta6g62m5y24j02zu44sflkxln
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwTEpxUHZtNk0zRlBoK0o0
            aUYyMWlicjJNcjFZank3cjVHOElqaUkzSUU4ClAzTzJFbXFZdVM2cVVnS0RycTNh
            OFZuR29jOWVSMkJsNmVFcE4xUDZIV1kKLS0tIHNHN1RCL3hBSlRjbUt1akg2OHlJ
            d01GT3VFNTY1L1JEUUV4V2xtOVJpOUkKvtwvPlx5sTe6KymZ0PMW+saH+viOa5PG
            /bXa7x8eY2phpd8+W1BX9qoKS7/o/xCbcte9HA1oIVSudOomtaSshQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1x9049ry5hz876qratphuc9gdxzuv4nnd06076842zdukl4unvazszfnjf6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHYnlRUG0rQkxrU1hVN09B
            dE1OWFg4WUV4L0N4NVV5T3RWaGJ6OUl6M1ZjCjFwajk4RWgvWEVvditlWlFIOE1u
            L2FZby9TWjRadFlpbEh4TFEyaTZsbFEKLS0tIDVLVXN3L25mS3hMMSs4TUw2R0Zl
            MmFiaU5FSmJkd0pWVzlZdlIvRTdINWsKA2k8BXPKehFYkXDwFG0+NiLuHk9YA9yV
            PPOj3W1r6a8g2pGDxtAgIL/2bx8rBFKCHQw1j0OSExd05UhIzDDg2A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1y5txpqz0vyyq03yyysmzuyvuyh8uzzpcw30cp5q3twxnwenfzpvs48ts0z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYemZJRzFGU290SSs5UTdl
            ZS9oSmlPU3l1THViOVFVV0s1UjNiUFJLT0dVCnNOQ3UwOXczOG5ORVRUdHdGOVBU
            eDM3TFUzRnR6ZmYrTlRHZXdTRXk4ZGMKLS0tIFVNeWpWM3lFenM4d1d6TndzQldW
            dnh5OVM4UVdEMjh2UHZBVTIxRzM5Zm8KbJ8McfivyTx9UmhayknIPgOaSAh8fU/C
            NcahUNo+tLo2lBR8yAdiTAy6GGauoU5rfwIeX5kBMwGOYLR3/s/iVg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-28T19:15:06Z"
    mac: ENC[AES256_GCM,data:b1pQHu2U43nL/qaUQMSa5zX8SebbDnagFvYNVTmPneehzBXtvjq/gW55zhWCOpoJGdrWh8//JFts7M68BfV42tG6h3oWNr70/o+B1AceLUoVvPMFWt/xlolfUOSc8KWAnIqZW0oDnr8zYdapozuZG6IRwd2dNjrssMavoEs066I=,iv:vwPD6bO+RfW5Df655Tg2bG7J0Y6JrDZu0+Q6CBnuQQ4=,tag:RffpqV1sLlpvpSU/kRhm0w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
