apiVersion: v1
kind: Secret
metadata:
    name: r2-credentials
    namespace: browser-streamer
type: Opaque
stringData:
    endpoint: ENC[AES256_GCM,data:a34fUjlRjwzzTeFNDy9JeZhh4pEmIJK5+2KjijNa+OGRro+a/+a3LVkwE41A+QbL07Fsj9KtxI+urZGyIpPBkO8=,iv:ZX4Xy/0rtTM+XWMXsSz+BEkl4FFMusgE92goxR0BUdY=,tag:G11EUH3gDQmrpsBmK1cleg==,type:str]
    access_key_id: ENC[AES256_GCM,data:JjQMV/BxVNYEfcq2HLDAnNkkRxtf51UmFtgg0P8kdEI=,iv:9ZXIhZjq/uNKlzXQQ26t3u3pXQY82FZSwHC2NVNPyy8=,tag:q1tLiZiDFkPhCkIe/80k5g==,type:str]
    secret_access_key: ENC[AES256_GCM,data:/ulBRhSkQnARtdPC/kAwodlk3FRTzj9fy/V+NNfNkVvoKAdv2VjAoWSYZNvZOXFWESKelPpj6IhwF9gi8Qos/w==,iv:I6olpH42ImK9fkRozzc8G3Q0OfcsmnY2jZgI9vAhRv4=,tag:9NezO0xoPfZ+LE6cw3GH2g==,type:str]
    bucket: ENC[AES256_GCM,data:jUdoFNZVQoWGFEzX38V7Vb3t5CwqsiLjF9hj,iv:G9RqDw/BdG8Vw8Mj+MG8d4RMfPkfSt1TGi1Zip5YFY8=,tag:I92qTSejXEi+1asmJsjw3A==,type:str]
sops:
    age:
        - recipient: age1ase59dknkacq26gemrs9dvwvu8xr8akhfya99lagv5py7c7h7plsmtucvv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLMTlYTGZTN2kwMmJ0MEJz
            RTJuOEpYTy9Lamcya0hTVzE4ancyM0Nnb0JZCmJsQ0ZlNERNREkvcUZHSTR0eFN3
            RFB2dEw5U25ZblNKUmhPckdmM1NOZ00KLS0tIGNjdU9yNGdRQks0NHZnQU5rOXZU
            dXVFQVJ0TGtSOFNjWUx4WWNQOGVmZ2cKF2OsF23RQMzi7dbBVBOoo8J6yi6K842o
            1eKmch9USTZ1gv0aH0CVUyrexEmF+13SqjwZ86ifB8iL6McKqEYZdg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age13zs054me9k5h4m8u3hwqw9nz4jg6lkpfmkzqn8mdujjqp76h6plsmlmtpy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3MUkzM1prYmZrRWhwQzVv
            OGV4YS82TG1jMGg5Z292NDVDQXZDTzlMc1c4CnJmVkJPUzVKSzNhdGNFK21NS1M0
            U1VOUDNtMzRuaTZpcjFaaXRaQUR1WGMKLS0tIE0rM0lKZ3RCYVA4bVZaWmMvMDBB
            MVhnVUlJM3ZnTGtmYTBETTBFOHpOaTQKhmnUxj0FNXG3+ZL0js6qs03QCtjVz8Fm
            lYcXZazuTlzQZylUvn5vT5DZSK8riLDNlzmVkKSQmrPPWbJH5TeeAQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17ttan4es6923ru96408ctjhs2f97mrxq9uw938plgnw6wkstv9cqsaq5cw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBubU5aNHpha3pvQ0k5UFp0
            OEZuNEp5MXJ5WU1KZThuTU5wcUUwbkh4SldvCm12dzYrOU1Jdm5ZdlBNZzQzVWQz
            aW50ZTlhcFJjWWNRSVlGdDQzeVpTOEkKLS0tIEVRa3I2VlpHeEpxcldqZFVQOTc2
            Q2NWMWRyazUxT2o2cU54V28yNWQxRm8KGnUpauonopCDr6G/rLkTZIAPuuPDZnrI
            /xGPxvh0Gb3pQhqPDmb5IR0I2Wa2fsVnMphBbPp8RTp6xUHBpIRmhQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1un8ajg06rd075pff8pglkq2q0g020peq7v23qzeqhuchl4y4kyfs0drxyf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNZFR3SXh6Uk5mN2hLMnkw
            QnFZNUNYQXIxV21nWW1YcDkxdzlxV0s4Y3pVCktUaGJEczRVbmlpUDQ4d1pleTRO
            Wm01NEtRbWJ6T0c0WGNrRjlNOHY2MFUKLS0tIGhXb1BCUkJFTkVya3JLSjZ3dk1o
            QTM5REgvL0lBdE81cGZYMjNFOFRaaGsKJMldGGeogmpSQBVIUDYsMQlc9gkMIvAb
            hK7GNOf5J6PJzSxGgAoUXrBWGyO2Is0sQ9xEjEFDCjXfK6MV+5F8ew==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18r3vk6aecpcd69ey7fhgjylg6z37ksfeff6c497mxgv4nwmnyupq4gsfua
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSOWZMZTJHd0N6S2w3YS9k
            NFhUT3RsdmhLRE9pZ210RGlLK0tuMTVWYWk4CmdoaGROOXZaNEk0OGZ6NmhFNEl3
            VGM2Z1ZscE5WTGpWUytPaklGYSs0bXMKLS0tIGNDMnVHVHg0L0JDWWdieFYvQ0JD
            L1ZqcE9LdE1ISkZrTGQzOXBlMzFjcFEK0CXfPeFjc47LxiqUQkl64+hnbPXBn0Ne
            WH2O5HUqeO2Vg6NXtJqBCteQ+aLQGBtGqENTeNnf9MSj4B40KPwX7A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1emw2e5x3d4cu0x4g0q4lrw8nj2fdv0qfzta6g62m5y24j02zu44sflkxln
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUdjVHWVdwVnVWMDJTUmla
            WGJjMTdBMFBHQm1QUHhiaFFhLytJVHpnMTBBCmNRamhkcFV1QUpLR1Fzb2tDZzlj
            Sk8zUlZEQ0hlamNTbzY0REtueDhUKzgKLS0tIFlnSWRYMUJEWWc2bzl0WHFINEZ4
            UnM4NTk3akJISlM5VEpBaU5IM2JOWGsKzSFbKz+K/eAtVueRiO2iRSSgL74XmjMG
            JpdhPbM0t+jvGcLnFd9VRQIQZ7oT0xWpy/gP5b0sHPSiIYXVuYrXqw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1x9049ry5hz876qratphuc9gdxzuv4nnd06076842zdukl4unvazszfnjf6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2d1JxOFJpS01sWjIrTk4z
            alhNQVNGOERzNmt5OGN1VGgxQXpOakU5MDM4ClB0VzQyVEFKQWZrM21RYW1qUmFZ
            SWxrL1crWGd0aWNDYnlnZFZ5a1Vhb2MKLS0tIFNlUXZwU1Y4WjVScUYyZlZPdWVm
            T2pkSWNiMTc3QXd2M3c3YzdZV3hhS0EKDiRFyqjY8jLgC3fwVeF2O8hNSqW2uqkh
            BRu2Cxm3AvrsIiEYXhWoNP+d3CLlUTzFi16MG8c49Sl73hECH3+9lg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-28T19:15:06Z"
    mac: ENC[AES256_GCM,data:b1pQHu2U43nL/qaUQMSa5zX8SebbDnagFvYNVTmPneehzBXtvjq/gW55zhWCOpoJGdrWh8//JFts7M68BfV42tG6h3oWNr70/o+B1AceLUoVvPMFWt/xlolfUOSc8KWAnIqZW0oDnr8zYdapozuZG6IRwd2dNjrssMavoEs066I=,iv:vwPD6bO+RfW5Df655Tg2bG7J0Y6JrDZu0+Q6CBnuQQ4=,tag:RffpqV1sLlpvpSU/kRhm0w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
