apiVersion: v1
kind: Secret
metadata:
    name: r2-credentials
    namespace: browser-streamer
type: Opaque
stringData:
    endpoint: ENC[AES256_GCM,data:a34fUjlRjwzzTeFNDy9JeZhh4pEmIJK5+2KjijNa+OGRro+a/+a3LVkwE41A+QbL07Fsj9KtxI+urZGyIpPBkO8=,iv:ZX4Xy/0rtTM+XWMXsSz+BEkl4FFMusgE92goxR0BUdY=,tag:G11EUH3gDQmrpsBmK1cleg==,type:str]
    access_key_id: ENC[AES256_GCM,data:JjQMV/BxVNYEfcq2HLDAnNkkRxtf51UmFtgg0P8kdEI=,iv:9ZXIhZjq/uNKlzXQQ26t3u3pXQY82FZSwHC2NVNPyy8=,tag:q1tLiZiDFkPhCkIe/80k5g==,type:str]
    secret_access_key: ENC[AES256_GCM,data:/ulBRhSkQnARtdPC/kAwodlk3FRTzj9fy/V+NNfNkVvoKAdv2VjAoWSYZNvZOXFWESKelPpj6IhwF9gi8Qos/w==,iv:I6olpH42ImK9fkRozzc8G3Q0OfcsmnY2jZgI9vAhRv4=,tag:9NezO0xoPfZ+LE6cw3GH2g==,type:str]
    bucket: ENC[AES256_GCM,data:jUdoFNZVQoWGFEzX38V7Vb3t5CwqsiLjF9hj,iv:G9RqDw/BdG8Vw8Mj+MG8d4RMfPkfSt1TGi1Zip5YFY8=,tag:I92qTSejXEi+1asmJsjw3A==,type:str]
sops:
    age:
        - recipient: age1ase59dknkacq26gemrs9dvwvu8xr8akhfya99lagv5py7c7h7plsmtucvv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMcTB2aUF6M1VkV2Q4Tjcx
            cUdENzBLOVlaSnhRMU1lMjgyYmhCd0JVd1MwCkxFY1JqZ0piUURoUEZaRStqU2Rp
            MzFPVTdrYUNVcjg3QW1qZWNmZ0lRUUEKLS0tIHdoTFI2ajJMbVI1WXRPb3RwNjdM
            VXYydXBGeTBldTYxVHZFOVRoR1VsRXcKONwy3DDn1ON+q6QIC7M9ie88nCRGNkE4
            aq4ZWb1hE96RDmjUCn1y4AitKNladRv9LPFkhQn6Aw0K9rYHI7vQzg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age13zs054me9k5h4m8u3hwqw9nz4jg6lkpfmkzqn8mdujjqp76h6plsmlmtpy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3cEZRSGRuZWhvMUN0eWJO
            ajdTRVZjZmY3R2RUTXlqK28vajlZNE04SHh3CmVRYlZBNDZab0pRR0dFcktSNGtk
            c1EydVAxK0N0bGRPLzhaU3JSTTIrMG8KLS0tIGdPTmRRdGxVUVcvZ214eXNKaG11
            QXVUVnlNazdiV2pGcE1vanBydFJDOEEKLZv0QRUFGUubaR9m9DFsbekdaX1z7bj8
            i+ADiKVvBgidqXoYeOsHnxYOVxGLsy/XiRFRJ65mH44gfhw79mFlpg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17ttan4es6923ru96408ctjhs2f97mrxq9uw938plgnw6wkstv9cqsaq5cw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2OW1kNlN1SUxqUHF3WnVq
            d2ZrekErRnl2bEd0S08yZ1c2eXpvb2tsVXdNCi9mSCtKaE0yK1RydmEzUkxNaTZk
            TnpMbWNvMzhMb3l5MEY5c2tFbndjaTQKLS0tIHdRcmRCTmpYWHpiQ3h5QTJGNC83
            aXVkNVdaVUQzZEtvallTS3g3UUQrbWcKJzZT/8r73fZpmwG3bvmOJZrU1lIYxKyZ
            eYqDCcN08UbgP3ApD2aiM4ceLeDrx6UndS6Q2JiVkxSQ88Ft36R9Lw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1un8ajg06rd075pff8pglkq2q0g020peq7v23qzeqhuchl4y4kyfs0drxyf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4MGtENXF2YkR6Y09OSGJ3
            SWpMMmY5MTlFRm5EcFlMVlFsMzFrdWpsUXlnCjYwSTFlRHdsWWx0OEdrVERJc3Q3
            OWQvR0VFQ29ibDRGb3ZlSjdjSkYrc1UKLS0tIE5HVzlpUXEwZWxtdDk4SVhHNlJR
            dnlDbTNJTnJua0dBK0ZJUVFzbHVDdEEKyx01y6nC7QLjv3uicqRbPQgD0ukJZ99q
            EYOFVV5A5QpwcQUu8CSsNUnouWC+tUjExx+NansYXJ3xEkHjdHh38A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18r3vk6aecpcd69ey7fhgjylg6z37ksfeff6c497mxgv4nwmnyupq4gsfua
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBua3pmazk2LzhJME5RYlVG
            RmtjU0dvSDRFYjZFQkpyZ3NuRy8zS2VTeW1rCkt2NGUzSTZPVnAvQVV2NWVqcndv
            cXdIMEJNMUFlVzltQjNaVVl4U1ZXd1UKLS0tIGEySWZHOW1yOE9zem53MGZScThS
            dzYxVHFjd3RQbFl0YlRVV2pJanBlN1UKsAGf8i7CXnjaTIKjGOhQAbz2DKKI1VA/
            N6fLfjmKTQRWSa96N1SYw+VaLb5wcVpBSom9oq+b15xRLfbCWF5X+w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1emw2e5x3d4cu0x4g0q4lrw8nj2fdv0qfzta6g62m5y24j02zu44sflkxln
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzUCsxVHBJOE5waEVXL0xn
            WmhGTW0zTi83dDVtMVozV283bFJ2bndqR2xJCmZTeE1yTDYwS2dCclVZY0NtNi9M
            TWFGeDREc3dNdFlSN0JJMWkzUFJDdVUKLS0tIDB1NmZuejkzcWtrcFg4NFY0TWpo
            M0lGNW04SEFsRW5wWlgxSW1IYjdNQU0KH2vMl2yaNsVs6KrXiCR0v7oOPLDUz+dA
            TgEOU14JAJQ0Mm0WL77Rw+C/BJuldlXR8pKvKwx7QcfIU6z5uJHF3w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1x9049ry5hz876qratphuc9gdxzuv4nnd06076842zdukl4unvazszfnjf6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxR05ZaFRvV3YwWnlNM3Mz
            VTZNbndGQldZcTJKYXZETVBhTklLdUpjT2pRCnltSmlRcGU0N1JNWElUa0ZUZGRL
            ZUNaV1hBN0JTTW53SXhEVjJrc1FiTDgKLS0tIElBbTVqR3FqZTJhS0VucWRIa2Z3
            K3MrRWkxOS9SdXRKVWdubHpob3B6dWsKIWAlSqYrbKE1xoNtYPZsSqUIbZWcLwxO
            e4LOuE/IxybiWsniY9T8k0dPOwe0woU0iCEKowkF1v3TjZb+mo9vjQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1y5txpqz0vyyq03yyysmzuyvuyh8uzzpcw30cp5q3twxnwenfzpvs48ts0z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAva3hxRk1iQXdPUU1LYWN4
            WW56TU02cFM4RTRRVmxVZUdldWVBNU1wL0dZCkQxMG0zSGZ3TnFqck90Z2xBVExt
            c2J4OHBJS25JOUlHa0xKMVRsYkNLNnMKLS0tIEp1SDN0d3VJWk81cENGY3BxNEN4
            TStDeGdtdWNmdVlCMnI5RDU2MFd2NHcKH2Bc9tnxVhdI44m+l4v2JqU2xbII19T7
            L86LC44U/Mdp6CZmgB4EMxO/1MZxAjb/ErlMzI+f6cPPTQ6lIjyYdA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-28T19:15:06Z"
    mac: ENC[AES256_GCM,data:b1pQHu2U43nL/qaUQMSa5zX8SebbDnagFvYNVTmPneehzBXtvjq/gW55zhWCOpoJGdrWh8//JFts7M68BfV42tG6h3oWNr70/o+B1AceLUoVvPMFWt/xlolfUOSc8KWAnIqZW0oDnr8zYdapozuZG6IRwd2dNjrssMavoEs066I=,iv:vwPD6bO+RfW5Df655Tg2bG7J0Y6JrDZu0+Q6CBnuQQ4=,tag:RffpqV1sLlpvpSU/kRhm0w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
