apiVersion: v1
kind: Secret
metadata:
    name: telemetry-config
    namespace: browser-streamer
type: Opaque
stringData:
    webhook-url: ENC[AES256_GCM,data:5qGsSl2XfzNVjZyJc5VAZ3LWGMlijTCMyGFRpv93pov129Erg/WZeGyQ6hm5V58aQcNhvZ6o+Pio/XleykVML+9/s/8cyvR0SKYnejfkXyvr,iv:2Q4j+H9x9TFXmPZEmwNyuP5qjSzY4sf1T0C1xd4qais=,tag:f0G0+ePBQk32WKoSLoZ5kQ==,type:str]
sops:
    age:
        - recipient: age1ase59dknkacq26gemrs9dvwvu8xr8akhfya99lagv5py7c7h7plsmtucvv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2TW5Ra2p1WldIcHZJdXpE
            QUs2MWc5clRhaThlWGdRM1hIMlhUanJHWHd3CjgrcldrT0ZHc2NROEppcnNIWGQr
            andtMW9oeXZWV1BlYWlGT09mSjBuUFEKLS0tIG5YcXNKL3pGT3pRYllGcWFSTENw
            R3VWaWU1eW1ZOFVWQ2tHaUxQTlYxOWMK41S65ixkqAA8dDEyt+7KH/0GOhG20IdO
            2x4jdyOUAHVjhP/nUAzMtFQb88NO9qgh2d/JmjgAeHkI2ZNQnqpl7Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age13zs054me9k5h4m8u3hwqw9nz4jg6lkpfmkzqn8mdujjqp76h6plsmlmtpy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXVzJueHdERmdvdGlqYTFx
            NW0rM1hZTUlEWjJxQnMzOExwM24xRFpaeldZCjRMenIvdmhsVGIzNkhCTjBBK0NW
            UUwzR3dDajBuZmJQeDkwRmc0ZTNNK2sKLS0tIFpIclI3K1p3VE5sNnVVZExEQWZp
            Qk9XUVM0OEJ0amhITzZadkNyS3RwR2sKDbM9WWDvKvNEaKB4+VIXaIXV5iSDKO6p
            BX6vXQqfGCoKSLd3vmxEi2APIzUR/aAIJ8fQoPrSLRrtWUui3NkREA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17ttan4es6923ru96408ctjhs2f97mrxq9uw938plgnw6wkstv9cqsaq5cw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArbjNNanIrRFU5S3hrMG9E
            dG1zakFMZ0w0ZEcvWkttRnhwVHhWam1ERDNFCkZzS2MyNU5pdUhQazl4OVQ0OHFw
            VFBGdEI0aEs4U0dWNDMyLyttcVp4TG8KLS0tIGpkaUtFMHE0ZGFKM0wxWS9vVVVE
            eXk0N2JuSE80ZERZTGVNbkJaWGI2bmcKMGIjZsUvqO+5QnuPJ9FlFnzYw09JtStR
            xJ2mLtPxf0d2NXoOs9AXws3KjQWjkbaHFYpM8qHuOPvC2xSdXwDLbw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1un8ajg06rd075pff8pglkq2q0g020peq7v23qzeqhuchl4y4kyfs0drxyf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlNUo1Y2lWMGFGSGVtaXd3
            Z2dkUDdacUpiektrRnRScTMxZkNTTVdiSFUwClFrT3pva0RBZ1JYOERWNGVLa2Nj
            WHdkc1dwdTM5WEx5RmlRYndWNm5YZEkKLS0tIDl1TTFFKytRMkJzZGRncmpRVFdl
            M1Q0VHI2TVMvRmErb1BYL1ZxeDRtbHMKqalbRgsX1VwklPwFRzM4EfZQis5qJsjf
            csUsOyd008mqnTbFUDc+5d52Au+gH+gOhkH5r7TVsK11rtcwRLUXlQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18r3vk6aecpcd69ey7fhgjylg6z37ksfeff6c497mxgv4nwmnyupq4gsfua
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjZ2k4RjV3cVlkT3VoVm5z
            TnU1aGI4eGVQUkpqaDBaZWZ1ZDVPcWxyekVjClRPazRXcnV0TnMySW5KdE12b2pM
            ZGNsMkYyQjVWTm5XZlBBYlN2Q1YxVEUKLS0tIG5MUC9Db0o4UkVEcGN0enBwVDIx
            TTJnVWVjRmNYZzMzbUlZZG5pTTJCWEEK3VYvscRfzztqeIvpqG6DZWgwy+06jZpY
            TvMF158HDyIV4Rl8ImrY+mPl36500LfVAQNzcf/eB/KO8OV6ltdiGA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1emw2e5x3d4cu0x4g0q4lrw8nj2fdv0qfzta6g62m5y24j02zu44sflkxln
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5OUZ2cHArYXo1ZUJOWXhu
            QjZIRTRLTE1nRnZIVGlwWCs1dDg3VVFLTkNRCldCcjB4YWYrbTIwMVdpSGtkSFlx
            dk5hWnphMWFFZUhYYWpSVUpkOWR4dk0KLS0tIGIrc1JzZjVjTnZmUXYwcFcxNmVw
            dXlnYXJGNzNraDBUajRtYy9kZktjSkEKLT9KLrv2Blg6KVM1ZzESTGxVdj8f1N4s
            hEvXqOM5fhW9U1cNhrkcFFkolbSAzD4vZrnXZ9J4JiDwoutL/lgQXQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1x9049ry5hz876qratphuc9gdxzuv4nnd06076842zdukl4unvazszfnjf6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByUGlmNzcrYzh6c2xyR0Jv
            bzZEQWdLeVhNNXpHUmx1cHJuNFBNZlo2eUNnCktYZWZEcEJ5ZUp6TlNYYmhxVFhJ
            VkdYdDIvLzhhQnpkbXUrQXlYMXZHejAKLS0tIHd3NUhZcVdRYVkzSDBSRjNQeEdr
            MGxFR2dGQ0dsSDNCMUdXekJFNFk2aXMKeJnMEN4KuNJPOboMqOE6ROF2+WQK1Y90
            NpiggxYplxPfeC45RLMkrtobfNqGPXiGoPuXYd5Aq7aj3LCDdehqTQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1y5txpqz0vyyq03yyysmzuyvuyh8uzzpcw30cp5q3twxnwenfzpvs48ts0z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSbkplUU1HbFlRU25vWUpk
            M2FSK1FGejBjaXhuRnpNOUtlZUN3OE1hOVVrCkxXVzdPbDlpcnV3MXNudVhNaUZO
            dnVmUnk3REQxODBvenRtQW1vckNrMVUKLS0tIGNTTDBpOVVDR0V5S3V6aHRKem9N
            dDFiODVPYWo3Z3drZnpCZnRDcHYzMlEKqRzl0FLgp0fRWlrkqmSbmBCRoSzgj05R
            n5fpHZL+sGmwsL8421lSnl2fA+3VMLdT19PPS9db8J+Vls4SsQGwHg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-28T22:18:59Z"
    mac: ENC[AES256_GCM,data:1D+r2LeSFifDI+9R3vB2ch1Psd2gQuKu2Lm8sw0BqFCFoYestvdxP11HEboO7hMgJR16sPqBO2Yx0p5p93v1gtYJGmCjyiigxS1xpJYI0ObPZKcGAByYt8688X6hrG+xw5r/XflV0sFM4GftKgyzcj21EDUjUH7On8AfsqKCvHo=,iv:3YvFGbFVTfYIt9o0B+yQNH/13ku5TYTiJ53BZSJdj2g=,tag:GVtw3jWXedDHca8eBQm8ZA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
