apiVersion: v1
kind: Secret
metadata:
    name: telemetry-config
    namespace: browser-streamer
type: Opaque
stringData:
    webhook-url: ENC[AES256_GCM,data:5qGsSl2XfzNVjZyJc5VAZ3LWGMlijTCMyGFRpv93pov129Erg/WZeGyQ6hm5V58aQcNhvZ6o+Pio/XleykVML+9/s/8cyvR0SKYnejfkXyvr,iv:2Q4j+H9x9TFXmPZEmwNyuP5qjSzY4sf1T0C1xd4qais=,tag:f0G0+ePBQk32WKoSLoZ5kQ==,type:str]
sops:
    age:
        - recipient: age1ase59dknkacq26gemrs9dvwvu8xr8akhfya99lagv5py7c7h7plsmtucvv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3T2NESkpQaXRoWnFPam9r
            VjY3Q0tqSkpRNFhWOXVaam8vZ1NjRnRIZFNFCnUyTUZHYUFxcjNLL3VRYXJEeVZL
            ZUd0N2VSeVJSOVI4M0lKNFppblpTOHcKLS0tIEJuSXhGYVhDZzBYVnoxeEpOVDVP
            eVA3SnlxRXBtWDFhaktCNHBhZ0VJa2sKbriTWPPpiPDBKFtD68px8wWil0KjiT+S
            hopX1widgYPSzjBDG/nCDCN2SWGO9feuVUq73gucwKLb6JOtnh604A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age13zs054me9k5h4m8u3hwqw9nz4jg6lkpfmkzqn8mdujjqp76h6plsmlmtpy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxSUwwZHA4cG9lYTNocXdR
            NXVnZkczT2w2SW4xTnM2bHNFS1hhb3VFcEFRCnRyVlhxSW1NNnAwVi82Qk9wK1Vs
            VEdWMUxzc0dZT1hZUGhNSjhuV0h4NjAKLS0tIDhHSC9FazNyZVo1OEdna0lwZzZa
            YWZJenhDdzFDczIvV3RGa3FIU0xIVzAKcZOlKMIArTsE1rnLFErj1LhCDkk9jZ5F
            gcLx8W3GHTSs56XhVQlNW4twR1qeUM/Cki3wkz7VbDVqhaEo91rinA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17ttan4es6923ru96408ctjhs2f97mrxq9uw938plgnw6wkstv9cqsaq5cw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByakpIcmlSREllOUlyWU55
            ZEpkME1pUFQrNnZwSCtidEpySCtlR3dWS25nCitlbkdvNHFURWx2UUxsd255dUVQ
            STdHNW9DZlMrbVJZK2ZhZGNGaHhiMFUKLS0tIE1vbmtvUWQ0SHJ1L0oxakFwc05u
            TmFibWJEdmw5eit1N01zL21EOHozKzAKHqfuUZNWixkBEonydBZbq/IEwhE4WOye
            ECe5iclOssJjUl2IWzNuDRsBQRZDVLocRur05CZjoOY6hJlhSzb/bg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1un8ajg06rd075pff8pglkq2q0g020peq7v23qzeqhuchl4y4kyfs0drxyf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQMTFxcldldkwzQzFwZXFG
            T3BxY0pTOHU2NzNNZEZSQUhXVFRZQVZ1cFZzCk9WdVcxZFRVNEQrVzBFNSswRFpl
            NWYwYW1ROTVsRGRyZk9BbGFlbGc1NDAKLS0tIGFVNTJTbXNyVkhGUWxwdk1rWGZm
            MzlLMDg1UkYzeG1qZldEc2xZcUFIY2sKpuP+vGzZFnCXJv3ZCVZxM+yb1e14ZArM
            QGFm5BGMkLGklMq5mnlVp+yAdumAodeq2aq3wLSV/00ywokN7KqnPw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-28T22:18:59Z"
    mac: ENC[AES256_GCM,data:1D+r2LeSFifDI+9R3vB2ch1Psd2gQuKu2Lm8sw0BqFCFoYestvdxP11HEboO7hMgJR16sPqBO2Yx0p5p93v1gtYJGmCjyiigxS1xpJYI0ObPZKcGAByYt8688X6hrG+xw5r/XflV0sFM4GftKgyzcj21EDUjUH7On8AfsqKCvHo=,iv:3YvFGbFVTfYIt9o0B+yQNH/13ku5TYTiJ53BZSJdj2g=,tag:GVtw3jWXedDHca8eBQm8ZA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
