apiVersion: v1
kind: Secret
metadata:
    name: telemetry-config
    namespace: browser-streamer
type: Opaque
stringData:
    webhook-url: ENC[AES256_GCM,data:5qGsSl2XfzNVjZyJc5VAZ3LWGMlijTCMyGFRpv93pov129Erg/WZeGyQ6hm5V58aQcNhvZ6o+Pio/XleykVML+9/s/8cyvR0SKYnejfkXyvr,iv:2Q4j+H9x9TFXmPZEmwNyuP5qjSzY4sf1T0C1xd4qais=,tag:f0G0+ePBQk32WKoSLoZ5kQ==,type:str]
sops:
    age:
        - recipient: age1ase59dknkacq26gemrs9dvwvu8xr8akhfya99lagv5py7c7h7plsmtucvv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaMVNNNW84SjRIWlNuZUo4
            SGl4aTZqWGJ4VVlNSGlyU2VhaVRNM1JFcmdFCnU4M0pQWSsrK0ltQnF1b3hBL2hT
            dHJUZjFjVkhPY0FWc3JaREdsS2lLLzQKLS0tIDdGWmFVMERaZTVVdGdreUZmOW5S
            Tm9rckI4M3VVOUkzNXg5Qk42ZFhwTkkK4KbGKOKwZHYRf1Mlj+kcguESK0/vkhWf
            bqINxfZ+sLwHQjZbMbd3ANTGE3n/gxlx8UE5cQHRhb76cT/DNTMz1Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age13zs054me9k5h4m8u3hwqw9nz4jg6lkpfmkzqn8mdujjqp76h6plsmlmtpy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxWWI5aldRaDlTaFJwTTc1
            WEpxTTM0S25YV1EvS2xwc2VOZWlpY1JjZDBnCkpmdHhmMHRQbFdDL2lvcDlWeGlE
            cy9GSUcvSjlqdmI5VWtjeW5OS0RHZWsKLS0tIFcwMnZldHZWQlFiOFpUN3JqSUky
            RzVSMU9BTUdQSTFNNHRHbW1CTTdHek0KbSu6II7lsdKWIiXhac0KkJqKOJVF/2g6
            fak7OHziIywrjn9kgKsXrU9lFlXKAq9olMhTOj1Xl7iSaW0fF3P8yg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17ttan4es6923ru96408ctjhs2f97mrxq9uw938plgnw6wkstv9cqsaq5cw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2OXNJTFRmcUY1clB6Ym42
            ODZQY1ZOcWErNWNkMENsUkQ4VG9zNzFuMlJVCmdpUlpOSEduNGJOQ0tJam5aSXJF
            R1lMNkUyWnlyN2RTZzdhb2p3SkYyek0KLS0tIGs2ZlZOeEIwcVgxcW1CVlkzMVNF
            L3lUQXJuVkthRk1xT2twSzZlbFlYWHMKNa3jyl88NZXNYRBMgnnuH1180m3N/iKh
            T0D0T4p8wFwKAN13ga5anDbs2AfQHyO3neYDoIxjrVZJtI8bT/wXaA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1un8ajg06rd075pff8pglkq2q0g020peq7v23qzeqhuchl4y4kyfs0drxyf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxTHc4MG1JYXoyczY5OG9o
            b2szWk9ZaXQ2SDJUckdjekx3UEVIT1ZMaEdNCmpWQTJQTGZjc3J6QnNtK09makps
            ZkNXVFFMdXduL1k2ZzBraUl4MEp0TmcKLS0tIGR2bHVDRk9OYXRhNWxSNWZxVGwr
            OUkzQ3VRTVlVMGhySWJSODNoSGh0Y1EKiCQaGJLA9FIeFX9Iqo+x+vXRQxUlMp4m
            OVQkIPnexs1UtN4R4CkyoGU3mQgVhXirEvzrzldgB90yfA4egyBhzw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18r3vk6aecpcd69ey7fhgjylg6z37ksfeff6c497mxgv4nwmnyupq4gsfua
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtUDNFMHZYa0g3RHlVUER1
            Vk1NOTlLTFRBMlNvT3RJeFo5QjM0YjZucG5RCitRcGE2S1BIbG1BYmZNRnQwK2FP
            aWRucjQvTmpoWEo0UHIrNThaOGQ1aTgKLS0tIEY2SVYrb3M4bi90L3UzbG9hVXBU
            K00xd0J2QmM5ZFlJcFQwTU5NQ2x3TG8KSiRwigKXuUO7k29l9n4A2rfsa7vAI7xq
            jP6eEGo2ZXf5MUIt/yQGtd5GQsYxFTEMkcNaQd0BSPoP2hpN300Ckg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1emw2e5x3d4cu0x4g0q4lrw8nj2fdv0qfzta6g62m5y24j02zu44sflkxln
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwMEN4c1lHYVhCV2c2MVFp
            NHJvNCtDbUpOYVQvdUtsM1IzU0toV2VrejJJCmZsVnNlc3IrUVBpdVJDMzE0K2hp
            L2ZxZDJ3R3hLWkhzSkV4TVlabzZzSHcKLS0tIHR4WmtldnlWa1J3Y0RFWU1aYzVV
            eTVlS0VLejVkMExzZ3RwZnREWmhrU3MKhX9dH9HvUGVRRVFU0tvpxaog9/WcREOH
            NUJoAPu20WMjPd1sF1Q6XEJvQ0MI92rf+NNRLLs7nylAX7p57JlDng==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1x9049ry5hz876qratphuc9gdxzuv4nnd06076842zdukl4unvazszfnjf6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmd0xDcGVrU0dSZUQ5ek5r
            NS9yUnZqTzFmN2k2L3NjVVo2eGV5aGpTdFJVCmlqYUdrOEFOcVJKeHlMS3BxSWRM
            eTlOaEpHNFd5emJnK0duOW5OdUhabVUKLS0tIGM5cVJsSHZ5Z3htcEhQbFQxYVhE
            YTB3KzNPK0lNZUU3aFh2ZTN3VEcxVWMK49xE56twmmop4tlxisEIcQRyanlWHAcj
            sfFkEhqGEQTOAE6Y9IcsTtp8/ru+UOiFYTZE2owkzA6/h2LjVZotIA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-28T22:18:59Z"
    mac: ENC[AES256_GCM,data:1D+r2LeSFifDI+9R3vB2ch1Psd2gQuKu2Lm8sw0BqFCFoYestvdxP11HEboO7hMgJR16sPqBO2Yx0p5p93v1gtYJGmCjyiigxS1xpJYI0ObPZKcGAByYt8688X6hrG+xw5r/XflV0sFM4GftKgyzcj21EDUjUH7On8AfsqKCvHo=,iv:3YvFGbFVTfYIt9o0B+yQNH/13ku5TYTiJ53BZSJdj2g=,tag:GVtw3jWXedDHca8eBQm8ZA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
