//! Visual reference tests: render HTML/CSS in stage-runtime and compare
//! against Chrome-rendered reference PNGs (RMSE threshold).
//!
//! Reference images generated by `tests/htmlcss_fixtures/generate.cjs` using Puppeteer.
//! Run `node tests/htmlcss_fixtures/generate.cjs` to regenerate.
//!
//! Set `SAVE_ALL=1` to save every rendered output as a PNG for visual inspection:
//!   SAVE_ALL=1 cargo test --test htmlcss_reference_test
//!
//! Run: cargo test --test htmlcss_reference_test

use std::path::Path;

const FIXTURES_DIR: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/htmlcss_fixtures");
const DEFAULT_THRESHOLD: f64 = 0.02;

/// RMSE between two RGBA pixel buffers. Returns 0.0–1.0.
fn rmse(a: &[u8], b: &[u8]) -> f64 {
    assert_eq!(a.len(), b.len(), "pixel buffers must be same size");
    if a.is_empty() { return 0.0; }
    let sum_sq: f64 = a.iter().zip(b.iter())
        .map(|(&av, &bv)| { let d = av as f64 - bv as f64; d * d })
        .sum();
    (sum_sq / a.len() as f64).sqrt() / 255.0
}

/// Load a PNG file → (width, height, rgba_pixels).
fn load_png(path: &Path) -> (u32, u32, Vec<u8>) {
    let data = std::fs::read(path).unwrap_or_else(|_| panic!("failed to read {}", path.display()));
    let decoder = png::Decoder::new(std::io::Cursor::new(data));
    let mut reader = decoder.read_info().expect("PNG decode failed");
    let mut buf = vec![0u8; reader.output_buffer_size()];
    let info = reader.next_frame(&mut buf).expect("PNG frame read failed");
    buf.truncate(info.buffer_size());

    let rgba = match info.color_type {
        png::ColorType::Rgba => buf,
        png::ColorType::Rgb => {
            let mut out = Vec::with_capacity(buf.len() / 3 * 4);
            for c in buf.chunks_exact(3) { out.extend_from_slice(c); out.push(255); }
            out
        }
        other => panic!("unsupported PNG color type: {:?}", other),
    };
    (info.width, info.height, rgba)
}

fn load_scenes() -> serde_json::Value {
    let p = Path::new(FIXTURES_DIR).join("scenes.json");
    serde_json::from_str(&std::fs::read_to_string(&p).unwrap()).unwrap()
}

/// Save RGBA pixel data as a PNG file.
fn save_png(path: &Path, width: u32, height: u32, rgba: &[u8]) {
    let file = std::fs::File::create(path).expect("failed to create PNG output");
    let w = std::io::BufWriter::new(file);
    let mut encoder = png::Encoder::new(w, width, height);
    encoder.set_color(png::ColorType::Rgba);
    encoder.set_depth(png::BitDepth::Eight);
    encoder.set_compression(png::Compression::Best);
    encoder.set_adaptive_filter(png::AdaptiveFilterType::Adaptive);
    let mut writer = encoder.write_header().expect("failed to write PNG header");
    writer.write_image_data(rgba).expect("failed to write PNG data");
}

fn run_scene(name: &str) {
    let scenes = load_scenes();
    let w = scenes["width"].as_u64().unwrap() as u32;
    let h = scenes["height"].as_u64().unwrap() as u32;
    let scene = &scenes["scenes"][name];
    let html = scene["html"].as_str().expect("scene must have html field");
    let threshold = scene.get("threshold")
        .and_then(|t| t.as_f64())
        .unwrap_or(DEFAULT_THRESHOLD);

    let ref_path = Path::new(FIXTURES_DIR).join(format!("{}.truth.png", name));
    if !ref_path.exists() {
        panic!("Reference missing: {}. Run `node tests/htmlcss_fixtures/generate.cjs`", ref_path.display());
    }

    let (rw, rh, ref_px) = load_png(&ref_path);
    assert_eq!((rw, rh), (w, h), "reference size mismatch for {}", name);

    // Render through our HTML/CSS pipeline
    let mut pixmap = tiny_skia::Pixmap::new(w, h).unwrap();
    dazzle_render::htmlcss::render_html(html, &mut pixmap);

    // Convert premultiplied RGBA to straight RGBA for comparison.
    // Chrome screenshots are straight RGBA; tiny-skia uses premultiplied internally.
    let rendered = unpremultiply(pixmap.data());

    // Save rendered output alongside reference when SAVE_ALL=1
    if std::env::var("SAVE_ALL").map(|v| v == "1").unwrap_or(false) {
        let out_path = Path::new(FIXTURES_DIR).join(format!("{}.render.png", name));
        save_png(&out_path, w, h, &rendered);
    }

    let err = rmse(&rendered, &ref_px);
    if err > threshold {
        // Save the failed render for inspection
        let fail_path = Path::new(FIXTURES_DIR).join(format!("{}.render.png", name));
        save_png(&fail_path, w, h, &rendered);
        panic!(
            "Scene '{}' RMSE {:.6} exceeds threshold {:.4}\n  Reference: {}\n  Rendered: {}",
            name, err, threshold, ref_path.display(), fail_path.display()
        );
    }
    eprintln!("  {} RMSE: {:.6} (threshold: {:.4}) ✓", name, err, threshold);
}

/// Convert premultiplied RGBA to straight RGBA.
fn unpremultiply(data: &[u8]) -> Vec<u8> {
    let mut out = vec![0u8; data.len()];
    for (s, d) in data.chunks_exact(4).zip(out.chunks_exact_mut(4)) {
        let a = s[3];
        if a == 0 {
            d[0] = 0; d[1] = 0; d[2] = 0; d[3] = 0;
        } else if a == 255 {
            d[0] = s[0]; d[1] = s[1]; d[2] = s[2]; d[3] = 255;
        } else {
            let af = a as f64 / 255.0;
            d[0] = (s[0] as f64 / af).min(255.0).round() as u8;
            d[1] = (s[1] as f64 / af).min(255.0).round() as u8;
            d[2] = (s[2] as f64 / af).min(255.0).round() as u8;
            d[3] = a;
        }
    }
    out
}

/// Generate `#[test]` functions for each scene in scenes.json.
/// Adding a new scene only requires adding it to scenes.json and regenerating
/// the reference image — no test code changes needed.
macro_rules! ref_scenes {
    ( $prefix:ident : $( $scene:ident ),* $(,)? ) => {
        $(
            #[test]
            fn $scene() {
                run_scene(stringify!($scene).strip_prefix(concat!(stringify!($prefix), "_")).unwrap());
            }
        )*
    };
}

ref_scenes! { ref:
    // Solid colors / backgrounds
    ref_solid_background, ref_nested_divs,
    // Layout: flex
    ref_flex_row,
    // Layout: grid
    ref_grid_2x2,
    // Border radius / solid
    ref_border_radius, ref_border_solid,
    // Gradients / opacity
    ref_gradient_linear, ref_opacity_layers,
    // Box model
    ref_margin_padding,
    // Text rendering
    ref_text_basic, ref_text_colors_sizes,
    // Complex layout
    ref_card_layout, ref_percentage_widths, ref_display_none, ref_overflow_hidden,
    // CSS custom properties
    ref_css_var_basic, ref_css_var_inheritance, ref_css_var_fallback, ref_css_var_nested,
    // CSS calc()
    ref_css_calc_width, ref_css_calc_padding,
    // box-shadow
    ref_box_shadow_basic, ref_box_shadow_colored, ref_box_shadow_offset,
    ref_box_shadow_multiple, ref_box_shadow_spread,
    // backdrop-filter
    ref_backdrop_filter_blur, ref_backdrop_filter_dark,
    // CSS transforms
    ref_transform_rotate, ref_transform_scale, ref_transform_translate,
    ref_transform_skew, ref_transform_compound, ref_transform_origin,
    // Additional layout
    ref_flex_wrap, ref_flex_column, ref_flex_center, ref_grid_3col, ref_absolute_position,
    // CSS units
    ref_padding_percent, ref_gap_vw, ref_font_size_em, ref_font_size_rem,
    ref_width_vw_vh, ref_margin_percent,
    // Complex visual
    ref_dashboard_card, ref_gradient_multi_stop, ref_border_radius_circle,
    ref_nested_border_radius,
    // Text properties
    ref_text_transform_upper, ref_text_transform_capitalize,
    ref_text_decoration_underline, ref_text_decoration_line_through,
    ref_font_style_italic, ref_letter_spacing_wide,
    // Pseudo-elements
    ref_pseudo_before_text, ref_pseudo_after_text, ref_pseudo_both,
    ref_pseudo_empty_content, ref_pseudo_with_background,
    // <img> rendering
    ref_img_basic, ref_img_natural_size, ref_img_in_flex, ref_img_no_src,
    // @media queries
    ref_media_min_width_match, ref_media_max_width_no_match, ref_media_screen,
    ref_media_print_ignored, ref_media_compound_and,
    ref_media_prefers_color_scheme_light, ref_media_not_print,
    ref_media_with_normal_rules,
    // Position
    ref_position_relative, ref_position_fixed,
    // Min/max sizing
    ref_min_width_height, ref_max_width_height,
    // z-index
    ref_z_index_stacking,
    // Display
    ref_display_inline_block,
    // Flex grow/shrink
    ref_flex_grow_ratio, ref_flex_shrink_ratio,
    // line-height
    ref_line_height_unitless,
    // text-overflow
    ref_text_overflow_ellipsis,
    // Border sides
    ref_border_sides,
    // Attribute selectors
    ref_attr_selector_exact, ref_attr_selector_starts,
    ref_attr_selector_ends, ref_attr_selector_contains,
    // Combinators
    ref_combinator_child, ref_combinator_adjacent, ref_combinator_general_sibling,
    // Compound selectors
    ref_compound_class,
    // Border-radius edge cases
    ref_border_radius_percent, ref_border_radius_mixed,
    // Transform percentage
    ref_transform_translate_percent, ref_transform_nested_stacking,
    // z-index stacking contexts
    ref_z_index_nested_stacking_contexts, ref_z_index_opacity_context,
    // Grid edge cases
    ref_grid_auto_columns, ref_grid_minmax, ref_grid_mixed_units,
    // Multi-line text
    ref_text_multiline_wrap, ref_text_multiline_break_word, ref_text_multiline_lineheight,
    // Overflow clipping
    ref_overflow_clip_nested, ref_overflow_hidden_border_radius,
    // Inline-block
    ref_inline_block_mixed,
    // Flex baseline
    ref_flex_align_baseline,
    // Negative margins
    ref_negative_margins,
    // rem custom root
    ref_font_size_rem_custom_root,
    // Complex layout
    ref_complex_dashboard_panel,
    // Overflow + transform
    ref_overflow_hidden_rotate, ref_overflow_hidden_scale, ref_overflow_hidden_translate,
    // Grid edge cases (continued)
    ref_grid_auto_fill, ref_grid_gap_percent, ref_grid_fr_mixed,
    // Transform-origin
    ref_transform_origin_percent, ref_transform_origin_bottom_right,
    // Backdrop filter variations
    ref_backdrop_filter_blur_small, ref_backdrop_filter_grayscale,
    // Box shadow edge cases
    ref_box_shadow_inset, ref_box_shadow_inset_colored, ref_box_shadow_with_border_radius,
    // Pseudo-elements with positioning
    ref_pseudo_absolute, ref_pseudo_with_transform,
    // Flex baseline mixed
    ref_flex_baseline_mixed,
    // Nested border-radius + overflow
    ref_border_radius_overflow_nested,
    // Text overflow + transform
    ref_text_ellipsis_uppercase,
    // Negative margins complex
    ref_negative_margin_overlap,
    // Gradient edge cases
    ref_gradient_angle_0, ref_gradient_angle_90, ref_gradient_transparent_stop,
    // Inline layout
    ref_inline_vertical_align_middle, ref_inline_img_baseline,
    ref_inline_block_wrap, ref_text_white_space_pre,
    // Flex/grid sizing
    ref_flex_basis_vs_width, ref_grid_explicit_placement,
    // Border styles
    ref_border_dashed, ref_border_dotted, ref_border_double,
    ref_border_dashed_radius, ref_border_mixed_styles,
    // Percentage sizing
    ref_percent_height_no_parent, ref_percent_height_explicit_chain,
    ref_percent_margin_in_flex, ref_flex_wrap_align_content, ref_min_max_in_flex,
    // Overflow + transform edge cases
    ref_overflow_hidden_compound_transform, ref_overflow_hidden_translate_partial,
    ref_overflow_hidden_nested_transform,
    // Text edge cases
    ref_text_multiline_ellipsis, ref_text_white_space_nowrap, ref_text_word_break_all,
    // Z-index stacking context edge cases
    ref_z_index_transform_context, ref_z_index_filter_context,
    ref_z_index_mixed_contexts, ref_z_index_nested_transform, ref_z_index_auto_vs_zero,
    // Unimplemented features
    ref_gradient_radial, ref_gradient_radial_ellipse,
    ref_filter_blur, ref_filter_grayscale, ref_filter_brightness_contrast,
    ref_filter_drop_shadow, ref_mix_blend_multiply, ref_mix_blend_screen,
    ref_text_shadow_basic, ref_text_shadow_glow,
    ref_clip_path_circle, ref_clip_path_polygon,
}

#[test]
fn debug_container_style() {
    let html = r#"<!DOCTYPE html><html><head><style>body { margin: 0; background: #111; font-family: sans-serif; padding: 10px; } .container { line-height: 80px; background: #1a1a2e; } .box { display: inline-block; vertical-align: middle; background: #e94560; } .small { width: 20px; height: 20px; } .med { width: 30px; height: 40px; } .tall { width: 25px; height: 60px; }</style></head><body><div class="container"><span class="box small"></span><span class="box med"></span><span class="box tall"></span></div></body></html>"#;
    let mut pixmap = tiny_skia::Pixmap::new(256, 256).unwrap();
    dazzle_render::htmlcss::render_html(html, &mut pixmap);
    let data = pixmap.data();
    // Scan column x=12 (inside container, inside small box region) for navy vs red
    eprintln!("Col x=12: (inside small box region horizontally)");
    for y in 10usize..=95 {
        let i=(y*256+12)*4;
        let (r,g,b) = (data[i],data[i+1],data[i+2]);
        if (r,g,b) != (0,0,0) { eprintln!("  y={}: ({},{},{})", y, r, g, b); }
    }
    eprintln!("Col x=35: (inside med box region horizontally)");
    for y in 10usize..=95 {
        let i=(y*256+35)*4;
        let (r,g,b) = (data[i],data[i+1],data[i+2]);
        if (r,g,b) != (0,0,0) { eprintln!("  y={}: ({},{},{})", y, r, g, b); }
    }
}
