//! Visual reference tests: render scenes in stage-runtime's Canvas2D
//! and compare against Chrome-rendered reference PNGs (RMSE threshold).
//!
//! Reference images generated by `tests/fixtures/generate.cjs` using Puppeteer.
//! Run `node tests/fixtures/generate.cjs` to regenerate.
//!
//! Set `SAVE_ALL=1` to save every rendered output as a PNG for visual inspection:
//!   SAVE_ALL=1 cargo test --package stage-runtime --test reference_test
//! Output goes to tests/fixtures/output/<scene_name>.png

use std::path::Path;

const FIXTURES_DIR: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/tests/fixtures");
const DEFAULT_THRESHOLD: f64 = 0.01;

/// RMSE between two RGBA pixel buffers. Returns 0.0–1.0.
fn rmse(a: &[u8], b: &[u8]) -> f64 {
    assert_eq!(a.len(), b.len(), "pixel buffers must be same size");
    if a.is_empty() { return 0.0; }
    let sum_sq: f64 = a.iter().zip(b.iter())
        .map(|(&av, &bv)| { let d = av as f64 - bv as f64; d * d })
        .sum();
    (sum_sq / a.len() as f64).sqrt() / 255.0
}

/// Load a PNG file → (width, height, rgba_pixels).
fn load_png(path: &Path) -> (u32, u32, Vec<u8>) {
    let data = std::fs::read(path).unwrap_or_else(|_| panic!("failed to read {}", path.display()));
    let decoder = png::Decoder::new(std::io::Cursor::new(data));
    let mut reader = decoder.read_info().expect("PNG decode failed");
    let mut buf = vec![0u8; reader.output_buffer_size()];
    let info = reader.next_frame(&mut buf).expect("PNG frame read failed");
    buf.truncate(info.buffer_size());

    let rgba = match info.color_type {
        png::ColorType::Rgba => buf,
        png::ColorType::Rgb => {
            let mut out = Vec::with_capacity(buf.len() / 3 * 4);
            for c in buf.chunks_exact(3) { out.extend_from_slice(c); out.push(255); }
            out
        }
        other => panic!("unsupported PNG color type: {:?}", other),
    };
    (info.width, info.height, rgba)
}

fn load_scenes() -> serde_json::Value {
    let p = Path::new(FIXTURES_DIR).join("scenes.json");
    serde_json::from_str(&std::fs::read_to_string(&p).unwrap()).unwrap()
}

/// Save RGBA pixel data as a PNG file.
fn save_png(path: &Path, width: u32, height: u32, rgba: &[u8]) {
    let file = std::fs::File::create(path).expect("failed to create PNG output");
    let w = std::io::BufWriter::new(file);
    let mut encoder = png::Encoder::new(w, width, height);
    encoder.set_color(png::ColorType::Rgba);
    encoder.set_depth(png::BitDepth::Eight);
    encoder.set_compression(png::Compression::Best);
    encoder.set_adaptive_filter(png::AdaptiveFilterType::Adaptive);
    let mut writer = encoder.write_header().expect("failed to write PNG header");
    writer.write_image_data(rgba).expect("failed to write PNG data");
}

fn run_scene(name: &str) {
    let scenes = load_scenes();
    let w = scenes["width"].as_u64().unwrap() as u32;
    let h = scenes["height"].as_u64().unwrap() as u32;
    let scene = &scenes["scenes"][name];
    let cmds = &scene["commands"];
    let threshold = scene.get("threshold")
        .and_then(|t| t.as_f64())
        .unwrap_or(DEFAULT_THRESHOLD);

    let ref_path = Path::new(FIXTURES_DIR).join(format!("{}.truth.png", name));
    if !ref_path.exists() {
        panic!("Reference missing: {}. Run `node tests/fixtures/generate.cjs`", ref_path.display());
    }

    let (rw, rh, ref_px) = load_png(&ref_path);
    assert_eq!((rw, rh), (w, h), "reference size mismatch for {}", name);

    let mut canvas = stage_runtime::canvas2d::Canvas2D::new(w, h);
    canvas.process_commands(cmds);
    let mut rendered = vec![0u8; (w * h * 4) as usize];
    canvas.read_pixels(&mut rendered);

    // Save rendered output alongside reference when SAVE_ALL=1
    // e.g. solid_rects.truth.png (Chrome) + solid_rects.render.png (ours)
    if std::env::var("SAVE_ALL").map(|v| v == "1").unwrap_or(false) {
        let out_path = Path::new(FIXTURES_DIR).join(format!("{}.render.png", name));
        save_png(&out_path, w, h, &rendered);
    }

    let err = rmse(&rendered, &ref_px);
    if err > threshold {
        // Save the failed render for inspection
        let fail_path = Path::new(FIXTURES_DIR).join(format!("{}.render.png", name));
        save_png(&fail_path, w, h, &rendered);
        panic!(
            "Scene '{}' RMSE {:.6} exceeds threshold {:.4}\n  Reference: {}\n  Failed output saved to: {}",
            name, err, threshold, ref_path.display(), fail_path.display()
        );
    }
    eprintln!("  {} RMSE: {:.6} (threshold: {:.4}) ✓", name, err, threshold);
}

/// Generate `#[test]` functions for each scene in scenes.json.
/// Adding a new scene only requires adding it to scenes.json and regenerating
/// the reference image — no test code changes needed.
macro_rules! ref_scenes {
    ( $prefix:ident : $( $scene:ident ),* $(,)? ) => {
        $(
            #[test]
            fn $scene() {
                run_scene(stringify!($scene).strip_prefix(concat!(stringify!($prefix), "_")).unwrap());
            }
        )*
    };
}

ref_scenes! { ref:
    // Rect operations
    ref_solid_rects, ref_clear_rect, ref_stroked_rect, ref_concentric_rects,
    // Colors
    ref_multiple_colors, ref_rgb_colors,
    // Alpha / blending
    ref_overlapping_alpha, ref_global_alpha_layers,
    // Transforms
    ref_translate_rects, ref_scale_rect, ref_nested_transforms, ref_setTransform_matrix,
    // Paths
    ref_path_triangle, ref_path_circle, ref_half_arc, ref_multiple_paths,
    // Curves
    ref_bezier_curve, ref_quad_curve,
    // Lines / stroke
    ref_stroked_path, ref_line_caps, ref_line_joins, ref_dashed_lines, ref_thin_lines,
    // Ellipses
    ref_ellipse_filled, ref_ellipse_rotated, ref_ellipse_stroked,
    // Arc variations
    ref_arc_ccw, ref_arc_stroked, ref_quarter_arcs, ref_stroked_circle,
    // Color formats
    ref_hsl_colors, ref_named_colors, ref_hex_alpha_colors,
    // Transform variations
    ref_rotate_rect, ref_transform_multiply, ref_reset_transform,
    ref_scale_and_translate, ref_negative_scale,
    // Line style variations
    ref_miter_limit, ref_line_dash_offset,
    // Complex paths
    ref_fill_and_stroke, ref_star_path, ref_complex_polygon,
    ref_spiral_path, ref_donut_shape, ref_dashed_shapes,
    // Bezier variations
    ref_bezier_s_curve, ref_multi_bezier_path, ref_filled_bezier,
    // Alpha blending
    ref_alpha_gradient_rects, ref_alpha_on_alpha,
    // State management
    ref_deep_save_restore,
    // Stroke rendering
    ref_overlapping_strokes, ref_wide_stroke, ref_closed_vs_open, ref_diagonal_lines,
    // Clip paths
    ref_clip_rect, ref_clip_circle, ref_clip_nested, ref_clip_transform,
    // Gradients
    ref_gradient_linear_basic, ref_gradient_linear_multi, ref_gradient_radial,
    // Composite operations
    ref_composite_multiply, ref_composite_screen, ref_composite_destination_out,
    ref_composite_source_atop, ref_composite_destination_over, ref_composite_lighter,
    ref_composite_xor, ref_composite_darken, ref_composite_lighten,
    ref_composite_difference, ref_composite_overlay, ref_composite_copy,
    // Shadow rendering
    ref_shadow_rect, ref_shadow_text,
    // arcTo
    ref_arcto_rounded_rect, ref_arcto_simple,
    // Extended named colors
    ref_named_colors_extended,
    // Edge cases
    ref_tiny_arc, ref_zero_width_stroke, ref_negative_rect_dims,
    ref_large_coordinates, ref_degenerate_bezier, ref_multiple_beginpath,
    ref_fill_rule_evenodd,
    // Transform edge cases
    ref_transform_mid_path, ref_scaled_stroke_width,
    ref_transform_order_rotate_scale, ref_transform_order_scale_rotate,
    ref_transform_persist_across_paths, ref_set_transform_overrides,
    ref_subpixel_transform,
    // Gradient fills
    ref_gradient_linear_fill, ref_gradient_radial_fill, ref_gradient_multi_stop_fill,
    // Shadow rendering (additional)
    ref_shadow_fillrect, ref_shadow_filltext,
    // roundRect paths
    ref_roundrect_basic, ref_roundrect_varied,
    // textBaseline modes
    ref_text_baseline_top, ref_text_baseline_middle, ref_text_baseline_bottom,
    // Rare composite operations
    ref_composite_color_dodge, ref_composite_color_burn,
    ref_composite_hard_light, ref_composite_soft_light,
    // Clip + fill/stroke variations
    ref_clip_fillrect, ref_clip_arc_fill, ref_clip_with_transform,
    ref_clip_nested_rects, ref_clip_multi_draw, ref_clip_with_stroke,
    // arcTo variations
    ref_arcto_corner, ref_arcto_full_roundrect,
    // drawImage
    ref_drawimage_inline_basic, ref_drawimage_inline_scaled, ref_drawimage_crop_9arg,
    ref_drawimage_with_transform, ref_drawimage_clip,
    // putImageData
    ref_putimagedata_basic, ref_putimagedata_ignores_transform,
    // Shadow + Alpha interaction
    ref_shadow_alpha_interaction, ref_shadow_on_stroked_path,
    // Radial gradient edge cases
    ref_radial_gradient_offset_center, ref_radial_gradient_concentric_tight,
    // Text edge cases
    ref_text_shadow_blur_extremes, ref_text_large_font,
    // Transform + Clip interaction
    ref_clip_after_transform, ref_nested_clip_transform,
    // Save/Restore style leak
    ref_save_restore_style_leak,
    // Composite edge cases
    ref_composite_source_in, ref_composite_destination_out_punch,
    // clearRect + transform
    ref_clearrect_after_transform,
}
