apiVersion: v1
kind: Secret
metadata:
    name: postgres-auth
    namespace: browser-streamer
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:H3jNFMyN7sMpYfDbetAgLtk/Ux3qfeV2zfXCKoHEh5UkN2IOOMZfeZFcRDC9rklL4ZHouW2tX1YpN33KeeGCEw==,iv:ms4v98dGosvIwGeJq+yYhk2CB+/zypIFhMLt2nnmPxA=,tag:CyJ9CjZT821xAbHsg++u7w==,type:str]
sops:
    age:
        - recipient: age1ase59dknkacq26gemrs9dvwvu8xr8akhfya99lagv5py7c7h7plsmtucvv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzSmFaTmJOSTVnNlYxUW40
            QUdEY0V3YmczL2JEb0c4eUhzZTFCNzFmWnp3Ckprc1crcGY5QndXTG5LZmxKUVE0
            eWZPTy9kVndoeEhkL2NJNkpCSjBjNnMKLS0tIFhEQkFPTGwvNllwSnBYWEI0SzU5
            OFh3VjNDZTRiem1SKy9nenZMbkFFWmsKV5Xk6Zkwa2eEEFHz1PMd2LQBb6aXE+y5
            Jq98PpQlcVR9UseZ5xLmgVT7SsY1ilaTs1PAhOl4Tyl6DYNsp9vOuw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age13zs054me9k5h4m8u3hwqw9nz4jg6lkpfmkzqn8mdujjqp76h6plsmlmtpy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEQU1aR0NlVytoTk5VWXJG
            RXlpaUhuSWpQcUZ0V1pzSFd1K2p5Wk1yTkI0CmV5NlkrZG5nY2V0WG5PSHVFU2Ja
            S0NkUzBTKzJTcUU2K2NrOU9GVEE5MEkKLS0tIGxXRi80YTVGUzdTZ2lENzg3MG84
            UFg3MCtMVFY5RDRwQTFFOHhmVElPeU0KSJI/Sc1C2csq+VnzWfFs5VOKEs9kAhMG
            qNZo9wpt5vdM/JOsl9I6skNIyZBhqROFoLeKmapJ5jqpO+xlWAnHZQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17ttan4es6923ru96408ctjhs2f97mrxq9uw938plgnw6wkstv9cqsaq5cw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmV1A5VU1kelZibEp3NVlt
            Ris0QnpxQ29OckF4akhqZitWaGxoenlMNmdzCmZmV2YrVFJoYXVaZmhtME03QllL
            dkY5M2FNZ3NYRTlxVnlSL29sdElTSjQKLS0tIGVQMFVKcytiVVowOVVVeFFoVzdM
            dEpqMWpXY1RMNmNEWEE0RSt6dHFYakkKjCNde/Z4C2YgT8ybXw8gR0MRNCzVFeAY
            oYxJtDoJh/iAAxPmHB37IaevnI/q92demosoIHjTZ0JsQKUOVaNWwQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1un8ajg06rd075pff8pglkq2q0g020peq7v23qzeqhuchl4y4kyfs0drxyf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJYVppSnQxVkhJZ2FsRkdj
            NDV1dWU4cXFaNVgyS01wR2tIYVhOejlQdFE4Cm5reUNPTkQzMFc1RzJpRWQ0dWUz
            SnFoV3RrYXEvWlNvdmJLU3VPYzd4MHMKLS0tIGdLWnM0enk1c2ZkdDIrOUV6ZnNt
            RFVSQU1UaklxVzBFSU1oczgyUmI2ZDAKE1t7RLFRnipAJi2LFl7k7A23DuKzJGNu
            CN42PuOX229rX1IYoPlLgkg+Lt6cleUTedM50HdpxKuxrqXylUh0cA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18r3vk6aecpcd69ey7fhgjylg6z37ksfeff6c497mxgv4nwmnyupq4gsfua
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0MUlLTFQrZnIyUUk1dDhD
            RGw5Z3N0SVBha2oya3AzYnRSUVV3SlpHSkNjCkVPYXY0Q1poWVBCRGZ5ZXZWYUFJ
            OWtHZTF2cEU2NExJNWlScEJBWTZnYjAKLS0tIDdUc01KK2UyTDU2V0FVUXdqRGZw
            RlJZRU5SaU42WVFOU1A0c2lOWEhPUG8KU/gro1iWqOO9f4KloG+7m1xGsYRWrXHH
            lcLdgCgpXWZr5Oe97BAAJIjKMzfVmYrg8D99NvzoHyBu7BXKLvd6cg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1emw2e5x3d4cu0x4g0q4lrw8nj2fdv0qfzta6g62m5y24j02zu44sflkxln
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKSVNPK2JsTFF4clJIMkw0
            QzNSTThWdWY1OG0xb2IvNGUzOWtJa3JrWFc0CnZ5QnhCVjVJRmZuUWl3V3VSUlhE
            eHlYMnVaS3JoZER6N3lpblBmRWoyWkUKLS0tIHRHMHVoSlhMQjRuVTJBQkhVR3Q1
            Y21uYmJFZlBwcFJ2R0dGaFpzSmYycmMKWJnoDm40xYaWX+ezq041+x6XJS+5gKNk
            2gDl4MJgDs4mRZ0S2cxPC5YGmOmYsZvTY/LG6nXYi6kmo0dJLpkvrg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1x9049ry5hz876qratphuc9gdxzuv4nnd06076842zdukl4unvazszfnjf6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiUFBWdUdaRytjQVkwK1cx
            QzlSczlpQWVJSjJIb3R0QW9wR3VDWVYxNFhZCmRLdWZiT0EvaC9BWFgzR0Npc0RL
            Vlo0NC9td2Z0TUdTVzV6bWptaG90RlEKLS0tIE1TOHk5cUM2WUdmSXpycGQ4czMr
            bDNEVklaV0hseVpxUzJWTFZjc0tUbTgKMDO5sPjYeg3uYdntqcy6btrmNDxpzjdR
            qY2f9kr9djxI6L2xnDV0mQFz0wQBX3SYjJzvnn03EKUVWhP1ZT9JiA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-28T18:37:00Z"
    mac: ENC[AES256_GCM,data:OWG85qMJB2mtw9s8skQnkDfhi2SIgP1hX7hITHnePZDNF/99n9a4L+ZXp48bTHUjKZxybHDb0vVMRynDKJpg0wIwKLkUdFC3R9+XSGybMXr6B6vqKM0VpXk7lyZuCG8AxVh8VFDbYYzSsXENkZfaify3k7s1bFTdnMqQhuOd7CE=,iv:YFOkdgrQb8QfvaYnNUNlP/Etckp+NtLaQihV7EjCg08=,tag:Xk5SoiAICKyvShmSKS/FYQ==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: clerk-auth
    namespace: browser-streamer
type: Opaque
stringData:
    secret-key: ENC[AES256_GCM,data:H4KYVNhiU7r00sc/0Kj0e9lXf+vflKt4g82s+CYZxXPOXAKVs7/MDGegcqtw6KkvnnI=,iv:H2xEFZ4vR8lrQVdLg07dQHY6Kd3E3c7W5C5Xhby3lJ0=,tag:qyPgK0Hjony4Akc9gzE9bw==,type:str]
sops:
    age:
        - recipient: age1ase59dknkacq26gemrs9dvwvu8xr8akhfya99lagv5py7c7h7plsmtucvv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzSmFaTmJOSTVnNlYxUW40
            QUdEY0V3YmczL2JEb0c4eUhzZTFCNzFmWnp3Ckprc1crcGY5QndXTG5LZmxKUVE0
            eWZPTy9kVndoeEhkL2NJNkpCSjBjNnMKLS0tIFhEQkFPTGwvNllwSnBYWEI0SzU5
            OFh3VjNDZTRiem1SKy9nenZMbkFFWmsKV5Xk6Zkwa2eEEFHz1PMd2LQBb6aXE+y5
            Jq98PpQlcVR9UseZ5xLmgVT7SsY1ilaTs1PAhOl4Tyl6DYNsp9vOuw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age13zs054me9k5h4m8u3hwqw9nz4jg6lkpfmkzqn8mdujjqp76h6plsmlmtpy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEQU1aR0NlVytoTk5VWXJG
            RXlpaUhuSWpQcUZ0V1pzSFd1K2p5Wk1yTkI0CmV5NlkrZG5nY2V0WG5PSHVFU2Ja
            S0NkUzBTKzJTcUU2K2NrOU9GVEE5MEkKLS0tIGxXRi80YTVGUzdTZ2lENzg3MG84
            UFg3MCtMVFY5RDRwQTFFOHhmVElPeU0KSJI/Sc1C2csq+VnzWfFs5VOKEs9kAhMG
            qNZo9wpt5vdM/JOsl9I6skNIyZBhqROFoLeKmapJ5jqpO+xlWAnHZQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17ttan4es6923ru96408ctjhs2f97mrxq9uw938plgnw6wkstv9cqsaq5cw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmV1A5VU1kelZibEp3NVlt
            Ris0QnpxQ29OckF4akhqZitWaGxoenlMNmdzCmZmV2YrVFJoYXVaZmhtME03QllL
            dkY5M2FNZ3NYRTlxVnlSL29sdElTSjQKLS0tIGVQMFVKcytiVVowOVVVeFFoVzdM
            dEpqMWpXY1RMNmNEWEE0RSt6dHFYakkKjCNde/Z4C2YgT8ybXw8gR0MRNCzVFeAY
            oYxJtDoJh/iAAxPmHB37IaevnI/q92demosoIHjTZ0JsQKUOVaNWwQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1un8ajg06rd075pff8pglkq2q0g020peq7v23qzeqhuchl4y4kyfs0drxyf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJYVppSnQxVkhJZ2FsRkdj
            NDV1dWU4cXFaNVgyS01wR2tIYVhOejlQdFE4Cm5reUNPTkQzMFc1RzJpRWQ0dWUz
            SnFoV3RrYXEvWlNvdmJLU3VPYzd4MHMKLS0tIGdLWnM0enk1c2ZkdDIrOUV6ZnNt
            RFVSQU1UaklxVzBFSU1oczgyUmI2ZDAKE1t7RLFRnipAJi2LFl7k7A23DuKzJGNu
            CN42PuOX229rX1IYoPlLgkg+Lt6cleUTedM50HdpxKuxrqXylUh0cA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18r3vk6aecpcd69ey7fhgjylg6z37ksfeff6c497mxgv4nwmnyupq4gsfua
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0MUlLTFQrZnIyUUk1dDhD
            RGw5Z3N0SVBha2oya3AzYnRSUVV3SlpHSkNjCkVPYXY0Q1poWVBCRGZ5ZXZWYUFJ
            OWtHZTF2cEU2NExJNWlScEJBWTZnYjAKLS0tIDdUc01KK2UyTDU2V0FVUXdqRGZw
            RlJZRU5SaU42WVFOU1A0c2lOWEhPUG8KU/gro1iWqOO9f4KloG+7m1xGsYRWrXHH
            lcLdgCgpXWZr5Oe97BAAJIjKMzfVmYrg8D99NvzoHyBu7BXKLvd6cg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1emw2e5x3d4cu0x4g0q4lrw8nj2fdv0qfzta6g62m5y24j02zu44sflkxln
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKSVNPK2JsTFF4clJIMkw0
            QzNSTThWdWY1OG0xb2IvNGUzOWtJa3JrWFc0CnZ5QnhCVjVJRmZuUWl3V3VSUlhE
            eHlYMnVaS3JoZER6N3lpblBmRWoyWkUKLS0tIHRHMHVoSlhMQjRuVTJBQkhVR3Q1
            Y21uYmJFZlBwcFJ2R0dGaFpzSmYycmMKWJnoDm40xYaWX+ezq041+x6XJS+5gKNk
            2gDl4MJgDs4mRZ0S2cxPC5YGmOmYsZvTY/LG6nXYi6kmo0dJLpkvrg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1x9049ry5hz876qratphuc9gdxzuv4nnd06076842zdukl4unvazszfnjf6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiUFBWdUdaRytjQVkwK1cx
            QzlSczlpQWVJSjJIb3R0QW9wR3VDWVYxNFhZCmRLdWZiT0EvaC9BWFgzR0Npc0RL
            Vlo0NC9td2Z0TUdTVzV6bWptaG90RlEKLS0tIE1TOHk5cUM2WUdmSXpycGQ4czMr
            bDNEVklaV0hseVpxUzJWTFZjc0tUbTgKMDO5sPjYeg3uYdntqcy6btrmNDxpzjdR
            qY2f9kr9djxI6L2xnDV0mQFz0wQBX3SYjJzvnn03EKUVWhP1ZT9JiA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-28T18:37:00Z"
    mac: ENC[AES256_GCM,data:OWG85qMJB2mtw9s8skQnkDfhi2SIgP1hX7hITHnePZDNF/99n9a4L+ZXp48bTHUjKZxybHDb0vVMRynDKJpg0wIwKLkUdFC3R9+XSGybMXr6B6vqKM0VpXk7lyZuCG8AxVh8VFDbYYzSsXENkZfaify3k7s1bFTdnMqQhuOd7CE=,iv:YFOkdgrQb8QfvaYnNUNlP/Etckp+NtLaQihV7EjCg08=,tag:Xk5SoiAICKyvShmSKS/FYQ==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: encryption-key
    namespace: browser-streamer
type: Opaque
stringData:
    key: ENC[AES256_GCM,data:+dUBdA4+ywS4AgS6zn3kgAIz2uO4aJ4mM72Eh9CWGRRaOMvHueIcQQEoFfn5lJNse/3sWz32wXAC6qNY5hwTpg==,iv:PENr7t4ILSqes0m2a8YNLA3HuzNvjPSiSMwLswerMbA=,tag:GEqC4gDwJJkvotgRr1P1Mg==,type:str]
sops:
    age:
        - recipient: age1ase59dknkacq26gemrs9dvwvu8xr8akhfya99lagv5py7c7h7plsmtucvv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzSmFaTmJOSTVnNlYxUW40
            QUdEY0V3YmczL2JEb0c4eUhzZTFCNzFmWnp3Ckprc1crcGY5QndXTG5LZmxKUVE0
            eWZPTy9kVndoeEhkL2NJNkpCSjBjNnMKLS0tIFhEQkFPTGwvNllwSnBYWEI0SzU5
            OFh3VjNDZTRiem1SKy9nenZMbkFFWmsKV5Xk6Zkwa2eEEFHz1PMd2LQBb6aXE+y5
            Jq98PpQlcVR9UseZ5xLmgVT7SsY1ilaTs1PAhOl4Tyl6DYNsp9vOuw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age13zs054me9k5h4m8u3hwqw9nz4jg6lkpfmkzqn8mdujjqp76h6plsmlmtpy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEQU1aR0NlVytoTk5VWXJG
            RXlpaUhuSWpQcUZ0V1pzSFd1K2p5Wk1yTkI0CmV5NlkrZG5nY2V0WG5PSHVFU2Ja
            S0NkUzBTKzJTcUU2K2NrOU9GVEE5MEkKLS0tIGxXRi80YTVGUzdTZ2lENzg3MG84
            UFg3MCtMVFY5RDRwQTFFOHhmVElPeU0KSJI/Sc1C2csq+VnzWfFs5VOKEs9kAhMG
            qNZo9wpt5vdM/JOsl9I6skNIyZBhqROFoLeKmapJ5jqpO+xlWAnHZQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17ttan4es6923ru96408ctjhs2f97mrxq9uw938plgnw6wkstv9cqsaq5cw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmV1A5VU1kelZibEp3NVlt
            Ris0QnpxQ29OckF4akhqZitWaGxoenlMNmdzCmZmV2YrVFJoYXVaZmhtME03QllL
            dkY5M2FNZ3NYRTlxVnlSL29sdElTSjQKLS0tIGVQMFVKcytiVVowOVVVeFFoVzdM
            dEpqMWpXY1RMNmNEWEE0RSt6dHFYakkKjCNde/Z4C2YgT8ybXw8gR0MRNCzVFeAY
            oYxJtDoJh/iAAxPmHB37IaevnI/q92demosoIHjTZ0JsQKUOVaNWwQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1un8ajg06rd075pff8pglkq2q0g020peq7v23qzeqhuchl4y4kyfs0drxyf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJYVppSnQxVkhJZ2FsRkdj
            NDV1dWU4cXFaNVgyS01wR2tIYVhOejlQdFE4Cm5reUNPTkQzMFc1RzJpRWQ0dWUz
            SnFoV3RrYXEvWlNvdmJLU3VPYzd4MHMKLS0tIGdLWnM0enk1c2ZkdDIrOUV6ZnNt
            RFVSQU1UaklxVzBFSU1oczgyUmI2ZDAKE1t7RLFRnipAJi2LFl7k7A23DuKzJGNu
            CN42PuOX229rX1IYoPlLgkg+Lt6cleUTedM50HdpxKuxrqXylUh0cA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18r3vk6aecpcd69ey7fhgjylg6z37ksfeff6c497mxgv4nwmnyupq4gsfua
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0MUlLTFQrZnIyUUk1dDhD
            RGw5Z3N0SVBha2oya3AzYnRSUVV3SlpHSkNjCkVPYXY0Q1poWVBCRGZ5ZXZWYUFJ
            OWtHZTF2cEU2NExJNWlScEJBWTZnYjAKLS0tIDdUc01KK2UyTDU2V0FVUXdqRGZw
            RlJZRU5SaU42WVFOU1A0c2lOWEhPUG8KU/gro1iWqOO9f4KloG+7m1xGsYRWrXHH
            lcLdgCgpXWZr5Oe97BAAJIjKMzfVmYrg8D99NvzoHyBu7BXKLvd6cg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1emw2e5x3d4cu0x4g0q4lrw8nj2fdv0qfzta6g62m5y24j02zu44sflkxln
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKSVNPK2JsTFF4clJIMkw0
            QzNSTThWdWY1OG0xb2IvNGUzOWtJa3JrWFc0CnZ5QnhCVjVJRmZuUWl3V3VSUlhE
            eHlYMnVaS3JoZER6N3lpblBmRWoyWkUKLS0tIHRHMHVoSlhMQjRuVTJBQkhVR3Q1
            Y21uYmJFZlBwcFJ2R0dGaFpzSmYycmMKWJnoDm40xYaWX+ezq041+x6XJS+5gKNk
            2gDl4MJgDs4mRZ0S2cxPC5YGmOmYsZvTY/LG6nXYi6kmo0dJLpkvrg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1x9049ry5hz876qratphuc9gdxzuv4nnd06076842zdukl4unvazszfnjf6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiUFBWdUdaRytjQVkwK1cx
            QzlSczlpQWVJSjJIb3R0QW9wR3VDWVYxNFhZCmRLdWZiT0EvaC9BWFgzR0Npc0RL
            Vlo0NC9td2Z0TUdTVzV6bWptaG90RlEKLS0tIE1TOHk5cUM2WUdmSXpycGQ4czMr
            bDNEVklaV0hseVpxUzJWTFZjc0tUbTgKMDO5sPjYeg3uYdntqcy6btrmNDxpzjdR
            qY2f9kr9djxI6L2xnDV0mQFz0wQBX3SYjJzvnn03EKUVWhP1ZT9JiA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-28T18:37:00Z"
    mac: ENC[AES256_GCM,data:OWG85qMJB2mtw9s8skQnkDfhi2SIgP1hX7hITHnePZDNF/99n9a4L+ZXp48bTHUjKZxybHDb0vVMRynDKJpg0wIwKLkUdFC3R9+XSGybMXr6B6vqKM0VpXk7lyZuCG8AxVh8VFDbYYzSsXENkZfaify3k7s1bFTdnMqQhuOd7CE=,iv:YFOkdgrQb8QfvaYnNUNlP/Etckp+NtLaQihV7EjCg08=,tag:Xk5SoiAICKyvShmSKS/FYQ==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: browserless-auth
    namespace: browser-streamer
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:hRqoF+KLQssL4v6k6WnVKEkCsAN29dx1Kp2KfrzWENVhLpVXUsMyvFlH05kicB3+7iUP9elqSvDq6hXVWEjznA==,iv:gwnRl8kUuf09TGk9sR315+RAh7Ehh2EQyBnH5VtE4p0=,tag:1QcuJlc8/h7afZfc01BXqg==,type:str]
sops:
    age:
        - recipient: age1ase59dknkacq26gemrs9dvwvu8xr8akhfya99lagv5py7c7h7plsmtucvv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzSmFaTmJOSTVnNlYxUW40
            QUdEY0V3YmczL2JEb0c4eUhzZTFCNzFmWnp3Ckprc1crcGY5QndXTG5LZmxKUVE0
            eWZPTy9kVndoeEhkL2NJNkpCSjBjNnMKLS0tIFhEQkFPTGwvNllwSnBYWEI0SzU5
            OFh3VjNDZTRiem1SKy9nenZMbkFFWmsKV5Xk6Zkwa2eEEFHz1PMd2LQBb6aXE+y5
            Jq98PpQlcVR9UseZ5xLmgVT7SsY1ilaTs1PAhOl4Tyl6DYNsp9vOuw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age13zs054me9k5h4m8u3hwqw9nz4jg6lkpfmkzqn8mdujjqp76h6plsmlmtpy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEQU1aR0NlVytoTk5VWXJG
            RXlpaUhuSWpQcUZ0V1pzSFd1K2p5Wk1yTkI0CmV5NlkrZG5nY2V0WG5PSHVFU2Ja
            S0NkUzBTKzJTcUU2K2NrOU9GVEE5MEkKLS0tIGxXRi80YTVGUzdTZ2lENzg3MG84
            UFg3MCtMVFY5RDRwQTFFOHhmVElPeU0KSJI/Sc1C2csq+VnzWfFs5VOKEs9kAhMG
            qNZo9wpt5vdM/JOsl9I6skNIyZBhqROFoLeKmapJ5jqpO+xlWAnHZQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17ttan4es6923ru96408ctjhs2f97mrxq9uw938plgnw6wkstv9cqsaq5cw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmV1A5VU1kelZibEp3NVlt
            Ris0QnpxQ29OckF4akhqZitWaGxoenlMNmdzCmZmV2YrVFJoYXVaZmhtME03QllL
            dkY5M2FNZ3NYRTlxVnlSL29sdElTSjQKLS0tIGVQMFVKcytiVVowOVVVeFFoVzdM
            dEpqMWpXY1RMNmNEWEE0RSt6dHFYakkKjCNde/Z4C2YgT8ybXw8gR0MRNCzVFeAY
            oYxJtDoJh/iAAxPmHB37IaevnI/q92demosoIHjTZ0JsQKUOVaNWwQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1un8ajg06rd075pff8pglkq2q0g020peq7v23qzeqhuchl4y4kyfs0drxyf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJYVppSnQxVkhJZ2FsRkdj
            NDV1dWU4cXFaNVgyS01wR2tIYVhOejlQdFE4Cm5reUNPTkQzMFc1RzJpRWQ0dWUz
            SnFoV3RrYXEvWlNvdmJLU3VPYzd4MHMKLS0tIGdLWnM0enk1c2ZkdDIrOUV6ZnNt
            RFVSQU1UaklxVzBFSU1oczgyUmI2ZDAKE1t7RLFRnipAJi2LFl7k7A23DuKzJGNu
            CN42PuOX229rX1IYoPlLgkg+Lt6cleUTedM50HdpxKuxrqXylUh0cA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18r3vk6aecpcd69ey7fhgjylg6z37ksfeff6c497mxgv4nwmnyupq4gsfua
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0MUlLTFQrZnIyUUk1dDhD
            RGw5Z3N0SVBha2oya3AzYnRSUVV3SlpHSkNjCkVPYXY0Q1poWVBCRGZ5ZXZWYUFJ
            OWtHZTF2cEU2NExJNWlScEJBWTZnYjAKLS0tIDdUc01KK2UyTDU2V0FVUXdqRGZw
            RlJZRU5SaU42WVFOU1A0c2lOWEhPUG8KU/gro1iWqOO9f4KloG+7m1xGsYRWrXHH
            lcLdgCgpXWZr5Oe97BAAJIjKMzfVmYrg8D99NvzoHyBu7BXKLvd6cg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1emw2e5x3d4cu0x4g0q4lrw8nj2fdv0qfzta6g62m5y24j02zu44sflkxln
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKSVNPK2JsTFF4clJIMkw0
            QzNSTThWdWY1OG0xb2IvNGUzOWtJa3JrWFc0CnZ5QnhCVjVJRmZuUWl3V3VSUlhE
            eHlYMnVaS3JoZER6N3lpblBmRWoyWkUKLS0tIHRHMHVoSlhMQjRuVTJBQkhVR3Q1
            Y21uYmJFZlBwcFJ2R0dGaFpzSmYycmMKWJnoDm40xYaWX+ezq041+x6XJS+5gKNk
            2gDl4MJgDs4mRZ0S2cxPC5YGmOmYsZvTY/LG6nXYi6kmo0dJLpkvrg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1x9049ry5hz876qratphuc9gdxzuv4nnd06076842zdukl4unvazszfnjf6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiUFBWdUdaRytjQVkwK1cx
            QzlSczlpQWVJSjJIb3R0QW9wR3VDWVYxNFhZCmRLdWZiT0EvaC9BWFgzR0Npc0RL
            Vlo0NC9td2Z0TUdTVzV6bWptaG90RlEKLS0tIE1TOHk5cUM2WUdmSXpycGQ4czMr
            bDNEVklaV0hseVpxUzJWTFZjc0tUbTgKMDO5sPjYeg3uYdntqcy6btrmNDxpzjdR
            qY2f9kr9djxI6L2xnDV0mQFz0wQBX3SYjJzvnn03EKUVWhP1ZT9JiA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-28T18:37:00Z"
    mac: ENC[AES256_GCM,data:OWG85qMJB2mtw9s8skQnkDfhi2SIgP1hX7hITHnePZDNF/99n9a4L+ZXp48bTHUjKZxybHDb0vVMRynDKJpg0wIwKLkUdFC3R9+XSGybMXr6B6vqKM0VpXk7lyZuCG8AxVh8VFDbYYzSsXENkZfaify3k7s1bFTdnMqQhuOd7CE=,iv:YFOkdgrQb8QfvaYnNUNlP/Etckp+NtLaQihV7EjCg08=,tag:Xk5SoiAICKyvShmSKS/FYQ==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.11.0
