apiVersion: v1
kind: Secret
metadata:
    name: postgres-auth
    namespace: browser-streamer
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:H3jNFMyN7sMpYfDbetAgLtk/Ux3qfeV2zfXCKoHEh5UkN2IOOMZfeZFcRDC9rklL4ZHouW2tX1YpN33KeeGCEw==,iv:ms4v98dGosvIwGeJq+yYhk2CB+/zypIFhMLt2nnmPxA=,tag:CyJ9CjZT821xAbHsg++u7w==,type:str]
sops:
    age:
        - recipient: age1ase59dknkacq26gemrs9dvwvu8xr8akhfya99lagv5py7c7h7plsmtucvv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsMUFweGhQMjhSMmNOdTZi
            U0xZY0gwM21WZnRoMEhZY3p4SWxUODA3M2dJCk8xQ1IxL3NHY1NqY2xKc09PRjE5
            RkpNL3E3OTFlYkR4c0JsS1NqTktyZXcKLS0tIHl2aC9TNGVtcURUUjJWSkEvNS9L
            OTU5MW13RVdDUHdDak5HRTFjNGx6VU0K2KNT9mIK4AVab0aBu/1L7qkvZBr6Xzd9
            5/tv4ZOMUAXqTg2vONgUhA2KbsDZCgUaDmjMZwryGTu7YksxH9TUXQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age13zs054me9k5h4m8u3hwqw9nz4jg6lkpfmkzqn8mdujjqp76h6plsmlmtpy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTRUM4UXF4U1FlTER6OVo2
            Z1JOaXgvQmdxNUxxRVZ1WUM0UCtWS2owcEJJCkdEN1ZwYW5LSDZQaE5FenlOMEdN
            QmxQR3c0UVIwTHcyeTA0eEF1ci9zYmMKLS0tIGN4ZXhUR1BuNm55Zkl2dVZOMmE5
            bE1KTjhIS0xPK0Q5T1BQUkx0SFBKeEkKx+qdjCXN43zXz6F9JKiJCNzFsf2HfZVw
            sJ9AjSzdmVMuMJ8i592X6agOi3pZz1RudGd4x4+rZdtxPYxmrRjArw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17ttan4es6923ru96408ctjhs2f97mrxq9uw938plgnw6wkstv9cqsaq5cw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmNVBncG1XME5EYmhUVy84
            MkxsZWhiSVZFMG5XZ2NOeTFyV0pKSE5lQUJ3CnpTa01OeldvU21xL3BLZjhKRHhi
            d25PNnpndFlUVG1MTkRIblExNWhVUFEKLS0tIG9xZDI1TU11RDBoNHhtdi9vU05u
            LzJOZ0NGVTFlODhnWVZTZVJDeXFocWsKLMnXZ2hAAYYPHpwwQeFlkx4DBfznzaaS
            v/45WcE8jZ/thS1iSUcXIG3y9jwvGpGeSlFtd/M8B7D62kX+wJp/Fw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1un8ajg06rd075pff8pglkq2q0g020peq7v23qzeqhuchl4y4kyfs0drxyf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWL1FvNDFRWmNkVHFKdTBQ
            MGl1OUtoZ2U3SGZWYlpTQmRRYjUybDFSb3hVClV1QXY3NEpKSkdPd05ZcHN0UWZB
            NHQwZDFlUVkvaDd2QXBmSXhBb3ptOTQKLS0tIGRLTG5BK0hNT3FVT3FlVUhzenpZ
            ckk4RTVqYzNZbUgzd2ZyMEp3V0l3QzAK82qFmExd5brhRIVqTYFg0ZFWiqEBJzY6
            4L7DSCom89CaunPOfldR+S0OO/GcRsK6y9ahjsHS4PiIl4glR3wMuw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-28T18:37:00Z"
    mac: ENC[AES256_GCM,data:OWG85qMJB2mtw9s8skQnkDfhi2SIgP1hX7hITHnePZDNF/99n9a4L+ZXp48bTHUjKZxybHDb0vVMRynDKJpg0wIwKLkUdFC3R9+XSGybMXr6B6vqKM0VpXk7lyZuCG8AxVh8VFDbYYzSsXENkZfaify3k7s1bFTdnMqQhuOd7CE=,iv:YFOkdgrQb8QfvaYnNUNlP/Etckp+NtLaQihV7EjCg08=,tag:Xk5SoiAICKyvShmSKS/FYQ==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: clerk-auth
    namespace: browser-streamer
type: Opaque
stringData:
    secret-key: ENC[AES256_GCM,data:H4KYVNhiU7r00sc/0Kj0e9lXf+vflKt4g82s+CYZxXPOXAKVs7/MDGegcqtw6KkvnnI=,iv:H2xEFZ4vR8lrQVdLg07dQHY6Kd3E3c7W5C5Xhby3lJ0=,tag:qyPgK0Hjony4Akc9gzE9bw==,type:str]
sops:
    age:
        - recipient: age1ase59dknkacq26gemrs9dvwvu8xr8akhfya99lagv5py7c7h7plsmtucvv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsMUFweGhQMjhSMmNOdTZi
            U0xZY0gwM21WZnRoMEhZY3p4SWxUODA3M2dJCk8xQ1IxL3NHY1NqY2xKc09PRjE5
            RkpNL3E3OTFlYkR4c0JsS1NqTktyZXcKLS0tIHl2aC9TNGVtcURUUjJWSkEvNS9L
            OTU5MW13RVdDUHdDak5HRTFjNGx6VU0K2KNT9mIK4AVab0aBu/1L7qkvZBr6Xzd9
            5/tv4ZOMUAXqTg2vONgUhA2KbsDZCgUaDmjMZwryGTu7YksxH9TUXQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age13zs054me9k5h4m8u3hwqw9nz4jg6lkpfmkzqn8mdujjqp76h6plsmlmtpy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTRUM4UXF4U1FlTER6OVo2
            Z1JOaXgvQmdxNUxxRVZ1WUM0UCtWS2owcEJJCkdEN1ZwYW5LSDZQaE5FenlOMEdN
            QmxQR3c0UVIwTHcyeTA0eEF1ci9zYmMKLS0tIGN4ZXhUR1BuNm55Zkl2dVZOMmE5
            bE1KTjhIS0xPK0Q5T1BQUkx0SFBKeEkKx+qdjCXN43zXz6F9JKiJCNzFsf2HfZVw
            sJ9AjSzdmVMuMJ8i592X6agOi3pZz1RudGd4x4+rZdtxPYxmrRjArw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17ttan4es6923ru96408ctjhs2f97mrxq9uw938plgnw6wkstv9cqsaq5cw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmNVBncG1XME5EYmhUVy84
            MkxsZWhiSVZFMG5XZ2NOeTFyV0pKSE5lQUJ3CnpTa01OeldvU21xL3BLZjhKRHhi
            d25PNnpndFlUVG1MTkRIblExNWhVUFEKLS0tIG9xZDI1TU11RDBoNHhtdi9vU05u
            LzJOZ0NGVTFlODhnWVZTZVJDeXFocWsKLMnXZ2hAAYYPHpwwQeFlkx4DBfznzaaS
            v/45WcE8jZ/thS1iSUcXIG3y9jwvGpGeSlFtd/M8B7D62kX+wJp/Fw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1un8ajg06rd075pff8pglkq2q0g020peq7v23qzeqhuchl4y4kyfs0drxyf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWL1FvNDFRWmNkVHFKdTBQ
            MGl1OUtoZ2U3SGZWYlpTQmRRYjUybDFSb3hVClV1QXY3NEpKSkdPd05ZcHN0UWZB
            NHQwZDFlUVkvaDd2QXBmSXhBb3ptOTQKLS0tIGRLTG5BK0hNT3FVT3FlVUhzenpZ
            ckk4RTVqYzNZbUgzd2ZyMEp3V0l3QzAK82qFmExd5brhRIVqTYFg0ZFWiqEBJzY6
            4L7DSCom89CaunPOfldR+S0OO/GcRsK6y9ahjsHS4PiIl4glR3wMuw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-28T18:37:00Z"
    mac: ENC[AES256_GCM,data:OWG85qMJB2mtw9s8skQnkDfhi2SIgP1hX7hITHnePZDNF/99n9a4L+ZXp48bTHUjKZxybHDb0vVMRynDKJpg0wIwKLkUdFC3R9+XSGybMXr6B6vqKM0VpXk7lyZuCG8AxVh8VFDbYYzSsXENkZfaify3k7s1bFTdnMqQhuOd7CE=,iv:YFOkdgrQb8QfvaYnNUNlP/Etckp+NtLaQihV7EjCg08=,tag:Xk5SoiAICKyvShmSKS/FYQ==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: encryption-key
    namespace: browser-streamer
type: Opaque
stringData:
    key: ENC[AES256_GCM,data:+dUBdA4+ywS4AgS6zn3kgAIz2uO4aJ4mM72Eh9CWGRRaOMvHueIcQQEoFfn5lJNse/3sWz32wXAC6qNY5hwTpg==,iv:PENr7t4ILSqes0m2a8YNLA3HuzNvjPSiSMwLswerMbA=,tag:GEqC4gDwJJkvotgRr1P1Mg==,type:str]
sops:
    age:
        - recipient: age1ase59dknkacq26gemrs9dvwvu8xr8akhfya99lagv5py7c7h7plsmtucvv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsMUFweGhQMjhSMmNOdTZi
            U0xZY0gwM21WZnRoMEhZY3p4SWxUODA3M2dJCk8xQ1IxL3NHY1NqY2xKc09PRjE5
            RkpNL3E3OTFlYkR4c0JsS1NqTktyZXcKLS0tIHl2aC9TNGVtcURUUjJWSkEvNS9L
            OTU5MW13RVdDUHdDak5HRTFjNGx6VU0K2KNT9mIK4AVab0aBu/1L7qkvZBr6Xzd9
            5/tv4ZOMUAXqTg2vONgUhA2KbsDZCgUaDmjMZwryGTu7YksxH9TUXQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age13zs054me9k5h4m8u3hwqw9nz4jg6lkpfmkzqn8mdujjqp76h6plsmlmtpy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTRUM4UXF4U1FlTER6OVo2
            Z1JOaXgvQmdxNUxxRVZ1WUM0UCtWS2owcEJJCkdEN1ZwYW5LSDZQaE5FenlOMEdN
            QmxQR3c0UVIwTHcyeTA0eEF1ci9zYmMKLS0tIGN4ZXhUR1BuNm55Zkl2dVZOMmE5
            bE1KTjhIS0xPK0Q5T1BQUkx0SFBKeEkKx+qdjCXN43zXz6F9JKiJCNzFsf2HfZVw
            sJ9AjSzdmVMuMJ8i592X6agOi3pZz1RudGd4x4+rZdtxPYxmrRjArw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17ttan4es6923ru96408ctjhs2f97mrxq9uw938plgnw6wkstv9cqsaq5cw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmNVBncG1XME5EYmhUVy84
            MkxsZWhiSVZFMG5XZ2NOeTFyV0pKSE5lQUJ3CnpTa01OeldvU21xL3BLZjhKRHhi
            d25PNnpndFlUVG1MTkRIblExNWhVUFEKLS0tIG9xZDI1TU11RDBoNHhtdi9vU05u
            LzJOZ0NGVTFlODhnWVZTZVJDeXFocWsKLMnXZ2hAAYYPHpwwQeFlkx4DBfznzaaS
            v/45WcE8jZ/thS1iSUcXIG3y9jwvGpGeSlFtd/M8B7D62kX+wJp/Fw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1un8ajg06rd075pff8pglkq2q0g020peq7v23qzeqhuchl4y4kyfs0drxyf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWL1FvNDFRWmNkVHFKdTBQ
            MGl1OUtoZ2U3SGZWYlpTQmRRYjUybDFSb3hVClV1QXY3NEpKSkdPd05ZcHN0UWZB
            NHQwZDFlUVkvaDd2QXBmSXhBb3ptOTQKLS0tIGRLTG5BK0hNT3FVT3FlVUhzenpZ
            ckk4RTVqYzNZbUgzd2ZyMEp3V0l3QzAK82qFmExd5brhRIVqTYFg0ZFWiqEBJzY6
            4L7DSCom89CaunPOfldR+S0OO/GcRsK6y9ahjsHS4PiIl4glR3wMuw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-28T18:37:00Z"
    mac: ENC[AES256_GCM,data:OWG85qMJB2mtw9s8skQnkDfhi2SIgP1hX7hITHnePZDNF/99n9a4L+ZXp48bTHUjKZxybHDb0vVMRynDKJpg0wIwKLkUdFC3R9+XSGybMXr6B6vqKM0VpXk7lyZuCG8AxVh8VFDbYYzSsXENkZfaify3k7s1bFTdnMqQhuOd7CE=,iv:YFOkdgrQb8QfvaYnNUNlP/Etckp+NtLaQihV7EjCg08=,tag:Xk5SoiAICKyvShmSKS/FYQ==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: browserless-auth
    namespace: browser-streamer
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:hRqoF+KLQssL4v6k6WnVKEkCsAN29dx1Kp2KfrzWENVhLpVXUsMyvFlH05kicB3+7iUP9elqSvDq6hXVWEjznA==,iv:gwnRl8kUuf09TGk9sR315+RAh7Ehh2EQyBnH5VtE4p0=,tag:1QcuJlc8/h7afZfc01BXqg==,type:str]
sops:
    age:
        - recipient: age1ase59dknkacq26gemrs9dvwvu8xr8akhfya99lagv5py7c7h7plsmtucvv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsMUFweGhQMjhSMmNOdTZi
            U0xZY0gwM21WZnRoMEhZY3p4SWxUODA3M2dJCk8xQ1IxL3NHY1NqY2xKc09PRjE5
            RkpNL3E3OTFlYkR4c0JsS1NqTktyZXcKLS0tIHl2aC9TNGVtcURUUjJWSkEvNS9L
            OTU5MW13RVdDUHdDak5HRTFjNGx6VU0K2KNT9mIK4AVab0aBu/1L7qkvZBr6Xzd9
            5/tv4ZOMUAXqTg2vONgUhA2KbsDZCgUaDmjMZwryGTu7YksxH9TUXQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age13zs054me9k5h4m8u3hwqw9nz4jg6lkpfmkzqn8mdujjqp76h6plsmlmtpy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTRUM4UXF4U1FlTER6OVo2
            Z1JOaXgvQmdxNUxxRVZ1WUM0UCtWS2owcEJJCkdEN1ZwYW5LSDZQaE5FenlOMEdN
            QmxQR3c0UVIwTHcyeTA0eEF1ci9zYmMKLS0tIGN4ZXhUR1BuNm55Zkl2dVZOMmE5
            bE1KTjhIS0xPK0Q5T1BQUkx0SFBKeEkKx+qdjCXN43zXz6F9JKiJCNzFsf2HfZVw
            sJ9AjSzdmVMuMJ8i592X6agOi3pZz1RudGd4x4+rZdtxPYxmrRjArw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17ttan4es6923ru96408ctjhs2f97mrxq9uw938plgnw6wkstv9cqsaq5cw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmNVBncG1XME5EYmhUVy84
            MkxsZWhiSVZFMG5XZ2NOeTFyV0pKSE5lQUJ3CnpTa01OeldvU21xL3BLZjhKRHhi
            d25PNnpndFlUVG1MTkRIblExNWhVUFEKLS0tIG9xZDI1TU11RDBoNHhtdi9vU05u
            LzJOZ0NGVTFlODhnWVZTZVJDeXFocWsKLMnXZ2hAAYYPHpwwQeFlkx4DBfznzaaS
            v/45WcE8jZ/thS1iSUcXIG3y9jwvGpGeSlFtd/M8B7D62kX+wJp/Fw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1un8ajg06rd075pff8pglkq2q0g020peq7v23qzeqhuchl4y4kyfs0drxyf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWL1FvNDFRWmNkVHFKdTBQ
            MGl1OUtoZ2U3SGZWYlpTQmRRYjUybDFSb3hVClV1QXY3NEpKSkdPd05ZcHN0UWZB
            NHQwZDFlUVkvaDd2QXBmSXhBb3ptOTQKLS0tIGRLTG5BK0hNT3FVT3FlVUhzenpZ
            ckk4RTVqYzNZbUgzd2ZyMEp3V0l3QzAK82qFmExd5brhRIVqTYFg0ZFWiqEBJzY6
            4L7DSCom89CaunPOfldR+S0OO/GcRsK6y9ahjsHS4PiIl4glR3wMuw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-28T18:37:00Z"
    mac: ENC[AES256_GCM,data:OWG85qMJB2mtw9s8skQnkDfhi2SIgP1hX7hITHnePZDNF/99n9a4L+ZXp48bTHUjKZxybHDb0vVMRynDKJpg0wIwKLkUdFC3R9+XSGybMXr6B6vqKM0VpXk7lyZuCG8AxVh8VFDbYYzSsXENkZfaify3k7s1bFTdnMqQhuOd7CE=,iv:YFOkdgrQb8QfvaYnNUNlP/Etckp+NtLaQihV7EjCg08=,tag:Xk5SoiAICKyvShmSKS/FYQ==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.11.0
