apiVersion: v1
kind: Secret
metadata:
    name: postgres-auth
    namespace: browser-streamer
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:H3jNFMyN7sMpYfDbetAgLtk/Ux3qfeV2zfXCKoHEh5UkN2IOOMZfeZFcRDC9rklL4ZHouW2tX1YpN33KeeGCEw==,iv:ms4v98dGosvIwGeJq+yYhk2CB+/zypIFhMLt2nnmPxA=,tag:CyJ9CjZT821xAbHsg++u7w==,type:str]
sops:
    age:
        - recipient: age18r3vk6aecpcd69ey7fhgjylg6z37ksfeff6c497mxgv4nwmnyupq4gsfua
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0UCt1dEZrSVN3ZnhsL3Vo
            WXMrWEJTa2hmckxDWUNhV0FNVjRCak1lelRZCktMajArelZPY0J5a2t4TzI4RS9Z
            V2VCenB0V2pVOEM2RU13U3NNQ1o2U2cKLS0tICtyVnZ1S3p5MzIxYVlUa2hVaXFB
            NnRrcmZBcGhvc1gyY1hFRktTTWNiL2cKurt8lpXxXIBXFS6yP5Z5Hriu9e5OPWUI
            CbUMMfvX1G8rU90CtMWa2MP50m1RAqK2Svmz3GxUllmjjn/8QFrU6Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1emw2e5x3d4cu0x4g0q4lrw8nj2fdv0qfzta6g62m5y24j02zu44sflkxln
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwdld4WFNEWEhHNWFqUE55
            dGFtVlI5eGhzS1BCQllHVmdCdTFtRUViY1dnCkdrRFQvTDdTWGk5ejdOSVpPWi9F
            dFlZdWM3Yy94VG8rSC9BdTRDRklPb3MKLS0tIGFMLzkyOU9xK2VobEt5b21iSC9k
            bnZzMjZjdGYvYXNRcXYvKzRlRjAzNFkKfbWcyF5+Vcz9tkwR3xf7MCpYkpHp9svu
            HrnGcTqp9xag9f64m49ba/H5H9xPIU8CjUw1f8rnU/er8iVGsd7t8w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1x9049ry5hz876qratphuc9gdxzuv4nnd06076842zdukl4unvazszfnjf6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2emlwL0F5ZnpROU9ySFlX
            NGhXNytzSGFqNlpRR09tbGZWS1ViSnRFdmhzCjRGWTBicWl0a2dKek9jU2dlMzkw
            TmprV2tSUHc0V3dmQWllRDhBVjBEVkkKLS0tIE9NczdZTnpxOHNGNGEvWTI1RlY1
            N1NvaFp5VGlEVlBncnhFUTdtbmRTdEUK3cyWAAK0dftCeQkS9maLjz1v5Gfm235E
            r3NSfmhIF+LIGaH/LMixCCD9GOKu/6ovHoeu7zBKef50dXRvHY6hBQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1y5txpqz0vyyq03yyysmzuyvuyh8uzzpcw30cp5q3twxnwenfzpvs48ts0z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwcWRKK0lLK2tKM1NoR2Ru
            QmZvN2syNlF0NXN4UzZQcUYwTkRla0R4d1cwCjhlM0NDSlRiS0VGUTJvZkQ4c3NI
            azhTeFlHcFBrTm01dThMT0ZvV1dTMTAKLS0tIC8zWEFHajh0UHNyRk9RYTZBZk1C
            N3RwQ2Z1ZVBFMHpRTE9tZ0EzYmowQjgKvpyqLWp7g8PLQpsMeQ1n1hR1XX252mgt
            YBj5QyzHvxRF5KtB9KnpuhrqLGvGRo9awukTR1YSboLwygYxF53+Nw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-28T18:37:00Z"
    mac: ENC[AES256_GCM,data:OWG85qMJB2mtw9s8skQnkDfhi2SIgP1hX7hITHnePZDNF/99n9a4L+ZXp48bTHUjKZxybHDb0vVMRynDKJpg0wIwKLkUdFC3R9+XSGybMXr6B6vqKM0VpXk7lyZuCG8AxVh8VFDbYYzSsXENkZfaify3k7s1bFTdnMqQhuOd7CE=,iv:YFOkdgrQb8QfvaYnNUNlP/Etckp+NtLaQihV7EjCg08=,tag:Xk5SoiAICKyvShmSKS/FYQ==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: clerk-auth
    namespace: browser-streamer
type: Opaque
stringData:
    secret-key: ENC[AES256_GCM,data:H4KYVNhiU7r00sc/0Kj0e9lXf+vflKt4g82s+CYZxXPOXAKVs7/MDGegcqtw6KkvnnI=,iv:H2xEFZ4vR8lrQVdLg07dQHY6Kd3E3c7W5C5Xhby3lJ0=,tag:qyPgK0Hjony4Akc9gzE9bw==,type:str]
sops:
    age:
        - recipient: age18r3vk6aecpcd69ey7fhgjylg6z37ksfeff6c497mxgv4nwmnyupq4gsfua
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0UCt1dEZrSVN3ZnhsL3Vo
            WXMrWEJTa2hmckxDWUNhV0FNVjRCak1lelRZCktMajArelZPY0J5a2t4TzI4RS9Z
            V2VCenB0V2pVOEM2RU13U3NNQ1o2U2cKLS0tICtyVnZ1S3p5MzIxYVlUa2hVaXFB
            NnRrcmZBcGhvc1gyY1hFRktTTWNiL2cKurt8lpXxXIBXFS6yP5Z5Hriu9e5OPWUI
            CbUMMfvX1G8rU90CtMWa2MP50m1RAqK2Svmz3GxUllmjjn/8QFrU6Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1emw2e5x3d4cu0x4g0q4lrw8nj2fdv0qfzta6g62m5y24j02zu44sflkxln
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwdld4WFNEWEhHNWFqUE55
            dGFtVlI5eGhzS1BCQllHVmdCdTFtRUViY1dnCkdrRFQvTDdTWGk5ejdOSVpPWi9F
            dFlZdWM3Yy94VG8rSC9BdTRDRklPb3MKLS0tIGFMLzkyOU9xK2VobEt5b21iSC9k
            bnZzMjZjdGYvYXNRcXYvKzRlRjAzNFkKfbWcyF5+Vcz9tkwR3xf7MCpYkpHp9svu
            HrnGcTqp9xag9f64m49ba/H5H9xPIU8CjUw1f8rnU/er8iVGsd7t8w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1x9049ry5hz876qratphuc9gdxzuv4nnd06076842zdukl4unvazszfnjf6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2emlwL0F5ZnpROU9ySFlX
            NGhXNytzSGFqNlpRR09tbGZWS1ViSnRFdmhzCjRGWTBicWl0a2dKek9jU2dlMzkw
            TmprV2tSUHc0V3dmQWllRDhBVjBEVkkKLS0tIE9NczdZTnpxOHNGNGEvWTI1RlY1
            N1NvaFp5VGlEVlBncnhFUTdtbmRTdEUK3cyWAAK0dftCeQkS9maLjz1v5Gfm235E
            r3NSfmhIF+LIGaH/LMixCCD9GOKu/6ovHoeu7zBKef50dXRvHY6hBQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1y5txpqz0vyyq03yyysmzuyvuyh8uzzpcw30cp5q3twxnwenfzpvs48ts0z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwcWRKK0lLK2tKM1NoR2Ru
            QmZvN2syNlF0NXN4UzZQcUYwTkRla0R4d1cwCjhlM0NDSlRiS0VGUTJvZkQ4c3NI
            azhTeFlHcFBrTm01dThMT0ZvV1dTMTAKLS0tIC8zWEFHajh0UHNyRk9RYTZBZk1C
            N3RwQ2Z1ZVBFMHpRTE9tZ0EzYmowQjgKvpyqLWp7g8PLQpsMeQ1n1hR1XX252mgt
            YBj5QyzHvxRF5KtB9KnpuhrqLGvGRo9awukTR1YSboLwygYxF53+Nw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-28T18:37:00Z"
    mac: ENC[AES256_GCM,data:OWG85qMJB2mtw9s8skQnkDfhi2SIgP1hX7hITHnePZDNF/99n9a4L+ZXp48bTHUjKZxybHDb0vVMRynDKJpg0wIwKLkUdFC3R9+XSGybMXr6B6vqKM0VpXk7lyZuCG8AxVh8VFDbYYzSsXENkZfaify3k7s1bFTdnMqQhuOd7CE=,iv:YFOkdgrQb8QfvaYnNUNlP/Etckp+NtLaQihV7EjCg08=,tag:Xk5SoiAICKyvShmSKS/FYQ==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: encryption-key
    namespace: browser-streamer
type: Opaque
stringData:
    key: ENC[AES256_GCM,data:+dUBdA4+ywS4AgS6zn3kgAIz2uO4aJ4mM72Eh9CWGRRaOMvHueIcQQEoFfn5lJNse/3sWz32wXAC6qNY5hwTpg==,iv:PENr7t4ILSqes0m2a8YNLA3HuzNvjPSiSMwLswerMbA=,tag:GEqC4gDwJJkvotgRr1P1Mg==,type:str]
sops:
    age:
        - recipient: age18r3vk6aecpcd69ey7fhgjylg6z37ksfeff6c497mxgv4nwmnyupq4gsfua
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0UCt1dEZrSVN3ZnhsL3Vo
            WXMrWEJTa2hmckxDWUNhV0FNVjRCak1lelRZCktMajArelZPY0J5a2t4TzI4RS9Z
            V2VCenB0V2pVOEM2RU13U3NNQ1o2U2cKLS0tICtyVnZ1S3p5MzIxYVlUa2hVaXFB
            NnRrcmZBcGhvc1gyY1hFRktTTWNiL2cKurt8lpXxXIBXFS6yP5Z5Hriu9e5OPWUI
            CbUMMfvX1G8rU90CtMWa2MP50m1RAqK2Svmz3GxUllmjjn/8QFrU6Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1emw2e5x3d4cu0x4g0q4lrw8nj2fdv0qfzta6g62m5y24j02zu44sflkxln
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwdld4WFNEWEhHNWFqUE55
            dGFtVlI5eGhzS1BCQllHVmdCdTFtRUViY1dnCkdrRFQvTDdTWGk5ejdOSVpPWi9F
            dFlZdWM3Yy94VG8rSC9BdTRDRklPb3MKLS0tIGFMLzkyOU9xK2VobEt5b21iSC9k
            bnZzMjZjdGYvYXNRcXYvKzRlRjAzNFkKfbWcyF5+Vcz9tkwR3xf7MCpYkpHp9svu
            HrnGcTqp9xag9f64m49ba/H5H9xPIU8CjUw1f8rnU/er8iVGsd7t8w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1x9049ry5hz876qratphuc9gdxzuv4nnd06076842zdukl4unvazszfnjf6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2emlwL0F5ZnpROU9ySFlX
            NGhXNytzSGFqNlpRR09tbGZWS1ViSnRFdmhzCjRGWTBicWl0a2dKek9jU2dlMzkw
            TmprV2tSUHc0V3dmQWllRDhBVjBEVkkKLS0tIE9NczdZTnpxOHNGNGEvWTI1RlY1
            N1NvaFp5VGlEVlBncnhFUTdtbmRTdEUK3cyWAAK0dftCeQkS9maLjz1v5Gfm235E
            r3NSfmhIF+LIGaH/LMixCCD9GOKu/6ovHoeu7zBKef50dXRvHY6hBQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1y5txpqz0vyyq03yyysmzuyvuyh8uzzpcw30cp5q3twxnwenfzpvs48ts0z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwcWRKK0lLK2tKM1NoR2Ru
            QmZvN2syNlF0NXN4UzZQcUYwTkRla0R4d1cwCjhlM0NDSlRiS0VGUTJvZkQ4c3NI
            azhTeFlHcFBrTm01dThMT0ZvV1dTMTAKLS0tIC8zWEFHajh0UHNyRk9RYTZBZk1C
            N3RwQ2Z1ZVBFMHpRTE9tZ0EzYmowQjgKvpyqLWp7g8PLQpsMeQ1n1hR1XX252mgt
            YBj5QyzHvxRF5KtB9KnpuhrqLGvGRo9awukTR1YSboLwygYxF53+Nw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-28T18:37:00Z"
    mac: ENC[AES256_GCM,data:OWG85qMJB2mtw9s8skQnkDfhi2SIgP1hX7hITHnePZDNF/99n9a4L+ZXp48bTHUjKZxybHDb0vVMRynDKJpg0wIwKLkUdFC3R9+XSGybMXr6B6vqKM0VpXk7lyZuCG8AxVh8VFDbYYzSsXENkZfaify3k7s1bFTdnMqQhuOd7CE=,iv:YFOkdgrQb8QfvaYnNUNlP/Etckp+NtLaQihV7EjCg08=,tag:Xk5SoiAICKyvShmSKS/FYQ==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
metadata:
    name: browserless-auth
    namespace: browser-streamer
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:hRqoF+KLQssL4v6k6WnVKEkCsAN29dx1Kp2KfrzWENVhLpVXUsMyvFlH05kicB3+7iUP9elqSvDq6hXVWEjznA==,iv:gwnRl8kUuf09TGk9sR315+RAh7Ehh2EQyBnH5VtE4p0=,tag:1QcuJlc8/h7afZfc01BXqg==,type:str]
sops:
    age:
        - recipient: age18r3vk6aecpcd69ey7fhgjylg6z37ksfeff6c497mxgv4nwmnyupq4gsfua
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0UCt1dEZrSVN3ZnhsL3Vo
            WXMrWEJTa2hmckxDWUNhV0FNVjRCak1lelRZCktMajArelZPY0J5a2t4TzI4RS9Z
            V2VCenB0V2pVOEM2RU13U3NNQ1o2U2cKLS0tICtyVnZ1S3p5MzIxYVlUa2hVaXFB
            NnRrcmZBcGhvc1gyY1hFRktTTWNiL2cKurt8lpXxXIBXFS6yP5Z5Hriu9e5OPWUI
            CbUMMfvX1G8rU90CtMWa2MP50m1RAqK2Svmz3GxUllmjjn/8QFrU6Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1emw2e5x3d4cu0x4g0q4lrw8nj2fdv0qfzta6g62m5y24j02zu44sflkxln
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwdld4WFNEWEhHNWFqUE55
            dGFtVlI5eGhzS1BCQllHVmdCdTFtRUViY1dnCkdrRFQvTDdTWGk5ejdOSVpPWi9F
            dFlZdWM3Yy94VG8rSC9BdTRDRklPb3MKLS0tIGFMLzkyOU9xK2VobEt5b21iSC9k
            bnZzMjZjdGYvYXNRcXYvKzRlRjAzNFkKfbWcyF5+Vcz9tkwR3xf7MCpYkpHp9svu
            HrnGcTqp9xag9f64m49ba/H5H9xPIU8CjUw1f8rnU/er8iVGsd7t8w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1x9049ry5hz876qratphuc9gdxzuv4nnd06076842zdukl4unvazszfnjf6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2emlwL0F5ZnpROU9ySFlX
            NGhXNytzSGFqNlpRR09tbGZWS1ViSnRFdmhzCjRGWTBicWl0a2dKek9jU2dlMzkw
            TmprV2tSUHc0V3dmQWllRDhBVjBEVkkKLS0tIE9NczdZTnpxOHNGNGEvWTI1RlY1
            N1NvaFp5VGlEVlBncnhFUTdtbmRTdEUK3cyWAAK0dftCeQkS9maLjz1v5Gfm235E
            r3NSfmhIF+LIGaH/LMixCCD9GOKu/6ovHoeu7zBKef50dXRvHY6hBQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1y5txpqz0vyyq03yyysmzuyvuyh8uzzpcw30cp5q3twxnwenfzpvs48ts0z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwcWRKK0lLK2tKM1NoR2Ru
            QmZvN2syNlF0NXN4UzZQcUYwTkRla0R4d1cwCjhlM0NDSlRiS0VGUTJvZkQ4c3NI
            azhTeFlHcFBrTm01dThMT0ZvV1dTMTAKLS0tIC8zWEFHajh0UHNyRk9RYTZBZk1C
            N3RwQ2Z1ZVBFMHpRTE9tZ0EzYmowQjgKvpyqLWp7g8PLQpsMeQ1n1hR1XX252mgt
            YBj5QyzHvxRF5KtB9KnpuhrqLGvGRo9awukTR1YSboLwygYxF53+Nw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-28T18:37:00Z"
    mac: ENC[AES256_GCM,data:OWG85qMJB2mtw9s8skQnkDfhi2SIgP1hX7hITHnePZDNF/99n9a4L+ZXp48bTHUjKZxybHDb0vVMRynDKJpg0wIwKLkUdFC3R9+XSGybMXr6B6vqKM0VpXk7lyZuCG8AxVh8VFDbYYzSsXENkZfaify3k7s1bFTdnMqQhuOd7CE=,iv:YFOkdgrQb8QfvaYnNUNlP/Etckp+NtLaQihV7EjCg08=,tag:Xk5SoiAICKyvShmSKS/FYQ==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.11.0
