-- Per-user stage limits.
ALTER TABLE users
  ADD COLUMN IF NOT EXISTS max_stages INTEGER NOT NULL DEFAULT 10,
  ADD COLUMN IF NOT EXISTS max_active_cpu_stages INTEGER NOT NULL DEFAULT 2,
  ADD COLUMN IF NOT EXISTS max_active_gpu_stages INTEGER NOT NULL DEFAULT 1;
