apiVersion: v1
kind: Secret
metadata:
    name: clerk-oauth
    namespace: browser-streamer
type: Opaque
stringData:
    client-secret: ENC[AES256_GCM,data:U00qtIu1HMZGi+vaVfB269yAiiFNC3HuesHyrehlcA0=,iv:R22UXcUbXjpmmoYC7oOMdfopFs33QBpdvTQAdjuVpWM=,tag:hYgH1TIeUsjTzXec6lQnTA==,type:str]
sops:
    age:
        - recipient: age1ase59dknkacq26gemrs9dvwvu8xr8akhfya99lagv5py7c7h7plsmtucvv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxUmRPRm1GeHFjdnNzVE4w
            ZklNZzhzajdNenJyamp4Y01IRlhLa2t4NlJvCnNXUWFuSmxDMFcySnd6M3h3R0JY
            Y1ZuK2lON3VkbGRBTVo0MUwxR0Z6eFEKLS0tIEtkWWlmVCtmNTI0eXBUS1l5ZzZ2
            bFRpSFhpcXZYcjlmbTlMV0JCc1VJcTQKcfDNmBbYXvNb34JwGr1uFtYMQB4OXdFz
            BrpBdeyWocQDPOuv81RSwzdJGIebU6TlcwijR7CLL5j7fhyCfQDhpQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age13zs054me9k5h4m8u3hwqw9nz4jg6lkpfmkzqn8mdujjqp76h6plsmlmtpy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1NklzZTRrNWNMbUNpeVE5
            VjZrZG5YbDFqV1h2SHBCTWh3SzQzZk1wZ0VBClNwSUdNUXFjRU5pc3Y0YW5jYWtt
            aDVUblY1NUl1bGNTVjhpQXdzQ09QMnMKLS0tIGNkelQ1YTJlUk1PeXdmdjRFeTI5
            Z1ZZZFJqeHpjYUVLeEp3VFZycU1NUFEKecHhv0OQaJLO0jVg9LxmkIPZBnreSFWH
            +mHpYHzQQzE8lAG1u6wI1TixT5cMbJSv+0Xk2ZxvSfyCqHvJzjP4jA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17ttan4es6923ru96408ctjhs2f97mrxq9uw938plgnw6wkstv9cqsaq5cw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGMjVYd2FhMCtNM3U2Z3pB
            MURsMEtUY1FqdmJibDVyYndBQWR5OTlMZVJBCmpCOEk2bExFREpML0NOc2k0R2Qr
            QWRmbHBZdlVZaW5PWCtUeHY4UGh6aTQKLS0tIEg1RkxiRE9SdVFxTGZnRkZCdTdS
            VDhNQkF2TW1kY09senNuRjFYQnJHQTgKwNPmYof49rAZQYbg+Job1zzMqH5Sx9S1
            Twe17ah81FCJiWx+pHUq/gwdICvIK9LLanvumX2OKoYW+BZEgGXW6Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1un8ajg06rd075pff8pglkq2q0g020peq7v23qzeqhuchl4y4kyfs0drxyf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvN1ZxUHMyYjZzL0Rnd3BQ
            bHRnNVpmU0VSMXJqSUJtQlVCT2hWZEtXQlFZCm9lM3hJemVPOFZ1ZGxKb3hBd28y
            cU1ZdHN5TS9XQ3JxN29jbFA3QVlxZXcKLS0tIDVzUys3elROb2lGMWhjZy85YW0r
            SzV5N2tSbGxCL3QwYkRXbll0T3l1cEUKHs/9LSQPPwyMiK8id6/NXJX2PyCRLHfw
            7x5Lx15677+MNweGS6V2wlo7WzShImGHc2wLGLnsxVIfg3VOdRgslw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-02T17:32:52Z"
    mac: ENC[AES256_GCM,data:iM7+jqpTxUQNhuP8tHxwIIOvn/v55VpuDbXXn2if4kocJR5GTpJVcLhQUomUyJj9x9/OTge+yP0g2SUXI74qkDifRBfXcuW6ouSX+WuGciPKZzYvs2wpnnlQoSgpm0RFSHlUxu8THHwIlfHyORk3wGxOpGI5nXhR8oTkJ6lK6x8=,iv:Bkuzf4RXuW7znkCjf7iHGx2fQBtY7BY4L4081bZ3DYc=,tag:v2SUjYnPOFg9AHoDc53hiA==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.11.0
