apiVersion: v1
kind: Secret
metadata:
    name: encryption-key
    namespace: browser-streamer
type: Opaque
stringData:
    key: ENC[AES256_GCM,data:VfkOv7yKK7D3S3ckX/0BjOePMG2GgJj1WKAX3jE38ck5bJ5zNLsRJmK8oxB5/AzRklbDc4v7GebLSuNkCAiTrg==,iv:JCdz3yaNnVfVE+aLdL/S/QtV2Mdnz2IKdurC+oEwXIY=,tag:GWfYPoxa0UJEFQEHgQv0wg==,type:str]
sops:
    age:
        - recipient: age1ase59dknkacq26gemrs9dvwvu8xr8akhfya99lagv5py7c7h7plsmtucvv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZSC8rMndhWFdrUjhCUFhF
            MkJScHFSSy80NUdGaVB4VUI2UUI4SXRMMDJnCmd0blhtak1IYzl4cHptSlNFOGtn
            UE9EZndNTUY2MGRPemE0QXBja2pPMkEKLS0tIDJnODhHRzU1V1UwaWNnMW96Tzdo
            OVlERUFFN3RtUnNqTEs3VXF1eHYxL2MKgb7aSbJ7lx8n/aVUvkRfD8QPvR+RRaf7
            +UKJ5+myahpToY009WWgpFNCESx9PyWYl7/XiJtmnrz42xLRk/Fi3w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age13zs054me9k5h4m8u3hwqw9nz4jg6lkpfmkzqn8mdujjqp76h6plsmlmtpy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtZVVtU01lZHp6VlVCSmYr
            RXFFSDVCbnRnU2R2Y3JmZ3BhSTBwZkdqdHc4CjAyWkVvWUpzNzNxUStlNElKNE1E
            WjQ3Nnl4NThRWWdDTGpCZEJxc2RZbHcKLS0tIGJoUG1EZkdNZCt1ayt2R3lLeDVq
            RzBYcTdJOTV3ak1pWk40OVRTQm1iSWsKwAyuf/SXr11KgM44gK9CyNM1nMxHgPhq
            EymeB5y8++EW5FL/uMyWdmtsFkUeBNEdUhtqBxuahfCe88n9Dd/JCQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age17ttan4es6923ru96408ctjhs2f97mrxq9uw938plgnw6wkstv9cqsaq5cw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFZktJcHloY0lFc2oyMFZY
            K2RScTNsbnlNQlN2UW95a29nS3FFNUpacFU0CkFlK25UaEtDUFhuVHJLQm9zaklY
            NlNOY0RXQXF6YTRsOWJqSkpiaXJxUTQKLS0tIFNvZ3pZZ2piNmZQWEdwYXAwdnRz
            QitKK2lnVk1oNzlMNzkzbTNLNVpSa28Kp69Nr+kXhZsOvMVHgdoZU5igtV+EgKW3
            tR0ylM8tQzd58t3jN/4BDgleVGKXUbVqVd3cdeNWYRCKo9rmkEWldQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1un8ajg06rd075pff8pglkq2q0g020peq7v23qzeqhuchl4y4kyfs0drxyf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYUTV0TDRiZnh5VkVOSUZY
            a251ZmgwcVVValJybUtmOTdEdXNNb3dDU1cwCkgycngydGdTVk9yNWZuQ2E0eThJ
            akt3S1kvSGhPMXVTd1kreFRzQ2Nmd2cKLS0tIHpRQ0Yyb3YvNU1uQXpGQ0tsOUFp
            VndaMFd4eksvaFhpdjRqejFRbWZUYlEKZCW/QaXgIuMnNfliDlU+ku14DDVx3geH
            MLnYifa2q84/gWiZlqoXVR6zpEcYiV/YhDTRL3wG07lZ8Ww9MGQxVQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-02T03:20:22Z"
    mac: ENC[AES256_GCM,data:HAM8NIQsMZb9z5vWL8NNX5j4QH0C6hJ4p/9Abd1noqWJbQMKG5GT1uj3nVCEC34B+p6yoqs6TLgZqojlDBXiv2VmRdJd4Ywrsq/gSCZuxyyWVMpB9iGXEJ5M3OWK8Sj0mD1A22GzHXaixRrPGQDMgi2iQrrtmPsXcilmRjtqphE=,iv:DfUwtkyU8ZKZS9iyUrycqngoWPDHCBtf/ffpY9S5g5E=,tag:P/5cJkDlF210RxASbs+mrg==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.11.0
