apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - infrastructure/postgres.yaml
  - control-plane/rbac.yaml
  - control-plane/deployment.yaml
  - control-plane/service.yaml
  - networking/ingress.yaml
  - networking/cluster-issuer.yaml
  - networking/traefik-config.yaml
  - monitoring/streamer-podmonitor.yaml
  - scheduling/priority-classes.yaml
  - scheduling/placeholder.yaml
  - scheduling/trimaran/metrics-rbac.yaml

helmCharts:
  - name: scheduler-plugins
    repo: https://scheduler-plugins.sigs.k8s.io
    namespace: kube-system
    releaseName: trimaran
    valuesFile: scheduling/trimaran/values.yaml
