apiVersion: v1
kind: Secret
metadata:
    name: clerk-auth
stringData:
    secret-key: ENC[AES256_GCM,data:3fmPzSMX4O730RhUs4zmrNNlzEkt+obsp9vuDVHOIAbhn6EsygLPP86GU2ufbP3frvE=,iv:03FxNo9pUwMB9dyBYBOicm1b0u4r9q88RTyEUliAl2A=,tag:cBJ0TE0Hv0dp/xuJ39BSGw==,type:str]
    publishable-key: ENC[AES256_GCM,data:rNSbFux1egK9STOfB0Bz5T0jaLy+1oZLXpe1px2hE9oi3xfHg5E301PXttIlkwdcck/Xm3Vnuw==,iv:mzzjlfZr8riTqXiJrDsw33KcbY5IJqGYyvXvbxxR/H0=,tag:ifsg657y1CH1lPtq3ZjTiA==,type:str]
sops:
    age:
        - recipient: age18r3vk6aecpcd69ey7fhgjylg6z37ksfeff6c497mxgv4nwmnyupq4gsfua
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFdktIT3BqNCtVWVFpTDg1
            YXkyU1o3OEpUeG14V3kwUEcxczdYTE5Udkh3CngzOVp2Y3M4cFVXZmdwemZhKzlw
            bHB2YnRLenVJbFMwVFNkbUtieHo3NFUKLS0tIENnSUE0Y1JpanMwOTJQMzFZRWdZ
            dDd2ZnR4R2x2SXQ2SmxDWGlsU25ZN0EKRxR+h2jKvv43XCQwod1kODzV3yleVU11
            k0hGTVr5mBJlDuCe1I4liGsS/aOl5IoaxyM+e34FwAdIfgeEKYJLpA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1emw2e5x3d4cu0x4g0q4lrw8nj2fdv0qfzta6g62m5y24j02zu44sflkxln
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0MHgzLzhmNUhGbEVzdVU3
            OGhaemkxTldGdVJ0UzJxT3hJd1VMR216K2hrCmxkRHVaMFROVEhDRTZuT0VFdjFm
            SWFUU3o3QkJoRlBxMGlZZGZGN08wTGcKLS0tIGxOUCtITjVFbVFkc1F3RmN3d1N1
            eVVDdXNDRG5zc0Q0UHRTdHZxRk5vbmMKdLcqWYq5K3usS0X8WdviObUrbmRfXpIB
            esGONpFLX+Ja10I2Q8uXBi78RWTep4Z83E1sk54iZEr7OAU1wNfspQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1x9049ry5hz876qratphuc9gdxzuv4nnd06076842zdukl4unvazszfnjf6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBibDE4a3dWR0R3TWI3Sno5
            cnl6ai9oTlNwN29tL1RVRnN0L1FnbTlxTkdJClcrUGhScHNXK1BSTDJ6SUlQUjBt
            RFRvbmtNWVJJWmQyVElENURlTEp2aW8KLS0tIE1xNVVWZEs4bi9rN0FjVEZuTUlB
            c1FpdndvWThTekZpZVAwYkN1UWl6N28KAGbAidpIomHwSRFtv8JBa1NsfncIHRDt
            SVtsLAG8WplTIp1PbV6tqK6HzhrEFy7HpB9FlcsPpohln+EYsfc0PQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1y5txpqz0vyyq03yyysmzuyvuyh8uzzpcw30cp5q3twxnwenfzpvs48ts0z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLd0FDaGJiT2psUmVjTENJ
            UnFCV3hDUGx1T3hJOGtRT3NpMFVWRG1IcG1FCjR6OVQzUnFlTC82TzJpdndJMUwz
            R2xZOXBUY0NjL3VyTWtHNVJOZHA5N2cKLS0tIGRxbHNqZFEvNll5Z2hBZVZVbFk4
            TElCcnZMN2pCUCtlaVVodVoxZDZZYVkKODUVrFPxrZQXyGmKU0iwzfUGHBPiP3U0
            KMQ0FW/ukxUYR9VhSGPO2+f0bauslr5yPNYF3DiuSB+WjJqI01SarA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-01T19:38:54Z"
    mac: ENC[AES256_GCM,data:ql+LTUUWqPsb1NOJJK1+LcwgdwYaPs0iAf8upMHqsZYpjGntC2vMZ/fEdCKjBbsEZIM60bqnpHW8btfgOESBYVXfTZ1go+42b+V4ewWiMkUJHtqodSi7hDnCiMKw4B9A8NB5yWDh6eWHpez5fATXtGpGHpPVu8H7lVBxiY81OaI=,iv:s8yeJg0fSAs29Mz4cLfhf5StiptCpWpLs77EMZAEFVs=,tag:c5UBy+9WtOmOdhgucNIA2Q==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.11.0
