apiVersion: v1
kind: Secret
metadata:
    name: clerk-auth
stringData:
    secret-key: ENC[AES256_GCM,data:ZDvgI7lnQsSot5095rmqx32bz8qdPswILM2xl/+TYcPoY37pwA4OO7GCdT+ODRocbqM=,iv:1OJX2xHEBFBNouQzr5TUNtO9v3DLw6grKE8DSOZOmnc=,tag:tH5SFIOTkDZLuTFaDAGXuw==,type:str]
    publishable-key: ENC[AES256_GCM,data:HmAtA3+ijVKuKyxcS0hVl0hVqXr6t3fLuRJzkj8DKj9LaMomQyt1/w5fU1DllPy1zESlxYC/4w==,iv:Rfot9sJq5RYxq+tv3hnS95/B566WoESGZw5cQflNGaM=,tag:D4IuVPNyw65TvlZT4hcbcQ==,type:str]
sops:
    age:
        - recipient: age1mulgnkldp0c6daway8auvrajfj7gmglr4tfhrnxjrhzg6pqump7qcamvts
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJQkJZZ2NBdFh6Ny9XQy92
            S1hvenR6Tys2OUExbWZ0VjZKOTg1d21kQndZClpLbWFYbGFQdGcxZUFPUFpZemF5
            bG9Rdk10WGxKVVhlaVF4eGpnMzZ6SXMKLS0tIEdBVzRtTzU3dDR6Z1YwQ2pGaUZU
            bmVmYkM0NExFVHhablZ5aUVDaHV3RE0KYYs2mo/7ARvTsbsvfkxDCQNYYjRL/zGL
            w2J1Z3Zf7hJGB0d7nqNcwvqFd8Tn/TUhAXZR+oIODBd75E9+RyhdaQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18r3vk6aecpcd69ey7fhgjylg6z37ksfeff6c497mxgv4nwmnyupq4gsfua
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3Z0ZCUENISm1tanZtcHRu
            MVZxNVBMWXlRNVlsVitXMmpnaG5Fd2x6M1FjCjluWUV5RU9sUkxqOXZwTUhYeDE1
            ajY3aUxqTTJsZ3BNVmdPczdPeUJuQzAKLS0tIGVkYVdjYWNqUkpwS1FleXFYOVhy
            RzNaV0RwV3JTTHRlUUVGZ284VnRQeFUKBKb8ZykN+UHc/p9JLsE7KuGiWTSEWDqL
            dIPlTKiuaRV0fsskMt9YbR0jSNKxFC9kMxLgIc+mosaOrTjSOBfp7g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1emw2e5x3d4cu0x4g0q4lrw8nj2fdv0qfzta6g62m5y24j02zu44sflkxln
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPZWk1MGtjYVl4OFpyY20z
            Tm1Gc2FHSE1UKzZ0OEM1WHZ0RithZyt2R1JjCldTNmZJeEFLMVRhK290K09mQzRu
            K0JmWmE3ZExjbnlBMzZnYUIzYnBkZXcKLS0tIHpVK2tXajJ5OXFrZS9GV1FJemt1
            WXcxWCtNZ3BDNEt4amJyZGVoalB3cFUKiYvwnp628jIf7afsRvp/bjF5aAP8RjOC
            jUCIjkqnYhJ+HP+RL2UwcbvDkr2/HXF3BUff8pDWGOLJt531v4CY1Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1x9049ry5hz876qratphuc9gdxzuv4nnd06076842zdukl4unvazszfnjf6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjVTJ6WHZrR2Q5aUljNStE
            d0xuME1XNzRUbEJLVEtBN25NQks2RkhLVlM4CmRFQTRTdE42ZkNXeUFSVlB6VDds
            Y2VaamUrb1NvUDlERmJHTnRzZXd2ckUKLS0tIHoySWdDcXYvWHFveFkraU82U295
            VVhYZ3FrN3dQM0VhNWVyS3RKQkZZbk0Ku4j4acAOXW3XYywoNyZLDrCWoYYa1u2e
            H1uVb8X/CXoLqJntWaXeejJS0dFczQalKZe/v9DClfUVGbQPPkmTXw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1y5txpqz0vyyq03yyysmzuyvuyh8uzzpcw30cp5q3twxnwenfzpvs48ts0z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGRytXeFVnaGNONmpBMHBm
            YjJsdGtNU3ZzTlIxSi9jSTN5bllTRDZJVUdrClpxZVdTNzhBaE5XZnpzY2F3OUNC
            ZkN6TmhvZEMvOUJYanBKOEZPd0cvblkKLS0tIEh2cVFPdEZtMnJxdDc4STVMbmlw
            UXRsUFpnd055d3VBYkxCRFhHYzRERkUKov1pbPS/jxJgFQ4p99qpIjyxP7IX5wVK
            KDLVbXrQpQ2gIi7/7AV61m352VQTCeI6zKti+g2gJ0zOZbcUGd2Wbw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-01T20:58:42Z"
    mac: ENC[AES256_GCM,data:Iylc6dfcuWlOkEeZwbyyZ0r1pT9R4RWD4QyQ5VatnQfSt3v65q9eNwwVohTSSnMjk6Or2ONCx4nTnhFebR3rr0baWhFp7T+yOxmDcWG8wdSB5YmC92saa+qjnTGhU0+sT+mzJwijdBRKDRgzLm8hoepNMIlpsYxX9T+6tW7asWs=,iv:IqyA2jOaueyZbCbQcVJSy4iE2RSABTl0SvFbEmF0cBw=,tag:9Iw3YpxXPs5Ms8WG3XEBNw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
