apiVersion: v1
kind: Secret
metadata:
    name: dazzle-mtls
stringData:
    ca.crt: ENC[AES256_GCM,data:ociUeWUm3XzZlw6ZAcO6dapUTgMptTo/iEBRhx7wRqVsgB7eq9nDsjXIXv5ZiKZoXHuays5O8IoxKUnR6TXEd3VPBi6KhlOXBqOa40NWgWXbnz/0bhwkxtLKdOpWSNfk425Y4omOW3HN1dz0b6vXxDNYYVmHumF6xk6Bqbm9ZBbohsNIZ7aIDgD0AMlIAky6td+5PSZx5WmExrlKrFgGeDyvXKCyAUmEok8A72yufKJSMZEQQf1xC+n6knvABJ1s87d/l06XoY16sc2B5RRZxNsM0oIttOy10/pN3/ZEwFmX8U6dKoc7U73LZue6ePOMEmbS99ae8JgLJEGhqkHa+9A+y82pc5jPStR9XPARKiCgT2mba3kxNakuIFacFhe8/XCrNXsxsLvAHsP9cKH1XP6cAS4GJpgn97PDKxp1b7q3rZQe3ya0bj21HBZbpgHRQHgGAxem3DggHw84EVE/1pRz8IaGHKm2W9sP14rHnYF0VfEOE4sQfUFAz829I4ctUD+ZKsdYoUdB5pEnMutFV4Fb26fY1F6z9gL+h55/y+V+coQMk0H1e5QNKcG49kbOefsF5tmD2LOCYMSe8XPtMDfF/vC3T4sC/7b8XXr3298+ayARM0Z8HPl6FjvhIKFAaF+Oq2nZoXjQOqc0nqrdfHqmrRnVDSyRk9iuTjZlbtTDYIZnzQStey8sunH2Enya5WNCJ0BZRWv/dUq9Xz+8SzjyM5nL8KLahtgg2H7Ejh93cDmw6nRhq94o2rmys4REFlyO+ZxU3t5pDSmELMsE,iv:zMLwkS0ZyclFPLye9tFl8lD/IlEuA7SInP0B8QeC0Ug=,tag:71qYlJf6o9uoX4dFjkxyKg==,type:str]
    server.crt: ENC[AES256_GCM,data:nxbJF9zxyeYhdAhCcN2MsrfCuhQQidBgJKts+d4ySpnXW7eU0fBLmWuZ9H8Nj6CQ1xJAO8EcCTimzUWcRBCGx0wXEdoQDi7WsQLfL2bxP/zhS0rpRAsoW+HeIZc4No+y6XeA2xykdU7ZFIFFrdRxxi+2kXXRSbcqjL2hmYNLbKDxmyCxTTHglO4FfuSFtCoWuWiouryDfzeCyM+9aqZhNNHvw6iJGTPbnHMVyrjvC5OA9RR07M9w9TZwkqZuPYBQZxx7aNxaAKoTtUWjQpeytOS+87IoQtnMayrnF57OnNemd1WeWo8Ih2s7kKywbxDzYZ5/zRLn8NqEiqFGjMKeYVKeEdd4NSMk3rUCUjFKRMUccFtQLAeFmKDRVuXN3dxgnbzCkSmcni7z1ufYaJfiOI9JDDe+tS75ORMk0vKE4r0pDbEMEvkt/yCC2bHbjbD1tN7HBVkeiCS2yyU8pUHSeCpoLGh/s//5M3cTi7wqJS8IPoIr6I6Nx+YVmFfE1OKlmlNg4FQGIh0dCyottxBcXSrcMCA/aIMz3WtHEW/RpGiGbSn8yI3t7XW2BYXD3X5nNwEUOle7lPHiGhMfjToesziQ4zHN/Zxy+TNISGfBQ3KbhvR9lzAohSdzwlmg5irDvOSwO5+SdSvYrZhCjoYH7GrbyjAes/k0Z8go/SM7yIqR6e28dpu2kMAp7gQk8gOKxjsGDuE3Jo62X+ulN5DzXgbwdF2p2jGqCfvRf/A5zQTdF184lyhGctcV,iv:nB4lX7OT/BMoWdfr174uoEITlhu9jHD5UtVc6dGUvIM=,tag:y59ufKkZd8zr36chgsgBpQ==,type:str]
    server.key: ENC[AES256_GCM,data:po/hj45HXhNLz57lxbk/Ij3NRLHUcf1ANIc3OEzAqH6wKsON82qu/OfjhhSeyPLL7zRghaCEulPWDjM/sc2nlw8t8lABs1UDWJ6sHFW6qJeBnHDjvdnE0wzPAp1WuDU7p7iyiV/sFMifA4BCdVge0NG3CjLK7V7Rl1z2oaNtzrvx/6smdAg7iqEMkbLxsiEoClalCIkZcEWT+kxxZi7wAzaFDTpevgngz1LNfetbkKpD+XnQ5r/PX8tj1wO2qdW4bIxcYQIo3JZNY/i4oei1VWoI44PWDx5wCu8IzZa+f56m4gJ7lai7pj/r+Sw3gwHWdw==,iv:wSCh7++hXIj+nV8OoM2YA1sTDlAV1X7lJhHdHQ+ecCw=,tag:SDhAhIrK2SozMlJiPzFElA==,type:str]
    client.crt: ENC[AES256_GCM,data:EvWP93tSHYRKIIbCzm3yvNLNdJphIBQXQc4VZ2j0VMryM9v+mbl5MC82d3YMLqAS2vtIgxsMJJ/4ODuAX1Fx9y+8DJVv8pyRTc992kJHk141AWXJQIX1ASbAkPZoqiTq1BCsYL/iyfKx0EBaT3lgBSEhJoF4pH2kBNSjjN3x1H3Ew387TqfkJdryZnAlE+aIZ0l30r1q6h2nd8H1fhXO3zkZpO/2IzyWC5O5M5ZxS/ukagwvQe6+BbqZuL4zu7JyRpKkekS07lP8zZZD1fiaV/p3sI70hKVPjUyI+qVxwzzWljt7Kbxi7mztqZlF+W3LItTfRF9sphDsMuYa7GLkBw9TeA42TLLqIyioPLFOUPFlqO92Lvo4E/Tx+6sjtqhmI1PZIfEPDr2v+kas9CbNCpA98v9rn2ia4E3tj+n3zFS7SXMVuRJTOJJ+zpxlnVRMOrkI7x1bDaFIKBRvVRGyqcY6Y0ztqAjuvge2mUR1DpgXzqVOl+GgLXoaMylV6dG0zJN6mlcGfLQgqWfl+lUb7L6XaLBVkXq87IkRmg5b2mPlg2YkrT1+kP5YmETzjlMKeIE9bXqXlRxExOfnhSfBRfBNZ8j+UVJOUKwwd74+GUVs2EvREM2M1E6B3P12Wpzb3vVRwMU3N53SMJopW+tqCXhSMJvpI0wg9Q9oZKfQkI/fAXpm4cncmhDiGMGQ0NyXqLVMcGk64ohiLBfPQRDu/OgVyR/9c41uYPBcZUI7rJ5nJkk/SSGEXAS8,iv:nSKGD/k9HvVTD+yq/vbeqnDQtWZJF72bOeh7FVFoTto=,tag:3ZW13NaWATgdr2AYnoNh0Q==,type:str]
    client.key: ENC[AES256_GCM,data:5moqQDRkEZhJTMaxQgdUc4HqHo5NHLJqPZf87yBiBI5VLu0a7tZkHVJ5NktTKxS4Y5hz8epLLuCjCoB2acmHSuXiSixS5UJyQjqt/CAFmYqEDWCamriYY1Cls9qUNDP7edbQC86N0TueN//ZR/RNc3iqRAW69ILzOKVZMhrSqCj7riBdLpjE5Y4xjWpHVIYJcxuLY+VYvfxsCran7PGJeNxXHlHNYb4+jTgabJgsTSO1myjaak6tDydgbMuHb17qeeLcwTFNAQmfSKRocdY1MoYLCJFkh8FGUVI2pqOdOkMlUdE1myD/SNVY3dX5E64OKQ==,iv:Okg3gD/pRTFhHnLSwHJKWv1m209uTHb00lvACbON+20=,tag:701oagreqzEB4cygC2gk9g==,type:str]
sops:
    age:
        - recipient: age18r3vk6aecpcd69ey7fhgjylg6z37ksfeff6c497mxgv4nwmnyupq4gsfua
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHTmZVbXZ3Z0c0RHF3VTVP
            anVjYjRnTFJDdGw2SWZ6STJteFZIek9CRDM0CnRVeUo2aVlkdkZoajVZREwwRWdP
            YXFVUzZtOWYzZVVRenk2SmtUOElNdGMKLS0tICthZWxIWXNXNERzaTl2akhLQ2F3
            TE96eUlvSkpjT0tNQ2RUUnlCbDlldFUKI4jhIUkVffGlsbq4015hM19fHUTsDLwT
            GmxJIw7bBN+DkjYbdmcYX0W/FVBc+Nwb4xa9kXOZ0xf6aHIcDFanPQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1emw2e5x3d4cu0x4g0q4lrw8nj2fdv0qfzta6g62m5y24j02zu44sflkxln
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWNDZxeTR2bmtYNmw0RXFr
            Ym0vNFkzMDE0aTBaUWhYeDl5MXFmVW5tbWxJCk42M2wySDhXb3dLVlRKRGI3cXpl
            TjFRNE83eENicjhOc1RzVVhoL2xQR2MKLS0tIDNyaDJyOGo5OTJRL0M5Wlh0RFg5
            TWdzcHhJRHAvU20vUnBMQ1lES0JsbGsKtjDYWWZQKZ3ox1aYifQnk3z5D8oz2wlQ
            gV7Y8H3WxWGBaCpMPP2KPPlV/Xy0dDZIEObyyS1wNiif3u0Rp/WalQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1x9049ry5hz876qratphuc9gdxzuv4nnd06076842zdukl4unvazszfnjf6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5RUxIL0preTZnQ3cwdTE4
            QXVvQXRKb3VuMkVyNld4V0pSUTN2K2MwSERjCjRZd04rSlBFS3pYcjVuanFCbFdO
            ZzZENXBVNndlVmJORm1jeVVnNUVjVmcKLS0tIFhMUEpmZEtMNjg4eU9JV3V4T0sw
            WmdFRTZDaVRnM0I0Wkh6ZDQ3cUZIaHMKLvXZeZubyi2NWfsMxk05ozNomrWyI4GL
            TEMjBjGNnYRB24xr7l5LBG9UHXrJ1UqBAZUhtJh7nr5UqlqCbll/Lw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1y5txpqz0vyyq03yyysmzuyvuyh8uzzpcw30cp5q3twxnwenfzpvs48ts0z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3SU1CSzhuVlJrbkdGN0Jl
            RWhYSjJmWGI5bDBhRENqUWxsaVptY24rdGlzCk56cDBoS0UrbFFoc1VDUk51cUV4
            c0YzNUkrdUU1MzN5TTVCdnY4eG5WWU0KLS0tIDZKOURDc2hhclZUZjBlWmZtQTJO
            bnhlUVVUb2d5MzZESGVSaEJldWErMEUK4my1yzOwB4e+uSzRxuv2qPU9HRSlkacy
            crXEUxCQkW+gEjp3BTYdL7HDZLt9qjwOj5C1cGA8czlEt5FBPbK7+g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-01T19:32:32Z"
    mac: ENC[AES256_GCM,data:7+ue7P4wAvBgcplmQs8AOeQuqN6CuuVWxSXGK13WX2Woh93uTJlCLy5Nd27RK8iJ10S+wol/x03wiMOcQlf5c1hvzRyioesPQTMCrMREw6fX8+hAMStE5EY++bXcJwNqUAr+obkdmcNZN2+f352Ewg618ELI1QtJiOV6pko32og=,iv:DGo0VREgKtVHEzX37whGjQbNuauXHAeWzCcdSGCI9GI=,tag:4z24jEF8tk9XNCOhUPSgXw==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.11.0
