apiVersion: v1
kind: Secret
metadata:
    name: dazzle-runpod
stringData:
    api-key: ENC[AES256_GCM,data:IYo2bfH7EoRMR5hNuM2MVDrP2wlfVA/cUOqeCnjrSyHC7F8r2VkYxgBO0b9P1pVuEJk=,iv:uQEkmJKHSRKqh/jXFywNhHlC4jM6HoEYc5F7YljG4T4=,tag:in0vjFAuSNMEdOKz7PoiSg==,type:str]
    registry-auth-id: ENC[AES256_GCM,data:kM5pf+JuoJqGqMs1BaENUHxKqHPv7DX/9A==,iv:k67J1yIRxCyxjidftyOLDJzNo/kp1uMDjRxuS/nwJMM=,tag:sAU9oCzGqGAe82eAa5hC0w==,type:str]
sops:
    age:
        - recipient: age1mulgnkldp0c6daway8auvrajfj7gmglr4tfhrnxjrhzg6pqump7qcamvts
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRSlM0RFg5MEVEL1d5RGYy
            RHBOa1JUYjVGV21rLzNjZE81UFlFTlByWEd3CmY4eW1Ia0w3dWNKQnV2eXpWWGNI
            RWhha2dzUmFIbTRtdDJnSGZhVzBzTEkKLS0tIEJzZ3FLK0hTWWlPZjBTYUU4U1li
            M2NOTmxjcjYvRWllY1lDTGtjK3MvU00K+po1gK1dS8B5OdagOfp4EzflF5ARWliy
            7qQm7Wf4AvQOuPAOI/dmaa53DxVdhI5fVZ8FmUIELO6bLMoiev7t+g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18r3vk6aecpcd69ey7fhgjylg6z37ksfeff6c497mxgv4nwmnyupq4gsfua
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsTHo5NXh1Z0ZNUEljMWNw
            b2tKTzZUTUVCREsvTDJ6cUNKTXkrZnp4VVJrCkZEc1AzL2NKWmsxeG84M2crc3I2
            Nm14cEluckgyaE0vbDlDNXBqTy9JKzQKLS0tIFNMdE1YdnVZVmdQV29hNCtFaTdG
            QmxBMEN1R0VzWmlYV0Z4ZmgxYlRMMXcKrlXWPWM5LOguhXOQW3+15mX33BlrS0j3
            KqjN6RTPWy8JS6qnrPbKRUPpOPabjD32lmwJhDSGFYTbzp4b2/C6Sw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1emw2e5x3d4cu0x4g0q4lrw8nj2fdv0qfzta6g62m5y24j02zu44sflkxln
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYd1ZaMTZBZSs3bWdDQXBp
            b3lJa3EwdnBweDJnL2JvRGVobHVQVFhDUUhjCnJzVjlBemkzcWlUcVNBaDlmMjVP
            dUQvS2pKZFI4UjJueStkV04xMEMvRkEKLS0tIHFCUnFmTlFYNUkzVmZYMGRqTG5z
            dzZZeXVueDNRVnh3Unc3NEd3NmtYVUkKg8L7k+KfCNiPfXOZwicMPVQ1u0yIXZ8M
            BYz7nIo2rIBLgZpv9q9FZr5Y5czxwjojlS+HTDEFRMUd54IPq85tRw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1x9049ry5hz876qratphuc9gdxzuv4nnd06076842zdukl4unvazszfnjf6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoNUpaQTBrWTZ2cTdHQ3ln
            aWtkSWt6STlGV0k0V1BJRFVJUUFBc0F3TEc4CnFBVkN0WW5RbWdkaE9qZXJpSDAv
            eEtVUjF3dTQyd0xJQnFwdkdjc05FY2cKLS0tIFJXY0tPbnBhWkg0amRpQ1Jvekta
            NzluaUdrY3h4RnNxSlNUZmtXejZEdFEK0zE0aKceipS0SRGXi/6Z9kBxeZOXHjKP
            x+IW8haRZFHb2KoWEsro5TCBqJeB1XrUxkgKHWTHysg3EIVcEKx7pg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1y5txpqz0vyyq03yyysmzuyvuyh8uzzpcw30cp5q3twxnwenfzpvs48ts0z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaWGt3cUV5WWNUdjZ3SS9x
            Q2Uvb0N0ZVhiSy92NGJCQkp4Z1lwNDVRN3lRCnI1R1N5blY0UWF2ODQ2dFRVbGV5
            K09iRUViY2dZbDVRRWMzRnAwVDNveG8KLS0tIDRqMEkzdGpiaDJ1Tk5wdTRPVEVL
            Y0FrUVo1cEpiSGMvTzNHbjl1SGptWm8K9COH6BwhmUTjB3hNnq5bdpr9M+Wdkw67
            6kFjCYEmfi/0icP0yyuxs7mWXYVT+Y9hO5QGCGKpe+TXZbBBcEQr3Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-01T20:58:14Z"
    mac: ENC[AES256_GCM,data:7I2Ygj48gJHAl/9mlwX2c3lNRgykHvP/k9QTvs37P9IJ/XKAskKvfYxqcf6fK5VzuVpJi4Nl+vJ4H4KAfU0Ggf7G5aFPLeECnaiCzfE0M8TPJgp2biV+P4T2MfkzWfDl+vnEuAa+WbW9QOp7jFA6QU7M5skjpl/qSckNAt88sko=,iv:xFUut/DMTrT94RfqKRb6LmhelqFUJVpthmyoiqcKS84=,tag:FugJW8TbEiMxYm3ouODdFw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
