apiVersion: v1
kind: Secret
metadata:
    name: dazzle-runpod
stringData:
    api-key: ENC[AES256_GCM,data:Y8a02RJxH62k9eyCqM/eSkn9BX8O+38Khw/zkEjD+J/Se+iK4LJ4wFoOeBlFiPrlAyw=,iv:A7zg0zXAfZDj7wwSubvp/FBikshM/qgUrKVo1gjVx1Y=,tag:k2mRGHrB3rmdfxlMMnesxw==,type:str]
    registry-auth-id: ENC[AES256_GCM,data:KKfQ9+1YGpFMUeHENd2mnk9IuEubeaFaOA==,iv:YtB/CvWcvwT0QPBiNwrMqX48419jutuMkuEw0xbjOSc=,tag:ctAqTiNEm9iqZCmo0tWZsQ==,type:str]
sops:
    age:
        - recipient: age18r3vk6aecpcd69ey7fhgjylg6z37ksfeff6c497mxgv4nwmnyupq4gsfua
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRMHdraU45YThFR1kwL3Jp
            Y0dWZWV2Q0tEY0h3aGY0Sm5LU0ZidkVQYWpzCmRPa042cmR6Z1JDQXBTRlJJbEFG
            SDV0Rzg1K09NMVZERTIrT2d3Ui9MZ00KLS0tIHpJeC9xQTNuRWpIWUJULzlPN3Fv
            RFBLZWF5UVJ4d3lYVzJtZGpuSElEeG8K8trhI17CzQ1nuCg93rcaScP2LX6jOlDl
            muXrm6BOpCHno1+qfYYwKMbV8CsnqZAYPyXT5zT9kyTW3C/007w6lw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1emw2e5x3d4cu0x4g0q4lrw8nj2fdv0qfzta6g62m5y24j02zu44sflkxln
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCUnpmOE9adjVvbU4rNWlK
            Q0hIZG9NVHkvY3JSenM1SUhyM1NDVi9NTEdRCitvQ08rL0hjbnU1SzdEcWdIMllD
            bkxiWElFTG5FK21XM09zcSt6RzhmdHcKLS0tICszQzJ1RzJqSG5hR0V3emd3RlZn
            VEhrOTFWS2FwMGpINituTXE5WDI3U3MKkaiLrDUfKiRjxOvW3fa9Q82LubTLDlcY
            HBNHXq2nt9TgjvKW6zDFN5yroZRgAnWcFDaSjRCg8YYCqZenSx8Eqw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1x9049ry5hz876qratphuc9gdxzuv4nnd06076842zdukl4unvazszfnjf6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFd1N1STY1eHJGQUsyQ2hp
            akVlNFg5L3VkVW90L202R0w3RW4zSXdqZ0JzClBqUkZmeTVaSHI0VU9XbmlySml0
            YkpjSWlKUGRvQm9PSWdDTnJyRUFYZUEKLS0tIHJzaW1qeXlWcUhxMDQ1akxlalor
            TSs1b1Y1ek0zay9HRE9Qc3U0dTRmVDQK+NdxzRU0tC7wcz+Q1A4hqaXs6EUxJmyH
            /8dMkAX7tMRgPCsQzLbKwJ1EAqW2s8UL/maRgN9gtAPGvrjX73ClaQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1y5txpqz0vyyq03yyysmzuyvuyh8uzzpcw30cp5q3twxnwenfzpvs48ts0z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEVVpHZmZza2Fza1JGa0hq
            MXp6RlFuVTREQ3J3QzVJTmRudUVFbTAyYUN3CnU4bFI2Z1dtelViZDdaNVBDQ2FP
            cnoyUVh0SG54aTAycFhEOGFycTRzVkkKLS0tIHdQT2hRYys0S2RvQkc5RHFHQlRU
            MXdFZ3JaMThJdElTVUR4VW5RYm42clkKwBf+Gtm/MuCHtDztSqBFkAAcX9yjEqaG
            Tj/3mmQqPnYp5ZW/a4ZkcSy9/8ChVtN6doUdrtTGS6vVhn1vG6PhJA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-01T19:38:54Z"
    mac: ENC[AES256_GCM,data:YcmwO5p86G4TJI394iL4+ha4IvNxcI/QWN9EsAMX1fnDCQn1lklBSNQETdaukabMoJYkFgQSVN+CHsASZHDlSpaLHYaqANkfA40kD64F/BwQ4t1s3gQscAr0Ch/UQkqen4nO9okLh8I79+XQ6ipx6RtRLl+YBIsCSvfWMPIooyQ=,iv:xYxLoRXj6OlhEg4YZp1oTJzIWiNBWeE+C2m9E9RG5yw=,tag:EUWZouve4ZE+KiQ7xk3ocA==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.11.0
