apiVersion: v1
kind: Secret
metadata:
    name: dazzle-mtls
stringData:
    ca.crt: ENC[AES256_GCM,data:OoKHjHozryIWLrNoQakYWzElC04GXGpdRdfkGmTIkfSPJ5gWa1qtl0xd8Ppb0L1RQEqmvWrpQU87hIWYE3CxUbQawrGgRGHByW/ATPRe9XwZmqmaFk3w59hNNUYuB3xKXh24sb/zGx9RJiyW0l/PawaoriWhOwOfcVxgargh0j6aonfPooRtVXUhG5cq2AgISMUxPqIwYBG9ap7Xd+GB8ZpGkHw2WBaivsFyX0p3zDgyFdrX5+27AKMUC++1gKGBZQhfudQa/DkyC0kDm/vftexwyQYC4jROb4/SJbppG9a8X+ucywWN/ANLnZlRaitdWzzmyiCtZWURVXpz9hkbZz4VMRB66JdcY7Mk99KPcbaJzK/wDaZDrE0qvAT2YawOCdOW7hVlGS7wNf4HHVd1GmmzbWkG3MSOYbB1BQEfKIn/g9+8T8gmjA3p0BQkjB3w+2lXrCiFoxAeuaWDcR8U3tYLqeUtGWa61k4G6k45TiBwTqhUv4LHyli6U4hsdbVXHxEqGn6Ny//CWyj6Fp35qmxp3xyvtTv2/JrTBwKeO9SZ0de2jU1k37siCNPrFHCB0d/Zef7bgSQAhik9fRadcJk6XR6rz09LG5eVH4tTuX0EtVgTD/SOcTnruMcx01adwVIT8VZCN8yiVUG2LrnVJjCmn+GZvTmbZ2ZbeoSGATicrxHTTIafnFKauO0Vw6gKwKP5HTyLNLCkXoe07G1J+iIQCjNKd0w4TYyXyyTsbXe+k3MRBofBSdOwgP7U3DdpWAqMNYhtBwWNdF08Ys6e,iv:wSANvFyURNYcENVgjvfen1fClOzZfzHtC9uIZkHiQho=,tag:Q8kI+8oae458j1JTxgIExw==,type:str]
    server.crt: ENC[AES256_GCM,data:dGBdejtZ0yaaOyJQf9TF4iBpR3K5ee6s88vUfnLoSUlq12EGFpdABFe47LFgSBgtJOCjlw0SJ5uC3348fRpvfQizgsiBDhjZ8bN8z3GI9D8nkEuChiz5jIwpNh5ONA8hAwiiEa/KdlsAEF5FUXZse0u1spSOlNwfJXeQQTe0AhpmkaLm58zI1nw66Wvt+KVuwcvK2Cn4n6GhF2yHNjnnWD3mSz+JKvsBHJSLjKa9WlNQhb4YiiNTcnsTgsjye/px2BfwrzS/tVmdeOkbkZQbqhddbzlPfepQlPkV8JCQrGMdjIYhRTo77lvATCPRearcql0oEiHGZ+lo+dklYoS7a+qVENrt6q1+0m2m3bBee1V89B/Fw0JWupu4YXi39n13dOajyNnfdXjRMhtQ70x9c0cB/F479YkMcSFeVaSwV0OXaDabus4eQOlJgy3lC24aoyc5aLjk52zGrL+KqNKxMSO8BLuYdsWqnqqoY4VrvpMGrEIxQBl0xbl2SP/aMt7g/C+jUXzENNpbmUuDW/Ij3QinqioUHRQUpXQJil+EzYLdWstDNHmuNcsvD9s2KKyvyWFLzoDUHCIx9LVYttYjvuf6V2bjaFoYPGigEu3lNqF6VKuTL1y0OHIXzMJOiqZ8AQh+HoIyo0xdCsu9b/cW1LkPB8Fh/GsownPXwTBqq/DNoQ5w/FIeJVRY9BRCKq83v6Q6a5Z5us5NVzHqEI3bZwemKFusFe7XSo/DiQv/D6kH1ysyO7+VO5pf,iv:xHBw/2CCJ5SKM2byBRUL105kq2rQosG9EWtxRVtAx2I=,tag:g9oy+m7SEn9FobCLEM1u7w==,type:str]
    server.key: ENC[AES256_GCM,data:8Jkl08qXKsnzHCuoY0GwnKRuu34gAusoCmdVgKtrFBbi9BADxrzsAkcr/S0A2nRZcHuGbKlKaz71wgtPj9icMBQYIX2RodgXDW1lTx5z6rfDPBKPYrymYDA//7YLIP1XcIfUk0ctHSmTZUFuWoag1zPRJ8yEhpyo27ZorBEq9RmyGxIwa7r4wv9oo7Vduq7AnjPwHru0whw2Jg27Kpja51oX+P3fSe+KRiUaNsARXhEj49NTQC/kBPx1zE7wdckyjiPCVnYPpQiUjKgAQBPGD/u7uwJNazCrNlEXqd2gYoxnrWhts/tlM1XvPbUTyRSX/w==,iv:DS9U/F1rMZlg0ITTx2cKEpyssMVE2vZRCcKRPrlT4bw=,tag:vsnNMrdKiq8F/5UjGKnsyw==,type:str]
    client.crt: ENC[AES256_GCM,data:r2YLzq0FMM7T91s3jcpilTcu6yZjghUAR1qeyLAs93XTv04shaBh10D/zv6eB0hlNPQF8U59vy6/6jcNT35o/mLtiDRzjfGHxlcndGfeHYATKUhRTtZv8cOprthafaLm697P63Eah3Txwb/AyKsQ6uSx5tvz+4IaUvFSRILIwI3MqbodO87Lkyq6kK7L0o0JZMnbVm/vGnHgcSnFZlbOQNKimDaMojPpJlbRGuwiHGJ5YeMcr8Q7a2Px9FpWaFEptgml4Q36Gf5yON5J/bDKHuGKbqL43mESv7cenJhWZZpDPSAvNAomXsFrX574Tv9n2LgyydWMuwXEawzqvDDvoyPccPYu7jE3ZH7WZtNw32kegtSbS098hvmDgZWvDbJSjoQTnAFWUUrjD7d8n6qoVARnLxP/Nmd3vKA936cPzKhBFALU67LEGe8n30/V0MfeMUOmp6QU7/+TOXABbcF80X9kv2iIjkVy58Re3N3iMIm1uA37mKyfxaXKJKYdGKkGrw2taoqZsO7he5wlNsTarQjRmwogTInGkT5GmOvujFYllj7bMdHP60kQF56hIXUpB5l4ZUJMiB6jk/4TAhGyVqRaiO9CnoXJBNeThjsIr+45UZsXO/bFtVn8ZXJpO6xHV08xWvJ+wH7njvI2Ia18gY6Uprqf3kbhBvUhn0vxNtd9GpefBFkC91aL5jRgy/cimrJRE4sm6ECTc1MJHf6tkKmOBTw3NNkTKeiOTHdHxGE61iNVPiQtB70M,iv:p0ETcK8oWkZEoHq2qqYLcNeYjcmpyuDDlQYm2Ll0QK0=,tag:l0ogcYgjbTXiqfRffZoBHg==,type:str]
    client.key: ENC[AES256_GCM,data:4GmU/xX5PlebWyzjQ3sfWVR2zOcThobgt+YPjHZK676GdGWem8JrhEQOSHoUlE158V4UlK/P+x4Lx96FMonDH2I0vriSr4OHSB4Wh6N3lsIPBWjg7yvbeoXM+S50YmSzBtRripA/zclvDHGBSVOSJNGteOAzpF4UZZanwh3l621sfw7LW3V92LVxGzBmjvUclQgUVgI55wNG/Q7K7xEQTlVj28Tynfi8fdMZrOD4P5Nu6Tt3BEiCgtfAmmtvUNeFCPX63Il7QNud9xlqWb2BpN2hX+em9mwL8P5LxTTCH0Fm/eO9kgKJXjwJbzgwHFsxWg==,iv:gpbwAVNkEM1RWJIo7zGADQjbTKJAcE72z32dNzkgPYk=,tag:3CQDYV+sxEYMUNjlqoO/Sg==,type:str]
sops:
    age:
        - recipient: age1mulgnkldp0c6daway8auvrajfj7gmglr4tfhrnxjrhzg6pqump7qcamvts
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOOTZwUU85Y05ITEZsVml2
            VDdPcFZDU0hGSzFqeFlrbFJ3R0dTMFZJL3lnCnp1d1NoY25DQnBzQVRmNnVISGdC
            bUs2YWFUbVpvVEYzeTRhZVorNHplbVEKLS0tIHdGekN5bmlTN1JSY2FqbVF3QWxR
            S1JyQXFQZGEyUEgxNXVUYm5jZlBwS3MKt7AYfRLA4r8QSNmU4U6TA/KtDshrJ3zs
            FjkGVpgWsJRQT8YUZG9WlkqHv+3M8z6YpKrSldxI9AI1hc5G63aUpQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18r3vk6aecpcd69ey7fhgjylg6z37ksfeff6c497mxgv4nwmnyupq4gsfua
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNNVdhR0tSbXM5ZDMzckNp
            V01UTzJ1RTZINy9oU041L0pBb29GeW12cm1NCjlBeFMxOTVyVTBaTE11Ti9LRkZR
            R2dzYXRBK2pBTFBZTDVneGlDOUlyS00KLS0tIGh5b0RUcU0wM2FwRHltSG1YTnFs
            SUY1VFYzLzdRL1B0bnVpV1dsMEw5SmMKhyThBIwnT8ZiUC3ylqcNu7CF7n98MriN
            vWUQY2e4w9zdEHD0gWMOwDcxK3+xtxu5VtgbTYDBlIB902kHmhCfPA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1emw2e5x3d4cu0x4g0q4lrw8nj2fdv0qfzta6g62m5y24j02zu44sflkxln
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuWS9FNnBXLzRCVHdDZ3pv
            aWtEVkFsekVnbStiREpMeXcvQzJkdVRlVWxNCkdBMFJSY0RBQnRBL1liNWFzS2pZ
            cGRmUlZLeFNpYkhEZU9lMXdHWDM5d0UKLS0tIFlLS0k0a1E3UktGK2dIa2loYTNG
            N2dkNVFYU1VVSDVoa3FRVEUzS3ZBYk0KrEdsAL3b1/k0raQRNmgn4cyDvQTgVo1m
            oizOxpsYssS+wts0eG1O3jD867mVFgpyOJ2mxs4wybitG6q0TdsG+A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1x9049ry5hz876qratphuc9gdxzuv4nnd06076842zdukl4unvazszfnjf6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3ZEM2bHZEOXJZeXg0Zjd2
            cUFWT3RVUG5sRm9uYUd6M2Y1NEhkSDZVaHhBCnlRT2FUR3Y5dzMrT2tkRXFvL1hv
            SXZTWDhkNDg0UHppaXpvUGpCQWVtMWsKLS0tIFBaR0tsSHhxdGErSHFVUE5vS21i
            Y1BxZFY1R3k5UEZSQXdiSW5Bb3V1dTgK2ynEi1yL/+ByvO10umflFq6REK24Xi/b
            a9rxbflS3U3uEZCSnIBKw8T2VxzSAIcPw47ZYSf0p+ae45/mRh/gJA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1y5txpqz0vyyq03yyysmzuyvuyh8uzzpcw30cp5q3twxnwenfzpvs48ts0z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZaHVBajgyRnQxRHpiSjFY
            NmcwREE1YzYybmxZVWE3M0MxN1FrNVBabkdrCmduckQxZGtTWlFBVFpXZHd0NExF
            dlhYTC8zZ3RrVVgwMER2U3VvbjEzdzgKLS0tIDJLS05zSmFNSEkxeFNWdERtNUpr
            SEJkRmxjVVhCS1QrVkdxcGdyM2RqM0EKrAd2Uv0A+gEN1XO9B5JYM11AaCi4I9hN
            d6W0x+4EwjiEbTfanOl4kWimpQsRMkLsGNZRmiXftrJEuA3inn+eyA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-01T20:58:14Z"
    mac: ENC[AES256_GCM,data:LqFTYaywkshrci6blwuZfnPl+L0zi8FIc+wAzCd+8Unjo8z7hSxyZoDkYQz/WgzMMzcbzk8h786Ec9C/ieBEFVcsjfHbNeqmqyKGAcOKL8DnZAcwZToQRTid+5NCgUbPx9C6fDfwUWxv6kH5+M8IxEo25YBRFjH5CeVg6i3uP74=,iv:eDpNUTrUbk2hvX6uw7SirVzb2vkTXwN45/ThGQhQj+w=,tag:stcstUBCt2sx2Go+qij0rA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
