apiVersion: v1
kind: Secret
metadata:
    name: dazzlefm-dockerhub-secret
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:dkGaurwISC2+hqcoeX69X6NtbPJTSjv65jNjmLY4WgYEA7B5nUixHswPgNNicLXtBZgWm23YHORBkLb+aRrO3XM42HSck8G9dWhE+I/kTk6+JRGId6zV8FpkMTwCpyXLwA8jpGrIWx5DnP4CG9R5Bk7heLv/+039PfJ7rrtF0w4fGnEPYXGC/kdYUnYlco2i/wqgPIE1JJm6LXMCWnnMO3EYcpKC4Lj1fjxcOi5JC1S6xhA5uUrvZzo1aQLybpJFoZCl8hC1ahBBO3lAe7gcBBFJjM44gm6/Yfz9B+tGz12Kij1QuvSgo2a+QXCg0/LvKFJh5UGR02w4oOyTHcLIxrUwyvMgbZ+njU23nw==,iv:l4c6ZMcwQR+gRETS8ueWCKjO+ecvkOwo5D0iiJWu/ck=,tag:801FRsDfxOqu504T0H8IHw==,type:str]
sops:
    age:
        - recipient: age1mulgnkldp0c6daway8auvrajfj7gmglr4tfhrnxjrhzg6pqump7qcamvts
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQQkVoSy85bkJnNVNWVUhK
            MmhFeWVCam9tVk5YdVcxSGhQNXhxQitCMnd3CnZiRTB2NlpBd1o4QXhBQUwzL0pI
            Njl6RGNNQlNPMUF0MSthcGJVRFRoKzgKLS0tIGNKOC9TRDV3clhLY2RiS0J4YmpT
            aDl0WEVlTTVLSDBkendQQU5tRktlK1kKD1SDQrUlBxFyg34S0nJ5K1GEMV+lgJF/
            L+OIB81fNBy8FA6IMq+Nlg/7uUCCOP0SXKGULUm/FI9GEKjqqrXqlQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18r3vk6aecpcd69ey7fhgjylg6z37ksfeff6c497mxgv4nwmnyupq4gsfua
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxYWgxYnMzR3EybklyTDh6
            c0FCZjV3bzV4ZnBwelRnaHI5YllRV3F3REJrCnNQUHpqaDM2cnU2cUZ6QTJGTUJW
            QWlxTGl0MXYydnB3akhmdDNjN1ZzUmsKLS0tIEhJZ09KTklzUkdOMWFKUmZFbTFD
            bzFvNHU3UVdzZlFuTzU0SXRrS0hxOXMKHnHrL0/JJV7VTU3oyfnaaC/BRzeAfTdH
            wtbfs9fUFg1RSK9226nLFupcCuDA3lT9jUOA4kRP3OJQxRW8r3rb4A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1emw2e5x3d4cu0x4g0q4lrw8nj2fdv0qfzta6g62m5y24j02zu44sflkxln
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1MmUzVGt0WXdBTnNUTE5Y
            cmZvR1B1S244VmpnQmQ4QjlMRkFjZ2x1MnpBCnpCMkNzOW5vS1RPTVZMWGZrMXk4
            VDZLWHNaVDF2eEVVcDloVmhONUM2QkUKLS0tIERnVHJxYXIvTlpvNnZXdWhTMmNR
            UDhJdEkvYXN5WnhrS0FJQWdvQ3FRUVkKVm0Vi1blQFseSoGqaqFN+zIbMdASmdRQ
            uAE9lSX27cljKuA3e8Pmd2P5hzflf6SYcKxfebRspt2M8XhUrz+IHg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1x9049ry5hz876qratphuc9gdxzuv4nnd06076842zdukl4unvazszfnjf6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBONXUwbldVNWJxSGFER2cr
            RTdvSWovbExXZi9SdG03NkZmdGUrdDFYRkhNCnpBMEFqUjYxSzV1SVJkM1dubXp5
            MWtWTlNYdVE1dkZHc3dST2FhVVkyWVkKLS0tIFdFNkJ4Q2lRbCsrRDc4WnpCRXNE
            S0NkTnZMUmgybjA3S3ZaMFBXTHN0TDgK0G22b5bCxWhRUxFWdnFXMeJy5KdIJTpu
            c4yTL07FgcIvCH7YEtUnrd9u3Nn13Sk91qVN1+HC0EHA3khCFinO7w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1y5txpqz0vyyq03yyysmzuyvuyh8uzzpcw30cp5q3twxnwenfzpvs48ts0z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2N3Jkc0pwSWlSZmczM3A5
            SEliNHN5SHR6alRsQUhSZVdXcW1Cbi9iYVdNClBweXZ5NDAxK2owYzJxL3krNW9D
            WEpqanBJN2dZaWlxWE9uS3pwWWJRTVEKLS0tIC9tenNKbW1BVCtpTnN1NUtMblVk
            cFRZQVY2VVZTVGt2NVJsaU1YcUEweUUKanTBwPZBr3XbIW4g4YYAqDAzC/ZaLg7w
            JL7ZTrfw4BD6aE7Ia0IbW/+mqgkwWwgbfZgyJvSHYPoVMiQJXJUPZg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-01T20:58:14Z"
    mac: ENC[AES256_GCM,data:bSodpT1gJNtLCeGueEaCQdcfGDWesAGOwCcBgwFTHUdpgUfH1/r21RXT2DUtalNcjQjCW7FsHa+8d2mOtnapOjmitK1BVcHGdSHHRBbBTRaH7I7NsZnC6VS//moqyOn3ljeoNKkmHu8c61QF3a8EKxyCMGvWh13LxzAMC8I7QjY=,iv:ZH5gktOmtbAS3r70eMsFgD5qsavkG/NHxcE5kzav+Ts=,tag:QnfGbZLBJ/T4/4AQKfAY5g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
