apiVersion: v1
kind: Secret
metadata:
    name: dazzlefm-dockerhub-secret
type: kubernetes.io/dockerconfigjson
stringData:
    .dockerconfigjson: ENC[AES256_GCM,data:L1h5qTR4e64IPl8Fj2UMS7y+qOYUO5bwTVfG7gHVJ3dwDSc/qLM6onkZqUH9LOENj6fX9fzL5kS1LrI7vrgZQx1sPyA/geUcQRqZb9F7/ADpKd8DV+YAgn8wau0G7z4XkonXikhMHgyfSw0pWzFlhbgm/PA31xqQyFXpBvCT49sUrPqyibu9fYdf/0DQ/y7jxj8rJyo9kfqrX5+ijAGhI0IsXcC6YcjC/xL5wUjoxvGTzoKC4n2+Q4qtvaKn2Q14JYOkOqfI9IVvFbA4YZ1bOEWY4P1VCBLHPvKyN+AtJr2M+n1RqBOTL8tUfFz546vloEbdk33TxqP+y1XvMbEzkv62Fh6IXqcWBJCV5A==,iv:Ww/4HLNBEha5ohJCabL9Q9g3lBf+gjU9S1HPtMe86p0=,tag:SNnal72eU/6FBUshtlQeVA==,type:str]
sops:
    age:
        - recipient: age1mulgnkldp0c6daway8auvrajfj7gmglr4tfhrnxjrhzg6pqump7qcamvts
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtSWlUZ1NCaHFjQWVwTTVt
            WkJaZkNBMGJ3UTRTYUZmQkhITDRReUk2SndNCkF6MlpNUlBTalNvOE9wR2FseVNq
            ZnlmY3JPVFVxN2dlWGJENENCWXRRNTgKLS0tIE5UNHRTZU5idkFvOERTUWFxSlhh
            NWFyazF2UkxFMnNpMmJGd3p2SlpZTm8KF8tF3ffJTcyFO78Wq/A4AKLAPD9m6WhM
            rveghhkZYfFJHFGODb3f1xxYjzfI2gElA+Hn7huf2gnpPY5mA3MeuQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18r3vk6aecpcd69ey7fhgjylg6z37ksfeff6c497mxgv4nwmnyupq4gsfua
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3K1E3bXpmWFhtWWg3Lytp
            VTlHbjZtTHFxWFkzb3dKUG5lTnMyUFpDS1VNClB5RmJiQ255alhWNkpZRExQdjRk
            cGllRFpkNjV4Sm9jbG9yaFpSNWxVQlUKLS0tIG9XbDJpR3hhaDJTM3pzbDJoUStr
            eFMyOWJqalV2YXo4dG1DckE5aTcvR2sK/2/R0XJzMP7cjL5jjjr7a8xeHhfDKbgo
            IkPwbP/QABOra/c+KOv+VUTWluF31JQiQsATOoZ4PiP2WMrtvZzGmw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1emw2e5x3d4cu0x4g0q4lrw8nj2fdv0qfzta6g62m5y24j02zu44sflkxln
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlRENiOUI5TzJRK0ZqQ0RH
            Qzc1UWpMSXVWRkFMQXBVcXNXbzFnLzNPMm5jClQzOHlQYVBEUVdOQTNRUW5lKzB0
            K3RWZmJUUzlNaU1qME9DSDFhbFNGcUEKLS0tIHhBbCtLWUM5aDY4cVpxOXNGeDVJ
            dVk0M3dsMzZMc04vQTErZnlLTGZPNlkKPFxSXKpOXwpPkb1McfEAkdkgauxqCqU+
            v8LVbRw8/5UJSqhF/9lzUNSddH8ri3w7VZHS3K1NdZfCDNGZpTvfHA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1x9049ry5hz876qratphuc9gdxzuv4nnd06076842zdukl4unvazszfnjf6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZMkhWS3VadVA1RzkvNCt4
            TlZ5dnUxU1dUclRQV0NWakxybHJuMDlMRmtjCjNzYk50TG5yaWMwcEc5cWRCamhi
            VUJzNUoyNWlvZGlzdDhnN3RBRXdjWjAKLS0tIFQyRFFPYUppWVB1eEN1VEwwdlc3
            WUs3ZEtYMXVzeXErVDJxMTIvOHp1TGcKerwAyndWMvy8n5qRTu1lZHdHvmvNiuLF
            sf2QY3VSTqx88W52pkE11E++Minm6XzYsvLevsajv9DQlwKZUFxYqA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1y5txpqz0vyyq03yyysmzuyvuyh8uzzpcw30cp5q3twxnwenfzpvs48ts0z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2T3lPeHlqci9aaXp4OUUx
            YkdsNXdFN3R3TmxZZkdJWmxrUWJiSkhDMEdBCkVSSTBobFJlb1laYkVralo2VHZy
            SVhvcHBDV3J6T0ZUd0M0d2tZa0p1VnMKLS0tIGFsUUF2Wmx2UUJsWTdlYXN3cHJy
            SVdYK21FRHJlVHpYSWR5Y3p3TGVVY2sKaiOjg11rgxyP7KtFeEaFxlzHP91dmGRe
            2Brzi7Y4cfNehQCbYM/VdqLrWQtbrfl+OdEUPhTqCT2chyzWKxdrAA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-01T19:38:54Z"
    mac: ENC[AES256_GCM,data:nev3rtR5VGLDfd8ZFbj8T/gcL5n43tXwOjrUqeNKGjcU1v+44dAem3y5DKDVTf81FIyvF+UfHnvfUsVxfnFxjodt5mIJjPAyWijorvHF8VBrr0tCwtDk/S9CsrxDVw/vLexK07osMr++Is48i7tgADSjZ/jntrKS2/4uza2KWFA=,iv:45OSjlU+3S9X2A2F4gcPew0CqKPr5YpAFLJCMjWLX1k=,tag:0aROwn6/pre0LffYuIJmnQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
