apiVersion: v1
kind: Secret
metadata:
    name: encryption-key
stringData:
    key: ENC[AES256_GCM,data:nZbgEKx/QIt1RIu2m12FL9nOpCAGbQBOAbOzIAgJu0QB/rsSSyxK96TXh7w=,iv:N3Rt2EWCE8RKuUClkJ/aB+XmC+g3aNnYHdkuQvj6x5Q=,tag:3rtyW74jgnF5Cqi4KH9j4Q==,type:str]
sops:
    age:
        - recipient: age1mulgnkldp0c6daway8auvrajfj7gmglr4tfhrnxjrhzg6pqump7qcamvts
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1WnpEU2pLQi9DZFNxNS8x
            T3Y4UVVraEh0azhVQ0hBVVRvOXBDeTVMYjJJCkk5d0ZwNlY1NFFjVEtFR3pqYjhs
            OGlNUklReElFNDlwL1Z6T0s4bG5tdUUKLS0tIGVybWpzMnZyK1R5QlBiWjdxRG1U
            YUFOK0NlZUxTYUtYdmttS05jVlRPR0kKD3ZJuC9hiu3Y8eSw0T+UTshtmt29C5LO
            AooS55EBPfpJXJ96wkJO1kvpBuXwHF+raeanUSQNBW1fia1I5FtJIQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18r3vk6aecpcd69ey7fhgjylg6z37ksfeff6c497mxgv4nwmnyupq4gsfua
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNanBSRS9oK0llaHBsOUNI
            dytNaDdybUxEVTBEekJaUW1oc1lHUjU4TjNJClZWb1J1anMxdUpBWkxoWUtGcTgr
            M2RCdTh4M2d2cldGMk15c1gxc0diUFUKLS0tIDB6OXNUUE82aVp3SFZOZmIvUnBD
            aHVPU1FNRzVzUTBtTGpIUnFURWZxQXMKKBUYlXIHXrkFsXJew2Y+mGyu1CPhsUmv
            5VmTryj3S3o4jwsoFvO5eMNLgsI+YUP/4NxQgNU53Y+mV0Pw/fORPg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1emw2e5x3d4cu0x4g0q4lrw8nj2fdv0qfzta6g62m5y24j02zu44sflkxln
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCVTJ3QTE5Q0RjdTFLVzU2
            aXFHM2gzZkU1cTdPR0wvNUE2amhLTkErUWtjCmc0SG82Uk1CTjU4QS95eWJjMUJ5
            azdsTHY5U21TNTlMdHlyK2NHUEM3VjgKLS0tIFl1RGU2elBGOVl0bjJjUnFId0JV
            RzAvMklIWUhxRlJkYXhVZVdmWkVWM00KvBmH9iapGWxAdjMatVpzhx0ZPDDO+kYZ
            W6aUzmn/wHf0xvhBrHhow/Jz6yJtj58dKNI16MOfb9wmvJiuJdQcIg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1x9049ry5hz876qratphuc9gdxzuv4nnd06076842zdukl4unvazszfnjf6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMVEFmL2ttclMwZmlvQ2gy
            ejIxdEw2bzN6MjhTTjJFd2lMN0JUQitTRVNrCmVSY2FTd1NpdlViTXoyT3ZYemIr
            S3B0NlZUejhBWEdjUnI2dWFlTVF4ZEUKLS0tIGI3Vmd2bWtqaGY5MzdoRzJCU21m
            WkV5Kyt0eTZ5TlQvM2ZaMndsdUVQZjAKsEUS8FXD2OtbWriLi0FulPcoVDwhnLA9
            y2KVLZh8f0i8xQX0zASdyvTXpMYGWqAal4M7Gqa0NuuGAOBLAKlLlA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1y5txpqz0vyyq03yyysmzuyvuyh8uzzpcw30cp5q3twxnwenfzpvs48ts0z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSQ0t4Uzc0MUlFZGR4NFIx
            SjFYMEVwUy9LTFNpZEt5VGJ3bEo5U3lIN0hjClY5OVo0Vmp2MzlwZXU3YmJSUzF3
            Z1Vva0hOMHlyRXZJLzRscG1TTE95SmMKLS0tIFlOczJhTEgzVHFXNXdDU2tiQWFk
            OHVTUVY5TE9FY2p2eGNScEZDNnZGK00KlGX6TB6CUyoQOVBiXWFsjnRRUwV7scDE
            h1RdmMMevUAUAJuesC/HhnV97iTKbBAPLBnlTG6HJ+yHQ9lGQuWXjA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-01T20:58:14Z"
    mac: ENC[AES256_GCM,data:GvqSmMLyCEWgqvVC0ijy5IANHn6gaqzVOFNKsHeadgA6B6fK2Aa2FOQPlHBuwuNJUP2WLt437nVt/fGtGP5Xlk7UfCI91JMYjmop/r3ed0Z8HeSQuQLl30Q5rSUTn4TTPS/obz1xUV4q3nKrnYPGsbEPAKLxbAypcVa8g3omWOA=,iv:3hNjGS8TDgl2mziEW30dFt/JLsPFbBslfqSpnoLIJr4=,tag:QBa6+ua046VddbwVJ4o0kQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
