apiVersion: v1
kind: Secret
metadata:
    name: encryption-key
stringData:
    key: ENC[AES256_GCM,data:h9NqZ1xaI1xBDDHtDo9qIGq5MDguSjIaa6PvHcZtQuJvt7TioL2qYqL4+D0=,iv:w38zxuIlC+M5+dQotrB7LxMg+d8AA50G+70f9EAM6l8=,tag:VxyHvTROSpEaR4qFOn0hPQ==,type:str]
sops:
    age:
        - recipient: age18r3vk6aecpcd69ey7fhgjylg6z37ksfeff6c497mxgv4nwmnyupq4gsfua
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlcVdNZjVMTmxIckhtdXdt
            VldOL1JJc2tkL1lHeGl3NUFKTWhLbFhEV1dvCk96MGFsc3VodnJyam93Qmk3S2Iy
            STJiQ3JlM05WMjUzVDV6dkZuOUI5d00KLS0tIHk1eDgxajZXZS9CY3hnS05UVi9t
            QmtxaFBuMmR0bXdWSGRheHhZckIrbDQKnyokmVIwE/VRCLE5sdofA+T+cl7hg2kF
            choDECw+0U1PM1Lrthk3k7Jzqx49hGsqwAmgMdp80eFSqjQ9iU0XRw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1emw2e5x3d4cu0x4g0q4lrw8nj2fdv0qfzta6g62m5y24j02zu44sflkxln
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBid1NSNFBsdzFMRWJpb2dC
            T0tUNERBenQ4ZDEyUElGMU1NVDVyeUh5SndBCjNibE11ckhlYURpUmpBVjFCMW5R
            MCtBSDNOSXBsRVp3YnVJK2tpT0FnR2sKLS0tIFFobkNON2NxKytkVGhDVHVXUHA0
            UmxQelY3TTFDcE1rdjhIeHc2ZHpOV0UKgzGMuPOgXwoVxj+nDEyavZbMGjy8B+iF
            oVBH7iezwNRToU7pTM4xGoFb/NAIqgbCgMX75d1nfVpF61BMdDPjgg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1x9049ry5hz876qratphuc9gdxzuv4nnd06076842zdukl4unvazszfnjf6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNc21GRXRCR1VHbkphTXEv
            RWJRQW1JKzhvVXVTSjM4OFJNUkV3RGpQTXlnCmdyTWM2Z1RlakJSeTdxVmxCOTE2
            RHRZQnFTUDBMdEdGY0Q1R0x4elNYZk0KLS0tIHBWOUlyZ0hKTG9CaDZVekdlTFV2
            cHlsY0t6K2xoWFNmN25GOUU4Z083bzQKvm0PzsVZD6fkrfy8JHYyf2bSm5fe8qVX
            p1A6FBjXjousHMr1i7EwvCJkvHTh2pI44saH4kLZppfGJzms0BBiAQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1y5txpqz0vyyq03yyysmzuyvuyh8uzzpcw30cp5q3twxnwenfzpvs48ts0z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSU0ZVVEt5Q1Nnc3R3dS82
            K0xHNWJpbWxoYVdteWRHVmcvUGtwUis4cjN3CjROMU03d0hCdTcvOU1ZKy9VZ05v
            Nis4SlNqNnV6RzRIcUkvSDdiNnVLc28KLS0tIDh5QUZuajJSbVI5NUF0OFdXR2h6
            Q1FKZ2grRTRyL1A4SFB3TUM3WDhPVHMK/oPtE6NPv6s021R4tBTvGhi77RgOQ1R+
            824w8Z3fV/UEWJlzzC77/+FpuPBSlrAu9tpNqwVSrgLMIoXgx8Jozw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-01T19:38:54Z"
    mac: ENC[AES256_GCM,data:rkYgXJ821rFrWVRmT3PZcp2XzSyd0K1cnTbUm+W1n6KiFap/4opsm8BjoPQL0tOHLVoTg+US9c5SgjzXbNbt+oolhZPCJkTnfpZaR0XLkv4Rj8UyM43lc886cuINrjdBSKTWkxghF69hEEE4+seDfMGJTjrzQkfRtuWe8MFT1DU=,iv:pLEwCGiO2gEzFIjPbOhg/ZVWylmWd7bgJX5qlgfpl90=,tag:C896QZxlFbenMXJhH3ONDw==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.11.0
