apiVersion: v1
kind: Secret
metadata:
    name: oauth-platform
    namespace: browser-streamer
type: Opaque
stringData:
    twitch-client-id: ENC[AES256_GCM,data:MsuJFSOYtG3c9P+gqVVc+folaJy/LBRA6QxnafTb,iv:HCzFzkW1PbUBapncFy1+kt8agak/nnLPywgqvH+BMdY=,tag:8hVRIE9ZqmooeyX2F5p/pg==,type:str]
    twitch-client-secret: ENC[AES256_GCM,data:wmO6nQS3gUvW3RHX+SioEd8/nwnHIw/IF4sHF8zQ,iv:rsQLnWps4ZoHVsMJilpMwcifCYKkpJwXQrRVgqP9SCM=,tag:miw+YW41cEMk4Y2UryMmvQ==,type:str]
    google-client-id: ENC[AES256_GCM,data:bCRLffwoPtiERaMnQ0TyX7RYRja9GQzTD+PChflI2hKpeF3majqFkZ/E8UF1UQMI0TXD0lcmKOGe67vxgSHAqIMTc8bikNbF,iv:mfCSwyICdc9dPorvh09KeMqYPE/NheYcVcemmxDRXJs=,tag:3erivITcbFFKpAuuXz8tgA==,type:str]
    google-client-secret: ENC[AES256_GCM,data:l3e4/kBT+l/bjWNiQ0/7JNkuODLWOvIEpPUO6I00WMBTDKU=,iv:uceiTrUuUIwPuMjVYqQvE+eYuoLZmbNnrTpe+Z5VgbA=,tag:wNtv7vi3hb/3dvQ/WfRaZQ==,type:str]
    kick-client-id: ENC[AES256_GCM,data:I235urFXWMwIoPTA14xNB0wH7GP0W9UNPJg=,iv:uek6xCvty4PMNFmnRapoL8shQHF7cfxwmb7HPVYGYFw=,tag:tEyTUVjgzK15L4BpC8+Ppw==,type:str]
    kick-client-secret: ENC[AES256_GCM,data:U1+ZKGkeXZWqAyJ9LuyZyJtlNAaKqVAgWpRG7dOcVnpMw0CpacRkjIoYUxDS/cWQ/2RmMBg3DNHVXPy0IS7AYQ==,iv:ez3tVb2W73oOC5yOsB2YNWPEiWPV1m2ZanrsLzowH1M=,tag:0IZiLIjip4Y+/VMyXRoVXA==,type:str]
    restream-client-id: ENC[AES256_GCM,data:MN7eW4j6oaAQNGziyFS0/hAUEk60kRdTBZDoXkG5oSb3a55w,iv:6WzPVpK9czqiCZKieYRZIKKD702dPd+ZJFlpYZ0qGVs=,tag:+8V4wbbIBokuo7uNoke55Q==,type:str]
    restream-client-secret: ENC[AES256_GCM,data:7DCufvhKsqSkbaxhyPcvxz1hH5RFjXp2KNrGTgsWT59ZTvyC,iv:AMUZginGsEKAPS34/GUcRsHAamtleL7FyWsvw9d6ltw=,tag:z6KV36kRc62eJPhE4VFF3A==,type:str]
sops:
    age:
        - recipient: age1mulgnkldp0c6daway8auvrajfj7gmglr4tfhrnxjrhzg6pqump7qcamvts
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkK3BzdXRCRzR1MzM0QnVw
            TWQrZjNIQnFoNFFCazB3eU1ZdXQ5VmpRQ1dVCkRTazd6T0puMjBXM3BPSE1WNksr
            V3ZaNFFRN2ZYNE1wdDkrWXRlU3VYOVUKLS0tIHlwYWtsRTRtcjJrUVhlVDRzZGZO
            QXYzY3ZvUStUbTVKejBId1BBb21sOHcKHW0J2bFlaYsNzpVoltrJvjaquZBgE4os
            2vIB3FEP4XnOmVCQ9VIXXqrTccFi14XupRYz+NTOVj9H7GbCQD2r4A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18r3vk6aecpcd69ey7fhgjylg6z37ksfeff6c497mxgv4nwmnyupq4gsfua
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHMURGd2g4M0pORm9rSzV1
            UzZpQnRvUzJrK25iY0tDR25YUjlrK1RCU0NBCm4vR21xVTdrbVhxalo4b0VSNmFR
            YTNzM2RNNzROM0dXV3FhQm9kcWlUTGMKLS0tIHFKaWJabW9sVk9HaUxHZGdDK0xz
            ZUNLREYwU3dGT2lTelZRRUw5T1p2VEEKAE1D4/UHixlePG5cwKBjADAEYDOldqEB
            tvDm95lRsQG+gdQ/tvxIsRlllCRWTKgLKLC1+l7I7Es/+X5BRgLB4g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1emw2e5x3d4cu0x4g0q4lrw8nj2fdv0qfzta6g62m5y24j02zu44sflkxln
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5dTJzRjdzZktGNFI4cDlk
            SG10Rm4vYXdXamViYStqT3VQd0djMVF2N1NJCkJPdWRyUWVCd3BzRzBOQm00Q2I1
            ZzhFU1gveTlXUWJvbHpVS0JFT1c2aU0KLS0tIDBzdUhabEpPVHpSUmQrWGNXVmJp
            T00yNnBjd01FV0owc3pqME4vY3BiWnMKJVji5LSLI5Kqta404wHrzje8skoAoAGI
            nEF7nG3Ll84JOay9BdB1vBmvCmc9Ok43shn5/u2At8/ndkWbU9HeYA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1x9049ry5hz876qratphuc9gdxzuv4nnd06076842zdukl4unvazszfnjf6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlcExLWi8zcjFEYW14b3pk
            REhhWmZaK0JRd09jY09aSjJLVlhXaUdhdTI4ClVtZnBKTzkrUUhVRjk3aElaMlRj
            SU5WOGFXLzlOWUJJVUczRU5haGRhSmcKLS0tIE1QUmIrSnYrWlhpaHhhQjR5M3Jz
            QXkydHBwejRnVzZVdkE1NllEU2tDNk0K8llMaNlgYtz+V5Wcl8DMWaG5ZpXvDdkh
            /kdO6gF6Ies47pui3t7AvgtdryEckWBEKPU8LgZTp1Zp79YMX/fKig==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1y5txpqz0vyyq03yyysmzuyvuyh8uzzpcw30cp5q3twxnwenfzpvs48ts0z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjZEIxTXcva3dPYkF5TzVh
            a2F2ZGY0bFdSOVZ0YzJPZSt4bVJIWHZKKzA4ClVpVTFnekY3Ykp0VkFyNzA2UzNo
            cGtjZXBVa3BmYXRCNFRiWGpsbFBwaTgKLS0tIHZGUHJNSlFDR2h6Q1h6eEFHeW5a
            L1JQUWNqMTQ2bFpYTy9VUW9YY3NjNUUKTO7LjH6x2S8LPGaw9kZ6efdQxJCnSxm4
            5+jSPUpnUISO/4EtJi9x/IzmLpeUEs0vRJ1SCD7RonQSUMqXV9EVeQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-01T23:10:36Z"
    mac: ENC[AES256_GCM,data:VHusAxmaxFqu1ixupgrNy7s52jUDmNo7duWwySlblt0VAaLh6z3dYMrWW+g59i98mmhPbnyJ4nIqM9I+mUuqT2ZpdYN+ECwBqDNUqT9UHDBueFZsYr5vCX89cQ44F4lG/bcLSCf56dsSUFg/Lv15AGxSI4ghVCu9YEd+KKGHgZc=,iv:QbFmy5vmEsrYGRURVGyGWN+9ioC37EdHvYAv+Bmy6u4=,tag:xBr0aEmrw3sHnphr/RgaUA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
