apiVersion: v1
kind: Secret
metadata:
    name: dev-tls
type: kubernetes.io/tls
stringData:
    tls.crt: ENC[AES256_GCM,data:n/BSe1nwceZVpRMFr4MFa/+XvfC7ELPnEXbqI6gBPiHga7KKZPh0XUPeYaV4tIEjOvo70hsnMOGPkyepylbKo0L6hO4lO3ouQwhsz5Mes2OGaCnMoeIPI2XJ910+qsuZH142J6h7iQ7XWWh1twR0BCoxJKeHgsoIlRT3UhYMUx9ExS/Y3704r1efhzn7ZPuL/VxWYG/AsfMhZ/Sr91+K4VQ9SuqWKZy+ynN6q5EuxUuKOWbgKcbzcuPAH1IhUYu2aUhsxyPpFDTInlLbtpTxw5BkfiUD3A9aZ6mFd4eSoyp2fQlJYCxZinp5s9i/iwjFxU9TlsxeW8nl8FMPfwaxs1C5wxMvaaJWLR9yi/HPmGjODcHvuQTFAfLMOWRJRTlWQA/wHyaWgWeQiwxodwfadWmrbh79Aa0vf4Qph4aWBkm2+DBETOlg6j39xVonQXkD46vyL3XWoh2gEuH3U96dm+j74HBtVoj2I27PoBxn6Gz8VKrL9u6JfIVkMuLqPeUIUD1jWX5aQXyOwXTosjHDpw6X+zxVINu14jv5xZH2PTThob/3ruJKuHr+NeSs29jyRaOlxWiCTZn42mfXbMfATqlOeKlgAcdB4FXJBfGqhzaFbC4v0fx+Fvo6tZvPzlaJ+p4WhNJndvm7Zl3AFD60V63TTrYFfUZS7dQjW8lNYFE+iuYyysksfGX7pQLUwmUUli6K8l5Arxn2GCLKRddWtCJFeq3MALP78CDm7ti+Nrk2BdoVE+83w0g+gKMC7sIrFv3wCNjGan7fMMtpU053LAseGyhgIbupTWmygp3pzsO5v1vpgvW+DhvBiJw4HM/+BUb+cDeUztHWCXvbE4fqy6Fvocd+inEw5am8Ow==,iv:lXtWJgufbvqz7iXiNyNrmvKaA48/zyARINSvX3vih+s=,tag:2WSQkYxQTD4kR+JWRkk3TQ==,type:str]
    tls.key: ENC[AES256_GCM,data:QOOwT0MtTZiQ6GlgqI2M1qBqT7vi8KeMxyvRtTSAWB52Ie5QGEtvVeVwB69tuiQ4Ajfp/Hdk+ucEOzxB86WPXoDcyuAFXBLHE/hjbZVNJmMiOmrKoUARpPp5IGRh8iLgU94loqroVbOysXCAlnb9mNIqrrDF9+zYyszLRbdUM94jzwLZlSFJClGzkat9k+FN6ahNazwqlk8IScRRj1ixhJzvARW4dSTod9jIny6BIRd6x7W9HeZ7dAgwkxb7S3NOdKi8O1t4JhQZrRPr27DUxj+XvvNOi1l2mzR6284wMevExdJ3bk3gqvyd7m4KNUBSCQ==,iv:KJmbfPTkRbPFmvbr77Pr5DgcGU0vfMHRtc9qc0BUGfM=,tag:3+Jzwae4TxGxizLHc6TamQ==,type:str]
sops:
    age:
        - recipient: age1mulgnkldp0c6daway8auvrajfj7gmglr4tfhrnxjrhzg6pqump7qcamvts
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRazY4bys4dXZuYWRGamJl
            Mkk1UTBaNjlYM2FLRFk2cFZnb2d6MDBVK0dJClk5T2wrOVVkUCswTTc2NTMvZnhq
            b2wrU0xtU1pOTWN2VGlNeEloSlRWSVEKLS0tIEJBZVoyR3NMRXJ0czdYKzhoZ3hj
            V0RBNUc5K2U2dDRsamlKVWxnNDYrMjQKI7tfxNjVSV0YcDqIOjm91QbyRrvl2MfX
            Lq4IrpGebHOwRM9IkWKO+FuDOT7ZnmL+tndf6lLQzsAsc6FjCcSSbw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18r3vk6aecpcd69ey7fhgjylg6z37ksfeff6c497mxgv4nwmnyupq4gsfua
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTcWVQbmJrNVl4bWFSSWs1
            dDU2RGJOZUdaVjRGblY0RFdXMTZLTmFiY2hFCjIwRjNhQW1wWW54Z3I3aTVLcXli
            RUo4SXNnTWFudlJJVXc5cjlrZjFMbG8KLS0tIG5iM2kzSWY4a2pjQVRHT3RwU2Y0
            VDFDQ2hVc1IzYmdwQ1dLeVJoN0FwMG8KACz0hmpCjvBtc8ZNV6bkmAwFbdLIg/5y
            xK/STGU95kiLcHKUH9JtCXuum/z37Bc057dSqj9xzYjs3LphvDVPXA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1emw2e5x3d4cu0x4g0q4lrw8nj2fdv0qfzta6g62m5y24j02zu44sflkxln
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVbnJhMU43cDUrTVZDWktC
            ZDJ6bkNScThieXV0NzlESHdUUWlVaVlxVkFzClJhVXFOaVdzODVrVFNJRjdDWjNk
            VGNGOTg1MTl1M2J4UVZVMFFRckdpaTQKLS0tIG83eFk2YnorVU4zV1h3Q0laU3Vo
            T3NEZ0xYb042RGZGbHd6ZEhoNUxZOHMKwccEAmDgF+ecF2wj+YveViFO304Ng4xj
            tQrf7Nex2axhFIUKJCZHUibqNNs9xmsj4M2BrlzRGFspROhUfs6/Ew==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1x9049ry5hz876qratphuc9gdxzuv4nnd06076842zdukl4unvazszfnjf6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaMXFLQ3JLYWNpdnNhSUpn
            S0VuSVZvZS82UTN1YWYwWFRuUlJ4cjZ0aHdNCjJERVZrR2VDTllINDFFVUVTbzRZ
            NW5udVdKQ3gxcFR0ekJ2MGVZVmMyaG8KLS0tIEtxM25jUlQ2dTYyTjdrUkVLRy84
            dDJoNExOb3oxVFl5T0VudVVEUkFjYTgKi/bSq3S0vbahY+1ta0Aoj1ymz9TarTaO
            38c5OLbiYIs6BO+iyNU01qBsI3ldK/ZCP3F5REzc4IhysHmuTH/R8Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1y5txpqz0vyyq03yyysmzuyvuyh8uzzpcw30cp5q3twxnwenfzpvs48ts0z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsZWJnNzZEdVNZM0J6Q2Vu
            dzA5cWdxd05JMmxRbWFEdElHTkZ1d1FsQnlRClJiTWNLbHNRcSt3WlprMlBVVFRq
            TXFRSk43Y0ROS2lmYUxtSFJwMGJhUlkKLS0tIFBMemloU0xFaC9PSlR1azMzNTNv
            U1NSSzQ1emVMbTNMeDhldnBvRnF3bmcKPkfFLSHuP0sPJS8DTTUeaTKiMkk59riM
            3VBdQiYlrb0LXcL94UHvMg7dRJOmipnsC6QuT+IDVQeB4mBUGtTX0Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-01T20:58:15Z"
    mac: ENC[AES256_GCM,data:1NrUQqsf1DoEGl8JSNvv49uvUzjHsWlBnH1oA9MnQZnHlsR/RK2XBoUJXJbt90jmGgC1q3lNC7l/jc5UchWPonxkQoBXiIwD/9iqCKC4mAq4n3VXFbvma/pnsw5XMAAuUmXnTCYA8uPcyzUnli5gjT4B+xn8MxZvCCOnhRe+ewA=,iv:7V2QXTEf4R1X3bIM6qyb6aCIXCLT8tQ0yyWaqWWYY1Q=,tag:Of5tY/4cnjmS82L46mupWQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
