apiVersion: v1
kind: Secret
metadata:
    name: dev-tls
type: kubernetes.io/tls
stringData:
    tls.crt: ENC[AES256_GCM,data:hSvC/BeuCQwVVw908PnocHR1Ie37O+tZJxW5XpEvER0T2wDU75bPfZDqsvN88LDgT6zVGs2Pz5ptyybQ2iV10p8AdlXK+8+UxL3kZSlzBmLQ8Vqr2wrIiq/zI4J5mr37/5dTYnVoqETa2q+31iq6bah9HqEH2Kpz8LCODCC8A2lA0hXxNMk21wE0JMNCq2+lb+XxlLzZ7ypM1dIoxKXvTew3AuW4du//ippRN5le2pkOY/K1RVZUK+xlegZKVG97hteLiL3Fpas7cyW8SPk0ACGIKZZVmd8SAOsY97hDl3VrSWejERJfmFXOhXw5wznwZlQpxW9OIpVareG0SCx8vZT6RDh9tzic+q5x4edsaDmAnTI/m8LpZ9Dq/X7CpLxwvl1SQwrzkwAkDDxQMLR9HjsSJur7atBtel/L3ckki2rYovm1VrczTfeLa50fSglmu3RpoSwadOyTjZJrl+D+Yojp++Oh1pvIhYUxcCucZdg673effL6QjV+Ne7pUpXhAHmIM0tFQG8Z01ln1wV0LyuaZu4ZBwe1S//UpyqK3im3YW1TWNfX56Y7QD4udRRYplzraSpYr65NcAw2NRSYJ5WYrXsvFn5ONXV1fp7nFEG1Sx2GsylCDWAADEdwDroMoDqjUgALPg7/jR10foEpQGQmrHmhgVrEQbpMsEcSjmmtXAPi1z1KTt62beF/1kbosQhns3XLk3+GJGUofh6WnMn/ZPhAxrEjpQCRwQM/Hmngf9wgsYM81ffoOE/MK19f7qNlOa6gchRDSY8ZXzfS4ErXgMsMpmfY1qRYKl5Dvmnkg4xdIx2PxdyuQsS4M129O5emMkvJh95U9CS5Fso4x29VAOFKbMgVYuW9OsA==,iv:9pBHqlrWKuMAtmFp/e08bwmACjYuo3hUVxtKV4mrsvY=,tag:uu22NkLkfnm6ZLvSluH/hw==,type:str]
    tls.key: ENC[AES256_GCM,data:EZnijJE64XU9Ssytwd7LcWuQrsX0p7bqYqp4TAYdKSGEaxHjpNtruKje08sB5FTm7C2UfqvtpgGlgYJyh9yaU7yK/Nym4jpb/1ebROtmKVJ/PzIE8b6u85PbTM8X24rY4LV2uynQETEpTWCg6fPNCEqdlb+gOaqHkPGiQnE+dLkv25hPgzqDrL3+iAIApERB40fvj8B/lS8o0d7NDRHwutzxYHIDCW9Hyhkb5fdBOesa1SYW3uE7jbqQljNGmQNMXw3ZMqHfoha7abJhKr2B6B8JlcHYc5k7O+CuQFguX+5euU1uJI5UUCSqAorYADGStA==,iv:sqk+9r4hWAwgq+nhvKvVLQjGjOWY0JZiVvglr5hnXWI=,tag:a7eNpbQIyI1OMeWGVwCzWA==,type:str]
sops:
    age:
        - recipient: age18r3vk6aecpcd69ey7fhgjylg6z37ksfeff6c497mxgv4nwmnyupq4gsfua
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3clhXOERBWVFseHgvN3Fw
            NHdXdUUweU5sMFlOQVR3ZndZb3dwRndSU3lnCkhpOU1JOVAzZm83YjBWRU9hWVM1
            bUs0aWFXOVdBd2UxeGhYZTdNNjlzNzQKLS0tIHFzR1M1eDZHU1I2Mklobmp6TENG
            bTZyQkpBNFVOYm9MRzI3bXdNZHkxUzQKRvdffodejYSX13Io47ibcS7vmu1AZ2IS
            mKOsDSMiWafOKbiB46oKr0oRltO1EGM9GtE2RFV744R5NkVEFDcuXw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1emw2e5x3d4cu0x4g0q4lrw8nj2fdv0qfzta6g62m5y24j02zu44sflkxln
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMa01FQUFndWdTWDgyVCts
            a1hFc3ZuaVdJWjB3aU9sSzd6UGtsNHZFYW5jCmE1NlhveVMxMDJnbktEa2pRVEVu
            blVDUXNWNWEveDN4Z3Z3bGxTOW9Pb3cKLS0tIDhVZVFRRGExcTFoRlBOcHJlTVpO
            cmM0UURNVHlBbWx3UVEwMDB5ZG4ydWcKQgObcU7vO+SFYrOcGNMV84YgnJnoWJco
            LtWRnzhXKvekNAwoJLHoIHgyI7ZgOiN4FzW2wEz4JZHpmO472AbOAg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1x9049ry5hz876qratphuc9gdxzuv4nnd06076842zdukl4unvazszfnjf6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZWWlUYU1zQnBiZlNOQ2ZC
            Rm1md2RPVmNMQnBLRHkxeWJWWFhZQkRWVFQwCkwxdVhNbnRWdlpRdW4wYWVvSWNK
            VXpRczRQaXRITFp6RW1Tc0c3RzdCelkKLS0tIG1zUnRuNFE3TmpaRmx1b1A1VW1Y
            YVdqTXN1R3lRZWlkRnF3cUxwakkyL1kKikzPiGprzpp3TkKKV1nqVuZYuOpj7JvO
            JtBBDcJ5bu/vOuUzzD7hw2saeQCbQQ4gvKhrwZjkN0i6es3A9DIPMA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1y5txpqz0vyyq03yyysmzuyvuyh8uzzpcw30cp5q3twxnwenfzpvs48ts0z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEd0laZXRLbktQSWJsc01V
            dEIxckxWb2dzdmo3Wkg3bVVJNVE3TFBiUG5jCkFobXdUWHZPbEM1WitqL0N0MkxE
            ZlhHS0ZBTlBOa0EwNlVhZ2pKajZZdFEKLS0tIE9uOHBXWWsrMU0ydmtFTFhoK3lW
            eUw2cDA3bE1hb1U0UlN2dmppQUtEZVUKdUvK8WT0pKr2qYN/zrBayVSt+Q70Uy7r
            PVMDDD+SGiyjpYuBzNfwDApkXAbpby/Vw//s6noTlBot/3MNjT4qQQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-01T19:38:54Z"
    mac: ENC[AES256_GCM,data:Pv1juXfLNTBLeHRUx/mXCrhmlzMRe6z1xV5PxK0KjP41ylnzlwcZC60niHvztqvLNlKzrfArsCUcQDLcPQzDkXsmKAvf3r7wwXCFcl59H/pVEmwCGTlAXqpcqy7lSXx8QPqKRdQ2CnRIoHMlL/mvjFQ6m5Da3zNFLOBOFOEzf1c=,iv:gu5rplYY01OMWCBLfbiuE/KDMnCy/Z3YDAbuIej0LZ0=,tag:K7nPLikHHY4Q95qIku3ENQ==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.11.0
