apiVersion: v1
kind: Secret
metadata:
    name: postgres-auth
stringData:
    password: ENC[AES256_GCM,data:fMqimtnYqy09A1jRo0iotNi7qy/TYQlRsABVuHLeafg=,iv:WeNwgpphCvShyb9EIkz8y11AWNB4jUBYZ7dNu5La84k=,tag:HjLIyUP8hl5YEvPtXj9oyA==,type:str]
sops:
    age:
        - recipient: age18r3vk6aecpcd69ey7fhgjylg6z37ksfeff6c497mxgv4nwmnyupq4gsfua
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVcE45bWczUkdvaDZ2R0RM
            djNxa3Y3OHpHUGc4VW0zTmQzS0pMNGhjMW1VCi9yQjNhaGNoWHcwaEtQVU9ldzZv
            cEE2ZURmcjBpakxNUWRwOC9FWkQ0M2sKLS0tIFYrZEhpaUZFKzhaOGtIUzV6Rmtj
            SngzTlYzSFd0Vm1PbWNtSmo5cmxMcG8K9XxRDEZkTMGyUznyNFwjXt6kdZbbZIUM
            YDX1ZRFl9H5SBIQSZMa5KhZZhFJb+4CmYTkrxdK5rMqz9dXXpU51lg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1emw2e5x3d4cu0x4g0q4lrw8nj2fdv0qfzta6g62m5y24j02zu44sflkxln
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiQ0QvQ3d5NE05VDlWaEhp
            VFZyc3JSV29aQ0kwb2RtSzRTS2dpWFJXUGtjCnpNNGxWeCs3aktzeW54ais1QmlB
            MlNDSFBUdHRwcGlFN2pXZGdWdWRlVWsKLS0tIG5acW9vQjNuWVAyNFNSQnAzMVJk
            R1N5NDRNaCtZSzFrejk2TEMrR1VkR3MKywGE3af17V6QLh1D2NTWrGTqii2JWCTc
            kosC2RZXXVJVWhCDNK+HgXGz4veo6qzsgvjSPJrNYzd4og3WD9m+bg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1x9049ry5hz876qratphuc9gdxzuv4nnd06076842zdukl4unvazszfnjf6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrS3ZUODExbmF2RC9jY216
            ZUUxQTdXWXdIeE54VmFYc2R3YmZlTzg2Y253ClA3bHAyK1JBa2l4Q0NxUnFGc2Z3
            LzVRVnQyWjY0d0NNQ2kwa3I5ejFOcFkKLS0tIEx0bGR2RjRnTktGSlBCZXFyZFNB
            Y1gzSXNFc01OZEJHc2J0Qkp6dm5ZWUUKSak96Yvamrmsc9sVj99uq5mdqtAVaXpQ
            u57LVy9vhaIlQf46+SE4hjismEl1DYAvWXN1YpU51MjT8qg9OamQ2Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1y5txpqz0vyyq03yyysmzuyvuyh8uzzpcw30cp5q3twxnwenfzpvs48ts0z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsUVF2bXFiWDQ4V2Y2RzNy
            Q0I0QlVoVnJZS2toKzVaNDJnN2s0WnpjTVI0Cmx5UzBUa3RLMld4K1AzWXlaNnkx
            bFdNeTNqOWJONDZWaWV2dWpEV0hsdlkKLS0tIHo5YTNwaEIyelk4U2NkS0o4VzJI
            elJpR2ZuUGNCZ3BFeWdtYTVtT1pTN2cKE7CgMl7/jYCU66b7FWImIoo/qVaH6dvC
            D9Xr14l+WNXEh1F1htPjrU7Q+cmNtv8I2GHrNDxusxfeu6UHGKQpjA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-01T19:38:54Z"
    mac: ENC[AES256_GCM,data:KJOBoBTvYyhyYQZs6T5o+PoRtOeD+6fxCzcP1okT+xzMeEXB0BNkMuS54Wq2DLvasH0ITVsuKM088Bi+EZmU+MbAXNHbK4usINGUZwi2Xb1o/yQ4mKsfNcz/g2HrCo60c8ugyDfrgMzCvaytAVES6ryQsw5dfLIsHN7vnzlWlUQ=,iv:fhMUKJgKrlzoZ08tzYwOzOL715OqxlVQ/gfVlNszs/M=,tag:+/gbTpiHyf3Nph/JX3lWug==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.11.0
