apiVersion: v1
kind: Secret
metadata:
    name: postgres-auth
stringData:
    password: ENC[AES256_GCM,data:N6IctWyfCPf8pPVfvG6If+A7Tas3t23s2yr9PbwsszI=,iv:WA9Y2LQHB9WROqf+dD+nFodFO7paJgR5Y40zXygOyfQ=,tag:zBQIgUoNWWZ3z3t5nfbA7A==,type:str]
sops:
    age:
        - recipient: age1mulgnkldp0c6daway8auvrajfj7gmglr4tfhrnxjrhzg6pqump7qcamvts
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHZ1JFMklQTW12R1FLSUc0
            M3BhTW1hRWVYRjVjY3ljaEwxeDNsK20rcXpzCkNvWjQ4UVVJNEduT0pGSWo1Tk85
            K2FpNUxjeFgzeW4xN1Q2UWk3QUxCeUUKLS0tIGQwVHFqQU1DQmZiSm1vQVNpb2Fa
            K2FFYnNkTWJBWVEzeUhKei82c3BCbmMKAEium4XntnwAdZC8vbifkkJXM2qMDTNP
            gwRArqjtBJqVwxcNazSsoxAroPYarFE4BmcwJt1OPPFb7o/sXnA5/Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18r3vk6aecpcd69ey7fhgjylg6z37ksfeff6c497mxgv4nwmnyupq4gsfua
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrN3g4Yyt4citGb0o2bkVG
            c25SMWsxYVZrMnpnQU45dUVDaVhGU3RRZndRCkUxaFhxY05aVmFwSndzcytNNlkv
            T3prT3lVbGU2ejBtR0JDbmcwNmtZK1EKLS0tIExyR1ErTnFFa05DeGFHTVE2RXov
            MGJOaDB2N09PZitwVGtvV3hCanpuTTQKFWr7EKcbyHYPrgss/ig1ZBOTWV79FmzD
            fsH9mXXCu+kHK96UI7Sb8T8E3nFEFFGE95sAn4TRBARC/4wMXus4UQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1emw2e5x3d4cu0x4g0q4lrw8nj2fdv0qfzta6g62m5y24j02zu44sflkxln
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzckp6Nk1mMTBvYjdxM3FX
            UnhxZzE4RWNnRmhNM0J6SFVzY3V0OVFWbVVvCmJvYWxrQVBXNmVwdmlDWW9BQ25t
            eGVuYUZKQ0R2ZHlrUVg4RVNJK21XeEUKLS0tIHQxeTIrVGRoRlhEL3Azd3V3NlBh
            OEh4ZDNDeks4TktrRE95c3lqcFlFRG8KIImeUbFcIPV9X76WuriOVLJxuLWk6tU0
            WsQfrDyDYonnHSd8hoXa/R3fHUDyqltmIIXiSDcv1UsHUgGKnQ7BDw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1x9049ry5hz876qratphuc9gdxzuv4nnd06076842zdukl4unvazszfnjf6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBMWtOb1pyK1UxN2swT1ZK
            ZG5OUHl4K2pVTjV0bWVoWUJmSVNuNXgyOTBFCllrd2JHRHpIdU5ZOGtUR09sMFlm
            RzZpV1JSYWJVbHpSVmZHcmpZa3Q0S1EKLS0tICtjaFlqbHQ3QjNoOW54UW02MXJ2
            cUpGdUx0UXg5a1pBZTZLREJ1eUtNZ1UKT3Az0/PkAWsRJQ9thT8ZbVCGTV3MjNYf
            O8ddvhLNhLOT6QXp8WKpqLQ/8oAzXoAUc/jEgTUGYeBJbbJgaYDZFw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1y5txpqz0vyyq03yyysmzuyvuyh8uzzpcw30cp5q3twxnwenfzpvs48ts0z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiaGVEbDBJOE1NaWFpR3NS
            dzh5VEM0aXdYZXBncFJHZHpRenowVnZ5NlQ0Cnc3NmxVTTZyY2tuVkhnSnVOS2pv
            UFpLMlprTW5aOWVjS1VKN2tWdWU2Z0UKLS0tIGpvUTAxSGdGb1doQkRkaEx3ZFRC
            UGZncWE5RVFldjUyUU1RVHprSXo0RDQKG/7vRiHcc6j8qcekWtzenylRDvRbOYx7
            jcg4hnNv75u9PI4hJd0I9xdWiBdPHmcVegDQRbNoNzM2bShq75qXkw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-01T20:58:15Z"
    mac: ENC[AES256_GCM,data:JmPKxY2ye9MYHQzSK3ilIp6Z6QFfFutDDNxxYACE+BXrBQMGqigpohygnlUn5tr8JN780Xc1qwi8Mabx5drrxvq1OJjFt+2DfYBWuie9NwuOhLMnzEnFHJn3w/ivE+y4Qad4W/Kmp9AinhzlXWpcaVZyeyOzZcoz+nDjWJIPeF4=,iv:WwoNpKLbw2qYZRQsS5TFAq7BJnG+OeeCsUsN3NBiy9Y=,tag:qOJ4A9iL5U0+NpzjUOajYw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
