apiVersion: v1
kind: Secret
metadata:
    name: r2-credentials
    namespace: browser-streamer
type: Opaque
stringData:
    endpoint: ENC[AES256_GCM,data:j9mMFb1E59kekqyhQlFiVnnyGfSN2z2v1VwBdoafwW8aXNibJD7JCDb/aRZb5quyQgGnS/MOcqQ0/dDYXfRc9A4=,iv:zZncpxptvnrklyvn4+9Pwahym3EYsNd1hkOi5veFf84=,tag:PrkkhE1NxC7STPuVpsy5Kg==,type:str]
    access_key_id: ENC[AES256_GCM,data:ydJqv2sQEBK+X6fQp+idBN6M4gGeY6x3HNA2eKJ5qAg=,iv:mTpbfl5wLZX5kCPaTZlstq6TorbWtoEE4K3fZ8qK5Kc=,tag:XAO7ZOPdvZAIfzUmDxjIlw==,type:str]
    secret_access_key: ENC[AES256_GCM,data:3VQ2rHbKxd7OyHLgkEZ3Mmm6UC8cHbVPOqcNRtwoMaVHi0zIG3UTcPe+GEvfwBMgv5ZIfWAPr3tJkKjO3OC19w==,iv:mSsNej87QIW8a0OXB70vvg+331jbDJag1xj4fBGNs7s=,tag:Zo06f4Jx8caFzitZO0525Q==,type:str]
    bucket: ENC[AES256_GCM,data:li1s54usEWwT+YXxnhyREeoWFtomRBbLuVT2,iv:JHgXkwbSJPGTuOPDTj5Asgpw4HLOEXnBH2K2HHHpdoU=,tag:eQRMOV4L8fl9Nf3/JkG62g==,type:str]
sops:
    age:
        - recipient: age1mulgnkldp0c6daway8auvrajfj7gmglr4tfhrnxjrhzg6pqump7qcamvts
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKTFRVSkxlcmk4V3A0UW5R
            WEQzbjIvalppUmVIWW1yeWRvcDNLSjNsbXhZCkFQa3VzMTlGbGV6N1BsOTErb2Jo
            QlhERVN6YXN5TjIvczZJUkt0RnBjUEUKLS0tIHJEZGlFNTVRamtnZFNCeFdwQXRh
            NmRZV1g1STJ1N0pxbTNNeGN6UDJHNzQKh+4fAbj2Ame4ktQcWdurI44j6kShaTK9
            jUKw6NPEuFyfxugjBqBV2WM0JV0aNFLSCmWrKobtTsGEA5VqMheDsQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18r3vk6aecpcd69ey7fhgjylg6z37ksfeff6c497mxgv4nwmnyupq4gsfua
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJdUNSbThvOUwwcGJqYlBm
            T3A3ZGR1TmpWTDNaSFZobmdiZVE1L052bkhVCnR2YytMdWhaMHBmVEFXbmdmYlF1
            QUplSk1Kc1F3MGJ3emt2ajh3VTFJc00KLS0tIFNxZjlzZWhEQ0VNKzN5SmxISlJo
            b3pYVkc2TGx4Vk9FdzdmYWkwMStDZEkK58QJk0hsHe+rMDxGn7Yf2S0hFXBSPWW+
            WkAhdKfoRGZZ271B/H6O0397Wi9OjgsKq4831VXWVRgS12XWekK/Qw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1emw2e5x3d4cu0x4g0q4lrw8nj2fdv0qfzta6g62m5y24j02zu44sflkxln
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3YlNjbjJDRWRHZlRIbmhC
            Q0NFQUhLRFRvZWRBUmc0NWpyY0FZNDUrVXljCjlNYzhzcnR2amFlekVYaG5BMmwz
            ZXEyVEN2ajhXVzc2ak1TZU4zM0JYUFkKLS0tIEVJMDdZcFNKVllZcnBUMTZpRi82
            UXR5YzE5d2JuNkNONVpBQ0NSZUR5VDAKFehnXcgm+gvW9C4Z3M+EY11B8VxFwPy4
            5YeS6fhs4GvzEn9fJmgwNbBbmvkNZDz2cokqxeg3+43jN05JE4tScQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1x9049ry5hz876qratphuc9gdxzuv4nnd06076842zdukl4unvazszfnjf6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRZ2xNUlV0T2JlbzU4cndw
            dUVJbkFNdGNCS2l3WXZseUVIM2FQalRTZXpvClRNVWxLNDNBckJWelRna0I5S3Fi
            R0RvUEQ5QXU5dTNsRERCWFh6NzREdVUKLS0tIHA0aWMweFBoZDErRnFibC9Eenc1
            ZDBvYmtSakFxRXVkSG0rT2E1WUk1ZWMKWkOkHrvIlue9OOPVQC2iuwhNO4J1z53C
            fEF+D89g7reO/8kgEgAadUsuOOPq3KRHcEg7Ymo658VjplBHXn0X9Q==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1y5txpqz0vyyq03yyysmzuyvuyh8uzzpcw30cp5q3twxnwenfzpvs48ts0z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDazFLQW9wRFNvL0h2blJ1
            WG8zMGp5ZDNabTBnWGJrYlh4SGwrREZLTzNFCmlyOHVxdkM3T2xoaHl5cGd2V2xa
            WVcvTHFnclJZQVltZCtGZDh0ZDRxa3MKLS0tIFI2V1NoMHJYZ0lRbHc3Z0t3ZzJB
            ZnJ3MnBlelhoUmVsSk9EQ3NnS1UzWGsKBLM67wr7nrB8YgPhd7FaP3U+8mCJrf3h
            58gzXY24uM2CJSNxq5IOPsomXZaxGJgpPZ0HOYZiX6gVpl41F5zF0w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-01T23:10:05Z"
    mac: ENC[AES256_GCM,data:sW8Qxgal48NgOC6BSaWoJQsAt5AHt2SiAvAHHafOQjuBl5ZX85Qizh0zYj9ysYJ1ABSgdVV6WcnyigGMMdZv40jkk8MEuwOQarES6ICeQ65nz7QZlGIABhivpGg4Sl8v5H63kWzCq/w8CkaG5sYia7eDCEQx0aaT403ze1gWkFI=,iv:Vq1AHOXu333s8Zx7sRb+vUn02jna6OpI9mrlF9thWB4=,tag:O1KJrG/UY1622mIlV1aMAQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
