apiVersion: v1
kind: Secret
metadata:
    name: redis-credentials
stringData:
    password: ENC[AES256_GCM,data:zj7RF3xvg3T5kwdbzG5mVQA24e1Bu24KVUJJIjmTbpY=,iv:Ons8JqPTk7y9MNR00iZzqrkUAo7RTk4kr/yxwPw3w/k=,tag:VdF9zCxSKwYUV5kqFySDOw==,type:str]
sops:
    age:
        - recipient: age1mulgnkldp0c6daway8auvrajfj7gmglr4tfhrnxjrhzg6pqump7qcamvts
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHWlR2UGpJWC9sL0lDN0RX
            cFFmbGwrbU90T1BlVEgxK0c0SkplakxOUFFvClNGUXpZcGhFV0ZsKy9IS3FtZFVx
            RzV0TDdvMWF2NDZ5UC8wNEZ2cUhqeTgKLS0tIGN3OVczK1FUKzlNS3g5RW1aRWV3
            Vm93TFlXdFBOc21jOXBuUE0waVBkRzQKN5WCiseB1Hmh/wyKD7SsIIV0qJAqf0xc
            AGiBZNRyqnQNuXEeaekT1VksxhOtRvgUOuxHy8Gvvoo85785mwimlA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18r3vk6aecpcd69ey7fhgjylg6z37ksfeff6c497mxgv4nwmnyupq4gsfua
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzWWRGVStDWFJSekZjUDI1
            dzJsUnllR2ZmUVZUNVNuVmlLWUxXLzloNjJBCmpxRm4vMHFRUXJsdTErM0wzOWxa
            RTE2SkwrWUxnZSs0MXBpdThZOWhETm8KLS0tIDNtbGFGaU5SdjVsbjRRZk1YeEM3
            UzlQbUQvN0tWMEpnUDRVbVVZODMzNEEKI6LejgnkKSNo8jvXfVSevv32My6PK69R
            h7FKe/ciKIhG1jyI7z7BLC7+vE40LmXj5pQFA4xsLYnL+VpYGql9pw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1emw2e5x3d4cu0x4g0q4lrw8nj2fdv0qfzta6g62m5y24j02zu44sflkxln
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlQkxJV01zOHQ4QUtIVDFW
            WHd6emFPK1hKT01HY2xYa24rWVBsL1M4bDN3CkU3Vnh5VFArMlJteXRLZThTbEtT
            bmdaMkFEaDlaSHhjMjNDNi9nRHJzR1UKLS0tIGRUR2tMYVROWE01VzlpclNwYTFo
            ZXpKZDZKc05TOVQxT3RHbFo1OWwySkEKCZw6vrfvC9IPjarKkjINlIUEfqFjK/z0
            keMUNr+yHJR3lcOcgSXBYi1mZRKvM78sEZPpDss9iOSzWag2Nav/Hg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1x9049ry5hz876qratphuc9gdxzuv4nnd06076842zdukl4unvazszfnjf6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2RUVPK2ljMll1T0lGN0ti
            THBCZml3NnVRSkM4Ly9DdlNWeEtRWHFaaDA0CmgvU251TWVxVlBFTzh1YnJTRVB2
            cVhLQk1kam05RG9hL2JQN2hscnBGR1EKLS0tIG9hWFZ5dDJ5cTF2YzdIdHlGeDgz
            QmpxcjgrL1pLZURJeEtnc0lDR0xHL3MKaEBExJFA2XjPfaJN1Ilu0bQlS6cXtjL9
            3zbeXRgZtoybMDofiDXmh3v1xeLtedoRHBK7f21/O9jKM2M87uR6oQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1y5txpqz0vyyq03yyysmzuyvuyh8uzzpcw30cp5q3twxnwenfzpvs48ts0z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHUlZmRVlzSDMwdHppNFI3
            YkZIMTVPeG1BWW9RYmF3VzBuVEFnS1lIUEdVCjljRndINnhNK05WdGNPNVBOdVl4
            RXp3aEc4M0RuaU85WCtmKzE3T3pzb0UKLS0tIG5MZEc2MWF5ZG9oM1ArSWdSSHI0
            OXQ2WUFWVHAva0xYaXVnb2c4ZVR4MDAKZSGGmlIr0z9+OnpdP678tgzgoUvBHAon
            /+tUPpVUblQ0DCbgA9uvv3tnq2jEcqwgAsugJnamLBAxSZ+iJAluFw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-01T23:21:38Z"
    mac: ENC[AES256_GCM,data:pMdDOdVT2867Fl2hWzlL6E27CW+QWBFB9rzCm+/hMRLXBfiOVYPgpZT434K2LghMSJc2WTVnYzkEA8LZJLjwDBFRo3t9nwSTZesspacrxgiQs3WN0s3QuLRZJZupr2E5AwmXQekD/k4KSV20QxDpab2ngHkxYn6RkMz2p8hN9XY=,iv:gjdkyBtUEaBYm88swIoTt6KPYGVBym5ALRdyuc47mAI=,tag:Plg6MRWpbmC2po/hLGBLwg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
