apiVersion: v1
kind: Secret
metadata:
    name: tailscale-auth
    namespace: tailscale
stringData:
    auth-key: ENC[AES256_GCM,data:q7zH+SE7FYTv3Zv/Ax0NmLXpecqVxIYYfvmTle5OI3cgfN5yS2lt7g6AW8pET2W6H4w95cqQV9nXyVhLZYQ=,iv:ZeUUXy0cFo7wVVH1b/grH+W3Aods7Rlmql3M+sZPcHc=,tag:8sAaWhvS+nHhn6Ecp2ogzQ==,type:str]
sops:
    age:
        - recipient: age1mulgnkldp0c6daway8auvrajfj7gmglr4tfhrnxjrhzg6pqump7qcamvts
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGSnlFU3NHbnBiYitGeHQ0
            aUd4VTZLdG5GUDYzVXhKcS9YTFAxeERKL2hjCjFxZUJaYnhlbVJ1am5qNTB2K015
            QUVLUGJjL3ViRGs1aGdldE9sQVpiYkUKLS0tIGV5UElRMXlzaXNjeGY4L3ZyK0hV
            aURLRUhKUkc5VVMzMkU4OWQ3dWZUeDgKnCuidbAYremvWyZZRvfB8jkqZnqm/V4T
            CJYag88zU8ftAJZcmEFTGoL7//EQ+889emNWsIhCmyeiey9N39nTfA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18r3vk6aecpcd69ey7fhgjylg6z37ksfeff6c497mxgv4nwmnyupq4gsfua
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmTFVPcWh4aW9SMnhKVXdW
            cGNyZm9zWHlFck84SlJBYU9ibE4zT2V2c3k4CllOdWNpcGljb01rbHdZSDhSRFRq
            VnMxNmx2NkpHZXJiNENBazI3U29zM1kKLS0tIHJ0ZHBpV0RWWml1Y2tycGcwd0pi
            aTQ4RTZ6Q3BXQm1qdkp2YnVlZDYrL28KIST13wUMsbp+WiuyIWULNDsX05BWoryd
            rU1hD6jHyxvW/lFlaIEv0p+dznK7t9GJoq1qpDMb8TD+0mQGLASrQQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1emw2e5x3d4cu0x4g0q4lrw8nj2fdv0qfzta6g62m5y24j02zu44sflkxln
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMc2IyZ2lsNXVzM3JlY29i
            TXNMeVJWeXJ0Q0NuVmRlUTZXYnoreExMcFdJCng3ZWVKZGpsdTdYRW1XUis2NGt2
            NStXRVpaTkR2UDN6WEJtdG5paENMUncKLS0tIENSa3AzbmhGV1ZPOXFTRXR0b2Zy
            N01CUlYwViswc0VPaUFDNFA4VGlPdEEK/Wrj3rODNDWQziqp9eRok4DCNGBsapAD
            XFwxeFWGgxoN74Jnb5K00wsZwSsTnw1B0Qd9QqThVG/hkfdqRjpSmQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1x9049ry5hz876qratphuc9gdxzuv4nnd06076842zdukl4unvazszfnjf6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkQ1pFaFpXSEl0bk9obnow
            bGtQV0dCc01IYUVGYndRL3dZWmlmRVJwQUZnCm5TU2NueXQ1OG1jZG5xQWY1RUF4
            aStkZ2pSNlNZSVUzTnd1R1N3azJNWVUKLS0tIGNQRmlVMnlVUklnQUFZWFR1YXYx
            bmVBdWJ6ZlBPM01ndi9kQTlpMnZzdWMKYJlukw/M3wn8UrxZEKNZkF5Cvd5+vlx+
            LvXLaiDwRybG9/nyp55ItDPlDBPlU5R4mCQ1LF0gFHvZ7Ojx9aXjFA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1y5txpqz0vyyq03yyysmzuyvuyh8uzzpcw30cp5q3twxnwenfzpvs48ts0z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCNDJMbjVtS1V6eFdHR2po
            VTdwWktBQmt0NWJhckVOeHZ4cmtrdWpWcVZRCmM1cG12UHBYVE9acEFqQzVxeDFQ
            N3J0MkY1eDRUSlRLTUVCVi85T0h5V1kKLS0tIGdVK0pMMFdlb0J5MlpFeEwzTmUy
            aUxUcjlWeWRIUmFwUDFLSStYWWFaaVUKwE++BVLK9tVvbfPtN93Uojx+8c9aEXji
            6vBuf1pA4Y/wHkkF3J0IPe+S03QdMDPcTQgITHcERbT+bO0J1XvKYA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-01T20:58:15Z"
    mac: ENC[AES256_GCM,data:IAv9yfqPNcNnlMWSAeXZ8xRYJXD+SqRMN8aat+4jxKxhvyiU2/Pl1rPmtRWIn0wafnDtxo0dL/YVfpYFG3acdcWzsQNzlCtMVLkmwoq89borj50CUYrisKtCMNWTjbVyDwb3Q2pxDbdybcOBTqA1R/AIWe1poOIGxCMzvKO+sVs=,iv:FPhXy0B1TfsszotkcejNRjNSLjYC++QV/eRh8xVM82w=,tag:VpXe01SANYCoaomf3BP1Gg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
