apiVersion: v1
kind: Secret
metadata:
    name: tailscale-auth
    namespace: tailscale
stringData:
    auth-key: ENC[AES256_GCM,data:S9kHdTk2SJgxrbPAIwEHHIPD2lcZ//X+6jr3CnXV2RRhTL0jXqHg5ipuHxjIImO4UeniMTijo92QLIYn2tE=,iv:vh70vEGJra5lEiEi8xSmN4WToY4HDEzNF8ltP2bD4dU=,tag:Q0x4W6b1LgplmuYsrfo8Fw==,type:str]
sops:
    age:
        - recipient: age18r3vk6aecpcd69ey7fhgjylg6z37ksfeff6c497mxgv4nwmnyupq4gsfua
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5bkNhOWxhMWZPRzJoNith
            OC9Nc0FLenU0czNCdlc4ZWl6bWJyb0x6d2xvCkxmbUkwQTczZDk2S3d2enpiaHNI
            eVFuMjBWb0tvdmdKdGg0WTcyT0lsY2cKLS0tIFRONDRCQVpkTW1zdFBCTTRPdi8r
            SlJZV1ZjV3BIZE15MEtwKzJWRU4rbmcKhHFjszvmJu04JPZaAeDTXDpIx2Xs6bxU
            IBQyW4h0e/Wh3l6daJ4++wogZPUHlf8wJygeUi/DEryRUv0UVMIALg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1emw2e5x3d4cu0x4g0q4lrw8nj2fdv0qfzta6g62m5y24j02zu44sflkxln
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrSXBjY3lCZVIyRnAxdUEx
            dmsvT3hGQVhIbktHRnR1OXQ3R0c1V05PUDBNCmdsd0psTWxFR1NWbkZORXBiQ3Ur
            UTFlYWwvdE5SUE5OcXBQZWFFVW55eUUKLS0tIDB5RlpkcHZtZytYWHlaUzNEdnBE
            WmFQMkJ0RGhyZFYzZXdxdmQyQS9BWG8K5dwpB8FFqN/ftJ3ckpMVQcUG4B2a2XnX
            vVAMOrbzAGJApFwjR14xtMNWUMf7a2JZezzT0g+qwvDZwsrp+MrPIw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1x9049ry5hz876qratphuc9gdxzuv4nnd06076842zdukl4unvazszfnjf6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvNDAyR3JKRzc4d09ZRjVn
            M1RSei9vOU5qSHdrczVaalFyMi9TVCtOcGljCkhSeW1xakc2cVdkcDdVRW1UVEhI
            SmIwUXhnMStlY1dIRFJpcVYvN3ZlUVEKLS0tIE1UZTg1Yk9zajJjeWlPV3FnazdG
            RVZFNUNNeFVPalJlUjloOUxYbkhKRFEKRyqwZfF3gDBM3qlTs9VRSvgOLp+sHO/6
            RbK5PxT7CaI5WxZEHw9tOWrTI1Rgk/CJSnV/ry3S8z0GgfdkK1TD7w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1y5txpqz0vyyq03yyysmzuyvuyh8uzzpcw30cp5q3twxnwenfzpvs48ts0z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOMHhTeFBMWlVTeWVZSGdO
            MHlHRVZXYVczdTJzcEpzWjBFd0Y0T24wdlZJCnVrNEluK0NiN0F6Q3VVdFdLcHhN
            S2pSc1NMZHh6eWI2cVUxYUZzelE0RUkKLS0tIHNXMDExNU9LRzJXd3pEbDNxdVlw
            dDRYNExPU3pod3IyY3E5V3g2amxyQjgK7SRDx6idreL4twrmj5J/v4EAJUu6qfTH
            rX0Zu1qw4R891AfPzz67jGyeU8lFTzLEXCHsze/smVhb4SwQCjC/6Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-01T19:20:14Z"
    mac: ENC[AES256_GCM,data:H9xRfVoOpZY/AJr6lE0jPsRuq4byneIy9FdRIUOXLaHur7QKIui6Qo4vSCyf7Qm7jWazWdav+RGC7Cyo293PJTnUwMOLuGC1Vnr0FdIDk/qCRhLFjQERBZJ/7aAyYUbIQlsKQ+JTBhsOF8qNQGS+LPS5cC2BFglRTpBCdE62F0E=,iv:wsq4JLRrO/inOINygn63UknKI0RjMRXHjkUbps+LQ9I=,tag:cq/rbzwfWZijOpkz4Ybt8w==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.11.0
