apiVersion: v1
kind: Secret
metadata:
    name: telemetry-config
    namespace: browser-streamer
type: Opaque
stringData:
    webhook-url: ENC[AES256_GCM,data:0A44TrNYIKsFe8PPX4uFuy0JAkeU1Lm3vkcBUgg7iU8xsIPCSC1pepnW67u70Uj3WEYxr/p2oGes/TQ411kLk1yBd0xeGVIUbPWsTTMfnAzx,iv:9+Er9RHvImF6x+VDEYqEHImnyI3ERt8R4U3g3+vs+I4=,tag:EJnuG84CbZSihS+7xA6/Lw==,type:str]
sops:
    age:
        - recipient: age1mulgnkldp0c6daway8auvrajfj7gmglr4tfhrnxjrhzg6pqump7qcamvts
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3YXFuY012Vzd4QVFwbU9k
            ZEdTNjlwYU5LTFhsaHFJTk92TnZlSUZLVVJzCndTVHBwbWo3ZFlWTGdTTDFQbEZX
            M2VadThQZEMvMEZCYjhkT2JHMUovSHMKLS0tIHJxVzRveDUzNHJxcXZGYWFlcjhX
            U3hXQmJrM0pIT1MrYzYxZUV6QzI4VjgKXcl5vMQZr9HOxpnTiosoH0ncRIoUkSRS
            aetbxhYaNsdFFAgMXmZVLb+QuS2c535BCgtr19Znr+S9+t3sJAmqXg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age18r3vk6aecpcd69ey7fhgjylg6z37ksfeff6c497mxgv4nwmnyupq4gsfua
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaNlAxQUFqNUpSaFUxMkxn
            eFhzVXpmVmZUeG41RE9DejBTOWxNWG5pamtRCjdnYTM2SHVsR0lGcUoreHE3enRl
            bTV0TUc0UEZ5THY5OFBuNHNoU3pDUFEKLS0tIDFWaU9jajJUNUlZUHp3NTFRbDk5
            YVFJYUhuWVhicVl4b0s3M29OdjZrYVUKgIkeHy0uFjz6Y/bxlfoS3MP4r7xFEmoy
            JFUWOv0ZFEolprtSEgHnrS/XEMts/vnUsBjFNXqKm5FksvNEKZynfw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1emw2e5x3d4cu0x4g0q4lrw8nj2fdv0qfzta6g62m5y24j02zu44sflkxln
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSYTkxbytQbVhNQTJGNEdj
            ekhwa2lVVFpNSmVzZGJLeDhBeTduaXdtWlJJCnVWc0R0UytoNlFKcGVYRG1OTXky
            aVR3SzhaYWdlSG9JNkFORGNVWnBkTE0KLS0tIE9md2NKWklybXFzb3lWQjFyblZy
            VUM2VVY3ZzYzcGlZOXFNdE5ncU1UNHcKYoFdchRS5VjDSZXA/LOO2IG7kUaguE/j
            Bf2SHVQdm0OkeqgpjxBwi2TxGmw7HqKpoTjYQBepS3Bw6EQ+uN8hUQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1x9049ry5hz876qratphuc9gdxzuv4nnd06076842zdukl4unvazszfnjf6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUR0NmRStCRVJzaGdlL2xZ
            ZFRwK0NVMTgveWhMTkgvYjN0NE9kcnI2TEZNCmVFSG5OV3orYVpRQzhWQW1rVGNO
            Z05NSkcrbFhTZU1kNVJZU09PcHpIVVEKLS0tIGIxR3I1TzljY09pMnp4MDZWRCtX
            MVQvZXlJcEpxb20rcEdKbmpTYUY4NEEKeuVM0zFgbZ/vmdKsH+H/uE2EMOCIrocS
            9svFF+RZ+lGggizlydCSRybjVPbq+iixuo4vTmycRhGEC5wFTmkq4A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1y5txpqz0vyyq03yyysmzuyvuyh8uzzpcw30cp5q3twxnwenfzpvs48ts0z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHU3hBejl4WUlVRGg3dTRx
            MWtzaGFUaWF0VHJzdTQzZlBBVGFwUnE4VVNzCi90dkVaY3ZtRFJWWWQ2MzVYNUt2
            T0lKSmIyVmZpYzhPWlZ1enlZTmZpQ1EKLS0tIC9BRDRsWlJ1VnBNYnlrZVJ6dDRL
            MmpsbndIMktNT0l3SjVyQW9Hcng0cm8KTyjyCp4VeNJrwQznOAq5crM+1GbSUSB5
            +Os2BinuZJmZ8aIqyaomLCzbi5jTaI0H+zdps8btSbww0ZGvweasMw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-01T23:10:36Z"
    mac: ENC[AES256_GCM,data:/c3kEWLomztB3W9vzPdiO4QcyjVueIXeGpIBNNe8SwxKNpWter3caP+Z9zAfUWjJlQNXXcThCU5uJQQx5oUApB8zwB+CcTn74QGuquBIKAh8rG+Zyqu0Vkxyx7PjtZWSE0IntcCnuyO1BwfpIZINOHc8M+UJVRnNW0miEs13p18=,iv:sxlFmRV87gR55SClJKiyiBsNXLG3rljaVj0ex/4hKFY=,tag:mo8NJXrwZ1TUQf1zFhdhHw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
