operator:
  replicas: 1
  nodeSelector:
    node-role.kubernetes.io/control-plane: "true"

encryption:
  enabled: true
  type: wireguard

k8sServiceHost: 10.255.0.101
k8sServicePort: 6443

kubeProxyReplacement: false

ipam:
  mode: kubernetes

routingMode: native
autoDirectNodeRoutes: true
ipv4NativeRoutingCIDR: 10.42.0.0/16
