# Helm values for scheduler-plugins chart (deployed as a second scheduler)
# Chart: scheduler-plugins/scheduler-plugins
# Repo: https://scheduler-plugins.sigs.k8s.io
#
# Default scheduler name: scheduler-plugins-scheduler

controller:
  enabled: false

scheduler:
  replicaCount: 1

plugins:
  enabled:
    - TargetLoadPacking
  disabled: []  # override chart default that disables PrioritySort (needed as QueueSort)

pluginConfig:
  - name: TargetLoadPacking
    args:
      targetUtilization: 65
      defaultRequests:
        cpu: 500m
      defaultRequestsMultiplier: "1"
      metricProvider:
        type: KubernetesMetricsServer
