.PHONY: help proto

help: ## Show this help
	@grep -E '^[a-zA-Z_-]+:.*##' $(MAKEFILE_LIST) | awk 'BEGIN {FS = ":.*## "}; {printf "  \033[36m%-24s\033[0m %s\n", $$1, $$2}'

proto: ## Generate protobuf code (Go + TypeScript)
	cd proto && buf generate
