apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamer-placeholder
  namespace: browser-streamer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamer-placeholder
  template:
    metadata:
      labels:
        app: streamer-placeholder
        managed-by: kustomize
    spec:
      priorityClassName: placeholder-priority
      schedulerName: trimaran
      terminationGracePeriodSeconds: 0
      containers:
        - name: pause
          image: registry.k8s.io/pause:3.9
          resources:
            requests:
              cpu: 500m
              memory: 2Gi
            limits:
              cpu: 500m
              memory: 2Gi
